= Shadowrun 5.4
little black dog <lbd@shadowforums.com>
:toc: left
:toc-title: Table des Matières
:toclevels: 2

// générer avec:
// asciidoctor-pdf <this doc>
// asciidoctor -a stylesheet=<path to css> <this doc>



== Plus ça change ...

Pour les habitué(e)s, voici un panorama rapide des modifications apportées par le système.

* Le système de base reste identique : une réserve de D6 toujours égale à <attribut+compétence>.
  5 ou 6 sur un dé représentent un succès.
  Le nombre de succès représente le degré de réussite,
  ou est comparé à un seuil pour les tests de type oui/non.
  Des modificateurs standardisés s'ajoutent et se retranchent à la réserve de dés pour faciliter ou
  compliquer la tâche, mais la réserve ne peut pas dépasser sa taille initiale.
* Les actions de combat se résolvent par _un seul jet opposé_ :
  attaque (toucher+dommages) contre défense (esquive+encaissement).
* Seulement 2 attributs physiques (Agilité et Réaction) et 2 mentaux (Intelligence et Charisme).
  Ils varient tous de 1 à 6 (9 si augmenté), _quel que soit le métatype_.
  La Force/Constitution devient un bonus qui s'applique à certaines actions :
  défense, corps à corps, lancer, ...
* 2 attributs spéciaux à choisir parmi 4 : Edge, Essence, Magie ou Résonance.
  Chacun est vraiment indépendant et peut progresser au delà de 6 grâce au karma (oui, même l'Essence).
* Moins de compétences, et chacune sert vraiment en cours de partie.
* Mêmes règles de création et de progression du personnage au karma.
  Une méthode alternative de création de perso réellement rapide est proposée.
* Utilisation des avantages/défauts pour plus de personnalisation.
  Par exemple, un mago peut être enchanteur, invocateur et se projeter astralement mais laisser
  tomber la sorcellerie (qu'il pourra apprendre en achetant l'avantage plus tard).
* Un point de karma, c'est 2500¥.
  Convertir de l'un à l'autre se fait suivant les besoins.
* Seulement _deux types d'actions matricielles_ illégales : hack subtil ou force brute.
  La force brute rend l'action plus facile, mais déclenche les alarmes plus rapidement.
  Un cyberdeck n'a plus qu'un seul indice. Il n'y a plus de programmes.
* Différencier cyberware, bioware, geneware, pouvoirs d'adepte ou châssis de borg n'est que fluff.
  Il reste quelques spécificités des implants ou des pouvoirs, mais la majorité est commune
  qu'on soit câblé ou adepte.
  Un câblé peut pouvoir passer les contrôles aussi bien qu'un adepte.
* Il n'y a plus que des types d'arme.
  Predator ou Manhunter, c'est un "pistolet lourd".
* La _Signature_ s'applique aux armes, implants, persos et véhicules comme Seuil de discrétion.
* Généralisation des _Grades_ de cyberware (alpha/beta/delta/occase) à tous les équipements.
* (*TODO*) Le système de construction/réparation/upgrade est unifié entre les mécanos de véhicule,
  les armuriers, les enchanteurs, les programmeurs et les autres.



== Objectifs

Quitte à refaire un système de jeu, autant l'améliorer. Du moins, d'un certain point de vue.
Chaque modification, chaque ajout ou retrait au système existant doit se faire en poursuivant les objectifs suivants.

* *Conserver le système de base* identique à celui des dernières éditions : une réserve de dés égale à attribut+compétence ; les 5 et les 6 comptent dans le nombre de succès.
* Définir des modificateurs simples et génériques aux réserves et aux seuils. On ne fait que *décliner* ces modificateurs, quel que soit le type d'action.
* Simplifier les règles pour *accélérer l'action*.
  Réduire le nombre de tests nécessaires à accomplir quelque chose, en particulier en ce qui concerne le combat et la matrice.
  Réduire aussi les calculs à faire pour calculer le nombre de succès nets.
* *Simplifier* les règles pour les rendre plus digestes. Limiter la nécessité d'avoir à consulter ses bouquins en pleine partie. +
  La présentation des règles elle-même devrait :
  ** Être claire et concise pour en faciliter la compréhension. Éviter d'obscurcir les règles avec de l'humour ou des appartés.
  ** Profiter du format numérique pour s'auto-référencer, facilitant ainsi le fait de retrouver une information précise.
* Rééquilibrer les différents profils de personage.
  ** Tout les profils devraient pouvoir contribuer d'une manière ou d'une autre à une situation donnée.
  ** Le jeu de rôle se joue _en groupe_ : éviter que certains puissent tout faire, tout le temps.
  ** Même si Shadowrun est un jeu à matos, ce sont les personnages, pas leurs outils, qui devraient primer.

== Principes de jeu

=== Test simple

* Le personnage lance une *réserve de dés* à 6 faces égale à *attribut + compétence*.
  Tous les dés dont le score est de 5 ou 6 représentent des *succès nets*.
* On compare les succès nets avec un *seuil* fixé par le MJ pour déterminer si l'action est une réussite ou un échec.

.Seuils
[width=35%, options="header"]
|===
|Seuil |Résultat

|0 ou -|Échec
|1     |Grossier
|2     |Standard
|3     |Supérieur
|4     |Exceptionnel
|===

[[chapter_modifiers]]
=== Modificateurs

Chaque test peut se voir assorti de modificateurs, reflétant la difficulté de la tâche entreprise.
Cette difficulté est issue de circonstances indépendantes des facultés du personnage.
Cela peut venir d'un peu n'importe quoi : l'environnement extérieur, les blessures qui affectent le personnage, la résistance passive d'un sujet, et ainsi de suite.

Quel qu'en soit la source, un modificateur s'ajoute ou se retranche à la réserve de dés.
Si différents modificateurs s'appliquent à un test donné, il suffit d'en faire la somme avant de l'appliquer à la réserve de dés du personnage.

Différents tests peuvent se voir assortis de différents modificateurs.
Ceux-ci sont détaillés dans les différents chapitres de ce livre, mais constituent toujours de simples applications des règles suivantes :

* si l'action du personnage est facilitée, le modificateur est positif. Si le personnage est gêné, le modificateur est négatif.
* un modificateur de 1 représente une petite aide ou une légère gène, quelque chose de presque imperceptible pour le personnage.
* un modificateur de 4 ou plus représente un méchant handicap ou une aide qui fait quasiment le travail à la place du personnage.

Si la situation n'est pas couverte par une règle précise, ou que le MJ n'a pas envie de se compliquer la vie, il peut utiliser la table suivante, qui montre les modificateurs les plus courants.

.Modificateurs
[width=35%, options="header"]
|===
|Difficulté       |Modificateur

|Action facile    |+1 à +10
|Action difficile |-1 à -10
|===

Si les modificateurs négatifs sont si importants qu'ils font passer la réserve de dés d'un personnage à 0 ou moins, la tâche entreprise semble impossible, et la plupart du temps l'action échoue automatiquement.
Dans ce cas, un personnage a néanmoins deux ultimes recours :

* il peut utiliser l'<<attribute_edge,Edge>> pour se donner des dés supplémentaires et surmonter la difficulté.
* le MJ peut toujours autoriser le personnage à lancer un unique dé. Si ce dé fait 5 ou 6, l'action réussit ... tout juste !


[[option_dices_cap]]
[NOTE.option,caption="Règle optionnelle"]
====
*Réserve de dés maximum*

*Règle :* Au cours d'un test, après application des modificateurs à une réserve de dés, le nombre maximal de dés à lancer ne peut jamais dépasser le nombre de dés tel qu'il était avant application des modificateurs.

*Motivation :* Cette règle vise à maîtriser l'inflation des réserves de dés.
Pour cela, il faut rendre à l'équipement son véritable rôle : rendre les personnages capables d'accomplir des actions en dépit de difficultés parfois extrêmes, et non pas faire le travail à leur place et leur permettre d'obtenir un résultat exceptionnel en dépit de leur manque de compétence.
====

[[option_limits]]
[NOTE.option,caption="Règle optionnelle"]
====
*Limites*

*Règle :* Le nombre de succès nets que peut obtenir un personnage sur un jet de dés est égal à l'indice de la compétence utilisée.
Ce nombre de succès nets maximal est appelé *Limite*.

Si le jet utilise deux attributs plutôt qu'un attribut et une compétence, la Limite est égale au plus faible des deux attributs.

*Motivation :* Cette règle vise à ...
Faire comme SR5 ? Gâcher la joie d'un coup de chance sur un jet de dé ?
Avec la disparition des limites liées à l'équipement, elle permet peut-être de valoriser les compétences par rapport aux attributs.
À vous de voir.
====




[[opposed_tests]]
=== Test opposé

Cela représente un conflit direct entre deux personnage, ou entre un personnage et un drone, etc.
Pour simplifier, on va qualifier un des deux opposants le personnage *actif*, et le second le personnage *passif*.
En cas de doute, c'est toujours le joueur qui est considéré actif.

* Les deux opposants lancent chacun une *réserve de dés* à 6 faces égale à leur *attribut + compétence* respectifs.
  Tous les dés dont le score est de 5 ou 6 représentent des *succès*.
* On retranche au nombre de succès du personnage actif le nombre de succès du personnage passif.
  Le nombre de succès restants représente le nombre de *succès nets*.
* On compare ces *succès nets* avec le *seuil* fixé par le MJ pour déterminer si l'action est une réussite ou un échec.

[[option_just_one_toss]]
[NOTE.option,caption="Règle optionnelle"]
====
*Lancer unique*

*Règle :* Lors d'un test opposé, seul le personnage qui a la plus grande réserve de dés lance les dés.
On retranche à sa réserve de dés un nombre de dés égal à la réserve de dés de son opposant.
Le nombre de succès obtenus lors de cet unique jet devient le nombre de succès nets du test opposé.

*Motivation :* Cette règle vise à accélerer le jeu.
Elle facilite aussi la vie du MJ, puisque c'est lui qui jette les dés des personnages passifs lors de la plupart des tests opposés.
Cependant, elle lui ôte aussi une part de contrôle, puisque le joueur est pleinement maître de son jet de dés ...

Cette règle optionnelle ne devrait être appliqué que lorsque une des réserves dépasse clairement l'autre (de 3 ou 5 dés minimum). En effet, il peut être frustant de n'avoir _aucune_ chance de vaincre un adversaire qui ne lance qu'un seul dé de plus ...
====

[[option_lotta_dice]]
[NOTE.option,caption="Règle optionnelle"]
====
*Limiter la taille de la brouette*

*Règle :* On ne lance que 12 dés au maximum.
Si la taille de la réserve a une taille supérieure, on compte un succès automatique pour 4 dés à lancer,
jusqu'à ce que le nombre de dés à lancer soit inférieur à 12.
Le nombre de succès obtenus en lançant les dés restants s'ajoutent aux succès automatiques.

*Motivation :* Cette règle vise à limiter le nombre de dés à lancer : on ne possède pas tous 40 dés.
Et, lorsqu'on doit additionner plusieurs lancers pour un seul test, le jeu se ralentit sérieusment.

Cette règle a pour effet additionnel que la puissance des personnages n'est plus linéaire :
au delà de 12 dés, on n'a plus une moyenne d'un succès pour 3 dés lancés ...
Elle peut donc être un moyen de limiter la puissance des grosses réserves de dés.
====











[[chapter_characters]]
== Personnages

=== Attributs physiques et mentaux

SR5.4 compte 4 attributs primaires répartis en deux attributs physiques (<<attribute_agility,Agilité>> et <<attribute_reaction,Réaction>>) et deux attributs mentaux (<<attribute_intelligence,Intelligence>> et <<attribute_charisma,Charisme>>).

L'indice d'un attribut ne peut jamais être inférieur à 1.
Un attribut peut <<chapter_karma,progresser>> jusqu'à un indice de 6.
Un attribut physique ou mental peut être <<chapter_augmentation,augmenté>> au maximum 3 fois, donc jusqu'à un indice de 9.

[[attribute_agility]]
==== AGILITÉ
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_reaction]]
==== RÉACTION
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_intelligence]]
==== INTELLIGENCE
Attribut inchangé par rapport à SR1, SR2 et SR3. Fusionne les rôles des attributs *Intuition* et *Logique* en SR4 et SR5.

[[attribute_charisma]]
==== CHARISME
Fusionne les rôles des anciens attributs *Volonté* et *Charisme*.


[[special_attributes]]
=== Attributs spéciaux

L'indice d'un attribut ne peut jamais être inférieur à 1.
Un attribut spécial peut <<chapter_karma,progresser>> jusqu'à un indice de 6, <<chapter_special_grades,parfois plus>>.
Un attribut spécial ne peut pas être <<chapter_augmentation,augmenté>>.

Tout personnage ne peut jamais avoir au maximum que deux attributs spéciaux en même temps.
Un personnage possédant deux attributs spéciaux mais désirant <<quality_special_attribute,acquérir un nouvel attribut spécial>>
doit forcément en abandonner au moins un autre.

Par défaut, un personnage commence avec les attributs spéciaux <<attribute_edge,Edge>> et <<attribute_essence,Essence>>.


[[option_specials_buckets]]
[NOTE.option,caption="Règle optionnelle"]
====
*Influence entre attributs spéciaux*

*Règle :* Lorsqu'un personnage possède deux attributs spéciaux, la valeur maximum du second est de 12 moins la valeur de son premier attribut spécial.

Ainsi, lorsqu'un personnage fait progresser un de ses attributs spéciaux, l'autre peut être amené à baisser.
Lorsqu'un attribut spécial baisse, le personnage perd le karma et/ou les nuyens investis.
Si, pour une raison ou une autre, le second attribut spécial ne peut pas baisser, la premier attribut spécial ne peut pas augmenter. Le personnage ne perd alors pas le karma et/ou les nuyens investis.

À partir du moment où le score d'un de ses attribut spéciaux atteint 12, le personnage perd son second attribut spécial.

*Motivation :* Cette règle vise à limiter la polyvalence d'un personnage ayant une valeur très élevée dans un de ses attributs spéciaux, en le forçant à ne pouvoir utiliser plus que cet attribut spécial précis.

_Peut-être illustrer ce cas avec l'exemple de ?Tom? le chaman Ours troll en Afrique du Sud dans Nuit de Sang._
====

[[attribute_edge]]
==== EDGE
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_essence]]
==== ESSENCE
Attribut inchangé par rapport à SR4 et SR5, hormis les points suivants :

* Un personnage peut le faire progresser en dépensant des points de karma, comme n'importe quel attribut spécial.
* Un personnage peut utiliser l'intégralité son essence pour <<chapter_augmentation,s'augmenter>>.
  Pas besoin de garder une Essence strictement positive ; son Essence restante peut être égale à zéro.
  Cependant, si le coût total de ses <<chapter_augmentation,augmentations>> devient strictement supérieure à son Essence, il meurt.
* Un personnage peut <<quality_special_attribute,échanger son attribut d'Essence>> contre un autre attribut spécial.
  Les considérations suivantes s'appliquent à un personnage dépourvu d'Essence :
** Il ne peut bénéficier d'aucune <<chapter_augmentation,augmentation>>.
   Toute intervention théoriquement bénéfique peut devenir inexplicablement inopérante ou même nuisible à son organisme.
   Ou alors, son corps rejette systématiquement, rapidement et plus ou moins proprement et douloureusement les implants.
   Le personnage peut aussi mourir inopinément d'une complication sur la table d'opérations,
   par exemple parce que son âme décide subitement de quitter un corps qu'elle ne reconnaît plus.
   Envie de tenter l'expérience, _omae_ ?
** Il est considéré avoir une valeur d'Essence égale à celle de son attribut spécial le plus élevé.
   S'il se retrouve dans une situation où son Essence est amenée à baisser, c'est cet autre attribut spécial qui baisse à la place.
   Si la perte d'Essence est temporaire, cet autre attribut spécial se reconstitue au même rythme que l'aurait fait l'Essence.
* Contrairement aux autres attributs spéciaux, son indice de départ est de 6.

[[attribute_magic]]
==== MAGIE
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_resonance]]
==== RÉSONANCE
Attribut inchangé par rapport à SR4 et SR5.



[[secondary_attributes]]
=== Caractéristiques secondaires

Les caractéristiques secondaires ne peuvent pas <<chapter_karma,progresser>> grâce au karma.

[[attribute_initiative]]
==== INITIATIVE
L'initiative est représentée par un ou plusieurs dés.

L'initiative de base d'un personnage est de 1D6.
L'initiative peut être <<chapter_augmentation,augmentée>> d'un ou plusieurs dés,
mais ne peut jamais être supérieure à 5D6.

Pour connaître l'ordre dans lequel les personnages agissent en combat,
chacun lance ses dés d'initiative, et fait la somme de leurs résultats.
Puis, il ajoute l'indice d'un attribut physique ou mental spécifique
(voir la <<initiative_attributes,table ci-après>>).
Le résultat final donné le *score d'initiative*.

[[initiative_attributes]]
.Initiative
[width=25%]
|===
|Physique |<<attribute_reaction,Réaction>>
|RA       |<<attribute_reaction,Réaction>>
|RV       |<<attribute_intelligence,Intelligence>>
|Astral   |<<attribute_intelligence,Intelligence>>
|===

Voir le chapitre <<combat_round,combat>> pour davantage de détails.

[[attribute_body]]
==== CONSTITUTION

Cette caractéristique secondaire représente la *Force* et la *Constitution* du personnage.
Elle reflète en particulier la supériorité physique des trolls, orks, nains et métahumains augmentés.
Un indice élevée reflète dans la majorité des cas une taille plus grande, un stature plus large, de gros muscles, et ainsi de suite.

Elle intervient dans différents contextes :

* résister aux dommages *<<chapter_combat,[?]>>*
* infliger des dommages au corps à corps *<<combat_melee,[?]>>*
* casser des trucs au corps à corps *<<barriers,[?]>>*
* calculer son encombrement [lien]
* intimider son prochain [lien]

La Constitution de base d'un personnage dépend de son <<chapter_metatypes,métatype>> :

* Les humains et les elfes ont un indice de base de 0.
* Les orks et les nains ont un indice de base de 1.
* Les trolls ont un indice de base de 3.

L'indice de Constitution d'un personnage peut uniquement être <<chapter_augmentation,augmenté>>.

[[attribute_condition_monitor]]
==== MONITEUR DE CONDITION

L'état de santé d'un personnage est représenté par un certain nombre de cases
répartis en deux moniteurs de condition.

* Le nombre de cases du moniteur de condition étourdissant est de *8 + <<attribute_charisma,Charisme>>/2*.
* Le nombre de cases du moniteur de condition physique est de *10 + <<attribute_body,Constitution>>*.

Lorsque le personnage subit des blessures, une ou plusieurs de ces cases sont marquées.

* Un personnage qui subit une blessure étourdissante coche le nombre de cases correspondant de son moniteur de condition étourdissant.
  S'il subit une blessure physique, il coche le nombre de cases correspondant de son moniteur de condition physique.
* Le personnage subit un modificateur négatif à ses actions en fonction
  du nombre total de cases *indemnes* (c'est à dire non cochées) sur ses deux moniteurs de condition :
** lorsqu'il lui reste moins de 18 cases indemnes, le modificateur est de -1 ;
** lorsqu'il lui reste moins de 15 cases indemnes, le modificateur est de -2 ;
** lorsqu'il lui reste moins de 12 cases indemnes, le modificateur est de -3 ;
** lorsqu'il lui reste moins de  9 cases indemnes, le modificateur est de -4 ;
** lorsqu'il lui reste moins de  6 cases indemnes, le modificateur est de -5 ;
** lorsqu'il lui reste moins de  3 cases indemnes, le modificateur est de -6.
* Lorsque la dernière case de son moniteur de condition étourdissant est cochée, le personnage tombe inconscient.
* Lorsque la dernière case de son moniteur de condition physique est cochée, le personnage est mourant.

Un personnage peut <<chapter_augmentation,augmenter>> chacun de ses moniteurs de 3 cases au maximum.

[[option_two_condition_monitors]]
[NOTE.option,caption="Règle optionnelle"]
====
*Un seul moniteur de condition*

*Règle :* Le personnage a un seul moniteur de condition au lieu de deux.

Le nombre de cases de ce moniteur unique est de *9 + <<attribute_charisma,Charisme>>/2 + <<attribute_body,Constitution>>*.

Lorsque le personnage subit des blessures, une ou plusieurs de ces cases sont marquées.

* Les blessures étourdissantes sont marquées d'une ou plusieurs *coches*.
* Les blessures physiques sont marquées d'une ou plusieurs *croix*, qui sont toujours placées au début du moniteur de condition.
  Une nouvelle blessure physique subie "décale" donc d'éventuelles blessures étourdissantes déjà subies par le personnage.
* Le personnage subit un modificateur négatif à ses actions en fonction
  du nombre de cases restées *indemnes* (c'est à dire non marquées) de son moniteur de condition :
** lorsqu'il lui reste moins de 9 cases indemnes, le modificateur est de -1 ;
** lorsqu'il lui reste moins de 6 cases indemnes, le modificateur est de -2 ;
** lorsqu'il lui reste moins de 3 cases indemnes, le modificateur est de -4.
* Lorsque la dernière case du moniteur de condition est marquée d'une coche, le personnage tombe inconscient.
* Lorsque la dernière case du moniteur de condition est marquée d'une croix, le personnage est mourant.

Le coût pour <<chapter_augmentation,augmenter>> de ce moniteur unique est le même qu'avec 2 moniteurs.
Le moniteur de condition unique ne peut toujours être augmenté que de 3 cases au maximum.

TODO _'faut carrément que j'illustre ça avec des dessins!_

*Motivation :* Cette règle propose d'accélérer le jeu aussi bien en augmentant la lethalité des combats
(les personnages ont moins de cases de blessures) et en simplifiant la gestion des blessures (une fois qu'on a pris le coup)
et en rendant le calcul du modificateur négatif dû aux blessures plus immédiat.

Un compromis semble être d'accorder deux moniteurs de conditions aux PJ et PNJ importants,
mais de ne conserver qu'un seul moniteur pour les autres.
====

[[option_LMSF_wounds]]
[NOTE.option,caption="Règle optionnelle"]
====
*Blessures Légères, Moyenne, Graves et Fatales*

*Règle :* Plutôt que de cocher un nombre de cases du moniteur de condition>> d'un personnage égal
au nombre de succès nets obtenus par l'attaquant, on utilise le tableau suivant :

.Types de blessure
[width=33%, cols="^1,^2,>1" options="header"]
|===
|Succès |Blessure |Cases
|1      |Légère   |1
|2      |Moyenne  |3
|3      |Grave    |6
|4      |Fatale   |10
|===

*Motivation :* Cette règle propose d'accélérer le jeu en augmentant la léthalité des combats.
En même temps, elle donne en même temps un coté _old school_ aux combats, puisqu'elle est inspirée de ce qui faisait de SR1 à SR3.

Évidemment, un personnage ayant plus de 10 cases dans son <<attribute_condition_monitor,moniteur de condition>>
ne sera pas mis hors combat par une seule blessure "Fatale".
C'est voulu, afin d'éviter de mettre le troll câblé au même niveau que le simple piéton sur un coup de chance de l'attaquant.

Un compromis semble être de n'appliquer cette règle que sur les hommes de main et autres PNJs anonymes,
en reprenant éventuellement l'indice de professionnalisme de l'époque, pour gérer leur moral.
====







include::chapters/skills.adoc[]

include::chapters/metatypes.adoc[]

include::chapters/karma.adoc[]

include::chapters/qualities.adoc[]






[[chapter_archetypes]]
== Archétypes

*TODO* _Liste des archétypes, en particulier ceux utilisés pour les exemples.
En effet, c'est mieux si les persos utilisés pour les exemples sont vraiment jouables.
Ne pas oublier de donner un peu de background à chacun pour qu'ils soient vraiment prêts à jouer._


== Règles

=== Modificateurs

*TODO*

=== Infiltration

*TODO*

==== Passer un contrôle

[.opposition]
|===
|Garde     |<<attribute_intelligence,Intelligence>> + <<skill_perception,Perception>> |Détection si Signature est inférieure aux succès obtenus.
|===

[.opposition]
|===
|Détecteur |Indice |Détection si la Signature est inférieure aux succès obtenus.
|===

Lors d'un contrôle donné, chaque détecteur ou garde fait un seul jet.
Tous les équipements illégaux dont la signature est inférieure ou égale au succès obtenus est détectée.
Ceux dont la signature est supérieure passent le contrôle sans être détectés.

En d'autres termes, la Signature d'un objet est le seuil nécessaire pour qu'il soit détecté.



[[barriers]]
==== Casser des trucs

Il est parfois nécessaire pour un personnage de briser un objet ou se frayer un passage à travers.

Pour cela, le personnage doit être muni d'une arme qui puisse endommager l'objet.
Peu importe que l'arme soit une arme à distance ou une arme de corps à corps, il faut que la situation soit vraisemblable :
inutile d'essayer de défoncer une porte à coup de flèches, ou un mur de plastobéton à coups de couteau !

* L'action se résoud par un <<chapter_combat,test opposé>> entre le personnage et l'objet.
** le personnage est *actif* et fait un *test d'attaque*
** l'objet est *passif* et fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs du personnage et de l'objet :
** si l'objet est vainqueur, il ne se passe rien. Le MJ peut décider que l'arme du personnage est endommagée.
** si le personnage est vainqueur, l'objet coche un nombre de cases de son <<attribute_condition_monitor,moniteur de condition>> que le nombre de *succès nets* du personnage

[[barriers_structure]]
.Barrières
[width=60%, options="header", cols="9,>1"]
|===
|Matériau                                                      |Structure
|Fragile (verre standard)                                      |0
|Simple (pneu, plâtre)                                         |2
|Solide (porte standard, meuble, plastique, verre pare-balles) |4
|Lourd (bois massif, lampadaire, chaîne)                       |6
|Renforcé (porte de sécurité, densiplast, kevlar)              |8
|Structurel (brique, plastobéton)                              |12
|Structurel lourd (béton, poutre en acier)                     |16
|Armuré (béton armé, blindage lourd)                           |24+
|===

Lors de son test de défense, un objet lance un nombre de dés égal à sa structure.

Le <<attribute_condition_monitor,moniteur de condition>> d'un objet comporte un nombre de cases égale à sa structure.




[[chapter_social]]
=== Social

*TODO*



[[option_cyberpsychosis]]
[NOTE.option,caption="Règle optionnelle"]
====
*Cyberpsychose*

*Règle :*
L'attribut d'Essence résume la métahumanité du personnage en un seul nombre.
Plus sa valeur est faible, plus le personnage aura des difficultés dans ses relations avec le reste de la métahumanité.
En termes de jeu, ces difficultés se traduisent par un modificateur négatif aux interactions sociales.
La valeur de ce modificateur dépend de l'Essence du personnage ainsi que de l'époque : plus l'augmentation humaine est ancienne, mieux elle tend à être acceptée par la société en général.
Le modicateur aux interactions sociales souffert par un personnage dépend de son <<attribute_essence,Essence>> restante, comme indiqué dans la table ci-après.

.Cyberpsychose
[cols="3,1,1,1,1,1,1,1", options="header"]
|===
|Essence restante | 6 | 5 | 4 | 3 | 2 | 1 | 0
|Techno-thriller  |±0 |-1 |-1 |-2 |-2 |-3 |-4
|Cyberpunk        |±0 |±0 |±0 |-1 |-1 |-2 |-3
|Post-Cyberpunk   |±0 |±0 |±0 |±0 |±0 |-1 |-1
|===

*Motivation :* Traduire en termes de règles un des fondamentaux du genre cyberpunk.
En raison du fait que l'Essence peut dépasser 6, le modificateur négatif ne doit pas dépendre du montant d'Essence perdue.
En effet, un personnage qui a fait progresser son <<attribute_essence,Essence>> grâce à son karma est d'une certaine manière _plus_ que métahumain ;
donc il ne devrait pas souffrir d'un stigmate social plus lourd !
L'important est la vigueur de l'âme qu'il lui reste, pas le chemin qu'elle a parcouru.
Les fans de la Mascarade pourraient même donner un modificateur positif aux interactions sociales d'un personnage doté d'une Essence restante supérieure à 6 ...

====

[NOTE.option,caption="Règle optionnelle"]
====
*Essence des interactions humaines*

*Règle :*
Les personnages dépourvus de l'attribut spécial <<attribute_essence,Essence>> souffrent d'un modificateur négatif allant de -1 à -4 à leurs tests sociaux.

On peut en effet considérer qu'un personnage qui fait le choix d'abandonner son attribut d'Essence pour se consacrer à la magie devient encore plus étrange(r) aux yeux des gens normaux.
Après tout, suivant l'époque, les magiciens ou les technomanciens sont aussi aussi entourés de préjugés négatifs, parfois mêmes plus lourds !

Pour quantifier ce handicap social en un modificateur négatif cadrant avec sa vision du monde, le MJ peut s'aider des <<chapter_modifiers,recommandations>> sur les modificateurs.
De la manière dont la magie ou la technomancie d'un personnage influe sur son humanité devrait découler l'impact de ses capacités surhumaines sur ses relations sociales.

Le modificateur applicable peut être fixe, mais peut aussi dépendre de la puissance des pouvoirs d'un personnage, comme le propose la <<option_weirdos_table,table ci-dessous>>.
En effet, la valeur de son attribut spécial le plus élevé représente directement l'investissement en temps qu'il y a mis et donc la manière dont celui-ci influe sur personnalité.
Or, plus ce pouvoir influe sur sa vision du monde, plus il affecte ses relations avec les gens : le pouvoir corrompt ...

[[option_weirdos_table]]
.Weirdopsychose
[cols="6,1,1,1,1,1,1,1,1,1", options="header"]
|===
|<<attribute_magic,Magie>> ou <<attribute_resonance,Résonance>> | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8+
|Modificateur     |±0 |±0 |±0 |-1 |-1 |-2 |-3 |-3 |-4
|===

*Motivation :* Réhausser l'intérêt de l'Essence face à l'Edge pour les magiciens, adeptes ou technomanciens.
De plus, si la règle optionnelle de <<option_cyberpsychosis,cyberpsychose>> est appliquée, celle-ci permet que les chromés ne soient pas les seuls à souffrir d'un stigmate social.
Et avec l'utilisation conjointe des deux règles optionnelles, le personnage "de base, ni magicien, ni chromé" reprend (un peu) de l'intérêt.
====





[[chapter_combat]]
=== Combat

* Toute violence physique se résoud par un <<opposed_tests,test opposé>> :
** l'attaquant est le personnage *actif* : il fait un *test d'attaque*
** le défenseur est le personnage *passif* : il fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs de l'attaquant et du défenseur :
** si le défenseur est vainqueur, il s'en tire sans aucun dommage
** si l'attaquant est vainqueur, le défenseur coche un nombre de cases de son <<condition_monitor,moniteur de condition>> égal au nombre de *succès nets* de l'attaquant

Sauf indication contraire, l'attaquant peut utiliser tout type d'arme à sa disposition, au corps à corps ou à distance, qu'il sache la manier ou non.
Cependant, une même arme ne peut être utilisée qu'une seule fois par passe d'initiative.

*TODO* mettre en évidence la règle d'une seule arme par passe et la volonté de valoriser l'ambidextrie, qui permet de tirer 2 fois une balle en CC ou 2 rafales en TR.



[[combat_distance]]
==== Combat à distance

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>>*

Compétences d'arme concernées : <<skill_pistols,Armes légères>>, <<skill_longarms,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_exotic_weapon,Arme exotique(arme à distance)>>

Exemple de modificateurs : portée, visibilité, malus de blessure de l'attaquant, couvert du défenseur, accessoires de l'arme

====== Modes de tir

De nombreuses armes à distance offrent plusieurs mode de tir.

* Tir unique : action simple, une balle, SS ou SA
* Tir semi-automatique : action complexe, 2 balles, SA
* Tir en rafale : action simple, 3 balles, TR
* Tir automatique : action complexe, 10 balles, TA
* Tir de barrage : action complexe, 20 balles, TA

Au cours d'un test d'attaque à distance, chaque balle après la première et dont le recul est compensé ajoute 1 dé à la réserve de dés.

*TODO* clarifier qu'il ne s'agit pas d'un modificateur, et playtester.

*TODO* qu'arrive-t'il aux balles non compensées ? --> règle optionnel du passant innocent / dommages colatéraux

===== Test de défense

*<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[combat_melee]]
==== Corps à corps

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>> + <<attribute_body,Constitution>>*

Compétences d'arme concernées : <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>, <<skill_exotic_weapon,Arme exotique(arme de corps à corps)>>

Exemple de modificateurs : visibilité, malus de blessure de l'attaquant

===== Test de défense

*<<attribute_reaction,Réaction>> + <compétence d'arme>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[defense_test_suprise]]
==== Surprise

Si un personnage est surpris, il ne peut pas attaquer jusqu'à ce qu'il puisse agir.
Il ne peut pas non plus entreprendre aucune des manoeuvre de défense active que sont la parade ou l'esquive.

En conséquence, sa réserve de dés lors de son <<combat_defense_test,Test de défense>> est réduite :

*<<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*



[[combat_round]]
==== Déroulement d'un tour de combat

*TODO*



include::chapters/augmentation.adoc[]

include::chapters/magic.adoc[]



[[chapter_matrix]]
=== Matrice

*TODO*



include::chapters/gear.adoc[]










== Règles optionnelles

*TODO* _Chaque règle optionnelle devrait peut-être se trouver directement dans le chapitre concerné, plutôt que pêle-mêle dans un chapitre à part._

[[option_only_one_pass]]
=== Une seule passe d'initiative

*TODO* _Tous les persos n'ont qu'une passe ; les passes supplémentaires sont convertis en effet pops sur les actions_

[[option_stress]]
=== Stress

*TODO* _Pour faire plaisir à okhin_

[[option_essence_drain]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Technomanciens et Drain d'Essence*

*Règle :* Les technomanciens dépourvus d'<<attribute_essence,Essence>> et de <<attribute_magic,Magie>> sont considérés avoir une valeur d'Essence de 0 dans le cadre du pouvoir de Drain d'Essence.
La nature des technomanciens est en effet foncièrement différente de celle des magiciens, adeptes et autres créatures magiques.

*Motivation :* Réhausser l'intérêt de la <<attribute_resonance,Résonance>> par rapport aux autres <<special_attributes,attributs spéciaux>>.
====


[[option_cybermancy]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Cybermancie*

*Règle :* Normalement, un attribut spécial <<special_attributes,ne peut pas être augmenté>>.
Pourtant, les rituels de cybermancie permettent d'augmenter l'<<attribute_essence,Essence>> d'un sujet sans que celui-ci ait à le faire <<chapter_karma,progresser>> avec son karma.
La cybermancie devient donc une méthode accélerée pour <<chapter_augmentation,augmenter>> toujours davantage un sujet, au prix d'un coût de maintenance important et des effets secondaires que l'on connait.
====

