= Shadowrun 54
:toc: left
:toc-title: Table des Matières
:toclevels: 2
:with-designer-notes!:

// générer avec:
// asciidoctor-pdf <this doc>
// asciidoctor -a stylesheet=<path to css> <this doc>


include::chapters/intro.adoc[]

include::chapters/principles.adoc[]





[[chapter_characters]]
== Personnages

include::chapters/attributes.adoc[]

include::chapters/skills.adoc[]

include::chapters/metatypes.adoc[]

include::chapters/karma.adoc[]

include::chapters/qualities.adoc[]






[[chapter_archetypes]]
== Archétypes

*TODO* _Liste des archétypes, en particulier ceux utilisés pour les exemples.
En effet, c'est mieux si les persos utilisés pour les exemples sont vraiment jouables.
Ne pas oublier de donner un peu de background à chacun pour qu'ils soient vraiment prêts à jouer._


== Règles

=== Modificateurs

*TODO*

=== Infiltration

Lorsqu'un personnage est attentif à son environnement, il effectue un test d'<<attribute_intelligence,Intelligence>> + <<skill_perception,Perception>>.
Ce test lui permet de détecter tout élément dont la signature est inférieure ou égale aux succès obtenus.

Lorsqu'un personnage décide de se dissimuler, il effectue un test d'<<attribute_agility,Agilité>> + <<skill_sneaking,Discrétion>>.
Ses succès se rajoutent à sa propre signature.

Lorsqu'un personnage décide de dissimuler un objet, il effectue un test d'<<attribute_intelligence,Intelligence>> + <<skill_sneaking,Discrétion>>.
Ses succès se rajoutent à la signature de l'objet.

La table ci-dessous donne des exemples de signature correspondant à des objets courants.

[[signature]]
.Signature
[width=70%, options="header", cols="1,^1,1"]
|===
|Le sujet est ...            |Signature |Exemple
|Grand / Bruyant             | 1 |Troll, voiture, coup de feu
|Normal                      | 2 |Humain, parole, enseigne
|Petit / Étouffé             | 3 |Créditube, chat, chuchotements
|Minuscule / Quasi-inaudible | 4 |Porte secrète, micropuce
|Partiellement dissimulé     |+1 |Dans une foule, sous une table, au milieu d'objets similaires
|En mouvement / en évidence  |-1 |Couleurs voyantes, phares
|===

==== Passer un contrôle

[.opposition]
|===
|Garde     |<<attribute_intelligence,Intelligence>> + <<skill_perception,Perception>> |Détection si la Signature est inférieure aux succès obtenus.
|===

[.opposition]
|===
|Détecteur |Indice |Détection si la Signature est inférieure aux succès obtenus.
|===

Lors d'un contrôle donné, chaque détecteur ou garde fait un seul jet.
Tous les équipements dont la signature est inférieure ou égale au nombre de succès obtenus sont détectés.
Ceux dont la signature est supérieure passent le contrôle sans être détectés.

En d'autres termes, la Signature d'un objet est le seuil nécessaire pour qu'il soit détecté.



[[barriers]]
==== Casser des trucs

Il est parfois nécessaire pour un personnage de briser un objet ou se frayer un passage à travers.

Pour cela, le personnage doit être muni d'une arme qui puisse endommager l'objet.
Peu importe que l'arme soit une arme à distance ou une arme de corps à corps, il faut que la situation soit vraisemblable :
inutile d'essayer de défoncer une porte à coup de flèches, ou un mur de plastobéton à coups de couteau !

* L'action se résoud par un <<chapter_combat,test opposé>> entre le personnage et l'objet.
** le personnage est *actif* et fait un *test d'attaque*
** l'objet est *passif* et fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs du personnage et de l'objet :
** si l'objet est vainqueur, il ne se passe rien. Le MJ peut décider que l'arme du personnage est endommagée.
** si le personnage est vainqueur, l'objet coche un nombre de cases de son <<attribute_condition_monitor,moniteur de condition>> que le nombre de *succès nets* du personnage

[[barriers_structure]]
.Barrières
[width=60%, options="header", cols="9,>1"]
|===
|Matériau                                                      |Structure
|Fragile (verre standard)                                      |0
|Simple (pneu, plâtre)                                         |2
|Solide (porte standard, meuble, plastique, verre pare-balles) |4
|Lourd (bois massif, lampadaire, chaîne)                       |6
|Renforcé (porte de sécurité, densiplast, kevlar)              |8
|Structurel (brique, plastobéton)                              |12
|Structurel lourd (béton, poutre en acier)                     |16
|Armuré (béton armé, blindage lourd)                           |24+
|===

Lors de son test de défense, un objet lance un nombre de dés égal à sa structure.

Le <<attribute_condition_monitor,moniteur de condition>> d'un objet comporte un nombre de cases égale à sa structure.




[[chapter_social]]
=== Social

*TODO*



[[option_cyberpsychosis]]
[NOTE.option,caption="Règle optionnelle"]
====
*Cyberpsychose*

*Règle :*
L'attribut d'Essence résume la métahumanité du personnage en un seul nombre.
Plus sa valeur est faible, plus le personnage aura des difficultés dans ses relations avec le reste de la métahumanité.
En termes de jeu, ces difficultés se traduisent par un modificateur négatif aux interactions sociales.
La valeur de ce modificateur dépend de l'Essence du personnage ainsi que de l'époque : plus l'augmentation humaine est ancienne, mieux elle tend à être acceptée par la société en général.
Le modicateur aux interactions sociales souffert par un personnage dépend de son <<attribute_essence,Essence>> restante, comme indiqué dans la table ci-après.

.Cyberpsychose
[cols="3,1,1,1,1,1,1,1", options="header"]
|===
|Essence restante | 6 | 5 | 4 | 3 | 2 | 1 | 0
|Techno-thriller  |±0 |-1 |-1 |-2 |-2 |-3 |-4
|Cyberpunk        |±0 |±0 |±0 |-1 |-1 |-2 |-3
|Post-Cyberpunk   |±0 |±0 |±0 |±0 |±0 |-1 |-1
|===

*Motivation :* Traduire en termes de règles un des fondamentaux du genre cyberpunk.
En raison du fait que l'Essence peut dépasser 6, le modificateur négatif ne doit pas dépendre du montant d'Essence perdue.
En effet, un personnage qui a fait progresser son <<attribute_essence,Essence>> grâce à son karma est d'une certaine manière _plus_ que métahumain ;
donc il ne devrait pas souffrir d'un stigmate social plus lourd !
L'important est la vigueur de l'âme qu'il lui reste, pas le chemin qu'elle a parcouru.
Un MJ pourrait même envisager de donner un modificateur positif aux interactions sociales d'un personnage doté d'une Essence restante supérieure à 6 ...

====

[NOTE.option,caption="Règle optionnelle"]
====
*Essence des interactions humaines*

*Règle :*
Les personnages dépourvus de l'attribut spécial <<attribute_essence,Essence>> souffrent d'un modificateur négatif allant de -1 à -4 à leurs tests sociaux.

On peut en effet considérer qu'un personnage qui fait le choix d'abandonner son attribut d'Essence pour se consacrer à la magie devient encore plus étrange(r) aux yeux des gens normaux.
Après tout, suivant l'époque, les magiciens ou les technomanciens sont aussi aussi entourés de préjugés négatifs, parfois mêmes plus lourds !

Pour quantifier ce handicap social en un modificateur négatif cadrant avec sa vision du monde, le MJ peut s'aider des <<test_modifiers,recommandations>> sur les modificateurs.
De la manière dont la magie ou la technomancie d'un personnage influe sur son humanité devrait découler l'impact de ses capacités surhumaines sur ses relations sociales.

Le modificateur applicable peut être fixe, mais peut aussi dépendre de la puissance des pouvoirs d'un personnage, comme le propose la <<option_weirdos_table,table ci-dessous>>.
En effet, la valeur de son attribut spécial le plus élevé représente directement l'investissement en temps qu'il y a mis et donc la manière dont celui-ci influe sur personnalité.
Or, plus ce pouvoir influe sur sa vision du monde, plus il affecte ses relations avec les gens : le pouvoir corrompt ...

[[option_weirdos_table]]
.Weirdopsychose
[cols="6,1,1,1,1,1,1,1,1,1,1", options="header"]
|===
|<<attribute_magic,Magie>> ou <<attribute_resonance,Résonance>> | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9+
|Modificateur     |±0 |±0 |±0 |-1 |-1 |-2 |-2 |-3 |-3 |-4
|===

*Motivation :* Réhausser l'intérêt de l'Essence face à l'Edge pour les magiciens, adeptes ou technomanciens.
De plus, si la règle optionnelle de <<option_cyberpsychosis,cyberpsychose>> est appliquée, celle-ci permet que les chromés ne soient pas les seuls à souffrir d'un stigmate social.
Et avec l'utilisation conjointe des deux règles optionnelles, le personnage "de base, ni magicien, ni chromé" reprend (un peu) de l'intérêt.
====





[[chapter_combat]]
=== Combat

* Toute violence physique se résoud par un <<opposed_test,test opposé>> :
** l'attaquant est le personnage *actif* : il fait un *test d'attaque*
** le défenseur est le personnage *passif* : il fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs de l'attaquant et du défenseur :
** si le défenseur est vainqueur, il s'en tire sans aucun dommage
** si l'attaquant est vainqueur, le défenseur coche un nombre de cases de son <<condition_monitor,moniteur de condition>> égal au nombre de *succès nets* de l'attaquant

Sauf indication contraire, l'attaquant peut utiliser tout type d'arme à sa disposition, au corps à corps ou à distance, qu'il sache la manier ou non.
Cependant, une même arme ne peut être utilisée qu'une seule fois par passe d'initiative.

*TODO* mettre en évidence la règle d'une seule arme par passe et la volonté de valoriser l'ambidextrie, qui permet de tirer 2 fois une balle en CC ou 2 rafales en TR.



[[combat_distance]]
==== Combat à distance

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>>*

Compétences d'arme concernées : <<skill_pistols,Armes légères>>, <<skill_longarms,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_exotic_weapon,Arme exotique(arme à distance)>>

Exemple de modificateurs : portée, visibilité, malus de blessure de l'attaquant, couvert du défenseur, accessoires de l'arme

====== Modes de tir

De nombreuses armes à distance offrent plusieurs mode de tir.

* Tir unique : action simple, une balle, SS ou SA
* Tir semi-automatique : action complexe, 2 balles, SA
* Tir en rafale : action simple, 3 balles, TR
* Tir automatique : action complexe, 10 balles, TA
* Tir de barrage : action complexe, 20 balles, TA

Au cours d'un test d'attaque à distance, chaque balle après la première et dont le recul est compensé ajoute 1 dé à la réserve de dés.

*TODO* clarifier qu'il ne s'agit pas d'un modificateur, et playtester.

*TODO* qu'arrive-t'il aux balles non compensées ? --> règle optionnel du passant innocent / dommages colatéraux

===== Test de défense

*<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[combat_melee]]
==== Corps à corps

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>> + <<attribute_body,Constitution>>*

Compétences d'arme concernées : <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>, <<skill_exotic_weapon,Arme exotique(arme de corps à corps)>>

Exemple de modificateurs : visibilité, malus de blessure de l'attaquant

===== Test de défense

*<<attribute_reaction,Réaction>> + <compétence d'arme>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[defense_test_suprise]]
==== Surprise

Si un personnage est surpris, il ne peut pas attaquer jusqu'à ce qu'il puisse agir.
Il ne peut pas non plus entreprendre aucune des manoeuvre de défense active que sont la parade ou l'esquive.

En conséquence, sa réserve de dés lors de son <<combat_defense_test,Test de défense>> est réduite :

*<<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*



[[combat_round]]
==== Déroulement d'un tour de combat

*TODO*


include::chapters/crafting.adoc[]

include::chapters/augmentation.adoc[]

include::chapters/magic.adoc[]

include::chapters/matrix.adoc[]

include::chapters/gear.adoc[]










== Règles optionnelles

*TODO* _Chaque règle optionnelle devrait peut-être se trouver directement dans le chapitre concerné, plutôt que pêle-mêle dans un chapitre à part._

[[option_only_one_pass]]
=== Une seule passe d'initiative

*TODO* _Tous les persos n'ont qu'une passe ; les passes supplémentaires sont convertis en effet pops sur les actions_

[[option_stress]]
=== Stress

*TODO* _Pour faire plaisir à okhin_

[[option_essence_drain]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Technomanciens et Drain d'Essence*

*Règle :* Les technomanciens dépourvus d'<<attribute_essence,Essence>> et de <<attribute_magic,Magie>> sont considérés avoir une valeur d'Essence de 0 dans le cadre du pouvoir de Drain d'Essence.
La nature des technomanciens est en effet foncièrement différente de celle des magiciens, adeptes et autres créatures magiques.

*Motivation :* Réhausser l'intérêt de la <<attribute_resonance,Résonance>> par rapport aux autres <<special_attributes,attributs spéciaux>>.
====


[[option_cybermancy]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Cybermancie*

*Règle :* Normalement, un attribut spécial <<special_attributes,ne peut pas être augmenté>>.
Pourtant, les rituels de cybermancie permettent d'augmenter l'<<attribute_essence,Essence>> d'un sujet sans que celui-ci ait à le faire <<chapter_karma,progresser>> avec son karma.
La cybermancie devient donc une méthode accélerée pour <<chapter_augmentation,augmenter>> toujours davantage un sujet, au prix d'un coût de maintenance important et des effets secondaires que l'on connait.
====



include::chapters/faq.adoc[]
