= Shadowrun 5.4
little black dog <lbd@shadowforums.com>
:toc: left
:toc-title: Table des Matières
:toclevels: 2

// générer avec:
// asciidoctor-pdf <this doc>
// asciidoctor -a stylesheet=<path to css> <this doc>

Rapide résumé.


1 couverture
2 dédicace
3 résumé super rapide des règles
4 table des matières
5 objectifs
7 principes de jeu
 - succès & seuils
 - tests
 - modificateurs
9 personnage
 - attributs physiques et mentaux
 - attributs spéciaux
   - edge effects
 - caractéristiques secondaires
 - compétences (conversion)
 - metatypes
12 création de personnage
 - karma & progression
   + coûts des attributs, compétences etc
   + achat de l'équipement
 - qualities
20 archétypes
30 règles
 - modificateurs
 - infiltration
 - social
 - combat: distance
     types de tir
 - combat: c/c
     casser des trucs
 - magie
     sorcellerie
	 invocation
 - matrice
 - TODO: véhicules
 - déroulement d'un tour de combat
     passes d'initiative
	 action (attaque)
	 conversion de passes en bonus (attaque de zone, etc)
38 règles optionnelles
 - limites: skill/2
 - ajuster la léthalité
 - convertir passes d'init en effets pops
 - règles de stress
 - custom races: liste traits raciaux
40 équipement
 - flingues
 - melee
 - kits de compétence
 - augmentations
  + table "coût en essence/pouvoir" <> bénéfice
50 notes du concepteur
55 commentaires: le but est-il atteint ?
60 TODO: fiche de personnage


¹
²
³







== Objectifs

Quitte à refaire un système de jeu, autant l'améliorer. Du moins, d'un certain point de vue.
Chaque modification, chaque ajout ou retrait au système existant doit se faire en poursuivant les objectifs suivants.

* *Conserver le système de base* identique à celui des dernières éditions : une réserve de dés égale à attribut+compétence ; les 5 et les 6 comptent dans le nombre de succès.
* Définir des modificateurs simples et génériques aux réserves et aux seuils. On ne fait que *décliner* ces modificateurs, quel que soit le type d'action.
* Simplifier les règles pour *accélérer l'action*.
  Réduire le nombre de tests nécessaires à accomplir quelque chose, en particulier en ce qui concerne le combat et la matrice.
  Réduire aussi les calculs à faire pour calculer le nombre de succès nets.
* *Simplifier* les règles pour les rendre plus digestes. Limiter la nécessité d'avoir à consulter ses bouquins en pleine partie. +
  La présentation des règles elle-même devrait :
  ** Être claire et concise pour en faciliter la compréhension. Éviter d'obscurcir les règles avec de l'humour ou des appartés.
  ** Profiter du format numérique pour s'auto-référencer, facilitant ainsi le fait de retrouver une information précise.
* Rééquilibrer les différents profils de personage.
  ** Tout les profils devraient pouvoir contribuer d'une manière ou d'une autre à une situation donnée.
  ** Le jeu de rôle se joue _en groupe_ : éviter que certains puissent tout faire, tout le temps.
  ** Même si Shadowrun est un jeu à matos, ce sont les personnages, pas leurs outils, qui devraient primer.

== Principes de jeu

=== Test simple

* Le personnage lance une *réserve de dés* à 6 faces égale à *attribut + compétence*.
  Tous les dés dont le score est de 5 ou 6 représentent des *succès nets*.
* On compare les succès nets avec un *seuil* fixé par le MJ pour déterminer si l'action est une réussite ou un échec.

.Seuils
[width=35%, options="header"]
|===
|Seuil |Résultat

|0 ou -|Échec
|1     |Grossier
|2     |Standard
|3     |Pas mal
|4     |Très précis
|===

[[chapter_modifiers]]
=== Modificateurs

Chaque test peut se voir assorti de modificateurs, reflétant la difficulté de la tâche entreprise.
Cette difficulté est issue de circonstances indépendantes des facultés du personnage.
Cela peut venir d'un peu n'importe quoi : l'environnement extérieur, les blessures qui affectent le personnage, la résistance passive d'un sujet, et ainsi de suite.

Quelle qu'en soit la source, un modificateur s'ajoute ou se retranche à la réserve de dés.
Si différents modificateurs s'appliquent à un test donné, il suffit d'en faire la somme avant de l'appliquer à la réserve de dés du personnage.

Différents tests peuvent se voir assortis de différents modificateurs.
Ceux-ci sont détaillés dans les différents chapitres de ce livre, mais constituent toujours de simples applications des règles suivantes :

* si l'action du personnage est facilitée, le modificateur est positif. Si le personnage est gêné, le modificateur est négatif.
* un modificateur de 1 représente une petite aide ou une légère gène, quelque chose de presque imperceptible pour le personnage.
* un modificateur de 4 ou plus représente un méchant handicap ou une aide qui fait quasiment le travail à la place du personnage.

Si la situation n'est pas couverte par une règle précise, ou que le MJ n'a pas envie de se compliquer la vie, il peut utiliser la table suivante, qui montre les modificateurs les plus courants.

.Modificateurs
[width=35%, options="header"]
|===
|Difficulté       |Modificateur

|Action facile    |+1 à +10
|Action difficile |-1 à -10
|===

Si les modificateurs négatifs sont si importants qu'ils font passer la réserve de dés d'un personnage à 0 ou moins, la tâche entreprise semble impossible, et la plupart du temps l'action échoue automatiquement.
Dans ce cas, un personnage a néanmoins deux ultimes recours :

* il peut utiliser l'<<attribute_edge,Edge>> pour se donner des dés supplémentaires et surmonter la difficulté.
* le MJ peut toujours autoriser le personnage à lancer un unique dé. Si ce dé fait 5 ou 6, l'action réussit ... tout juste !


[[option_dices_cap]]
[NOTE.option,caption="Règle optionnelle"]
====
*Réserve de dés maximum*

*Règle :* Au cours d'un test, après application des modificateurs à une réserve de dés, le nombre maximal de dés à lancer ne peut jamais dépasser le nombre de dés tel qu'il était avant application des modificateurs.

*Motivation :* Cette règle vise à maîtriser l'inflation des réserves de dés.
Pour cela, il faut rendre à l'équipement son véritable rôle : rendre les personnages capables d'accomplir des actions en dépit de difficultés parfois extrêmes, et non pas faire le travail à leur place, en leur permettre d'obtenir un résultat exceptionnel en dépit de leur manque de compétence.
====

[[option_limits]]
[NOTE.option,caption="Règle optionnelle"]
====
*Limites*

*Règle :* Le nombre de *succès nets* que peut obtenir un personnage sur un jet de dés est égal à l'indice de la *compétence utilisée*.

*Motivation :* Cette règle vise à ...
Faire comme SR5 ? Gâcher la joie d'un coup de chance sur un jet de dé ?
Avec la disparition des limites liées à l'équipement, elle permet peut-être de valoriser les compétences par rapport aux attributs.
À vous de voir.
====




[[opposed_tests]]
=== Test opposé

Cela représente un conflit direct entre deux personnage, ou entre un personnage et un drone, etc.
Pour simplifier, on va qualifier un des deux opposants le personnage *actif*, et le second le personnage *passif*.

* Les deux opposants lancent chacun une *réserve de dés* à 6 faces égale à leur *attribut + compétence* respectifs.
  Tous les dés dont le score est de 5 ou 6 représentent des *succès*.
* On retranche au nombre de succès du personnage actif le nombre de succès du personnage passif.
  Le nombre de succès restants représente le nombre de *succès nets*.
* On compare ces *succès nets* avec le *seuil* fixé par le MJ pour déterminer si l'action est une réussite ou un échec.










[[chapter_characters]]
== Personnages

=== Attributs physiques et mentaux

SR5.4 compte 4 attributs primaires répartis en deux attributs physiques (<<attribute_agility,Agilité>> et <<attribute_reaction,Réaction>>) et deux attributs mentaux (<<attribute_intelligence,Intelligence>> et <<attribute_charisma,Charisme>>).

La valeur d'un attribut ne peut jamais être inférieure à 1.
Un attribut peut <<chapter_karma,progresser>> jusqu'à la valeur de 6.
Un attribut peut être <<chapter_augmentation,augmenté>> jusqu'à la valeur de 9.

[[attribute_agility]]
==== AGILITÉ
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_reaction]]
==== RÉACTION
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_intelligence]]
==== INTELLIGENCE
Attribut inchangé par rapport à SR1, SR2 et SR3. Fusionne les rôles des attributs *Intuition* et *Logique* en SR4 et SR5.

[[attribute_charisma]]
==== CHARISME
Fusionne les rôles des anciens attributs *Volonté* et *Charisme*.


[[special_attributes]]
=== Attributs spéciaux

Tout personnage ne peut jamais avoir que deux attributs spéciaux en même temps.

Un attribut spécial peut seulement <<chapter_karma,progresser grâce au karma>>.
Un attribut spécial ne peut pas être <<chapter_augmentation,augmenté>>.

La valeur minimum d'un attribut spécial est de 1.
Un attribut spécial n'a pas de valeur maximum.

Un personnage possédant deux attributs spéciaux mais désirant <<quality_special_attribute,acquérir un nouvel attribut spécial>> doit forcément en abandonner au moins un autre.

Par défaut, un personnage commence avec les attributs spéciaux <<attribute_edge,Edge>> et <<attribute_essence,Essence>>.


[[option_specials_buckets]]
[NOTE.option,caption="Règle optionnelle"]
====
*Influence entre attributs spéciaux*

*Règle :* Lorsqu'un personnage possède deux attributs spéciaux, la valeur maximum du second est de 12 moins la valeur de son premier attribut spécial.

Ainsi, lorsqu'un personnage fait progresser un de ses attributs spéciaux, l'autre peut être amené à baisser.
Lorsqu'un attribut spécial baisse, le personnage perd le karma et/ou les nuyens investis.
Si, pour une raison ou une autre, le second attribut spécial ne peut pas baisser, la premier attribut spécial ne peut pas augmenter. Le personnage ne perd alors pas le karma et/ou les nuyens investis.

À partir du moment où le score d'un de ses attribut spéciaux atteint 12, le personnage perd son second attribut spécial.

*Motivation :* Cette règle vise à limiter la polyvalence d'un personnage ayant une valeur très élevée dans un de ses attributs spéciaux, en le forçant à ne pouvoir utiliser plus que cet attribut spécial précis.

Par exemple, si tu t'inities, ton <<attribute_edge,Edge>> peut se mettre à baisser. Si ton mago a de l'<<attribute_essence,Essence>> et est blindé de cyberware, 'va falloir te mettre à purger ton chrome d'une façon ou d'une autre avant d'augmenter ta <<attribute_magic,Magie>>. Ou alors, ton cyber va devenir inopérant. Ou encore, tu vas mourir dans d'atroces souffrances lorsque ton âme s'en ira sans prévenir. Tu as envie de tenter l'expérience, _omae_ ?

_Peut-être illustrer ce cas avec l'exemple de ?Tom? le chaman Ours troll en Afrique du Sud dans Nuit de Sang._
====




[[attribute_edge]]
==== EDGE
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_essence]]
==== ESSENCE
Attribut inchangé par rapport à SR4 et SR5, hormis les points suivants :

* Contrairement aux autres attributs spéciaux, sa valeur de départ est de 6.
* Un personnage peut le faire progresser en dépensant des points de karma, comme n'importe quel attribut spécial.
* Un personnage peut utiliser l'intégralité son essence pour <<chapter_augmentation,s'augmenter>>.
  Pas besoin de garder une Essence strictement positive ; son Essence restante peut être égale à zéro.
  Cependant, si le coût en Essence de son <<chapter_augmentation,augmentation>> devient strictement supérieure à sa valeur d'Essence, il meurt.
* Un personnage peut, sous certaines conditions, <<quality_special_attribute,échanger son attribut d'Essence>> contre un autre attribut spécial.
** Toutefois, un personnage dépourvu d'Essence ne peut bénéficier d'aucune <<chapter_augmentation,augmentation>> due à la technologie.
   Il est possible que toute intervention bénéfique devienne inexplicablement inopérante ou nuisible à son organisme.
   Ou alors, son corps rejette systématiquement, rapidement et plus ou moins proprement et douloureusement les implants.
   Le personnage peut aussi mourir sans prévenir lors d'une complication sur la table d'opérations, par exemple parce que son âme décide de quitter son corps.
   Envie de tenter l'expérience, _omae_ ?
** Un personnage dépourvu d'essence est considéré avoir une valeur d'Essence égale à celle de son attribut spécial le plus élevé.
   S'il se retrouve dans une situation où son Essence est amenée à baisser, c'est cet autre attribut spécial qui baisse à la place.
   Si la perte d'Essence est temporaire, cet autre attribut spécial se reconstitue au même rythme que l'aurait fait l'Essence.

[[attribute_magic]]
==== MAGIE
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_equilibrium]]
==== ÉQUILIBRE
L'attribut spécial *Équilibre* est utilisé par les adeptes pour acquérir leurs pouvoirs.
Il représente l'équilibre que maintient tout éveillé entre son comportement et sa nature profonde pour déployer ses pouvoirs.

[[attribute_resonance]]
==== RÉSONANCE
Attribut inchangé par rapport à SR4 et SR5.

[[secondary_attributes]]
=== Caractéristiques secondaires

Le <<chapter_karma,karma>> ne peut pas faire progresser directement ces deux attributs, que cela soit à la création de personnage ou ultérieurement.
L'<<chapter_augmentation,augmentation>> le peut, de 3 points maximum.

[[attribute_initiative]]
==== INITIATIVE
Le rôle de l'initiative reste largement inchangée. On lui ajoute le résultat d'un ou plusieurs D6 pour donner le score d'initiative. Voir le chapitre <<combat_round,combat>> pour davantage de détails.
Sa valeur de base dépend du contexte:

.Initiative
[width=25%]
|===
|Physique |<<attribute_reaction,Réaction>>
|RA       |<<attribute_reaction,Réaction>>
|RV       |<<attribute_intelligence,Intelligence>>
|Astral   |<<attribute_intelligence,Intelligence>>
|===



[[attribute_body]]
==== CONSTITUTION
La constitution est maintenant un attribut secondaire. Elle regroupe les anciens attributs de *Force* et *Constitution*, et reflète en particulier la supériorité physique des trolls, orks, nains et métahumains augmentés. Une Constitution élevée reflète dans la majorité des cas une taille plus grande, un stature plus large, de gros muscles, ... Enfin, vous avez saisi l'idée.

Sa valeur intervient comme modificateur dans différents contextes :

* résister aux dommages *<<chapter_combat,[?]>>*
* infliger des dommages au corps à corps *<<combat_melee,[?]>>*
* casser des trucs au corps à corps *<<barriers,[?]>>*
* calculer son encombrement [lien]
* intimider son prochain [lien]

La valeur de Constitution d'un humain non augmenté est de 0.



[[attribute_condition_monitor]]
==== MONITEUR DE CONDITION
* Le nombre de cases du moniteur de condition physique est de *10 + <<attribute_body,Constitution>>*.
* Le nombre de cases du moniteur de condition étourdissant est de *8 + <<attribute_charisma,Charisme>>/2*.

[[option_one_condition_monitor]]
[NOTE.option,caption="Règle optionnelle"]
====
*Un seul moniteur de condition*

*Règle :* Chaque personnage n'utilise plus qu'un seul moniteur de condition.
Ce moniteur unique tient compte à la fois des dommages physiques et étourdissants.

Son nombre de cases est de *8 + <<attribute_charisma,Charisme>>/2 + <<attribute_body,Constitution>>*.

On marque les blessures étourdissants d'une "coche" et les blessures physiques d'une "croix", comme le marquage des blessures léthales et aggravées dans le monde des ténèbres.
Quand le moniteur de condition d'un personnage est rempli d'un mix de "coches" et de "croix", et qu'il subit des dommages (que ceux-ci soient physiques ou étourdissants) les "coches" deviennent des "croix".
Quand le moniteur est rempli de croix, la mort est proche.

*Motivation :* Cette règle propose d'accélérer le jeu, aussi bien en rendant plus immédiate la gestion des blessures qu'en augmentant la lethalité des combats.
====



include::chapters/skills.adoc[]

include::chapters/metatypes.adoc[]

include::chapters/karma.adoc[]

include::chapters/qualities.adoc[]






[[chapter_archetypes]]
== Archétypes

*TODO* _Liste des archétypes, en particulier ceux utilisés pour les exemples.
En effet, c'est mieux si les persos utilisés pour les exemples sont vraiment jouables.
Ne pas oublier de donner un peu de background à chacun pour qu'ils soient vraiment prêts à jouer._


== Règles

=== Modificateurs

*TODO*

=== Infiltration

*TODO*

==== Passer un contrôle

[.opposition]
|===
|Garde     |<<attribute_intelligence,Intelligence>> + <<skill_perception,Perception>> |Détection si Signature est inférieure aux succès obtenus.
|===

[.opposition]
|===
|Détecteur |Indice |Détection si la Signature est inférieure aux succès obtenus.
|===

Lors d'un contrôle donné, chaque détecteur ou garde fait un seul jet.
Tous les équipements illégaux dont la signature est inférieure ou égale au succès obtenus est détectée.
Ceux dont la signature est supérieure passent le contrôle sans être détectés.

En d'autres termes, la Signature d'un objet est le seuil nécessaire pour qu'il soit détecté.



[[barriers]]
==== Casser des trucs

Il est parfois nécessaire pour un personnage de briser un objet ou se frayer un passage à travers.

Pour cela, le personnage doit être muni d'une arme qui puisse endommager l'objet.
Peu importe que l'arme soit une arme à distance ou une arme de corps à corps, il faut que la situation soit vraisemblable :
inutile d'essayer de défoncer une porte à coup de flèches, ou un mur de plastobéton à coups de couteau !

* L'action se résoud par un <<chapter_combat,test opposé>> entre le personnage et l'objet.
** le personnage est *actif* et fait un *test d'attaque*
** l'objet est *passif* et fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs du personnage et de l'objet :
** si l'objet est vainqueur, il ne se passe rien. Le MJ peut décider que l'arme du personnage est endommagée.
** si le personnage est vainqueur, l'objet coche un nombre de cases de son <<attribute_condition_monitor,moniteur de condition>> que le nombre de *succès nets* du personnage

[[barriers_structure]]
.Barrières
[width=60%, options="header", cols="9,>1"]
|===
|Matériau                                                      |Structure
|Fragile (verre standard)                                      |0
|Simple (pneu, plâtre)                                         |2
|Solide (porte standard, meuble, plastique, verre pare-balles) |4
|Lourd (bois massif, lampadaire, chaîne)                       |6
|Renforcé (porte de sécurité, densiplast, kevlar)              |8
|Structurel (brique, plastobéton)                              |12
|Structurel lourd (béton, poutre en acier)                     |16
|Armuré (béton armé, blindage lourd)                           |24+
|===

Lors de son test de défense, un objet lance un nombre de dés égal à sa structure.

Le <<attribute_condition_monitor,moniteur de condition>> d'un objet comporte un nombre de cases égale à sa structure.




[[chapter_social]]
=== Social

*TODO*



[[option_cyberpsychosis]]
[NOTE.option,caption="Règle optionnelle"]
====
*Cyberpsychose*

*Règle :*
L'attribut d'Essence résume la métahumanité du personnage en un seul nombre.
Plus sa valeur est faible, plus le personnage aura des difficultés dans ses relations avec le reste de la métahumanité.
En termes de jeu, ces difficultés se traduisent par un modificateur négatif aux interactions sociales.
La valeur de ce modificateur dépend de l'Essence du personnage ainsi que de l'époque : plus l'augmentation humaine est ancienne, mieux elle tend à être acceptée par la société en général.
Le modicateur aux interactions sociales souffert par un personnage dépend de son <<attribute_essence,Essence>> restante, comme indiqué dans la table ci-après.

.Cyberpsychose
[cols="3,1,1,1,1,1,1,1", options="header"]
|===
|Essence restante | 6 | 5 | 4 | 3 | 2 | 1 | 0
|Techno-thriller  |±0 |-1 |-1 |-2 |-2 |-3 |-4
|Cyberpunk        |±0 |±0 |±0 |-1 |-1 |-2 |-3
|Post-Cyberpunk   |±0 |±0 |±0 |±0 |±0 |-1 |-1
|===

*Motivation :* Traduire en termes de règles un des fondamentaux du genre cyberpunk.
En raison du fait que l'Essence peut dépasser 6, le modificateur négatif ne doit pas dépendre du montant d'Essence perdue.
En effet, un personnage qui a fait progresser son <<attribute_essence,Essence>> grâce à son karma est d'une certaine manière _plus_ que métahumain ;
donc il ne devrait pas souffrir d'un stigmate social plus lourd !
L'important est la vigueur de l'âme qu'il lui reste, pas le chemin qu'elle a parcouru.
Les fans de la Mascarade pourraient même donner un modificateur positif aux interactions sociales d'un personnage doté d'une Essence restante supérieure à 6 ...

====

[NOTE.option,caption="Règle optionnelle"]
====
*Essence des interactions humaines*

*Règle :*
Les personnages dépourvus de l'attribut spécial <<attribute_essence,Essence>> souffrent d'un modificateur négatif allant de -1 à -4 à leurs tests sociaux.

On peut en effet considérer qu'un personnage qui fait le choix d'abandonner son attribut d'Essence pour se consacrer à la magie devient encore plus étrange(r) aux yeux des gens normaux.
Après tout, suivant l'époque, les magiciens ou les technomanciens sont aussi aussi entourés de préjugés négatifs, parfois mêmes plus lourds !

Pour quantifier ce handicap social en un modificateur négatif cadrant avec sa vision du monde, le MJ peut s'aider des <<chapter_modifiers,recommandations>> sur les modificateurs.
De la manière dont la magie ou la technomancie d'un personnage influe sur son humanité devrait découler l'impact de ses capacités surhumaines sur ses relations sociales.

Le modificateur applicable peut être fixe, mais peut aussi dépendre de la puissance des pouvoirs d'un personnage, comme le propose la <<option_weirdos_table,table ci-dessous>>.
En effet, la valeur de son attribut spécial le plus élevé représente directement l'investissement en temps qu'il y a mis et donc la manière dont celui-ci influe sur personnalité.
Or, plus ce pouvoir influe sur sa vision du monde, plus il affecte ses relations avec les gens : le pouvoir corrompt ...

[[option_weirdos_table]]
.Weirdopsychose
[cols="6,1,1,1,1,1,1,1,1,1", options="header"]
|===
|<<attribute_magic,Magie>>,<<attribute_equilibrium,Équilibre>> ou <<attribute_resonance,Résonance>> | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8+
|Modificateur     |±0 |±0 |±0 |-1 |-1 |-2 |-3 |-3 |-4
|===

*Motivation :* Réhausser l'intérêt de l'Essence face à l'Edge pour les magiciens, adeptes ou technomanciens.
De plus, si la règle optionnelle de <<option_cyberpsychosis,cyberpsychose>> est appliquée, celle-ci permet que les chromés ne soient pas les seuls à souffrir d'un stigmate social.
Et avec l'utilisation conjointe des deux règles optionnelles, le personnage "de base, ni magicien, ni chromé" reprend (un peu) de l'intérêt.
====





[[chapter_combat]]
=== Combat

* Toute violence physique se résoud par un <<opposed_tests,test opposé>> :
** l'attaquant est le personnage *actif* : il fait un *test d'attaque*
** le défenseur est le personnage *passif* : il fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs de l'attaquant et du défenseur :
** si le défenseur est vainqueur, il s'en tire sans aucun dommage
** si l'attaquant est vainqueur, le défenseur coche un nombre de cases de son <<condition_monitor,moniteur de condition>> égal au nombre de *succès nets* de l'attaquant

Sauf indication contraire, l'attaquant peut utiliser tout type d'arme à sa disposition, au corps à corps ou à distance, qu'il sache la manier ou non.
Cependant, une même arme ne peut être utilisée qu'une seule fois par passe d'initiative.

*TODO* mettre en évidence la règle d'une seule arme par passe et la volonté de valoriser l'ambidextrie, qui permet de tirer 2 fois une balle en CC ou 2 rafales en TR.



[[combat_distance]]
==== Combat à distance

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>>*

Compétences d'arme concernées : <<skill_pistols,Armes légères>>, <<skill_longarms,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_exotic_weapon,Arme exotique(arme à distance)>>

Exemple de modificateurs : portée, visibilité, malus de blessure de l'attaquant, couvert du défenseur, accessoires de l'arme

====== Modes de tir

De nombreuses armes à distance offrent plusieurs mode de tir.

* Tir unique : action simple, une balle, SS ou SA
* Tir semi-automatique : action complexe, 2 balles, SA
* Tir en rafale : action simple, 3 balles, TR
* Tir automatique : action complexe, 10 balles, TA
* Tir de barrage : action complexe, 20 balles, TA

Au cours d'un test d'attaque à distance, chaque balle après la première et dont le recul est compensé ajoute 1 dé à la réserve de dés.

*TODO* clarifier qu'il ne s'agit pas d'un modificateur, et playtester.

*TODO* qu'arrive-t'il aux balles non compensées ? --> règle optionnel du passant innocent / dommages colatéraux

===== Test de défense

*<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[combat_melee]]
==== Corps à corps

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>> + <<attribute_body,Constitution>>*

Compétences d'arme concernées : <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>, <<skill_exotic_weapon,Arme exotique(arme de corps à corps)>>

Exemple de modificateurs : visibilité, malus de blessure de l'attaquant

===== Test de défense

*<<attribute_reaction,Réaction>> + <compétence d'arme>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[defense_test_suprise]]
==== Surprise

Si un personnage est surpris, il ne peut pas attaquer jusqu'à ce qu'il puisse agir.
Il ne peut pas non plus entreprendre aucune des manoeuvre de défense active que sont la parade ou l'esquive.

En conséquence, sa réserve de dés lors de son <<combat_defense_test,Test de défense>> est réduite :

*<<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*



[[combat_round]]
==== Déroulement d'un tour de combat

*TODO*



[[chapter_augmentation]]
=== Augmentation

*TODO*





include::chapters/magic.adoc[]




[[chapter_matrix]]
=== Matrice

*TODO*





== Équipement

[[gear_grades]]
=== Grades d'équipement

Afin de répondre à tous les besoins (et à tous les segments de marché), de nombreux produits sont disponibles en plusieurs grades, reflétant leur qualité de production -et leur prix.
Les grades sont les suivants :

.Grades d'équipement
[width=50%, options="header", cols="2*,.>"]
|===
|Grade    |Disponibilité |Prix
|Standard |-             |×1
|Alpha    |+2            |×2
|Beta     |+4            |×5
|Delta    |+8            |×10
|Omega    |-4            |×0.5
|===

* Le grade *Standard* représente les produits de grande consommation, sans personnalisation. Tous les équipements présentés dans ce chapitre sont de grade Standard.
* Le grade *Omega* représente des produits d'occasion, usagés, endommagés, démodés, ou dont l'usage a été suplanté par une technologie plus récente. Dans la plupart des cas, et hormis son prix, il est en tout point inférieur au grade Standard.
* Les autres grades représentent divers raffinements et personnalisations du produit, toujours de qualité supérieure au grade Standard. Le grade *Delta* représente le SOTA, ce qui se fait de mieux, et qui profite des plus récentes avancées technologiques pour une époque donnée.

Un produit donné ne peut être que d'un seul grade, qui peut varier suivant l'époque.

Dans une époque techno-thriller, par exemple, il est en général encore impossible de se faire implanter du cyberware d'occasion, car cette technologie est encore trop neuve et trop peu fiable.
De même, l'avènement du cyberware est encore trop récent pour avoir été rafiné en produits de grade delta.
À l'inverse, au fur et à mesure des innovations et des changements de direction technologiques (en ce qui concerne les différentes infrastructures matricielles qui se sont succédées, par exemple),
les époques ultérieures ont rendu obsolètes plusieurs produits anciennement de grade Standard ou supérieur.
Ces produits sont passés au grade Omega, quand il n'ont pas été rendus purement et simplement inutilisables.



[[gear_weapons]]
=== Armes

==== Caractéristiques

===== Dégâts

Représente le nombre de dés supplémentaires à lancer lors d'un test d'attaque.

* Le caractère **+** devant signifie que la <<attribute_body,Constitution>> de l'utilisateur s'ajoute aux dégâts de l'arme.
* Le caractère **S** derrière signifie que l'arme occasionne des dégâts étourdissants.

===== Signature

La signature d'une arme représente son Seuil pour la détecter lors d'un contrôle.



==== Armes de mêlée

[[gear_weapons_melee]]
.Armes de mêlée
[width="70%", options="header", cols="4,^1,^1,^1,>1"]
|===
|Arme                  |Dégâts|Signature|Disponibilité |Prix
|Bâton                 | +2S  | 0¹      |2             |   50¥
|Batte                 | +2   | 1       |-             |   10¥
|Couteau de combat     | +1   | 3       |-             |   25¥
|Électro-matraque      |  4S  | 1       |4R            |  750¥
|Épée                  | +2   | 1       |6R            |  500¥
|Fouet                 | +1   | 1       |2             |   50¥
|Fouet monofilament    |  3³  | 0       |12F           | 3000¥
|Gant énergétique²     |  4S  | 2       |6R            | 1000¥
|Hache de combat       | +4   | 0       |8R            | 1000¥
|Matraque              | +1S  | 3       |-             |   10¥
|Lames d'avant-bras    | +2   | 0¹      |6R            |  150¥
|Tomahawk              | +2   | 2       |4             |   50¥
|===
¹ Lorsque cette arme est rétractée, sa Signature est augmentée de 2.
² S'utilise avec la compétence <<skill_unarmed,Combat à mains nues>>.
³ La cible ne bénéficie pas de son armure.



==== Armes à distance

[[gear_weapons_throwing]]
.Armes de jet
[options="header", cols="4,^1,^1,^3,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Signature|Disponibilité |Prix
|Couteau de lancer     | CC  | +1   |  TODO          | 3       | 4            |   25¥
|Grenade TODO          | CC  |TODO  |  TODO          | TODO    |TODO          | TODO¥
|Grenade TODO          | CC  |TODO  |  TODO          | TODO    |TODO          | TODO¥
|Grenade TODO          | CC  |TODO  |  TODO          | TODO    |TODO          | TODO¥
|Tomahawk              | CC  | +2   |  TODO          | 4       | 4            |   50¥
|===

[[gear_weapons_archery]]
.Armes de trait
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Signature|Disponibilité |Prix
|Arc                   | CC  |+4    |  5/50/150/300  |  1(f)   | 0       |2             |  300¥
|===

[[gear_weapons_pistols]]
.Armes de poing
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Signature|Disponibilité |Prix
|Arbalète de poing     |CC/TR|  2   |  5/10/15/20    |  3(f)   | 2       |4R            |  300¥
|Taser                 | CC  |  4S  |  5/10/15/20    |  4(m)   | 2       |-             |  200¥
|Pistolet petit calibre| CC  |  2   |  5/15/30/50    |  6(c)   | 4       |4R            |  150¥
|Pistolet léger        | SA  |  2   |  5/15/30/50    | 12(c)   | 3       |4R            |  250¥
|Pistolet automatique  | TR  |  2   |  5/15/30/50    | 35(c)   | 3       |8R            |  500¥
|Pistolet lourd        | SA  |  3   |  5/20/40/60    | 12(c)   | 2       |4R            |  500¥
|Pistolet mitrailleur  | TR  |  3   | 10/40/80/120   | 24(c)   | 1       |6R            |  750¥
|===

[[gear_weapons_rifles]]
.Armes d'épaule
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Signature|Disponibilité |Prix
|Arbalète lourde       | CC  |  4   | 10/40/80/120   |  1(f)   | 1       |4R            |  300¥
|Fusil à pompe         | SA  |  4   | 10/40/80/120   |  8(m)   | 1       |4R            | 1000¥
|Fusil d'assaut     |SA/TR/TA|  3   | 50/150/300/500 | 35(c)   | 1       |8F            | 2000¥
|Fusil de chasse       | CC  |  4   |100/250/500/800 |  8(m)   | 0       |4R            | 1000¥
|Fusil de sniper       | CC  |  5   |150/300/800/1500| 12(c)   | 0¹      |12F           |10000¥
|===

[[gear_weapons_heavy]]
.Armes lourdes
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts |Portée          |Munitions      |Signature|Disponibilité |Prix
|Mitrailleuse          | TA  |  6    | 80/250/800/1200|50(c) ou 100(b)|0/Oublie |12F           | 7500¥
|Canon d'assaut        | CC  |  8    |100/300/800/1500| 20(c)         |0/Oublie |20F           | 5000¥
|Lance-grenades        | CC  |Grenade|*50/100/150/500 |  8(m)         | 1       |10F           | 1500¥
|Lance-missiles        | CC  |Missile|*80/250/500/1500|  1(ml)        |0/Oublie |10F           | 1500¥
|===



[[gear_armor]]
=== Armures

L'indice d'une armure représente le nombre de dés supplémentaires à lancer lors du <<defense_test,test de défense>> du personnage qui la porte.

.Armures
[width=70%, options="header", cols="4,^2,>3,>3"]
|===
|Armure              |Indice |Disponibilité |Prix
|Vêtements normaux   |0      |-             |20¥-100000¥
|Vêtements renforcés |1      |2             |500¥
|Veste blindée       |2      |4             |1000¥
|Armure de sécurité  |4      |14R           |2000¥
|===

Altérer le grade d'une armure influe sur son indice de protection, comme l'indique la <<gear_armor_grades,table suivante>>.

[[gear_armor_grades]]
.Armures: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Indice
|Alpha    |+1
|Beta     |+2
|Delta    |+3
|Omega    |-1¹
|===
¹ L'indice ne peut pas passer en dessous de 0.
Des vêtements normaux de grade Omega sont très démodés ou portent clairement un ou plusieurs témoignages de leur porteur précédent, et peuvent infliger un modificateur négatif aux <<chapter_social,interactions sociales>> du personnage qui les porte.



[[gear_cyberdeck]]
=== Cyberdecks

L'indice d'un cyberdeck représente la puissance globale de ses composants et des programmes installés.
Le détail des spécifications techniques varie grandement, et l'indice lui même subit diverses appellations (par exemple, MPCP ou FADS) suivant l'époque.
Dans tous les cas, l'indice du cyberdeck utilisé par un personnage entre directement dans le calcul de la réserve de dés lors des <<chapter_matrix,actions matricielles>> qu'il entreprend.

.Cyberdecks
[width=25%, options="header", cols="^1,>2"]
|===
|Indice|Prix
|1     |  4000¥
|2     |  8000¥
|3     | 16000¥
|4     | 32000¥
|5     | 64000¥
|6     |128000¥
|===

Altérer le grade d'un cyberdeck influe sur l'initiative de son l'utilisateur, comme l'indique la <<gear_cyberdeck_grades,la table suivante>>.

[[gear_cyberdeck_grades]]
.Cyberdecks: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Initiative
|Alpha    |+1D6
|Beta     |+2D6
|Delta    |+3D6
|Omega¹   |-
|===
¹ Un cyberdeck de grade Omega ne peut pas passer en Hot-Sim.


[[gear_false_identity]]
=== Fausses identités

La Signature d'une fausse identité ou d'un faux permis correspond à son Indice.

L'Indice maximal d'une fausse identité ou d'un faux permis est de 6.

Si une fausse identité est mise à jour, tous les faux permis associés le sont aussi.

.Fausses identités
[width=50%, options="header", cols="1,^1,>1"]
|===
|Type            |Disponibilité |Prix
|Fausse identité |(Indice × 3)F |Indice × 2500¥
|Faux permis     |(Indice × 3)F |Indice ×  200¥
|===




=== Kits de compétence

*TODO*

=== Drogues

*TODO* _'Pas trop mon truc, mais bon ..._
















== Règles optionnelles

*TODO* _Chaque règle optionnelle devrait peut-être se trouver directement dans le chapitre concerné, plutôt que pêle-mêle dans un chapitre à part._


[[option_LMSF_wounds]]
=== Blessures Légères, Moyenne, Graves et Fatales

Cette règle propose d'accélérer le jeu en augmentant la léthalité des combats.
En même temps, elle donne en même temps un peit coté _old school_ aux combats, puisqu'elle est inspiré de ce qui faisait en SR1, SR2 et SR3.

Plutôt que de cocher un nombre de cases du <<attribute_condition_monitor,moniteur de condition>> d'un personnage égal au nombre de succès nets optenus par l'attaquant, on utilise le tableau suivant :

.Types de blessure
[width=33%, cols="^1,^2,>1" options="header"]
|===
|Succès |Blessure |Cases
|1      |Légère   |1
|2      |Moyenne  |3
|3      |Grave    |6
|4      |Fatale   |10
|===

Évidemment, un personnage ayant plus de 10 cases dans son <<attribute_condition_monitor,moniteur de condition>> ne sera pas mis hors combat par une seule blessure fatale.
C'est voulu, afin d'éviter de mettre le troll blindé d'augmentations au même niveau que le simple piéton sur un coup de chance de l'attaquant.

Le meneur de jeu peut n'appliquer cette règle que sur les hommes de main et autres PNJs anonymes, en reprenant éventuellement le niveau de professionnalisme de l'époque, pour se faciliter la tâche.


[[option_only_one_pass]]
=== Une seule passe d'initiative

*TODO* _Tous les persos n'ont qu'une passe ; les passes supplémentaires sont convertis en effet pops sur les actions_

[[option_stress]]
=== Stress

*TODO* _Pour faire plaisir à okhin_

[[option_essence_drain]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Technomanciens et Drain d'Essence*

*Règle :* Les technomanciens dépourvus d'<<attribute_essence,Essence>>, mais aussi de <<attribute_magic,Magie>> et d'<<attribute_equilibrium,Équilibre>>, sont considérés avoir une valeur d'Essence de 0 dans le cadre du pouvoir de Drain d'Essence.
La nature des technomanciens est en effet foncièrement différente de celle des magiciens, adeptes et autres créatures magiques.

*Motivation :* Réhausser l'intérêt de la <<attribute_resonance,Résonance>> par rapport aux autres <<special_attributes,attributs spéciaux>>.
====


[[option_cybermancy]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Cybermancie*

*Règle :* Normalement, un attribut spécial <<special_attributes,ne peut pas être augmenté>>.
Pourtant, les rituels de cybermancie permettent d'augmenter l'<<attribute_essence,Essence>> d'un sujet sans que celui-ci ait à le faire <<chapter_karma,progresser>> avec son karma.
La cybermancie devient donc une méthode accélerée pour <<chapter_augmentation,augmenter>> toujours davantage un sujet, au prix d'un coût de maintenance important et des effets secondaires que l'on connait.
====

