= Shadowrun 5.4
little black dog <lbd@shadowforums.com>
:toc: left
:toc-title: Table des Matières
:toclevels: 2

// générer avec:
// asciidoctor-pdf <this doc>
// asciidoctor -a stylesheet=<path to css> <this doc>

Rapide résumé.


1 couverture
2 dédicace
3 résumé super rapide des règles
4 table des matières
5 objectifs
7 principes de jeu
 - succès & seuils
 - tests
 - modificateurs
9 personnage
 - attributs physiques et mentaux
 - attributs spéciaux
   - edge effects
 - caractéristiques secondaires
 - compétences (conversion)
 - metatypes
12 création de personnage
 - karma & progression
   + coûts des attributs, compétences etc
   + achat de l'équipement
 - qualities
20 archétypes
30 règles
 - modificateurs
 - infiltration
 - social
 - combat: distance
     types de tir
 - combat: c/c
     casser des trucs
 - magie
     sorcellerie
	 invocation
 - matrice
 - TODO: véhicules
 - déroulement d'un tour de combat
     passes d'initiative
	 action (attaque)
	 conversion de passes en bonus (attaque de zone, etc)
38 règles optionnelles
 - limites: skill/2
 - ajuster la léthalité
 - convertir passes d'init en effets pops
 - règles de stress
 - custom races: liste traits raciaux
40 équipement
 - flingues
 - melee
 - kits de compétence
 - augmentations
  + table "coût en essence/pouvoir" <> bénéfice
50 notes du concepteur
55 commentaires: le but est-il atteint ?
60 TODO: fiche de personnage









== Objectifs

Quitte à refaire un système de jeu, autant l'améliorer. Du moins, d'un certain point de vue.
Chaque modification, chaque ajout ou retrait au système existant doit se faire en poursuivant les objectifs suivants.

* *Conserver le système de base* identique à celui des dernières éditions : une réserve de dés égale à attribut+compétence ; les 5 et les 6 comptent dans le nombre de succès.
* Définir des modificateurs simples et génériques aux réserves et aux seuils. On ne fait que *décliner* ces modificateurs, quel que soit le type d'action.
* Simplifier les règles pour *accélérer l'action*.
  Réduire le nombre de tests nécessaires à accomplir quelque chose, en particulier en ce qui concerne le combat et la matrice.
  Réduire aussi les calculs à faire pour calculer le nombre de succès nets.
* *Simplifier* les règles pour les rendre plus digestes. Limiter la nécessité d'avoir à consulter ses bouquins en pleine partie. +
  La présentation des règles elle-même devrait :
  ** Être claire et concise pour en faciliter la compréhension. Éviter d'obscurcir les règles avec de l'humour ou des appartés.
  ** Profiter du format numérique pour s'auto-référencer, facilitant ainsi le fait de retrouver une information précise.
* Rééquilibrer les différents profils de personage.
  ** Tout les profils devraient pouvoir contribuer d'une manière ou d'une autre à une situation donnée.
  ** Le jeu de rôle se joue _en groupe_ : éviter que certains puissent tout faire, tout le temps.
  ** Même si Shadowrun est un jeu à matos, ce sont les personnages, pas leurs outils, qui devraient primer.

== Principes de jeu

=== Test simple

* Le personnage lance une *réserve de dés* à 6 faces égale à *attribut + compétence*.
  Tous les dés dont le score est de 5 ou 6 représentent des *succès nets*.
* On compare les succès nets avec un *seuil* fixé par le MJ pour déterminer si l'action est une réussite ou un échec.

.Seuils
[width=35%, options="header"]
|===
|Seuil |Résultat

|0 ou -|Échec
|1     |Grossier
|2     |Standard
|3     |Pas mal
|4     |Très précis
|===

[[chapter_modifiers]]
=== Modificateurs

Chaque test peut se voir assorti de modificateurs, reflétant la difficulté de la tâche entreprise.
Cette difficulté est issue de circonstances indépendantes des facultés du personnage.
Cela peut venir d'un peu n'importe quoi : l'environnement extérieur, les blessures qui affectent le personnage, la résistance passive d'un sujet, et ainsi de suite.

Quelle qu'en soit la source, un modificateur s'ajoute ou se retranche à la réserve de dés.
Si différents modificateurs s'appliquent à un test donné, il suffit d'en faire la somme avant de l'appliquer à la réserve de dés du personnage.

Différents tests peuvent se voir assortis de différents modificateurs.
Ceux-ci sont détaillés dans les différents chapitres de ce livre, mais constituent toujours de simples applications des règles suivantes :

* si l'action du personnage est facilitée, le modificateur est positif. Si le personnage est gêné, le modificateur est négatif.
* un modificateur de 1 représente une petite aide ou une légère gène, quelque chose de presque imperceptible pour le personnage.
* un modificateur de 4 ou plus représente un méchant handicap ou une aide qui fait quasiment le travail à la place du personnage.

Si la situation n'est pas couverte par une règle précise, ou que le MJ n'a pas envie de se compliquer la vie, il peut utiliser la table suivante, qui montre les modificateurs les plus courants.

.Modificateurs
[width=35%, options="header"]
|===
|Difficulté       |Modificateur

|Action facile    |+1 à +10
|Action difficile |-1 à -10
|===

Si les modificateurs négatifs sont si importants qu'ils font passer la réserve de dés d'un personnage à 0 ou moins, la tâche entreprise semble impossible, et la plupart du temps l'action échoue automatiquement.
Dans ce cas, un personnage a néanmoins deux ultimes recours :

* il peut utiliser l'<<attribute_edge,Edge>> pour se donner des dés supplémentaires et surmonter la difficulté.
* le MJ peut toujours autoriser le personnage à lancer un unique dé. Si ce dé fait 5 ou 6, l'action réussit ... tout juste !


[[option_dices_cap]]
[NOTE.option,caption="Règle optionnelle"]
====
*Réserve de dés maximum*

*Règle :* Au cours d'un test, après application des modificateurs à une réserve de dés, le nombre maximal de dés à lancer ne peut jamais dépasser le nombre de dés tel qu'il était avant application des modificateurs.

*Motivation :* Cette règle vise à maîtriser l'inflation des réserves de dés.
Pour cela, il faut rendre à l'équipement son véritable rôle : rendre les personnages capables d'accomplir des actions en dépit de difficultés parfois extrêmes, et non pas faire le travail à leur place, en leur permettre d'obtenir un résultat exceptionnel en dépit de leur manque de compétence.
====

[[option_limits]]
[NOTE.option,caption="Règle optionnelle"]
====
*Limites*

*Règle :* Le nombre de *succès nets* que peut obtenir un personnage sur un jet de dés est égal à l'indice de la *compétence utilisée*.

*Motivation :* Cette règle vise à ...
Faire comme SR5 ? Gâcher la joie d'un coup de chance sur un jet de dé ?
Avec la disparition des limites liées à l'équipement, elle permet peut-être de valoriser les compétences par rapport aux attributs.
À vous de voir.
====




[[opposed_tests]]
=== Test opposé

Cela représente un conflit direct entre deux personnage, ou entre un personnage et un drone, etc.
Pour simplifier, on va qualifier un des deux opposants le personnage *actif*, et le second le personnage *passif*.

* Les deux opposants lancent chacun une *réserve de dés* à 6 faces égale à leur *attribut + compétence* respectifs.
  Tous les dés dont le score est de 5 ou 6 représentent des *succès*.
* On retranche au nombre de succès du personnage actif le nombre de succès du personnage passif.
  Le nombre de succès restants représente le nombre de *succès nets*.
* On compare ces *succès nets* avec le *seuil* fixé par le MJ pour déterminer si l'action est une réussite ou un échec.










[[chapter_characters]]
== Personnages

=== Attributs physiques et mentaux

SR5.4 compte 4 attributs primaires répartis en deux attributs physiques (<<attribute_agility,Agilité>> et <<attribute_reaction,Réaction>>) et deux attributs mentaux (<<attribute_intelligence,Intelligence>> et <<attribute_charisma,Charisme>>).

La valeur d'un attribut ne peut jamais être inférieure à 1.
Un attribut peut <<chapter_karma,progresser>> jusqu'à la valeur de 6.
Un attribut peut être <<chapter_augmentation,augmenté>> jusqu'à la valeur de 9.

[[attribute_agility]]
==== AGILITÉ
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_reaction]]
==== RÉACTION
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_intelligence]]
==== INTELLIGENCE
Attribut inchangé par rapport à SR1, SR2 et SR3. Fusionne les rôles des attributs *Intuition* et *Logique* en SR4 et SR5.

[[attribute_charisma]]
==== CHARISME
Fusionne les rôles des anciens attributs *Volonté* et *Charisme*.


[[special_attributes]]
=== Attributs spéciaux

Tout personnage ne peut jamais avoir que deux attributs spéciaux en même temps.

Un attribut spécial peut seulement <<chapter_karma,progresser grâce au karma>>.
Un attribut spécial ne peut pas être <<chapter_augmentation,augmenté>>.

La valeur minimum d'un attribut spécial est de 1.
Un attribut spécial n'a pas de valeur maximum.

Un personnage possédant deux attributs spéciaux mais désirant <<quality_special_attribute,acquérir un nouvel attribut spécial>> doit forcément en abandonner au moins un autre.

Par défaut, un personnage commence avec les attributs spéciaux <<attribute_edge,Edge>> et <<attribute_essence,Essence>>.


[[option_specials_buckets]]
[NOTE.option,caption="Règle optionnelle"]
====
*Influence entre attributs spéciaux*

*Règle :* Lorsqu'un personnage possède deux attributs spéciaux, la valeur maximum du second est de 12 moins la valeur de son premier attribut spécial.

Ainsi, lorsqu'un personnage fait progresser un de ses attributs spéciaux, l'autre peut être amené à baisser.
Lorsqu'un attribut spécial baisse, le personnage perd le karma et/ou les nuyens investis.
Si, pour une raison ou une autre, le second attribut spécial ne peut pas baisser, la premier attribut spécial ne peut pas augmenter. Le personnage ne perd alors pas le karma et/ou les nuyens investis.

À partir du moment où le score d'un de ses attribut spéciaux atteint 12, le personnage perd son second attribut spécial.

*Motivation :* Cette règle vise à limiter la polyvalence d'un personnage ayant une valeur très élevée dans un de ses attributs spéciaux, en le forçant à ne pouvoir utiliser plus que cet attribut spécial précis.

Par exemple, si tu t'inities, ton <<attribute_edge,Edge>> peut se mettre à baisser. Si ton mago a de l'<<attribute_essence,Essence>> et est blindé de cyberware, 'va falloir te mettre à purger ton chrome d'une façon ou d'une autre avant d'augmenter ta <<attribute_magic,Magie>>. Ou alors, ton cyber va devenir inopérant. Ou encore, tu vas mourir dans d'atroces souffrances lorsque ton âme s'en ira sans prévenir. Tu as envie de tenter l'expérience, _omae_ ?

_Peut-être illustrer ce cas avec l'exemple de ?Tom? le chaman Ours troll en Afrique du Sud dans Nuit de Sang._
====




[[attribute_edge]]
==== EDGE
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_essence]]
==== ESSENCE
Attribut inchangé par rapport à SR4 et SR5, hormis les points suivants :

* Contrairement aux autres attributs spéciaux, sa valeur de départ est de 6.
* Un personnage peut le faire progresser en dépensant des points de karma, comme n'importe quel attribut spécial.
* Un personnage peut utiliser l'intégralité son essence pour <<chapter_augmentation,s'augmenter>>.
  Pas besoin de garder une Essence strictement positive ; son Essence restante peut être égale à zéro.
  Cependant, si le coût en Essence de son <<chapter_augmentation,augmentation>> devient strictement supérieure à sa valeur d'Essence, il meurt.
* Un personnage peut, sous certaines conditions, <<quality_special_attribute,échanger son attribut d'Essence>> contre un autre attribut spécial.
** Toutefois, un personnage dépourvu d'Essence ne peut bénéficier d'aucune <<chapter_augmentation,augmentation>> due à la technologie.
   Il est possible que toute intervention bénéfique devienne inexplicablement inopérante ou nuisible à son organisme.
   Ou alors, son corps rejette systématiquement, rapidement et plus ou moins proprement et douloureusement les implants.
   Le personnage peut aussi mourir sans prévenir lors d'une complication sur la table d'opérations, par exemple parce que son âme décide de quitter son corps.
   Envie de tenter l'expérience, _omae_ ?
** Un personnage dépourvu d'essence est considéré avoir une valeur d'Essence égale à celle de son attribut spécial le plus élevé.
   S'il se retrouve dans une situation où son Essence est amenée à baisser, c'est cet autre attribut spécial qui baisse à la place.
   Si la perte d'Essence est temporaire, cet autre attribut spécial se reconstitue au même rythme que l'aurait fait l'Essence.

[[attribute_magic]]
==== MAGIE
Attribut inchangé par rapport à SR4 et SR5.

[[attribute_equilibrium]]
==== ÉQUILIBRE
L'attribut spécial *Équilibre* est utilisé par les adeptes pour acquérir leurs pouvoirs.
Il représente l'équilibre que maintient tout éveillé entre son comportement et sa nature profonde pour déployer ses pouvoirs.

[[attribute_resonance]]
==== RÉSONANCE
Attribut inchangé par rapport à SR4 et SR5.

[[secondary_attributes]]
=== Caractéristiques secondaires

Le <<chapter_karma,karma>> ne peut pas faire progresser directement ces deux attributs, que cela soit à la création de personnage ou ultérieurement.
L'<<chapter_augmentation,augmentation>> le peut, de 3 points maximum.

[[attribute_initiative]]
==== INITIATIVE
Le rôle de l'initiative reste largement inchangée. On lui ajoute le résultat d'un ou plusieurs D6 pour donner le score d'initiative. Voir le chapitre <<combat_round,combat>> pour davantage de détails.
Sa valeur de base dépend du contexte:

.Initiative
[width=25%]
|===
|Physique |<<attribute_reaction,Réaction>>
|RA       |<<attribute_reaction,Réaction>>
|RV       |<<attribute_intelligence,Intelligence>>
|Astral   |<<attribute_intelligence,Intelligence>>
|===



[[attribute_body]]
==== CONSTITUTION
La constitution est maintenant un attribut secondaire. Elle regroupe les anciens attributs de *Force* et *Constitution*, et reflète en particulier la supériorité physique des trolls, orks, nains et métahumains augmentés. Une Constitution élevée reflète dans la majorité des cas une taille plus grande, un stature plus large, de gros muscles, ... Enfin, vous avez saisi l'idée.

Sa valeur intervient comme modificateur dans différents contextes :

* résister aux dommages *<<chapter_combat,[?]>>*
* infliger des dommages au corps à corps *<<combat_melee,[?]>>*
* casser des trucs au corps à corps *<<barriers,[?]>>*
* calculer son encombrement [lien]
* intimider son prochain [lien]

La valeur de Constitution d'un humain non augmenté est de 0.



[[attribute_condition_monitor]]
==== MONITEUR DE CONDITION
* Le nombre de cases du moniteur de condition physique est de *10 + <<attribute_body,Constitution>>*.
* Le nombre de cases du moniteur de condition étourdissant est de *8 + <<attribute_charisma,Charisme>>/2*.

[[option_one_condition_monitor]]
[NOTE.option,caption="Règle optionnelle"]
====
*Un seul moniteur de condition*

*Règle :* Chaque personnage n'utilise plus qu'un seul moniteur de condition.
Ce moniteur unique tient compte à la fois des dommages physiques et étourdissants.

Son nombre de cases est de *8 + <<attribute_charisma,Charisme>>/2 + <<attribute_body,Constitution>>*.

On marque les blessures étourdissants d'une "coche" et les blessures physiques d'une "croix", comme le marquage des blessures léthales et aggravées dans le monde des ténèbres.
Quand le moniteur de condition d'un personnage est rempli d'un mix de "coches" et de "croix", et qu'il subit des dommages (que ceux-ci soient physiques ou étourdissants) les "coches" deviennent des "croix".
Quand le moniteur est rempli de croix, la mort est proche.

*Motivation :* Cette règle propose d'accélérer le jeu, aussi bien en rendant plus immédiate la gestion des blessures qu'en augmentant la lethalité des combats.
====



include::chapters/skills.adoc[]

include::chapters/metatypes.adoc[]

include::chapters/karma.adoc[]

include::chapters/qualities.adoc[]






[[chapter_archetypes]]
== Archétypes

*TODO* _Liste des archétypes, en particulier ceux utilisés pour les exemples.
En effet, c'est mieux si les persos utilisés pour les exemples sont vraiment jouables.
Ne pas oublier de donner un peu de background à chacun pour qu'ils soient vraiment prêts à jouer._


== Règles

=== Modificateurs

*TODO*

=== Infiltration

*TODO*



[[barriers]]
==== Casser des trucs

*TODO* _trouver dans quel chapitre ranger ça (infiltration ou combat?)

Il est parfois nécessaire pour un personnage de briser un objet ou se frayer un passage à travers.

Pour cela, le personnage doit être muni d'une arme qui puisse endommager l'objet.
Peu importe que l'arme soit une arme à distance ou une arme de corps à corps, il faut que la situation soit vraisemblable :
inutile d'essayer de défoncer une porte à coup de flèches, ou un mur de plastobéton à coups de couteau !

* L'action se résoud par un <<chapter_combat,test opposé>> entre le personnage et l'objet.
** le personnage est *actif* et fait un *test d'attaque*
** l'objet est *passif* et fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs du personnage et de l'objet :
** si l'objet est vainqueur, il ne se passe rien. Le MJ peut décider que l'arme du personnage est endommagée.
** si le personnage est vainqueur, l'objet coche un nombre de cases de son <<attribute_condition_monitor,moniteur de condition>> que le nombre de *succès nets* du personnage

[[barriers_structure]]
.Barrières
[width=60%, options="header", cols="9,>1"]
|===
|Matériau                                                      |Structure
|Fragile (verre standard)                                      |0
|Simple (pneu, plâtre)                                         |2
|Solide (porte standard, meuble, plastique, verre pare-balles) |4
|Lourd (bois massif, lampadaire, chaîne)                       |6
|Renforcé (porte de sécurité, densiplast, kevlar)              |8
|Structurel (brique, plastobéton)                              |12
|Structurel lourd (béton, poutre en acier)                     |16
|Armuré (béton armé, blindage lourd)                           |24+
|===

Lors de son test de défense, un objet lance un nombre de dés égal à sa structure.

Le <<attribute_condition_monitor,moniteur de condition>> d'un objet comporte un nombre de cases égale à sa structure.




[[chapter_social]]
=== Social

*TODO*



[[option_cyberpsychosis]]
[NOTE.option,caption="Règle optionnelle"]
====
*Cyberpsychose*

*Règle :*
L'attribut d'Essence résume la métahumanité du personnage en un seul nombre.
Plus sa valeur est faible, plus le personnage aura des difficultés dans ses relations avec le reste de la métahumanité.
En termes de jeu, ces difficultés se traduisent par un modificateur négatif aux interactions sociales.
La valeur de ce modificateur dépend de l'Essence du personnage ainsi que de l'époque : plus l'augmentation humaine est ancienne, mieux elle tend à être acceptée par la société en général.
Le modicateur aux interactions sociales souffert par un personnage dépend de son <<attribute_essence,Essence>> restante, comme indiqué dans la table ci-après.

.Cyberpsychose
[cols="3,1,1,1,1,1,1,1", options="header"]
|===
|Essence restante | 6 | 5 | 4 | 3 | 2 | 1 | 0
|Techno-thriller  |±0 |-1 |-1 |-2 |-2 |-3 |-4
|Cyberpunk        |±0 |±0 |±0 |-1 |-1 |-2 |-3
|Post-Cyberpunk   |±0 |±0 |±0 |±0 |±0 |-1 |-1
|===

*Motivation :* Traduire en termes de règles un des fondamentaux du genre cyberpunk.
En raison du fait que l'Essence peut dépasser 6, le modificateur négatif ne doit pas dépendre du montant d'Essence perdue.
En effet, un personnage qui a fait progresser son <<attribute_essence,Essence>> grâce à son karma est d'une certaine manière _plus_ que métahumain ;
donc il ne devrait pas souffrir d'un stigmate social plus lourd !
L'important est la vigueur de l'âme qu'il lui reste, pas le chemin qu'elle a parcouru.
Les fans de la Mascarade pourraient même donner un modificateur positif aux interactions sociales d'un personnage doté d'une Essence restante supérieure à 6 ...

====

[NOTE.option,caption="Règle optionnelle"]
====
*Essence des interactions humaines*

*Règle :*
Les personnages dépourvus de l'attribut spécial <<attribute_essence,Essence>> souffrent d'un modificateur négatif allant de -1 à -4 à leurs tests sociaux.

On peut en effet considérer qu'un personnage qui fait le choix d'abandonner son attribut d'Essence pour se consacrer à la magie devient encore plus étrange(r) aux yeux des gens normaux.
Après tout, suivant l'époque, les magiciens ou les technomanciens sont aussi aussi entourés de préjugés négatifs, parfois mêmes plus lourds !

Pour quantifier ce handicap social en un modificateur négatif cadrant avec sa vision du monde, le MJ peut s'aider des <<chapter_modifiers,recommandations>> sur les modificateurs.
De la manière dont la magie ou la technomancie d'un personnage influe sur son humanité devrait découler l'impact de ses capacités surhumaines sur ses relations sociales.

Le modificateur applicable peut être fixe, mais peut aussi dépendre de la puissance des pouvoirs d'un personnage, comme le propose la <<option_weirdos_table,table ci-dessous>>.
En effet, la valeur de son attribut spécial le plus élevé représente directement l'investissement en temps qu'il y a mis et donc la manière dont celui-ci influe sur personnalité.
Or, plus ce pouvoir influe sur sa vision du monde, plus il affecte ses relations avec les gens : le pouvoir corrompt ...

[[option_weirdos_table]]
.Weirdopsychose
[cols="6,1,1,1,1,1,1,1,1,1", options="header"]
|===
|<<attribute_magic,Magie>>,<<attribute_equilibrium,Équilibre>> ou <<attribute_resonance,Résonance>> | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8+
|Modificateur     |±0 |±0 |±0 |-1 |-1 |-2 |-3 |-3 |-4
|===

*Motivation :* Réhausser l'intérêt de l'Essence face à l'Edge pour les magiciens, adeptes ou technomanciens.
De plus, si la règle optionnelle de <<option_cyberpsychosis,cyberpsychose>> est appliquée, celle-ci permet que les chromés ne soient pas les seuls à souffrir d'un stigmate social.
Et avec l'utilisation conjointe des deux règles optionnelles, le personnage "de base, ni magicien, ni chromé" reprend (un peu) de l'intérêt.
====





[[chapter_combat]]
=== Combat

* Toute violence physique se résoud par un <<opposed_tests,test opposé>> :
** l'attaquant est le personnage *actif* : il fait un *test d'attaque*
** le défenseur est le personnage *passif* : il fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs de l'attaquant et du défenseur :
** si le défenseur est vainqueur, il s'en tire sans aucun dommage
** si l'attaquant est vainqueur, le défenseur coche un nombre de cases de son <<condition_monitor,moniteur de condition>> égal au nombre de *succès nets* de l'attaquant

Sauf indication contraire, l'attaquant peut utiliser tout type d'arme à sa disposition, au corps à corps ou à distance, qu'il sache la manier ou non.
Cependant, une même arme ne peut être utilisée qu'une seule fois par passe d'initiative.

*TODO* mettre en évidence la règle d'une seule arme par passe et la volonté de valoriser l'ambidextrie, qui permet de tirer 2 fois une balle en CC ou 2 rafales en TR.



[[combat_distance]]
==== Combat à distance

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>>*

Compétences d'arme concernées : <<skill_pistols,Armes légères>>, <<skill_longarms,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_exotic_weapon,Arme exotique(arme à distance)>>

Exemple de modificateurs : portée, visibilité, malus de blessure de l'attaquant, couvert du défenseur, accessoires de l'arme

====== Modes de tir

De nombreuses armes à distance offrent plusieurs mode de tir.

* Tir unique : action simple, une balle, SS ou SA
* Tir semi-automatique : action complexe, 2 balles, SA
* Tir en rafale : action simple, 3 balles, TR
* Tir automatique : action complexe, 10 balles, TA
* Tir de barrage : action complexe, 20 balles, TA

Au cours d'un test d'attaque à distance, chaque balle après la première et dont le recul est compensé ajoute 1 dé à la réserve de dés.

*TODO* clarifier qu'il ne s'agit pas d'un modificateur, et playtester.

*TODO* qu'arrive-t'il aux balles non compensées ? --> règle optionnel du passant innocent / dommages colatéraux

===== Test de défense

*<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[combat_melee]]
==== Corps à corps

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>> + <<attribute_body,Constitution>>*

Compétences d'arme concernées : <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>, <<skill_exotic_weapon,Arme exotique(arme de corps à corps)>>

Exemple de modificateurs : visibilité, malus de blessure de l'attaquant

===== Test de défense

*<<attribute_reaction,Réaction>> + <compétence d'arme>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[defense_test_suprise]]
==== Surprise

Si un personnage est surpris, il ne peut pas attaquer jusqu'à ce qu'il puisse agir.
Il ne peut pas non plus entreprendre aucune des manoeuvre de défense active que sont la parade ou l'esquive.

En conséquence, sa réserve de dés lors de son <<combat_defense_test,Test de défense>> est réduite :

*<<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*



[[combat_round]]
==== Déroulement d'un tour de combat

*TODO*



[[chapter_augmentation]]
=== Augmentation

*TODO*





include::chapters/magic.adoc[]




[[chapter_matrix]]
=== Matrice

*TODO*





== Équipement

[[gear_grades]]
=== Grades d'équipement

Afin de répondre à tous les besoins (et à tous les segments de marché), de nombreux produits sont disponibles en plusieurs grades, reflétant leur qualité de production -et leur prix.
Les grades sont les suivants :

.Grades d'équipement
[width=50%, options="header", cols="2*,.>"]
|===
|Grade    |Disponibilité |Prix
|Standard |-             |×1
|Alpha    |+2            |×2
|Beta     |+4            |×5
|Delta    |+8            |×10
|Omega    |-4            |×0.5
|===

* Le grade *Standard* représente les produits de grande consommation, sans personnalisation. Tous les équipements présentés dans ce chapitre sont de grade Standard.
* Le grade *Omega* représente des produits d'occasion, usagés, endommagés, démodés, ou dont l'usage a été suplanté par une technologie plus récente. Dans la plupart des cas, et hormis son prix, il est en tout point inférieur au grade Standard.
* Les autres grades représentent divers raffinements et personnalisations du produit, toujours de qualité supérieure au grade Standard. Le grade *Delta* représente le SOTA, ce qui se fait de mieux, et qui profite des plus récentes avancées technologiques pour une époque donnée.

Un produit donné ne peut être que d'un seul grade, qui peut varier suivant l'époque.

Dans une époque techno-thriller, par exemple, il est en général encore impossible de se faire implanter du cyberware d'occasion, car cette technologie est encore trop neuve et trop peu fiable.
De même, l'avènement du cyberware est encore trop récent pour avoir été rafiné en produits de grade delta.
À l'inverse, au fur et à mesure des innovations et des changements de direction technologiques (en ce qui concerne les différentes infrastructures matricielles qui se sont succédées, par exemple),
les époques ultérieures ont rendu obsolètes plusieurs produits anciennement de grade Standard ou supérieur.
Ces produits sont passés au grade Omega, quand il n'ont pas été rendus purement et simplement inutilisables.



[[gear_weapons]]
=== Armes

==== Armes de mêlée

.Armes de mêlée
[width="70%", options="header", cols="4,^1,^1,^1,>1"]
|===
|Arme                  |Dégâts|Dissimulation|Disponibilité |Prix
|Bâton                 | +2S  |+8           |2             |   50¥
|Batte                 | +2S  |+4           |-             |   10¥
|Couteau de combat     | +1   |-2           |-             |   25¥
|Électro-matraque      |  6S  |+4           |4R            |  750¥
|Épée                  | +2   |+6           |6R            |  500¥
|Hache de combat       | +4   |+8           |8R            | 1000¥
|Matraque              | +1S  |-2           |-             |   10¥
|Lames d'avant-bras    | +2   |+4¹          |6R            |  150¥
|===

.Armes exotiques
[width="70%", options="header", cols="4,^1,^1,^1,>1"]
|===
|Arme                  |Dégâts|Dissimulation|Disponibilité |Prix
|Fouet                 | +0   |+2           |4             |   50¥
|Fouet monofilament    |  6   | 0           |12F           | 3000¥
|Gant énergétique      |  6S  |-2           |6R            | 1000¥
|===

==== Armes à distance

.Armes de trait
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Dissimulation|Disponibilité |Prix
|Arc                   | CC  | 4    |  5/50/150/300  |  1(f)   |+8           |2             |  300¥
|Arbalète              | CC  | 5    | 10/30/90/150   |  1(f)   |+6           |4R            |  300¥
|===

.Armes de poing
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Dissimulation|Disponibilité |Prix
|Taser                 | CC  |  8S  |  5/10/15/20    |  4(m)   |0            |-             |  200¥
|Pistolet petit calibre| CC  |  4   |  5/15/30/50    |  6(c)   |-4           |4R            |  150¥
|Pistolet léger        | SA  |  4   |  5/15/30/50    | 12(c)   |-2           |4R            |  250¥
|Pistolet automatique  |SA/TR|  4   |  5/15/30/50    | 35(c)   |0            |8R            |  500¥
|Pistolet lourd        | SA  |  5   |  5/20/40/60    | 12(c)   |0            |4R            |  500¥
|Pistolet mitrailleur  | TR  |  5   | 10/40/80/120   | 24(c)   |+2           |6R            |  750¥
|===

.Armes d'épaule
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Dissimulation|Disponibilité |Prix
|Fusil à pompe         | SA  |  6   | 10/40/80/120   |  8(m)   |+6           |4R            | 1000¥
|Fusil d'assaut        |TR/TA|  6   | 50/150/300/500 | 35(c)   |+6           |8F            | 2000¥
|Fusil de chasse       | CC  |  6   |100/250/500/800 |  8(m)   |+6           |4R            | 1000¥
|Fusil de sniper       | CC  |  7   |150/300/800/1500| 12(c)   |+8¹          |12F           |10000¥
|===

.Armes lourdes
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts |Portée          |Munitions      |Dissimulation|Disponibilité |Prix
|Mitrailleuse          | TA  |  8    | 80/250/800/1200|50(c) ou 100(b)|+10/Oublie   |12F           | 7500¥
|Canon d'assaut        | CC  | 10    |100/300/800/1500| 20(c)         |+10/Oublie   |20F           | 5000¥
|Lance-grenades        | CC  |Grenade|*50/100/150/500 |  8(m)         | +8          |10F           | 1500¥
|Lance-missiles        | CC  |Missile|*80/250/500/1500|  1(ml)        |+10/Oublie   |10F           | 1500¥
|===



[[gear_armor]]
=== Armures

L'indice d'une armure représente le nombre de dés supplémentaires à lancer lors du <<defense_test,test de défense>> du personnage qui la porte.

.Armures
[width=70%, options="header", cols="4,^2,>3,>3"]
|===
|Armure              |Indice |Disponibilité |Prix
|Vêtements normaux   |0      |-             |20¥-100000¥
|Vêtements renforcés |1      |2             |500¥
|Veste blindée       |2      |4             |1000¥
|Armure de sécurité  |4      |14R           |2000¥
|===

Altérer le grade d'une armure influe sur son indice de protection, comme l'indique la <<gear_armor_grades,table suivante>>.

[[gear_armor_grades]]
.Armures: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Indice
|Alpha    |+1
|Beta     |+2
|Delta    |+3
|Omega    |-1¹
|===
¹ L'indice ne peut pas passer en dessous de 0.
Des vêtements normaux de grade Omega sont très démodés ou portent clairement un ou plusieurs témoignages de leur porteur précédent, et peuvent infliger un modificateur négatif aux <<chapter_social,interactions sociales>> du personnage qui les porte.



[[gear_cyberdeck]]
=== Cyberdecks

L'indice d'un cyberdeck représente la puissance globale de ses composants et des programmes installés.
Le détail des spécifications techniques varie grandement, et l'indice lui même subit diverses appellations (par exemple, MPCP ou FADS) suivant l'époque.
Dans tous les cas, l'indice du cyberdeck utilisé par un personnage entre directement dans le calcul de la réserve de dés lors des <<chapter_matrix,actions matricielles>> qu'il entreprend.

.Cyberdecks
[width=25%, options="header", cols="^1,>2"]
|===
|Indice|Prix
|1     |  4000¥
|2     |  8000¥
|3     | 16000¥
|4     | 32000¥
|5     | 64000¥
|6     |128000¥
|===

Altérer le grade d'un cyberdeck influe sur l'initiative de son l'utilisateur, comme l'indique la <<gear_cyberdeck_grades,la table suivante>>.

[[gear_cyberdeck_grades]]
.Cyberdecks: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Initiative
|Alpha    |+1D6
|Beta     |+2D6
|Delta    |+3D6
|Omega¹   |-
|===
¹ Un cyberdeck de grade Omega ne peut pas passer en Hot-Sim.



=== Kits de compétence

*TODO*

=== Drogues

*TODO* _'Pas trop mon truc, mais bon ..._
















== Règles optionnelles

*TODO* _Chaque règle optionnelle devrait peut-être se trouver directement dans le chapitre concerné, plutôt que pêle-mêle dans un chapitre à part._


[[option_LMSF_wounds]]
=== Blessures Légères, Moyenne, Graves et Fatales

Cette règle propose d'accélérer le jeu en augmentant la léthalité des combats.
En même temps, elle donne en même temps un peit coté _old school_ aux combats, puisqu'elle est inspiré de ce qui faisait en SR1, SR2 et SR3.

Plutôt que de cocher un nombre de cases du <<attribute_condition_monitor,moniteur de condition>> d'un personnage égal au nombre de succès nets optenus par l'attaquant, on utilise le tableau suivant :

.Types de blessure
[width=33%, cols="^1,^2,>1" options="header"]
|===
|Succès |Blessure |Cases
|1      |Légère   |1
|2      |Moyenne  |3
|3      |Grave    |6
|4      |Fatale   |10
|===

Évidemment, un personnage ayant plus de 10 cases dans son <<attribute_condition_monitor,moniteur de condition>> ne sera pas mis hors combat par une seule blessure fatale.
C'est voulu, afin d'éviter de mettre le troll blindé d'augmentations au même niveau que le simple piéton sur un coup de chance de l'attaquant.

Le meneur de jeu peut n'appliquer cette règle que sur les hommes de main et autres PNJs anonymes, en reprenant éventuellement le niveau de professionnalisme de l'époque, pour se faciliter la tâche.


[[option_only_one_pass]]
=== Une seule passe d'initiative

*TODO* _Tous les persos n'ont qu'une passe ; les passes supplémentaires sont convertis en effet pops sur les actions_

[[option_stress]]
=== Stress

*TODO* _Pour faire plaisir à okhin_

[[option_essence_drain]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Technomanciens et Drain d'Essence*

*Règle :* Les technomanciens dépourvus d'<<attribute_essence,Essence>>, mais aussi de <<attribute_magic,Magie>> et d'<<attribute_equilibrium,Équilibre>>, sont considérés avoir une valeur d'Essence de 0 dans le cadre du pouvoir de Drain d'Essence.
La nature des technomanciens est en effet foncièrement différente de celle des magiciens, adeptes et autres créatures magiques.

*Motivation :* Réhausser l'intérêt de la <<attribute_resonance,Résonance>> par rapport aux autres <<special_attributes,attributs spéciaux>>.
====


[[option_cybermancy]]
[NOTE.option,caption="Règle optionnelle"]
====
*[MJ ONLY] Cybermancie*

*Règle :* Normalement, un attribut spécial <<special_attributes,ne peut pas être augmenté>>.
Pourtant, les rituels de cybermancie permettent d'augmenter l'<<attribute_essence,Essence>> d'un sujet sans que celui-ci ait à le faire <<chapter_karma,progresser>> avec son karma.
La cybermancie devient donc une méthode accélerée pour <<chapter_augmentation,augmenter>> toujours davantage un sujet, au prix d'un coût de maintenance important et des effets secondaires que l'on connait.
====















== Notes de conception

=== Motivation

J'aime Shadowrun. J'_adore_ Shadowrun. J'aimerais bien y rejouer. Mais, il semble que dans ma zone géographique, je n'ai aucune chance de jouer si je ne mène pas une campagne moi-même.

Or, j'ai aujourd'hui bien moins de temps à consacrer à des parties de jeu de rôle que dans le passé. Et, pendant une partie, il me semble plus important de faire progresser l'intrigue et les personnages via le roleplay que de lancer des dés, par exemple en résolvant un combat, même si celui-ci est excitant.

Malheureusement, pour paraphraser un autre joueur de Shadowrun, le système de jeu en lui même est, au minimum fouillis et mal pensé, au pire raté. Donc, il me faut absolument un système léger et qui roule bien.

==== Pourquoi pas un système générique ?

En fait, je menais à ce moment une campagne de Deadlands Reloaded, avec le système de Savage Worlds. Il existe au moins une version pour Shadowrun (Savage Shadowrun [lien]). Mais je n'ai pas vraiment été convaincu à sa lecture. Je me suis retrouvé à faire de trop nombreux ajustements pour essayer qu'il me convienne.

En faisant ces ajustements, je me suis retrouvé un peu perdu. En fait, je ne retrouvais plus "le truc" qui m'avait fait aimer Shadowrun. C'est peut-être du au système de Savage Worlds lui-même qui, malgré ses qualités, ne me convient pas tant que ça ? Ou alors, c'est lancer des brouettes de D6 [lien] qui me manque ?

Quoi qu'il en soit, j'imagine que, quel que soit le système générique, il me manquerait toujours un truc. Le D6 System de West End Games [lien] fonctionnerait peut-être mieux que les autres ... Mais, quitte à adapter un système et à se fader d'écrire un bouquin dessus, pourquoi ne pas adapter directement le système de Shadowrun ?

Peut-être que ça débouchera sur quelque chose d'assez générique pour que je l'utilise aussi à Earthdawn ... Mais quand même, ne rêvons pas trop.


==== Pourquoi pas Shadowrun Universes [lien] ?

D'abord, j'ai commencé à réfléchir à tout ça avant de tomber sur le projet de Blade. Blade a clairement davantage réfléchi au sujet que moi, et semble se diriger vers une approche encore plus abstraite que la mienne, à travers son système de jetons. Je dois avouer que ses jetons m'ont fait penser aux pépites de Deadlands (les poker chips de Savage Worlds). J'aime bien l'idée, mais je n'ai pas bien saisi le mode de fonctionnement des recharges, et je ne suis pas sûr que ça corresponde à mes joueurs et moi. Notre campagne Deadlands me porte à croire que ma table n'est peut-être pas faite pour ce genre de systèmes à jetons. Quoi qu'il en soit, il faudrait que je playteste Shadowrun Universes, mais je ne suis pas sur Paris, et je ne veux/peux pas proposer deux systèmes de règles différents à mes joueurs, par manque de temps.

Après, après lu ses règles, je dois avouer qu'il y a de sacrément bonnes idées dedans. Je suis fan, et j'espère qu'il pourra y avoir un échange à ce niveau-là. Ce serait bien de faire un truc modulaire plutôt qu'un gros bouquin, des chapitres qui pourraient être combinés à l'envie de chaque MJ, et éviter de faire le travail d'écriture plusieurs fois.

Et puis Blade, et d'autres membres des Shadowforums sont éminemment plus versés dans le lore et plus doués que moi pour produire des documents de qualité à partir du background de Shadowrun. Sérieux, les 3 époques de jeu, permettant à chaque table de retrouver une certaine ambiance de jeu ? Du moment que ça ne complexifie pas le système ni ne segmente trop la fanbase (genre, pas comme la franchise Sonic [lien]), c'est de l'idée en or !


==== L'origine du nom

Pourquoi Shadowrun 5.4 ?

À l'époque où j'écris ces lignes, Shadowrun en est à sa 5ème édition, et pourquoi n'aurais-je pas moi aussi le droit de céder à la surenchère de numérotation ?
Blague à part, c'est parce ces règles sont une simplification de SR5 qui tire aussi beaucoup d'enseignements de SR4.
Et puis j'aime bien 54, car à l'époque où j'ai commencé à jouer à Shadowrun 2nde édition, la timeline en était à 2054 ...

Mais, bon je dois reconnaître que j'ai toujours été notoirement mauvais à trouver des noms qui claquent.

Si il y a une collaboration avec Blade, je lui laisserai le choix du nom, parce qu'il a trop la classe. Et si d'autres personnes participent, le nom devrait satisfaire tout le monde.

Après, c'est juste un nom ...


==== Le choix de la langue

J'aurais pu écrire ce bouquin en anglais. Mais mes joueurs préfèrent jouer en français, la communauté des Shadowforums parle français, et pour ce que j'en sais (à savoir: rien), les joueurs anglophones semblent satisfaits de SR5. Alors: français.

J'en ferai peut-être une traduction anglaise quand les règles seront stabilisées, si il y a un réel besoin et/ou que je suis toujours motivé.


=== Personnages

==== Attributs physiques et mentaux

Ça n'est pas moi qui vais remettre en cause l'utilité de l'<<agility,Agilité>>. De tous les attributs, il a toujours été le plus utile et ce, pour l'immense majorité des personnages de Shadowrun. Son poids par rapport aux autres attributs semblait même _trop_ important. Réduire le nombre total d'attributs contribue à gommer ce déséquilibre.

La <<reaction,Réaction>> semble avoir gagné sa place d'attribut primaire depuis SR4, grâce à son utilité pour l'*esquive* et l'*initiative* pour tous les personnages en général, et pour les compétences de rigger en particulier.

L'attribut *Force* semble n'avoir jamais vraiment servi que pour le combat au contact. Et même alors, il ne s'est jamais suffi à lui-même, puisque pour combattre au contact, il a toujours fallu une grande *Agilité* pour toucher. Deux attributs à maxer au lieu d'un, et une prise de risque plus importante pour des dommages souvent insuffisants ont souvent fait du combat au corps à corps un second choix comparé au combat à distance. Exit donc la *Force*.

Concernant la *Constitution*, le constat semble similaire : trop peu de compétence liées, et celles-ci sont trop rares d'utilisation. Le grand avantage d'une valeur importante dans cet attribut a toujours évidemment été de bien encaisser les dommages. Cependant, pour chaque attaque ou presque, il y avait un jet spécifique d'encaissement. En simplifiant largement, on peut donc se dire que la 'moitié des jets de combat' était dédié à la seule *Consitution*. Donc, en se débarassant d'elle en tant qu'attribut, on peut potentiellement diviser le nombre de jets en combat par 2 !

À noter qu'avec la disparition de la *Force* et de la *Constitution*, on perd une bonne partie de la spécificité de 3 des 5 races de Shadowrun.
C'est à la fois un avantage (cela ouvre peut-être la voie à des races moins différentes mécaniquement et donc à une simplification de la création de personnage) et un inconvénient (comment permettre à nos amis orks, trolls et même nains de continuer à se différencier ?). Le problème est résolu par les changements apportés à la <<body,Constitution>>.

La séparation *Logique* - *Intuition* semblant artificielle, ces deux attributs (nés avec SR4) peuvent donc être à nouveau fusionnés dans l'ancien attribut <<intelligence,Intelligence>> (mort avec SR3).

La place de la *Volonté* semblait elle aussi discutable : outre sa niche des compétences de "survie en environnement non urbain", elle semblait n'être utilisé que pour la résistance au drain et aux effets des sorts. Un attribut pour et contre les magiciens, donc. Un genre de dépense que des personnages à priori peu intéressés par la magie était quand même obligés de payer sous peine de devenir des cibles faciles pour les menaces magiques.

Le *Charisme*, lui, intéresse tous les types de personnages, hormis les plus associaux : le relations avec les différents contacts et autres PNJs étant censé faire partie intégrante d'une run à part entière. Même les magiciens sont appelés à s'en servir pour l'invocation. Pourtant, la multiplicité des attributs et le coté prédominant du combat faisait que tout le monde était tenté, à *Shadowrun* comme dans de nombreux autres jeux de rôle, de laisser le *Charisme* au plus faible niveau.

*Volonté* et *Charisme* se voient donc fusionnés : après tout, un charisme au dessus de la moyenne traduit souvent une grande force de caractère, donc de grande volonté.
J'ai choisi d'appeler ce nouvel attribut <<charisma,Charisme>>, bien que *Volonté* aurait peut-être été moins connoté.
En effet, le 4 grandes qualités qui font une run réussie sont : capacité à s'infiltrer et à être discret, réagir plus vite que l'adversaire, se servir de l'information comme d'une arme, et avoir assez de bagout et de force de caractère pour contourner et exploiter le système. <<attribute_agility,Agilité>>, <<attribute_reaction,Réaction>>, <<attribute_intelligence,Intelligence,>>, <<attribute_charisma,Charisme>>.



==== Attributs spéciaux

Le nouveau fonctionnement des attriuts spéciaux est issu de plusieurs (vieux) constats :

* le câblé démarre avec un capital limité d'essence. Il n'a aucun moyen d'augmenter la limite de 6 points d'essence, alors que la puissance des magiciens et des adeptes est virtuellement infinie, grâce à l'initiation.
* le câblé est, d'une certaine manière, moins "fiable" que l'adepte. Il affole les détecteurs de cyberware. Si les malus sociaux du cyberware sont appliqués (et avec SR5, ce n'est plus une règle optionnelle), il lui devient très difficile de communiquer en face à face. Et, si les règles de dommage aux implants sont appliqués, son cyberware si coûteux devient encore plus ... coûteux.
* il y a un certain empiètement des adeptes sur les magiciens, et inversement, ce qui tend à rendre malaisé le fait de mixer les deux dans un même archétype. Les adeptes augmentent leur attribut de magie, acquérant ainsi des points de pouvoir avec lesquels ils achètent des pouvoirs d'adepte. Les adeptes mystiques rendent la situation encore plus alambiquée, répartissant les points de leur attribut de magie entre points de magie utilisés pour leurs pouvoirs de magicien et points magie convertis en points de pouvoirs que les adeptes "mystiques" utilisaient pour acheter leurs pouvoirs d'adepte "tout court", l'appelation d'adepte "physique" ayant pour ainsi dire disparu, et en plus on parle ici d'adeptes "mystiques", pas "physiques", vous me suivez ? Oui, je grossis le trait. Mais quand même : il doit y avoir moyen de faire plus simple.

Il semblait donc nécessaire de mettre tout ce petit monde (câblés, mages complets, adeptes et maintenant technomanciens) sur un meilleur pied d'égalité.
De leur permettre de briller dans leur domaine, sans que ce domaine n'empiète (trop) sur celui des autres, et sans non plus trop les cloisonner.

Donc là, chacun peut avoir 2 domaines différents, et même les mundane ont le leur, avec l'<<attribute_edge,Edge>>. Si un magicien veut se câbler ou devenir adepte mystique, il perd son <<attribute_edge,Edge>>.
Au mieux, il faudrait que les mundane non câblés aient deux attributs spéciaux vraiment utiles. Parce que là, ils ne tirent pas vraiment partie de leur <<attribute_essence,Essence>>.
Mais bon, "découper" les différentes possibilités de l'<<attribute_edge,Edge>> semble injuste car affaiblissant cet attribut, et je n'avais pas d'autre idée.
Si vous pensez à une solution, n'hésitez pas à m'en faire part !


===== Différents types de personnages

Pousser plus loin la séparation des attributs spéciaux que ne le faisaient SR4 et SR5, permet néanmoins de faire les mêmes profils qu'avant.
On peut cependant aussi créer plus facilement certains profils auparavant peu pratiques, voire impossibles à construire.

.Profils de personnages et attributs spéciaux
[width=60%,cols="4,6"]
|===
|Personnage de base | EDGE + ESSENCE
|Magicien           | EDGE + MAGIE
|Mage Burnout       | ESSENCE + MAGIE
|Adepte             | EDGE + ÉQUILIBRE
|Adepte mystique    | MAGIE + ÉQUILIBRE
|Technomancien      | RÉSONANCE + EDGE
|«Not Dodger»       | ESSENCE + RÉSONANCE
|«Not Jashugan»     | ESSENCE + ÉQUILIBRE
|Cyberzombie        | ESSENCE <<option_cybermancy,augmentée>>
|===

En théorie, les combinaisons MAGIE + RÉSONANCE et ÉQUILIBRE + RÉSONANCE semblent exclues du fluff de Shadowrun. À chaque MJ de trancher, s'il autorise l'une ou l'autre de ces combinaisons.
Si oui, il peut être intéressant de se poser les questions suivantes:

* Le technomancien peut-il percevoir les flux d'information depuis l'espace astral ?
* Le technomancien peut-il utiliser ses pouvoirs en perception / projection astrale ?
* Le technomancien peut-il user de perception astrale en RA ?

Dans tous les cas, on ne peut pas lancer de sorts ni invoquer d'esprits en étant connecté à la matrice, ni y bénéficier de pouvoirs d'adepte "physiques". Enfin, à vous de voir.

===== Équilibre de jeu

Maintenant qu'on a des attributs spéciaux différents, et qu'on peut en avoir deux en même temps, il a fallu s'assurer que chacun contribue réellement par rapport aux autres.

- L'<<attribute_edge,Edge>> permet de dépasser ponctuellement sa réserve de dés habituelle, de contourner les lois de l'univers (c'est à dire les règles de base) même après coup, ou encore de sauver la peau de son perso. Suivant le personnage, tout cela peut arriver en puisant dans sa nature, ses croyances, ou ses pouvoirs mystiques, en redlinant ses implants ou par pure et simple chance. Sans <<attribute_edge,Edge>>, tu es soumis au bon vouloir des dés.

- L'<<attribute_essence,Essence>> permet de se faire implanter du cyberware (ou du bioware, ou du geneware, etc). Certes, cela coûte en plus des nuyens, mais l'<<attribute_essence,Essence>> commence à 6, contrairement aux autres attributs. Ça économise 100 points de karma, rien que ça. Sans <<attribute_essence,Essence>>, pas de cyberware. Le personnage a un système sensible, son corps rejette systématiquement les implants bénéfiques, il meurt inexplicablement sur la table d'opération parce que son âme se fait la malle, et ainsi de suite. Pas d'exceptions.

- L'<<attribute_equilibrium,Équilibre>> permet d'obtenir généralement des effets similaires à ceux obtenus grâce au -ware. Il permet d'une certaine manière de payer ces bénéfices avec du karma plutôt qu'avec des nuyens. Il a cependant l'avantage d'être un peu plus discret : pour cette raison, et pour préserver l'équilibre de jeu, les effets des pouvoirs d'adeptes devraient être limité aux simples augmentations d'attributs, de réserve de dés, et à certaines niches (kinesics, armure mystique, ...), et ne pas reproduire les effets d'équipements implantés. La limite exacte entre ce que peuvent faire ou pas les pouvoirs d'adepte parait donc directement liée à la visibilité du -ware dans chaque campagne.

- La <<attribute_magic,Magie>> permet de lancer des sorts et d'invoquer des esprits. De manipuler à sa guise deux des trois mondes de Shadowrun. 'Nuff said.

- La <<attribute_resonance,Résonance>> permet de manipuler à sa guise le monde matriciel, de manière plus efficace qu'un decker. Par la compréhension des flux de communication et des réseaux, elle permet d'acquérir une perception plus fine du monde réel. Les technomanciens ne font pas que payer avec du karma ce que les deckers payent avec des nuyens : ils peuvent dépasser la limite dure du MPCP 6, ils ont accès aux formes complexes, et les sprites devraient pouvoir faire des choses hors de portée de simples agents.

À noter : un personnage possédant un attribut de <<attribute_magic,Magie>>, d'<<attribute_equilibrium,Équilibre>> ou de <<attribute_resonance,Résonance>> doit abandonner un de ses deux attributs spéciaux par défaut. S'il ne souhaite pas se câbler, il peut être tenté de conserver son <<attribute_edge,Edge>>, mécaniquement plus intéressant plus intéressant que son <<attribute_essence,Essence>>. En agissant ainsi, il conserve le style, la chance, ou quoi que soit qui lui fait bénéficier de ses effets. Mais il se sépare de la métahumanité, ce qui le rend plus étrange, compliquant ses interactions sociales, et il devient donc plus étrange, plus remarquable, plus visible -ce qui peut être un vrai handicap pour un runner.

Ceci étant dit, je suis quand même un peu inquiet que la <<attribute_resonance,Résonance>> reste en retrait par rapport aux autres et que la <<attribute_magic,Magie>> mange comme d'habitude sur la tête des autres de par sa nature généraliste. Il faudra aussi bien faire attention à la balance entre <<attribute_equilibrium,Équilibre>> et <<attribute_essence,Essence>>.

Mais allez, globalement, ça semble pas mal.

===== Pas de maximum

Quoi qu'il arrive, les attributs primaires ont un maximum non augmenté de 6, et un maximum augmenté de 9.
Les attributs spéciaux n'ont, eux, théoriquement pas de valeur maximum.
Cela parait dommageable pour l'inflation des réserves de dés, mais est à tempérer de la manière suivante :

* un attribut spécial ne peut pas profiter de l'augmentation. Donc, il faut payer avec son karma, coût qui est prohibitif.
* un attribut spécial est peu ou n'est plus du tout utilisé de façon directe dans les réserves de dés. Plus de magie qui fait tout même le café, et la résonance est affaiblie de la même manière pour la compilation de sprites. Maintenant, tu fais de la sorcellerie ou du hacking avec l'intelligence, et de l'invocation ou de la compilation avec le charisme. La magie et la résonance ne servent plus qu'à fixer l'effet et les limitations de ce que tu sais faire.

Donc, la seule manière de faire enfler les réserves de dés à l'infini reste les compétences.

===== Magiciens et cyberware

Avec ces nouvelles règles, un magicien qui se fait poser du -ware ne subit pas de perte de magie.
Par contre, il devra impérativement posséder l'attribut d'<<attribute_essence,Essence>>, puisqu'il est impossible de bénéficier d'augmentation technologiques sans cet attribut.
Étant donné qu'il a complètement abandonné tout possibilité de faire appel à l'<<attribute_edge,Edge>>, il a payé le prix de son chrome. Cela me semble équilibré.

Si le magicien décide de conserver son <<attribute_edge,Edge>>, il doit abandonner l'idée de se faire implanter un jour du -ware. On retrouve le magicien "traditionnel", qui ne possède aucune augmentation technologique.

Si le magicien décide  plutôt d'acquérir un attribut d'<<attribute_equilibrium,Équilibre>> en plus de son attribut de <<attribute_magic,Magie>>, il devient un adepte mystique, qui ne pourra jamais ni edger, ni se faire implanter.

Alors oui, cela signifie qu'un adepte mystique ne peut pas se faire câbler, ou qu'un sammie qui edge déjà ne pourra jamais en plus devenir technomancien ou magicien.
Personnellement, ça ne me gène pas (trop), car de tels personnages me semblent déjà avoir suffisamment de resources pour contribuer efficacement au cours d'une run.

Après, si vous avez une idée, toute suggestion est la bienvenue -du moment qu'il s'agit de renforcer le système au bénéfice de tous les types de persos, et pas d'une seule niche.
Mais là, j'ai le sentiment qu'autoriser plus de 2 attributs spéciaux, ou créer des exceptions me semble fragiliser le système de jeu pour l'unique bénéfice des Mary Sue ou des personnages à 1000 points de karma ...

===== Équilibrium

Sinon, au sujet du nommage de l'attribut <<attribute_equilibrium,Équilibre>>. Pour la petite histoire, nommer cet attribut "pouvoir" me semblait trop vague, donc j'ai repris et francisé le terme "equilibrium" issu de Shadowrun Returns [link] (commodément déjà utilisé par les adeptes pour leurs pouvoirs). En plus, ce terme me semble bien refléter l'équilibre/l'harmonie que doit maintenir tout adepte entre son comportement et sa nature profonde pour déployer ses pouvoirs. Mais bon, l'harmonie me faisait davantage penser à l'attribut spécial d'un barde de D&D catapulté dans le monde de Shadowrun.

D'ailleurs, j'ai l'impression que ce nouveau système d'attributs spéciaux est assez robuste pour permettre de créer de nouveaux attributs spéciaux. Je ne propose pas de règle optionnelle pour cela, car il s'agit plus d'un art pour équilibrer tout ça que d'un set de modificateurs à appliquer.
Mais, vous avez envie de jouer des psioniques, des negamages, des jedis ou même des bardes à Shadowrun ? Lancez-vous ! Mais essayez de garder ça équilibré avec le reste ...



=== Équipement

Les grades alpha et delta appliqués à davantage de technologies que le seul cyberware, ça le fait !

Les prix des grades avancés sont par contre aussi prohibitifs qu'en SR4 et précédents.
Cependant, je trouve que ça reflète bien le fossé béant qu'il y a entre la majorité et les nantis.
En effet, si on peut se procurer du matériel delta à seulement 2,5 fois le prix de base, qui va encore s'acheter du matériel standard ?
Et à quoi servent les grades alpha et beta ? Aurais-je du supprimer ces grades intermédiaires, et faire perdre des possibilités de personnalisation aux personnages ?
Peut être ...

Néanmoins, il faut bien le reconnaître : déployer des trésors de patience, accumuler des contacts et des informations, économiser des scénarios entiers et parfois risquer sa vie pour voir ses efforts se concrétiser en un équipement delta, potentiellement le seul de sa vie, représente un vrai achèvement.
Devoir attendre d'engranger assez de succès, à cause de ces satanées règles de disponibilité, seule barrière plus ou moins abstraite entre son personnage et son prochain équipement delta qu'il aurait pu se payer depuis déjà 5 scénarios au moins, et recommencer le processus à zéro pour l'équipement delta suivant, ça parait juste frustrant ... En SR5, où est le coté rare, quasiment inatteignable et presque légendaire de l'équipement delta ?

Et puis, ton équipement delta de l'époque techno-thriller, ça devient du alpha ou même du standard pendant la période cyberpunk, et il devient obsolète à l'ère post-cyberpunk.
Le SOTA d'hier est la risée de demain, la vie est une course perdue d'avance pour rester compétitif, il y aura toujours un plus gros poisson que toi, tout ça ... c'est du cyberpunk.

==== Armures

Ouais, j'ai réduit leurs indices. Ils passent de 8-15 environ à 1-4.

D'abord, ça combat l'inflation des réserves de dés, donc le temps nécessaire à compter ses succès, donc ça accélère le jeu.

Ensuite, vu qu'il fallait résoudre chaque round de violence avec un seul jet opposé, je devais fusionner les tests d'esquive et d'encaissement en un seul.
Cependant, lancer la moitié ou davantage de la réserve dés de ce nouveau test de défense grâce à son armure aurait contrevenu à l'objectif de replacer les capacités d'un personnage au centre, plutôt que son équipement.

En plus, le test de défense est à la fois de l'esquive et de l'encaissement.
Or, on peut considérer qu'une grosse armure ralentit les mouvements : l'armure devient plus lourde, plus rigide ...
Donc, l'apport des dés d'armure à la réserve de défense n'est pas aussi grand qu'on peut le penser, puisqu'en gagnant en blindage, on perd en esquive.

Enfin, ça semble contribuer à valoriser les grades d'équipement: gagner deux dés sur sa veste blindée beta pour passer sa protection de 9 à 11 lors d'un seul des deux jets de "défense", c'est pas forcément terrible.
Gagner deux dés pour la passer de 2 à 4 dés et doubler son indice pour le _seul_ jet de défense, comparativement ça semble tout de suite avoir davantage d'impact et justifier les nuyens supplémentaires.

