[[test_modifiers]]
= Modificateurs

Chaque test peut se voir assorti de différents modificateurs reflétant les circonstances particulières dans lesquelles ce test se déroule (luminosité, distance, <<tools,outils>>, blessures, ...).
Quelle qu'en soit la source, un modificateur s'ajoute ou se retranche à la réserve de dés.
Si différents modificateurs s'appliquent à un test donné, il suffit d'en faire la somme avant de l'appliquer à la réserve de dés du personnage.
Cependant, la somme totale des modificateurs ne peut _jamais_ dépasser ±0.
En d'autres termes, la taille de la réserve de dés à lancer après application des modificateurs ne peut _jamais_ dépasser sa taille _avant_ application des modificateurs.
Exprimé encore d'une autre manière, le modificateur total ne peut être qu'un _malus_.

Ces modificateurs sont détaillés à travers les différents chapitres de ce livre.
Si une situation n'est pas couverte directement par une règle, ou que le MJ n'a pas envie de se compliquer la vie, il peut utiliser la table suivante, qui montre les modificateurs les plus courants.

.Modificateurs
[width=35%, options="header"]
|===
|Conditions             |Modificateur total

|Standards              | ±0
|Assez gênantes         |-3
|Franchement difficiles |-6
|Quasi-impossibles      |-9
|===


ifdef::with-designer-notes[]
displayer::design[label="Afficher"]
[.design]
****
J'ai mis des modificateurs multiples de 3 à dessein.
Étant donné qu'un succès est statiquement obtenu pour trois dés lancés, ça n'est pas la peine de se prendre la tête avec des modificateurs plus détaillés que ceux-ci.
****
endif::with-designer-notes[]



Si les modificateurs négatifs sont si importants qu'ils font passer la réserve de dés d'un personnage à 0 ou moins, la tâche entreprise semble impossible.
En conséquence, l'action échoue donc automatiquement.
Dans de telles circonstances, seul un personnage doté d'<<attribute_edge,Edge>> peut obtenir un dernier recours.


ifdef::with-designer-notes[]
displayer::design[label="Afficher"]
[.design]
****
Allez, ça vaut le coup de le répéter encore une fois :
[quote]
____
Cependant, la somme totale des modificateurs ne peut *jamais*, *jamais*, *jamais* dépasser ±0.
____
Ce passage est absolument fondamental à SR54.
À lui seul, il stoppe quasiment l'inflation des réserves de dés.
C'était un de mes <<objectives,objectifs>> primordiaux : c'est une chose de lancer plusieurs D6, ça fait partie du jeu.
Perdre cette base du système (genre lancer d'autres types de dés, passer à des jets de pourcentage, etc) aurait fait perdre, à mon sens, l'impression de jouer au même jeu.

Quand un runner est très très doué, il lance environ 12 ou 15 dés.
C'est déjà beaucoup (et, avec ces règles, ça représente déjà un certain investissement en karma).
Lancer 20 ou 30 dés pour la moindre action alors qu'on n'y est même pas spécialisé, c'est _trop_.
Les dés, ça coûte de l'argent.
Mais surtout, ça coûte le temps de réunir les dés, de compter qu'on en a le nombre exact, de les ramasser sous la table quand ils roulent partout, et de compter ses succès.
Plusieurs fois par passe d'initiative.
Tout ça ralentit l'action.
Or, accélerer l'action était un autre de mes <<objectives,objectifs>> prioritaires.
Permettons à l'action d'être aussi rapide, nerveuse et immersive qu'un monde cyberpunk est censé l'être : un seul jet par joueur et par tour, ça suffit.

Ensuite, je sais pas vous, mais je trouve ridicule qu'un perso avec 3 dans son attribut, et 1 dans sa compétence lance 15 dés, sous prétexte qu'il dispose d'un excellent matériel.
En gros, le syndrome du _script-kiddie_ dans le milieu de la Matrice.
Avec mes règles, un tel personnage lancera 4 dés, même avec le meilleur matos et dans les conditions les plus favorables du monde.
Les héros du jeu sont les runners, les PJs, _pas_ leur matos à whatmille nuyens.
Refaire des attributs et des compétences les stars du système était encore un de mes <<objectives,objectifs>>.

Enfin, une petite parenthèse sur le fait où vous voudriez donner un modificateur positif pour « conditions grandement facilitées ».
Si un test est facile, il n'y a pas d'enjeu. Et s'il n'y a pas d'enjeu, pourquoi voulez-vous lancer les dés ? On n'a pas de temps à perdre avec des banalités !

****
endif::with-designer-notes[]


