[[archetypes]]
== Archétypes

ifdef::with-designer-notes[]
displayer::design[label="Afficher"]
[.design]
****
J'ai essayé de créer des archétypes les plus cohérents possible.
Je voulais aussi que ce soient ces personnages qui soient utilisés tels quels dans les différents exemples dispersées dans le bouquin.
Dans une certaine mesure, cela permet de valider leur jouabilité.
Cela permet aussi au lecteur de reconnaître les noms dans les exemple, et de se reporter à l'archétype en cas de doute.

Je voulais aussi donner un nom et un peu de background à chacun pour qu'ils soient réellement prêts à jouer.
J'ai aussi voulu inclure à chaque fois au moins une problématique, un axe de développement possible pour les personnages, pour suggérer l'idée qu'ils n'étaient pas statiques, pas gravés dans le marbre.
Dans tous les cas, il fallait que le texte reste fluide et conçis, mais descriptif.

Ah, et j'ai aussi essayé d'être un peu inclusif en ce qui concerne de la représentation au sein des métatypes, des genres, des origines, ...

Les archétypes sont présentés sans ordre particulier ; j'ai simplement essayé de placer chacun près des archétypes ayant des thèmes voisins, afin de fluidifier la lecture.
****
endif::with-designer-notes[]

Ce chapitre présente différents archétypes de personnage.
Chaque joueur peut simplement en sélectionner un et commencer à jouer.
Il peut aussi s'en inspirer pour s'aider lors de la <<character_creation,création de son personnage>>.

Chacun de ces archétypes est créé avec *400 points de karma*.

L'archétype choisi peut être modifié pour mieux correspondre à l'idée du joueur, que ce soit au niveau du nom, du background proposé ou de n'importe laquelle de ses caractéristiques.

*Attributs et caractéristiques secondaires :* ::
Les abréviations utilisées sont les suivantes : +
*A* : <<attribute_agility,Agilité>> +
*R* : <<attribute_reaction,Réaction>> +
*I* : <<attribute_intelligence,Intelligence>> +
*C* : <<attribute_charisma,Charisme>> +
*Ess* : <<attribute_essence,Essence>>. Le nombre entre parenthèses indique l'Essence encore disponible pour de futures <<chapter_augmentation,augmentations>>. +
*Edg* : <<attribute_edge,Edge>> +
*Mag* : <<attribute_magic,Magie>> +
ifdef::with-technomancy[*Res* : <<attribute_resonance,Résonance>> +]
*Init* : <<attribute_initiative,Initiative>> +
*PI* : <<pi,Phases d'Initiative>> supplémentaires +
*Con* : <<attribute_body,Constitution>> +
*Arm* : Indice de l'<<gear_armor,Armure>> portée

*Compétences :* ::
Liste alphabétique des compétences du personnage.
Les coût indiqué entre parenthèses [.formula]#( )# tient compte des réductions dues aux groupes de compétences, le cas échéant.

*Connaissances :* ::
Liste alphabétique des connaissances, des hobbies, mais aussi des langues parlées par le personnage.

*Augmentations :* ::
Liste des augmentations du personnage, si celui-ci en possède.
Les augmentations magiques d'un personnage possédant le trait <<quality_adept,Adepte>> sont indiquées par un ^M^.
Celles qui ne portent aucune mention sont des augmentations technologiques de grade standard.
Les augmentations technologiques de <<gear_grades,grade différent>> sont indiquées par un ^A^ (alphaware), un ^B^ (betaware), un ^D^ (deltaware) ou un ^O^ (omega).

*Sorts :* ::
Liste des sorts connus par le personnage, le cas échéant.

*Équipement :* ::
Liste des possessions du personnage, achetée avec l'équivalence <<KEY,1 karma = 2500¥>>.

*Traits :* ::
Liste des <<chapter_qualities,traits>> possédés par le personnage.
Les traits obtenus gratuitement grâce au métatype sont indiqués par un ^R^.
À noter qu'afin de les garder les plus « génériques » possibles, aucun de ces archétypes n'a acquis de défaut (au sens du système de <<chapter_qualities,traits>>) -hormis ceux communs à son <<chapter_metatypes,métatype>>, évidemment.
De même, seuls les avantages strictement indispensables à son concept ont été achetés.



=== Samouraï des rues

==== Description
Guerrier urbain cybernétiquement amélioré, le samouraï des rues suit souvent un code d'honneur strict qui l'aide à préserver son humanité et le différencie des tueurs sans foi ni loi qui rôdent dans les Ombres.

////
==== Background
Guerrier cybernétiquement amélioré, Crush parcourt les rues du plexe pour survivre.
Évoluant parfois sur le fil du rasoir entre la chair et la machine, il préserve son humanité en suivant scrupuleusement son code d'honneur et en émulant de nobles sentiments.
Au fond, Instant Crush est un romantique ! Au plus profond des Ombres, peut-être trouvera-t'il l'amour ?


.Instant Crush, ork mâle
[options="header", caption="", cols="10*^"]
|===
|A |R |I |C |Ess    |Edg |Init |PI |Con |Arm
|5 |5 |2 |3 |6(1.1) |3   |10   |+2 |2   |2
2+>.^h|Compétences [.formula]#(105)# 8+<|
Armes de Jet 2, Armes de mêlée 3, Armes de poing 4, Armes d'épaule 4, Armes lourdes 4, Armurerie 2, Athlétisme 2, Combat à mains nues 3, Cybertech 1, Discrétion 2, Esquive 3, Intimidation 3, Perception 2, Pilotage terrestre 2, Premiers soins 1, Survie 2
2+>.^h|Connaissances [.formula]#(25)# 8+<|
Étiquette(La Rue), Gangs Locaux, Love Stories, Tactique Militaire, Underground Ork
2+>.^h|Augmentations [.formula]#(49)# 8+<|
Réaction +1, Constitution +1, +2 Passes d'Initiative, +
Yeux cybernétiques (anti-flash, caméra, interface d'armes, vision thermographique), +
Fusil à pompe cyber-implanté
2+>.^h|Equipement [.formula]#(4)# 8+<|
Veste blindée, Katana, Pistolet mitrailleur, 7750¥
2+>.^h|Traits [.formula]#(0)# 8+<|
Vision nocturne ^R^
|===

////


=== Cyborg

==== Description
Habitant un corps tenant davantage de la machine que de l'humain, le cyborg transcende sa chair pour atteindre un stade différent d'évolution, débarrassé de la plupart des faiblesses humaines.

////
==== Background

Ex-cadre corporatiste réputé dans le domaine des implants cybernétiques, ses médecins lui ont diagnostiqué une maladie dégénérative généralisée.
Ayant détourné illégalement les resources du projet de cyber-soldat à ses propres fins, Tin a remplacé tous ses organes déficients.
Son corps entièrement amélioré, mais ayant fui son ancienne corporation, Tin trouvera peut-être un sens à sa seconde vie ?

*TODO* lui donner pour 8.75 points de 'ware (105K = 7 d'essence en alpha).

.Tin, humain non genré
[options="header", caption="", cols="10*^"]
|===
|A |R |I |C |Ess    |Edg |Init |PI |Con |Arm
|6 |6 |3 |3 |7(7.6) |1   |10   |+2 |0   |3
2+>.^h|Compétences [.formula]#(84)# 8+<|
Armes d'épaule 3, Athlétisme 3, Combat à mains nues 3, Cybertech 3, Esquive 3, Perception 3
2+>.^h|Connaissances [.formula]#(15)# 8+<|
Étiquette(Corpos), Management, Politique Corporatiste
2+>.^h|Augmentations [.formula]#(105)# 8+<|
Agilité +2 ^A^, Réaction +2 ^A^, Armure +3 ^A^, +2 Passes d'Initiative ^A^, +
Yeux cybernétiques (anti-flash, interface d'armes, vision thermographique, vision nocturne) ^A^, +
Fusil d'assaut cyber-implanté ^A^
2+>.^h|Equipement [.formula]#(1)# 8+<|
2500¥
2+>.^h|Traits [.formula]#(0)# 8+<|
Vision nocturne ^R^
|===

////


=== Rigger

==== Description
Lorsque les cycles moteur deviennent les pulsations de son cœur et l'arrivée d'essence son flux d'adrénaline, le rigger est capable de contrôler les machines mieux que son propre corps, faisant faire des prouesses à son véhicule ou faire qu'une petite armée de drones exécute sa volonté.

////
==== Background
// NM
*TODO*
////


=== Hacker

==== Description
Pirate informatique parfaitement à son aise dans les univers virtuels, le hacker est capable d'altérer, de contrôler ou de détruire la Matrice pour arriver à ses fins.

////
==== Background
// NF
*TODO*
////

ifdef::with-technomancy[]
=== Technomancien

==== Description
*TODO*

==== Background
// HF
*TODO*
endif::with-technomancy[]

=== Rocker

==== Description
Éternel révolté, le rocker renie la culture de masse, et est donc rarement célèbre.
Il parcourt les Ombres pour s'opposer plus directement au système, trouver l'inspiration, ou financer son prochain album.

////
==== Background
// T
*TODO*
////



=== Face

==== Description
Aussi à l'aise dans des cercles aussi variés qu'une soirée mondaine, une réunion corporatiste ou la rue d'un quartier chaud, une Face utilise son charisme et son bagout naturels comme la plus discrète et efficace des armes.

////
==== Background
// EF
*TODO*
////




=== Spec Ops

==== Description
Capable d'escalader une tour de verre et de s'infiltrer dans un quartier de haute sécurité, le spécialiste des opérations clandestines excelle dans les missions qui demande discrétion, rapidité et efficacité.

////
==== Background
// HF
*TODO*
////




=== Adepte (physique)

==== Description
L'adepte utilise sa magie de manière interne, instinctive, dans le but d'atteindre l'excellence dans son domaine, que celui-ci soit sportif, artistique, combattant, ou plus exotique.

////
==== Background
// EM
*TODO*
////



////
=== Joueur d'Urban Brawl

==== Description
*TODO*

==== Background
*TODO*
////

=== Adepte mystique

==== Description
À mi chemin entre l'adepte physique et le magicien, la polyvalence de l'adepte mystique lui permet de faire face à un vaste panel de situations.

////
==== Background

La jeune Fiyf, de son pseudo complet Fireball-In-Your-Face, a quitté Tír na nÓg pour deux raisons : la discrimination à l'encontre de son métatype, et diverses accusations de violences et d'incendie volontaire à son encontre.
Les deux raisons étant probablement liées, Fiyf trouvera-t'elle une place au calme dans sa nouvelle patrie ?

.Fiyf, orke femelle
[options="header", caption="", cols="10*^"]
|===
|A |R |I |C |Ess  |Mag |Init |PI |Con |Arm
|5 |3 |3 |4 |6(3) |2   |6    |+1 |1   |1
2+>.^h|Compétences [.formula]#(102)# 8+<|
Arcanes 2, Armes de jet 2, Armes de poing 3, Athlétisme 3, Combat à mains nues 3, Discrétion 3, Esquive 3, Incantation 3, Intimidation 2, Perception 2, Pilotage terrestre 2
2+>.^h|Connaissances [.formula]#(20)# 8+<|
Combats à Moto, Étiquette(Magie), Équitation, Tír na nÓg
2+>.^h|Augmentations [.formula]#(25)# 8+<|
Agilité +1 ^M^, +1 Passe d'Initiative ^M^, Résistance à la magie 2 ^M^
2+>.^h|Sorts [.formula]#(15)# 8+<|
Chaos, Détection des ennemis, Boule de feu
2+>.^h|Equipement [.formula]#(6)# 8+<|
Vêtements renforcés, Pistolet lourd, 14000¥
2+>.^h|Traits [.formula]#(25)# 8+<|
Adepte, Attribut spécial (Magie), Sorcier, Vision nocturne ^R^
|===

////


=== Magicien

==== Description
Qu'il soit une mine de connaissances occultes hermétiques, ou qu'il foule la Terre en harmonie avec ses Ancêtres, le magicien tire ses pouvoirs d'une tradition ésotérique ; ils le rendent capable de lancer des sorts variés, d'invoquer de nombreux types d'esprits à son service, et de fabriquer divers objets enchantés.

////
==== Background
// T
*TODO*
////



=== Burnout

==== Description
Désabusé, ce magicien a choisi de palier les insuffisances de sa magie par la cybernétique.
Étonamment, il est parvenu à concilier les deux de manière inédite, efficace mais parfois dérangeante.

////
==== Background
// HM (hermétique)
*TODO*
////



=== Brave

==== Description
Bien qu'il ne soit pas chaman, ce guerrier amérindien suit la voie de ses ancêtres.
Il a quitté sa tribu pour tenter d'aider les âmes perdues du métroplexe, sans entâcher son honneur ni se compromettre avec la technologie.

////
==== Background
*TODO*
////



=== Chasseur de primes

==== Description
Pisteur d'exception, chasseur sans merci, ce rôdeur moderne est capable de traquer, dans tout type d'environnement, tout type de proie -que celle-ci soit sauvage ou métahumaine, banale ou merveilleuse, dangereuse ou délicieuse.

////
==== Background
*TODO*
////



=== Ex-Agent corporatiste

==== Description
Alors qu'il était au service de sa corporation, cet ancien agent a été écœuré par la corruption qu'il y a découvert.
Depuis, il a coupé les ponts avec elle, et tente de préserver ce qu'il peut et de gagner sa vie avec les talents qui lui restent.

////
==== Background
*TODO*
////



=== Ganger

==== Description
Enfant des rues et de la violence, le ganger est un survivant qui est parvenu à se hisser en haut de la chaîne alimentaire de son quartier.
Il peut considérer le gang dont il est issu comme une bande de perdants ou d'outils utiles, ou au contraire avoir juré de rester toute sa vie loyal à ses origines.

////
==== Background
*TODO*
////



=== Garde du corps

==== Description
Expert de la protection personnelle, le garde du corps officie parfois de manière moins « officielle », que ce soit par appât du gain, par goût du risque ou par obligation, en raison d'une erreur lui ayant coûte sa réputation, et la vie à son client.

////
==== Background
*TODO*
////



=== Mercenaire

==== Description
Miliraire habitué des champs de bataille, le mercenaire loue aussi parfois ses talents dans des conflits à plus petite échelle, où le plus offrant peut profiter de son expérience de combattant professionnel et de son expertise tactique.

////
==== Background
*TODO*
////



=== Privé

==== Description
Parfois franchement dépassé sur le plan technologique ou magique, le privé persiste à croire en ses méthodes « à l'ancienne », en sa bonne étoile et en son flair, qui lui en permis jusqu'ici de mener à bien ses affaires sans avoir besoin de « tricher ».

////
==== Background
*TODO*
////
