[[chapter_augmentation]]
== Augmentation

Il existe deux sources par le biais desquelles un personnage peut avoir accès à l'augmentation :

* les *implants*, qui s'achètent avec des nuyens et sous soumis
  à la <<gear_availability,disponibilité>>, comme tout autre équipement.
  Le prix d'un implant est égal à son *Coût × 25 000¥*
* les *pouvoirs d'adepte* qui s'aquièrent grâce au karma.
  Un pouvoir coûte un nombre de points de karma égal à son *Coût × 10* points de karma.

Le coût de toutes les augmentations d'un personnage se cumule, et ce,
quelle que soit la source (pouvoir ou implant) des ces augmentations.
Ce coût cumulé doit toujours être inférieur ou égal à son indice d'<<attribute_essence,Essence>>.
Sinon, le personnage meurt -c'est aussi simple que cela.

Ce chapitre détaille 3 types d'augmentation :

* les <<augmentation_generic,augmentations génériques>>, accessible à tout personnage doté d'<<attribute_essence,Essence>>
* les augmentations technologiques, accessibles uniquement via des implants
* les <<adept_powers,augmentations magiques>>, accessibles uniquement via des pouvoirs d'adepte



[[augmentation_generic]]
=== Augmentations génériques

Aucun personnage ne peut bénéficier de plus de 3 fois du même bonus d'augmentation.
Cette limitation s'applique quelle que soit la source de l'augmentation.

.Bonus d'augmentation
[width=60%, options="header", cols="4,^1,^1,^1"]
|===
|Augmentation               | Bonus |Signature|Coût
|Attribut physique ou mental| +1    | 2       |0.5
|Armure¹                    | +1    | 1       |0.5
|Passe d'Initiative         | -     | 1       |1.5
|Moniteur de condition      |+1 case| 2       |0.25
|Résistance (autre)²        | +1    | 2       |0.1
|===

¹ Non cumulative avec une armure portée.

² Choisir un type de résistance: toxines, pathogènes, feu, froid, électricité, acide ...



[[augmentation_technologic]]
=== Augmentations technologiques

.Cyberware
[width=60%, options="header", cols="4,^1,^1"]
|===
|Augmentation                     |Signature|Coût
|<<datajack,Datajack>>            | 1       |0.1
|<<chipjack,Chipjack>>            | 1       |0.2
|Drone occulaire                  | 2       |0.12
|<<smartlink,Interface d'armes>>  | 1       |0.2
|<<control_rig,ICV>>              | 2       |Indice × 0.5
|===

[[datajack]] *Datajack :* ::
L'implant roi pour quiconque désire se connecter à la Matrice.
Il est possible de se servir d'un casque équipés de trodes à la place, mais l'utilisateur souffre d'un <<test_modifiers,modificateur>> de -2 à toutes ses actions matricielles.

[[chipjack]] *Chipjack :* ::
Ce datajack spécialisé permet de lire et d'utiliser tout type de puces, en particulier les *logiciels de connaissance* (_knowledge softs_, _linguasofts_).
Un logiciel de connaissance coûte *2500¥* et permet à son utilisateur d'utiliser la <<knowledges,connaissance>> contenue dans la puce comme s'il l'avait apprise lui-même.
Cependant, dès que la puce est retirée du chipjack, l'utilisateur n'en garde aucun souvenir.

[[smartlink]] *Interface d'armes :* ::
Cet implant permet à son porteur de bénéficier d'un <<test_modifiers,modificateur>> supplémentaire de +2 (pour un total de +3) lorsqu'il tire avec une arme équipée d'un <<weapon_upgrade_accuracy,module d'interface>>.

[[control_rig]] *ICV (Interface de Contrôle de Véhicule) :* ::
Cet implant relativement invasif permet à son porteur de <<jump_into_rigged_device,se brancher>> sur tout véhicule ou machine préparée à cet effet.
Tant qu'il est <<jump_into_rigged_device,connecté>>, il bénéficie des avantages suivants :

* un <<test_modifiers,modificateur>> de [.formula]#+Indice×2# à tous ses tests de pilotage du véhicule, ou de tir à l'aide d'une des armes du véhicule.
* +1 <<pi,Passe d'initiative>> par point d'indice.

+
Une ICV peut être d'*indice 1 à 3*.


==== Autres implants

Pour ainsi dire tout type d'équipement peut être implanté dans le corps d'un personnage.
Un implant reproduisant l'effet d'un équipement nécessite souvent que sa forme soit minitaturisée
ou altérée d'une façon ou d'une autre pour se conformer à l'endroit du corps où il sera greffé.
Son mode de commande habituel doit se conformer aux contraintes physiques de son utilisateur
(interrupteur sous la peau, dans une dent, etc) mais est souvent complémenté (ou totalement remplacé)
par une interface neurale directe.

Pour connaître le prix d'un tel implant, il faut multiplier le prix original de l'implant par 10.
Pour connaître son coût en <<attribute_essence,Essence>>, il faut diviser ce nouveau prix par 25000¥.

.Équipement implanté
[width=75%, options="header", cols="4,^1,^3,>3"]
|===
|Augmentation               |Signature|Coût          |Prix
|Équipement implanté        | 2       |Prix / 25000¥ |Prix de base × 10¥
|===

[NOTE.example,caption="Exemple"]
====
Les copains de Crush lui ont suggéré de faire preuve de davantage de subtilité dans son métier.
Crush déborde d'envie de bien faire mais son amour pour le concept de subtilité est parfois fugace.
Aussi décide-t-il de se faire couper un bras et de le faire remplacer par un autre dissimulant un fusil à pompe.

Cela lui coûtera 10 × 1000¥ (le prix d'un fusil à pompe) = 10000¥.
Une fois greffé, cette arme implantée lui coûtera 10000 / 25000 = 0.4 points d'Essence.
====

[NOTE.example,caption="Exemple"]
====
Catgirl désire se faire implanter des yeux cybernétiques ressemblant à des yeux de chat.
Quitte à faire charcuter, elle fait le plein d'options: interface d'arme (10 × 500¥),
caméra (10 × 50¥), anti-flash (10 × 50¥) et vision thermographique (10 × 100¥).
Elle désire aussi qu'un de ses yeux soit en fait un drone occulaire (0.12 × 25000¥ = 3000¥).
En tant qu'elfe, elle n'a pas besoin de "racheter" sa vision nocturne naturelle.

Enfin, elle veut que ses nouveaux yeux soient de grade alpha.

Son achat lui coûtera 1.5 (alphaware) × 10000¥ (somme de toutes les options) = 15000¥.
Une fois greffés, ses yeux cyber lui coûteront 10000 × 0.8 (alphaware) / 25000 = 0.32 points d'Essence.
====



[[adept_powers]]
=== Augmentations magiques

Toute <<augmentation_generic,augmentation générique>> peut être acquise comme un *pouvoir d'adepte*
(mais pas les <<augmentation_technologic,augmentations technologiques>>).

Un pouvoir d'adepte, contrairement à un implant, n'est pas soumis aux règles de <<gear_availability,Disponibilité>> :
un <<quality_adept,adepte>> peut en bénéficier instantanément, du moment qu'il peut payer le coût en <<attribute_essence,Essence>>
requis et dispose du karma nécessaire.

Un pouvoir d'adepte ne peut pas être extrait du personnage qui le possède et encore moins transféré à quelqu'un d'autre.

Bien que la nature d'un adepte puisse être détectée lors d'un examen médical ou d'une <<skill_assensing,Lecture d'aura>>,
un pouvoir d'adepte est considéré bénéficiant de l'avantage <<quality_cyberware,'Ware discret>> (à 20 points) :
il n'est pas détectable par un moyen technologique, et même en lisant son aura, il est difficile de savoir à priori
de quoi un adepte est vraiment capable ...
Bien sûr, si un adepte se fait greffer des implants, ceux-ci ne sont pas plus discrets que la normale.

En plus des augmentations génériques, un adepte a accès à l'augmentation suivante.
Aucun <<gear_cyberware,implant>> ne permet de l'acquérir.

.Bonus d'augmentation
[width=60%, options="header", cols="4,^1,^1,^1"]
|===
|Augmentation                      | Bonus |Signature|Coût
|<<magic_defense,Défense magique>> | +1    | NA      |0.5
|===
