
[[chapter_combat]]
=== Combat

[[combat_distance]]
==== Combat à distance

La procédure de résolution d'une attaque à distance est la suivante :

* L'attaquant et sa cible effectuent un <<opposed_test,test opposé>> :
** L'attaquant effectue un test d'<<attribute_agility,Agilité>> + *<compétence d'arme appropriée>*.
** Le défenseur effectue un test de <<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>>.
* Si le défenseur est vainqueur, il s'en tire sans aucun dommage.
* Si l'attaquant est vainqueur, le défenseur coche un nombre de cases de son <<attribute_condition_monitor,moniteur de condition>> égal à :
  *Dégâts de l'<<gear_distance_weapons,arme>> de l'attaquant* + *succès nets de l'attaquant* - *son indice de <<attribute_defense,Défense>>* +
  Il ne peut évidemment pas encaisser moins de 0 cases de dommages de cette manière.

*Compétences d'arme appropriées :* <<skill_pistols,Armes de poing>>, <<skill_rifles,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_throwing_weapons,Armes de jet>>.

*Modificateurs applicables :* portée, visibilité, malus de blessure, couverture du défenseur, ...

===== Modes de tir

De nombreuses armes à distance offrent plusieurs mode de tir.

* Tir unique : action simple, une balle, SS ou SA
* Tir semi-automatique : action complexe, 2 balles, SA
* Tir en rafale : action simple, 3 balles, TR
* Tir automatique : action complexe, 10 balles, TA
* Tir de barrage : action complexe, 20 balles, TA

Au cours d'un test d'attaque à distance, chaque balle après la première et dont le recul est compensé fait bénéficier le tireur d'un modificateur de +1 dé à la réserve de dés.

*TODO* qu'arrive-t'il aux balles non compensées ? --> règle optionnelle du passant innocent / dommages colatéraux



[[combat_melee]]
==== Corps à corps

La procédure de résolution d'un corps à corps est la suivante :

* L'attaquant et sa cible effectuent un <<opposed_test,test opposé>>, en utilisant chacun leur <<attribute_agility,Agilité>> + *<compétence d'arme appropriée>*.
* Le perdant coche un nombre de cases de son <<attribute_condition_monitor,moniteur de condition>> égal à :
  *Dégâts de l'<<gear_distance_weapons,arme>> du vainqueur* + *succès nets du vainqueur* - *son indice de <<attribute_defense,Défense>>* +
  Il ne peut évidemment pas encaisser moins de 0 cases de dommages de cette manière.

*Compétences d'arme appropriées :* <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>.
Un personnage peut éventuellement utiliser <<skill_pistols,Armes de poing>>, mais il subit un modificateur de -4.
Il peut aussi utiliser <<skill_rifles,Armes d'épaule>>, mais il subit un modificateur de -6.

*Modificateurs applicables :* visibilité, malus de blessure, ...



[[suprise]]
==== Surprise

Si un personnage est surpris, il ne peut pas attaquer jusqu'à ce qu'il puisse agir.
Il ne peut pas non plus ni esquiver une attaque à distance.
Enfin, lors d'un test opposé de corps à corps, il n'utilise que son indice de <<attribute_reaction,Réaction>>.



[[pi]]
==== Passes d'Initiative

Un personnage dont l'<<attribute_initiative,initative>> a été <<augmentation_generic,augmentée>> agit plus rapidement en combat.
De son point de vue, tout et tout le monde semble bouger comme au ralenti autour de lui.

Chaque passe d'initiative supplémentaire dont bénéficie le personnage lui fait bénéficier d'un *Point d'Action (PA)*, qu'il peut utiliser à chaque tour.
Les *PA* peuvent être dépensés pour bénéficier des effets suivants :

* *Action rapide (1 PA) :* Le personnage peut effectuer rapidement une action (recharger une arme, changer l'arme qu'il tient en main, observer attentivement quelque chose, ...).
  Il est impossible d'effectuer des actions d'attaque supplémentaires de cette manière.
* *Anticipation (1 PA) :* Toutes les attaques à distance prenant le personnage pour cible souffrent d'un modificateur de *-2×PI*.
* *Harcèlement (1 PA) :* Une cible au choix du personnage souffre d'un modificateur de *-2×PI* à ses actions.
  Le personnage doit évidemment voir sa cible pour l'affecter.
  Il doit de plus manier une arme à distance pour pouvoir affecter une cible éloignée plus loin que son allonge.
* *Tornade (2 PA) :*
** Si le personnage attaque à distance, son attaque affecte jusqu'à *1+PI* cibles en même temps.
** Si le personnage attaque au corps à corps, son attaque affecte jusqu'à *2×PI* cibles en même temps.

+
Toutes les cibles doivent être à portée.
Le personnage n'effectue qu'un seul jet d'attaque, contre lequel chaque cible se défend indépendamment.
L'arme du personnage consomme *1+PI* fois plus de munitions que lors d'une attaque normale.
* *Zen (1 PA) :* Tous les test de compétences de combat du personnage bénéficient d'un modificateur de *+2×PI*.
