
[[chapter_combat]]
=== Combat

* Toute violence physique se résoud par un <<opposed_test,test opposé>> :
** l'attaquant est le personnage *actif* : il fait un *test d'attaque*
** le défenseur est le personnage *passif* : il fait un *test de défense*
* On fait la différence entre le nombre de *succès* respectifs de l'attaquant et du défenseur :
** si le défenseur est vainqueur, il s'en tire sans aucun dommage
** si l'attaquant est vainqueur, le défenseur coche un nombre de cases de son <<condition_monitor,moniteur de condition>> égal au nombre de *succès nets* de l'attaquant

Sauf indication contraire, l'attaquant peut utiliser tout type d'arme à sa disposition, au corps à corps ou à distance, qu'il sache la manier ou non.
Cependant, une même arme ne peut être utilisée qu'une seule fois par passe d'initiative.

*TODO* mettre en évidence la règle d'une seule arme par passe et la volonté de valoriser l'ambidextrie, qui permet de tirer 2 fois une balle en CC ou 2 rafales en TR.



[[combat_distance]]
==== Combat à distance

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>>*

Compétences d'arme concernées : <<skill_pistols,Armes légères>>, <<skill_longarms,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_exotic_weapon,Arme exotique(arme à distance)>>

Exemple de modificateurs : portée, visibilité, malus de blessure de l'attaquant, couvert du défenseur, accessoires de l'arme

====== Modes de tir

De nombreuses armes à distance offrent plusieurs mode de tir.

* Tir unique : action simple, une balle, SS ou SA
* Tir semi-automatique : action complexe, 2 balles, SA
* Tir en rafale : action simple, 3 balles, TR
* Tir automatique : action complexe, 10 balles, TA
* Tir de barrage : action complexe, 20 balles, TA

Au cours d'un test d'attaque à distance, chaque balle après la première et dont le recul est compensé ajoute 1 dé à la réserve de dés.

*TODO* clarifier qu'il ne s'agit pas d'un modificateur, et playtester.

*TODO* qu'arrive-t'il aux balles non compensées ? --> règle optionnel du passant innocent / dommages colatéraux

===== Test de défense

*<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[combat_melee]]
==== Corps à corps

===== Test d'attaque

*AGILITÉ + <compétence d'arme> + <VD de l'<<gear_weapons,arme>>> + <<attribute_body,Constitution>>*

Compétences d'arme concernées : <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>, <<skill_exotic_weapon,Arme exotique(arme de corps à corps)>>

Exemple de modificateurs : visibilité, malus de blessure de l'attaquant

===== Test de défense

*<<attribute_reaction,Réaction>> + <compétence d'arme>> + <<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*

Exemple de modificateurs : malus de blessure du défenseur



[[defense_test_suprise]]
==== Surprise

Si un personnage est surpris, il ne peut pas attaquer jusqu'à ce qu'il puisse agir.
Il ne peut pas non plus entreprendre aucune des manoeuvre de défense active que sont la parade ou l'esquive.

En conséquence, sa réserve de dés lors de son <<combat_defense_test,Test de défense>> est réduite :

*<<attribute_body,Constitution>> + <indice d'<<gear_armor,armure>>>*



[[combat_round]]
==== Déroulement d'un tour de combat

*TODO*
