
[[chapter_combat]]
=== Combat

[[apply_damage]]
==== Subir des dégâts

La plupart des attaques visent à infliger des dégâts à leur cible.
Pour la cible de l'attaque, ces dommages prennent la forme d'un certain nombre de cases à cocher de son <<attribute_condition_monitor,Moniteur de condition>>.

Chaque attaque possède un *Valeur de Dommages (VD)*.
Les <<gear_weapons,tables d'armes>> indiquent la VD de chaque arme.
Ajoutez à cette VD les <<simple_test,succès nets>> obtenus lors du test d'attaque (voir ci-après) pour obtenir les *Dégâts* de l'attaque.

Déduisez des dégâts de l'attaque la <<attribute_body,Constitution>> de la cible.
Sauf mention contraire, déduisez aussi l'indice de l'<<gear_armor,armure>> qu'elle porte.
Le résultat donne le nombre de cases de son <<attribute_condition_monitor,Moniteur de condition>> que la cible de l'attaque doit cocher.
Un résultat inférieur ou égal à 0 implique évidemment de ne cocher aucune case.

La manière de cocher des cases du <<attribute_condition_monitor,Moniteur de condition>> dépend de la nature des dégâts subis :

* Les *dégâts étourdissants* sont marqués d'une ou plusieurs *coches* (un trait oblique). +
  Lorsque la dernière case est marquée d'une coche, le personnage tombe inconscient.
* Les *dégâts physiques* sont marqués d'une ou plusieurs *croix*, qui sont toujours placées au début du moniteur de condition.
  Une nouvelle blessure physique subie « décale » donc d'éventuelles blessures étourdissantes déjà subies par un personnage. +
  Lorsque la dernière case est marquée d'une croix, le personnage est mourant.

[[wound_modifier]]
==== Modificateurs de blessure

ifdef::with-designer-notes[]
displayer::design[label="Afficher"]
[.design]
****
----
                  -1    -2    -4   ✝
                  [ | | | | | | | | ] <-- (1)
                [ | | | | | | | | | ] <-- (2)
              [ | | | | | | | | | | ] <-- (2)
[ | | | | | | | | | | | | | | | | | ] <-- (3)
                  -1    -2    -4   ✝
----
(1) [ 9 cases] moniteur minimum avec un Charisme à 1 +
(2) [10 cases] moniteur standard avec un Charisme à 2 ou 3 +
(3) [11 cases] moniteur avec un Charisme à 4 ou 5 ou une Constitution de 1, par exemple +
(4) [18 cases] moniteur maximum avec un Charisme à 8 ou plus, une Constitution de 2, et 3 cases d'augmentation de son moniteur

Les cases supplémentaires se gagnent au début du Moniteur de condition, pas à la fin ! +
Le principe d'un troll ou d'un augmenté est qu'ils mettent longtemps avant de que leurs blessures soient un problème.
Pas qu'ils deviennent des légumes incapables d'agir longtemps avant de pouvoir être tués ...
****
endif::with-designer-notes[]

Le personnage souffre d'un modificateur à toutes ses tests en fonction du nombre de cases marquées de son <<attribute_condition_monitor,Moniteur de condition>>.

* lorsqu'il lui reste moins de 9 cases indemnes, le modificateur est de -1 ;
* lorsqu'il lui reste moins de 6 cases indemnes, le modificateur est de -2 ;
* lorsqu'il lui reste moins de 3 cases indemnes, le modificateur est de -4.

[NOTE.example,caption="Exemple"]
====
*Appliquer les dégâts*

Étudions la manière d'appliquer les dégâts sur le moniteur de condition d'un personnage.
Pour cela, prenons l'exemple d'un humain de base, non augmenté, avec un <<attribute_charisma,Charisme>> normal, de 2 ou 3.

. Son <<attribute_condition_monitor,Moniteur de condition>> a 10 cases. +
  Au départ, il est indemne : pas de malus.
+
----
                -1    -2    -4   ✝
              [ | | | | | | | | | ]
----
. Il subit 1 dégât physique : pas de malus non plus. +
  Notez qu'un personnage avec le minimum de <<attribute_charisma,Charisme>>, représentant une très faible volonté ainsi qu'une absence totale de classe, écoperait d'un malus dès sa première blessure.
  Douillet, va	.
+
----
                -1    -2    -4   ✝
              [X| | | | | | | | | ]
----
. Il subit ensuite 1 dégât étourdissant : son modificateur de blessure passe à -1.
+
----
                -1    -2    -4   ✝
              [X|\| | | | | | | | ]
----
. Il subit ensuite 2 dégâts physiques : son modificateur de blessure reste à -1. +
  Observez que les cases physiques sont toujours marqués le plus à gauche possible, donc ils « poussent » les dégâts étourdissants déjà présents vers la droite.
  On procède de la sorte de manière à ne pas « mourir » en cochant la case la plus à droite d'une dernière blessure physique, alors que notre moniteur de condition contient encore une ou plusieurs cases cochées en étourdissant.
+
----
                -1    -2    -4   ✝
              [X|X|X|\| | | | | | ]
----
. Il subit ensuite 4 dégâts étourdissants : son modificateur de blessure passe à -4. +
  Ça devient très compliqué pour lui : le modificateur de blessure s'applique à _tous_ les jets.
+
----
                -1    -2    -4   ✝
              [X|X|X|\|\|\|\|\| | ]
----
. Maintenant, partant de l'état du <<attribute_condition_monitor,Moniteur de condition>> en 5., étudions plusieurs cas de figure :
.. S'il subit 2 dégâts étourdissants : il tombe dans l'inconscience.
+
----
                -1    -2    -4   ✝
              [X|X|X|\|\|\|\|\|\|\]
----
.. S'il subit plutôt 2 dégâts physiques : il tombe dans l'inconscience aussi. +
   Rappelez-vous que les dégâts physiques « poussent » les dégats étourdissants vers la droite.
+
----
                -1    -2    -4   ✝
              [X|X|X|X|X|\|\|\|\|\]
----
.. S'il subit à la place 5 dégâts étourdissants : il tombe là encore dans l'inconscience, mais après avoir coché les 2 dernières cases en étourdissant (comme en 6.a), il nous reste 3 cases à cocher ...
   Donc on remet une marque dans les cases précédemment cochées une fois, les coches deviennent des croix, ce qui représente des dégâts physiques. +
+
----
                -1    -2    -4   ✝
              [X|X|X|X|X|X|\|\|\|\]
----
.. Pour rendre mourant le perso à partir de l'état 5., il faut 7 dégâts physiques (il est sérieusement étourdi, mais pas tant blessé que ça). +
   Cependant, 9 dégâts étourdissants font le même travail, étant donné que les dégâts qui « dépassent » le moniteur de condition deviennent physiques.
   Moralité, on peut effectivement vous tuer à mains nues.
   Mais ça prendra davantage de temps.
   Ou de force.
+
----
                -1    -2    -4   ✝
              [X|X|X|X|X|X|X|X|X|X]
----
====



[[option_old_school_wounds]]
[NOTE.option,caption="Règle optionnelle"]
====
*Blessures Légères, Moyenne, Graves et Fatales*

*Règle :* Plutôt que de cocher un nombre de cases du moniteur de condition d'un personnage égal
au nombre de succès nets obtenus par l'attaquant, on utilise le tableau suivant :

.Types de blessure
[width=33%, cols="^1,^2,>1" options="header"]
|===
|Succès |Blessure |Cases
|1      |Légère   |1
|2      |Moyenne  |3
|3      |Grave    |6
|4      |Fatale   |10
|===

*Motivation :* Cette règle propose d'accélérer le jeu en augmentant la léthalité des combats.
Elle donne en même temps un coté « old school » aux combats.

Évidemment, un personnage ayant plus de 10 cases dans son <<attribute_condition_monitor,moniteur de condition>>
ne sera pas mis hors combat par une seule blessure "Fatale".
C'est voulu, afin d'éviter de mettre le troll câblé au même niveau que le simple piéton sur un coup de chance de l'attaquant.

Un compromis semble être de n'appliquer cette règle qu'aux hommes de main et autres PNJs anonymes,
en reprenant éventuellement le principe d'indice de professionnalisme de l'époque.
====


[[damage_overflow]]
==== Mort

Un personnage qui subit suffisamment de dégâts pour que toutes les cases du <<attribute_condition_monitor,moniteur de condition>> soient cochées devient *Mourant*.
Il peut rester Mourant dispose d'un *Surplus de Dégâts Maximum* égal à [.formula]#<<attribute_body,Constitution>> + <<attribute_charisma,Charisme>>#.
Cette valeur représente le nombre de minutes qu'il lui reste à vivre.

* À chaque minute passée sans subir de soins appropriés, un personnage mourant augmente son *Surplus de Dégâts* de 1.
* S'il doit cocher davantage de cases de dégâts que son <<attribute_condition_monitor,moniteur de condition>> ne lui permet car celui-ci est entièrement coché de dégâts physiques, chaque case de dégâts en trop augmente de même son *Surplus de Dégâts* de 1.

Lorsque le *Surplus de Dégâts* d'un personnage atteint son *Surplus de Dégâts Maximum*, celui-ci meurt pour de bon.

Un test étendu d'[.formula]#<<attribute_intelligence,Intelligence>> + <<skill_first_aid,Premiers soins>> (Surplus de Dégâts)# permet de stabiliser un personnage mourant.



[[combat_distance]]
==== Combat à distance

Lors d'une attaque à distance, l'attaquant et sa cible effectuent un <<opposed_test,test opposé>> :

* L'attaquant effectue un test d'[.formula]#<<attribute_agility,Agilité>> + <compétence appropriée>#.
* Le défenseur effectue un test de [.formula]#<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>>#.

Si le défenseur est vainqueur, il s'en tire sans aucun dommage.
Si l'attaquant est vainqueur, <<apply_damage,appliquez les dégâts>> comme décrit en début de chapitre.

*Compétences appropriées :* <<skill_pistols,Armes de poing>>, <<skill_rifles,Armes d'épaule>>, <<skill_heavy_weapons,Armes lourdes>>, <<skill_throwing_weapons,Armes de jet>>.

*Modificateurs applicables :* portée, visibilité, modificateur de blessure, couverture du défenseur, ...



[[suppressive_fire]]
==== Tir de couverture

Un personnage équipé d'une <<gear_distance_weapons,arme à distance>> cable de tirer en <<mode_ta,tir automatique>> peut saturer une zone de balles.
Après avoir ciblé une zone (un cône de 10 mètres de large et 2 mètres de haut au maximum), le tirer effectue un test d'[.formula]#<<attribute_agility,Agilité>> + <compétence appropriée>#.

Le nombre de succès nets devient un <<test_modifiers,modificateur négatif>> s'appliquant à toutes les actions de quiconque se trouve dans la zone ciblée.

De plus, toute personne dans la zone ciblée encaisse des dégâts égaux aux dommages de base de l'arme.
Un test de [.formula]#<<attribute_reaction,Réaction>> + <<skill_dodge,Esquive>># permet de réduire ces dégâts de 1 case par réussite.



[[combat_melee]]
==== Corps à corps

Lors d'un corps à corps, les deux adversaires effectuent un <<opposed_test,test opposé>>, en utilisant chacun leur [.formula]#<<attribute_agility,Agilité>> + <compétence appropriée>#.

Le perdant <<apply_damage,subit des dégâts>> comme décrit en début de chapitre.

*Compétences appropriées :* <<skill_melee_weapons,Armes de mêlée>>, <<skill_unarmed,Combat à mains nues>>.
Un personnage peut éventuellement utiliser <<skill_pistols,Armes de poing>>, mais il subit un modificateur de -4.
Il peut aussi utiliser <<skill_rifles,Armes d'épaule>>, mais il subit un modificateur de -6.

*Modificateurs applicables :* visibilité, modificateur de blessure, ...



[[ambidextry]]
==== Ambidextrie

Un personnage peut attaquer un seul adversaire avec deux armes en même temps, une dans chaque main.
Ses attaques sont résolues comme s'il n'en tenait qu'une seule, mais la <<weapon_damage,VD>> de ses attaques est augmentée de 2.

Par contre, il subit un <<test_modifiers,modificateur négatif>> à ses attaques de -4.

Cette option n'est possible que si le personnage attaque le même adversaire avec ses deux armes.
Il doit de plus utilise deux <<gear_melee_weapons,armes de mêlée>> _Légères_ ou _Normales_, ou deux <<gear_pistols,armes de poing>>.
Il peut utiliser une <<gear_melee_weapons,armes de mêlée>> _Légère_ ou _Normale_ et une <<gear_pistols,armes de poing>>, mais est alors dans la situation d'utiliser une <<fire_into_melee,arme à feu au corps à corps>>.



[[fire_into_melee]]
==== Armes à feu au corps à corps

Un personnage tentant d'utiliser une arme à feu pour frapper son adversaire utilise sa compétence <<skill_melee_weapons,Armes de mêlée>>, mais subit un malus de -4.

Un personnage tentant de tirer avec une arme à feu utilise sa compétence habituelle, mais subit un malus de -2 s'il tient son arme à une main, ou de -4 s'il lui faut ses deux mains.
De plus, un adversaire au corps à corps avec lui peut décider de résoudre la situation comme un combat au corps à corps.
Dans ce cas, il utilise sa compétence <<skill_unarmed,Combat à mains nues>> ou <<skill_melee_weapons,Armes de mêlée>> (le cas échéant) au lieu d'<<skill_dodge,Esquive>>.
Si cet adversaire gagne le test opposé de cette manière, il infligera au tireur les dommages de corps à corps habituels.



[[suprise]]
==== Surprise

Un personnage ne peut pas attaquer tant qu'il est surpris.
Il ne peut pas non plus esquiver une attaque à distance.
Enfin, lors d'un test opposé de corps à corps, il n'utilise que son indice de <<attribute_reaction,Réaction>>.



[[pi]]
==== Passes d'Initiative

Un personnage dont l'<<attribute_initiative,initative>> a été <<augmentation_generic,augmentée>> agit plus rapidement en combat.
De son point de vue, tout et tout le monde semble bouger comme au ralenti autour de lui.

Chaque passe d'initiative supplémentaire dont bénéficie le personnage lui fait bénéficier d'un *Point d'Action (PA)*, qu'il peut utiliser à chaque tour.
Les *PA* peuvent être dépensés pour bénéficier des effets décrits ci-après.
Un effet marqué d'un *+* peut être utilisés plusieurs fois dans le tour, en dépensant les PA correspondant à chaque fois.

* *Action rapide (1 PA+) :* Le personnage peut effectuer rapidement une action (recharger une arme, changer l'arme qu'il tient en main, observer attentivement quelque chose, ...).
  Il est impossible d'effectuer des actions d'attaque supplémentaires de cette manière.
* *Anticipation (1 PA) :* Toutes les attaques à distance prenant le personnage pour cible souffrent d'un modificateur de *-2×PI*.
* *Harcèlement (1 PA+) :* Une cible au choix du personnage souffre d'un modificateur de *-2×PI* à ses actions.
  Le personnage doit évidemment voir sa cible pour l'affecter.
  Il doit de plus manier une arme à distance pour pouvoir affecter une cible éloignée plus loin que son allonge.
* *Point faible (1 PA+) :* L'attaque du personnage bénéficie de *+2* à sa VD.
* *Tornade (2 PA) :*
** Si le personnage attaque à distance, son attaque affecte jusqu'à *1+PI* cibles en même temps.
** Si le personnage attaque au corps à corps, son attaque affecte jusqu'à *2×PI* cibles en même temps.

+
Toutes les cibles doivent être à portée.
Le personnage n'effectue qu'un seul jet d'attaque, contre lequel chaque cible se défend indépendamment.
L'arme utilisée consomme des munitions pour chaque cible attaquée.
* *Zen (1 PA) :* Tous les test de compétences de combat du personnage bénéficient d'un modificateur de *+2×PI*.
