
1 couverture
2 dédicace
3 résumé super rapide des règles
4 table des matières
5 objectifs
7 principes de jeu
 - succès & seuils
 - tests
 - modificateurs
9 personnage
 - attributs physiques et mentaux
 - attributs spéciaux
   - edge effects
 - caractéristiques secondaires
 - compétences (conversion)
 - metatypes
12 création de personnage
 - karma & progression
   + coûts des attributs, compétences etc
   + achat de l'équipement
 - qualities
20 archétypes
30 règles
 - modificateurs
 - infiltration
 - social
 - combat: distance
     types de tir
 - combat: c/c
     casser des trucs
 - magie
     sorcellerie
	 invocation
 - matrice
 - TODO: véhicules
 - déroulement d'un tour de combat
     passes d'initiative
	 action (attaque)
	 conversion de passes en bonus (attaque de zone, etc)
38 règles optionnelles
 - limites: skill/2
 - ajuster la léthalité
 - convertir passes d'init en effets pops
 - règles de stress
 - custom races: liste traits raciaux
40 équipement
 - flingues
 - melee
 - kits de compétence
 - augmentations
  + table "coût en essence/pouvoir" <> bénéfice
50 notes du concepteur
55 commentaires: le but est-il atteint ?
60 TODO: fiche de personnage


¹
²
³





include::faq.adoc[]

== Notes de conception

=== Personnages







==== Compétences


===== Réorganisation en détails

Groupes conservés tels quels: CRACKING(PIRATAGE), ELECTRONICS(ÉLECTRONIQUE), TASKING(TECHNOMANCIE), SORCERY(SORCELLERIE), CONJURING(CONJURATION), ENCHANTING(ENCHANTEMENT).

Groupe modifié: INFLUENCE

* impersonation + disguise = impersonation (déguisement) - c'est le talent d'acteur qui prime ; si pas la bonne tenue et/ou pas le bon lieu -> malus
* con + negociation = con (manipulation) - on va pas créer une comp exprès pour négocier le salaire
* intimidation


Groupe modifié: FIREARMS(ARMES À FEU)

* pistols (pistolets)
* rifles (armes d'épaule)
* heavy weapons (armes lourdes)

Groupe modifié: CLOSE COMBAT(CORPS À CORPS)

* melee weapons (armes de mêlée)
* unarmed combat (combat à mains nues)
* dodge (esquive): utile dans ce groupe pour _atteindre_ le corps à corps


Groupe modifié: STEALTH(FURTIVITÉ)

* sneaking (discrétion): camouflage, discrétion, filature, escamotage
* perception (perception)
* lockpicking (serrurerie)

Groupe modifié: OUTDOORS(PLEIN AIR)

* gymnastics (athlétisme)
* lancer + arc (armes de jet)
* survival (survie)

Nouveau groupe: ASTRAL CRAFT(ASTRAL)

* arcana (arcanes): créer des trames de sort qui sont des entités astrales ... allez, ça va pas trop mal conceptuellement avec les deux autres
* assensing (perception astrale): trouver les indices dans le monde astral
* astral combat (combat astral): taper les indices dans le monde astral

Groupe modifié: PILOT(CONDUITE)

* pilot aircraft + pilot aerospace (pilotage aérien)
* pilot ground craft + pilot walkers (pilotage terrestre)
* pilot watercraft (pilotage nautique)

Groupe modifié: ENGINEERING(INGÉNIERIE)

* aeronautics + automotive + nautical mechanics = vehicle mechanic (mécanique de véhicules)
* gun mechanic (armurerie): construire/réparer les flingues
* industrial mechanic (mécanique industrielle): de facture industrielle, hors véhicule, flingue ou -ware
* artisan (artisanat): pour tout le reste, y compris le travail de faussaire (artistique ou papier)


Groupe modifié: BIOTECH

* medecine (médecine): premiers soins, administration de médicaments ...
* chirurgy (chirurgie): tout ce qui nécessite d'ouvrir, de découper ou de greffer
* cybertechnology + biotechnology (cybertech): construire/réparer ce qui est augmentation technologique


Compétences de connaissance:

* etiquette : devient plusieurs compétences de connaissance: etiquette:la rue, etiquette:corpos, etc
* animal handling, escape artist, diving, free fall, performance, tracking: toutes celles-là sont d'un usage trop rare/fluff
* demolitions : de peu d'usage (setup booby trap + gagner un peu de DV pour quelque chose qui en fait déjà tant que ça).
  On va dire que les explosifs ça tue, avec ou sans la compétence.
* instruction : une compétence de connaissance pour pouvoir faire un jet de teamwork et aider un copain à apprendre ...
  Allez, ça passe !
  Baisser le prix à une compétence de connaissance peut servir à favoriser le travail d'équipe et à souder le groupe ...
  Du point de vue d'un MJ, c'est un outil qui ne fait pas de mal, je pense.
* leadership : perso, ça me gêne quand les PJ ne sont pas tous sur un pied d'égalité.
  Donc je refuserais de laisser les PJs bénéficier du jet de leadership d'un autre PJ.
  Cette compétence est donc réservée aux cas d'usage:
** PNJ chef d'un groupe de PNJs ou d'un groupe de PJ (et dans ce cas, peu importe combien de karma a investi le PNJ pour faire évoluer sa compétence)
** PJ chef d'un groupe de PNJs: cas rare, à priori -hormis si le PNJ parvient à se faire passer pour le chef de la sécurité d'un site ou d'un officier de police ...
   Auquel cas la compétence de leadership ne se suffit pas à elle-même, et c'est déguisement qui fait le gros du boulot.


Compétences supprimées:

* groupe ACTING : compétences déplacées dans INFLUENCE, ou supprimées ou passées en compétences de connaissance
* exotic melee weapon, exotic ranged weapon, exotic vehicle: pas mécontent de m'en être débarassées, de celles-là !
* gunnery : c'est pas parce que tu utilise une arme montée en anneau ou en tourelle qu'elle se manie différement.
  Et un interfacé doit avoir appris à manier l'arme montée sur le véhicule où il plonge pour l'utiliser correctement, de même qu'un sammie qui se fait greffer une arme dans son bras ...
  Si il y avait eu une compétence nécessaire pour utiliser une arme télécommandée, quelle que soit cette arme, je l'aurais conservée (en passant probablement pilot watercraft en compétence de connaissance), mais là ...
* navigation, running, swimming (avec l'atout : le PJ ne se noie jamais ; avec le handicap: il coule comme une pierre ; par défaut : le PJ sait à peu près nager).


=== Équipement

==== Grades

Les grades alpha et delta appliqués à davantage de technologies que le seul cyberware, ça le fait !

Les prix des grades avancés sont par contre aussi prohibitifs qu'en SR4 et précédents.
Cependant, je trouve que ça reflète bien le fossé béant qu'il y a entre la majorité et les nantis.
En effet, si on peut se procurer du matériel delta à seulement 2 fois le prix de base, qui va encore s'acheter du matériel standard ?

Et à quoi servent les grades alpha et beta ?
Aurais-je du supprimer ces grades intermédiaires, et faire perdre des possibilités de personnalisation aux personnages ?
Peut être ...

Néanmoins, il faut bien le reconnaître : déployer des trésors de patience, accumuler des contacts et des informations,
économiser des scénarios entiers et parfois risquer sa vie pour voir ses efforts se concrétiser
en un équipement delta, potentiellement le seul de sa vie, représente un vrai achèvement.
Devoir attendre d'engranger assez de succès, à cause de ces satanées règles de disponibilité,
seule barrière plus ou moins abstraite entre son personnage et son prochain équipement delta qu'il aurait pu se payer depuis déjà 5 scénarios au moins,
et recommencer le processus à zéro pour l'équipement delta suivant, ça parait juste frustrant ...
En SR5, où est le coté rare, quasiment inatteignable et presque légendaire de l'équipement delta ?

Et puis, ton équipement delta de l'époque techno-thriller, ça devient du alpha ou même du standard
pendant la période cyberpunk, et il devient obsolète à l'ère post-cyberpunk.
Le SOTA d'hier est la risée de demain, la vie est une course perdue d'avance pour rester compétitif,
il y aura toujours un plus gros poisson que toi, tout ça ... c'est cyberpunk.

==== Signature

Le système pour savoir si un personnage arrive à transporter son arme dans un lieu donné ni vu ni connu était, selon moi, bancal.
Un bonus/malus à la réserve de dés qui dépend de chaque arme signifie qu'il faut faire un test pour chaque arme. C'est long à résoudre.
De plus, le concept de seuil, une des bases du système, ne sert à rien, puisqu'on est dans un cadre binaire : "mon arme est détectée ? oui/non".
Enfin, les armes, les véhicules et les personnages ont chacun un système spécifique pour savoir s'ils sont reconnus en tant que tel.
Ça complique les choses.

J'ai donc repris le concept de Signature, qui est suffisamment abstrait pour s'appliquer aux personnages et aux objets.
Cela simplifie la résolution : maintenant, le détecteur/garde fait son jet simple.
Ce jet est assorti de modificateurs positifs en fonction de son outillage ou de sa méthode (détecteur, fouille au corps, ...).
On applique aussi des modificateurs négatifs si le personnage a pris des mesures particulières (tout sous le black trenchcoat, armes démontées, ...).

Ensuite, on fait une seule fois le jet, au lieu d'une fois par arme.
Toutes les armes dont la signature est inférieure aux succès nets obtenus est détectée , les autres passent le contrôle.
La Signature d'une arme est donc le seuil nécessaire pour la détecter lors d'un contrôle,
et un seul jet de perception peut détecter certaines armes et pas d'autres.

J'espère pouvoir appliquer le même principe aux véhicules ainsi que pour reconnaître/filer/retrouver la trace d'un personnage.


==== Armes

Le système de règle ne présente plus que les différents types d'armes.
On perd en choix ce qu'on gagne en simplicité.
De toutes façons, le vaste choix apparent des tables d'origine aboutissait souvent à voir les mêmes (meilleures) armes apparaître sur les PJ.
À l'inverse, certaines armes n'étaient jamais choisies, car non optimales.

Un choix si vaste est difficile à appréhender pour certains joueurs (débutants ou peu intéressés par le matos).
Il ralentit la création de personnage et distrait les joueurs (occupés à faire leur shopping plutôt qu'à faire avancer l'intrigue) en cours de partie.

Donc : on choisit son type d'arme, on lui colle un nom pour le fluff, mais quel que soit le nom ce sont les mêmes caractéristiques.
Si tu veux altérer les propriétés de ton arme, tu peux toujours altérer son grade,
ou considérer que certains accessoires ou types de munitions sont inclus de base dans un modèle donné (en ajustant le prix).

==== Armures

Ouais, j'ai réduit leurs indices. Ils passent de 8-15 environ à 1-3.

D'abord, ça combat l'inflation des réserves de dés, donc le temps nécessaire à compter ses succès, donc ça accélère le jeu.

Ensuite, vu qu'il fallait résoudre chaque round de violence avec un seul jet opposé,
je devais fusionner les tests d'esquive et d'encaissement en un seul lancer de dés.
Cependant, lancer la moitié ou davantage de la réserve dés de ce nouveau test de défense grâce à son armure
aurait contrevenu à l'objectif de replacer les capacités d'un personnage au centre, plutôt que son équipement.

En plus, le test de défense est à la fois de l'esquive et de l'encaissement.
Or, on peut considérer qu'une grosse armure ralentit les mouvements : l'armure devient plus lourde, plus rigide ...
Donc, l'apport des dés d'armure à la réserve de défense n'est pas aussi grand qu'on peut le penser, puisqu'en gagnant en blindage, on perd en esquive.

Enfin, ça semble contribuer à valoriser les grades d'équipement :
gagner deux dés sur sa veste blindée beta pour passer sa protection de 9 à 11 lors d'un seul des deux jets de "défense", c'est pas forcément remarquable.
Gagner deux dés pour la passer de 2 à 4 dés et doubler son indice pour le _seul_ jet de défense,
comparativement ça semble tout de suite avoir davantage d'impact et justifier les nuyens supplémentaires.

