
1 couverture
2 dédicace
3 résumé super rapide des règles
4 table des matières
5 objectifs
7 principes de jeu
 - succès & seuils
 - tests
 - modificateurs
9 personnage
 - attributs physiques et mentaux
 - attributs spéciaux
   - edge effects
 - caractéristiques secondaires
 - compétences (conversion)
 - metatypes
12 création de personnage
 - karma & progression
   + coûts des attributs, compétences etc
   + achat de l'équipement
 - qualities
20 archétypes
30 règles
 - modificateurs
 - infiltration
 - social
 - combat: distance
     types de tir
 - combat: c/c
     casser des trucs
 - magie
     sorcellerie
	 invocation
 - matrice
 - TODO: véhicules
 - déroulement d'un tour de combat
     passes d'initiative
	 action (attaque)
	 conversion de passes en bonus (attaque de zone, etc)
38 règles optionnelles
 - limites: skill/2
 - ajuster la léthalité
 - convertir passes d'init en effets pops
 - règles de stress
 - custom races: liste traits raciaux
40 équipement
 - flingues
 - melee
 - kits de compétence
 - augmentations
  + table "coût en essence/pouvoir" <> bénéfice
50 notes du concepteur
55 commentaires: le but est-il atteint ?
60 TODO: fiche de personnage


¹
²
³




== Notes de conception

=== Motivation

J'aime Shadowrun. J'_adore_ Shadowrun. J'aimerais bien y rejouer. Mais, il semble que dans ma zone géographique, je n'ai aucune chance de jouer si je ne mène pas une campagne moi-même.

Or, j'ai aujourd'hui bien moins de temps à consacrer à des parties de jeu de rôle que dans le passé. Et, pendant une partie, il me semble plus important de faire progresser l'intrigue et les personnages via le roleplay que de lancer des dés, par exemple en résolvant un combat, même si celui-ci est excitant.

Malheureusement, pour paraphraser un autre joueur de Shadowrun, le système de jeu en lui même est, au minimum fouillis et mal pensé, au pire raté. Donc, il me faut absolument un système léger et qui roule bien.

==== Pourquoi pas un système générique ?

En fait, je menais à ce moment une campagne de Deadlands Reloaded, avec le système de Savage Worlds. Il existe au moins une version pour Shadowrun (Savage Shadowrun [lien]). Mais je n'ai pas vraiment été convaincu à sa lecture. Je me suis retrouvé à faire de trop nombreux ajustements pour essayer qu'il me convienne.

En faisant ces ajustements, je me suis retrouvé un peu perdu. En fait, je ne retrouvais plus "le truc" qui m'avait fait aimer Shadowrun. C'est peut-être du au système de Savage Worlds lui-même qui, malgré ses qualités, ne me convient pas tant que ça ? Ou alors, c'est lancer des brouettes de D6 [lien] qui me manque ?

Quoi qu'il en soit, j'imagine que, quel que soit le système générique, il me manquerait toujours un truc. Le D6 System de West End Games [lien] fonctionnerait peut-être mieux que les autres ... Mais, quitte à adapter un système et à se fader d'écrire un bouquin dessus, pourquoi ne pas adapter directement le système de Shadowrun ?

Peut-être que ça débouchera sur quelque chose d'assez générique pour que je l'utilise aussi à Earthdawn ... Mais quand même, ne rêvons pas trop.


==== Pourquoi pas Shadowrun Universes [lien] ?

D'abord, j'ai commencé à réfléchir à tout ça avant de tomber sur le projet de Blade. Blade a clairement davantage réfléchi au sujet que moi, et semble se diriger vers une approche encore plus abstraite que la mienne, à travers son système de jetons. Je dois avouer que ses jetons m'ont fait penser aux pépites de Deadlands (les poker chips de Savage Worlds). J'aime bien l'idée, mais je n'ai pas bien saisi le mode de fonctionnement des recharges, et je ne suis pas sûr que ça corresponde à mes joueurs et moi. Notre campagne Deadlands me porte à croire que ma table n'est peut-être pas faite pour ce genre de systèmes à jetons. Quoi qu'il en soit, il faudrait que je playteste Shadowrun Universes, mais je ne suis pas sur Paris, et je ne veux/peux pas proposer deux systèmes de règles différents à mes joueurs, par manque de temps.

Après, après lu ses règles, je dois avouer qu'il y a de sacrément bonnes idées dedans. Je suis fan, et j'espère qu'il pourra y avoir un échange à ce niveau-là. Ce serait bien de faire un truc modulaire plutôt qu'un gros bouquin, des chapitres qui pourraient être combinés à l'envie de chaque MJ, et éviter de faire le travail d'écriture plusieurs fois.

Et puis Blade, et d'autres membres des Shadowforums sont éminemment plus versés dans le lore et plus doués que moi pour produire des documents de qualité à partir du background de Shadowrun. Sérieux, les 3 époques de jeu, permettant à chaque table de retrouver une certaine ambiance de jeu ? Du moment que ça ne complexifie pas le système ni ne segmente trop la fanbase (genre, pas comme la franchise Sonic [lien]), c'est de l'idée en or !


==== L'origine du nom

Pourquoi Shadowrun 5.4 ?

À l'époque où j'écris ces lignes, Shadowrun en est à sa 5ème édition, et pourquoi n'aurais-je pas moi aussi le droit de céder à la surenchère de numérotation ?
Blague à part, c'est parce ces règles sont une simplification de SR5 qui tire aussi beaucoup d'enseignements de SR4.
Et puis j'aime bien 54, car à l'époque où j'ai commencé à jouer à Shadowrun 2nde édition, la timeline en était à 2054 ...

Mais, bon je dois reconnaître que j'ai toujours été notoirement mauvais à trouver des noms qui claquent.

Si il y a une collaboration avec Blade, je lui laisserai le choix du nom, parce qu'il a trop la classe. Et si d'autres personnes participent, le nom devrait satisfaire tout le monde.

Après, c'est juste un nom ...


==== Le choix de la langue

J'aurais pu écrire ce bouquin en anglais. Mais mes joueurs préfèrent jouer en français, la communauté des Shadowforums parle français, et pour ce que j'en sais (à savoir: rien), les joueurs anglophones semblent satisfaits de SR5. Alors: français.

J'en ferai peut-être une traduction anglaise quand les règles seront stabilisées, si il y a un réel besoin et/ou que je suis toujours motivé.


=== Personnages

==== Attributs physiques et mentaux

Ça n'est pas moi qui vais remettre en cause l'utilité de l'<<agility,Agilité>>. De tous les attributs, il a toujours été le plus utile et ce, pour l'immense majorité des personnages de Shadowrun. Son poids par rapport aux autres attributs semblait même _trop_ important. Réduire le nombre total d'attributs contribue à gommer ce déséquilibre.

La <<reaction,Réaction>> semble avoir gagné sa place d'attribut primaire depuis SR4, grâce à son utilité pour l'*esquive* et l'*initiative* pour tous les personnages en général, et pour les compétences de rigger en particulier.

L'attribut *Force* semble n'avoir jamais vraiment servi que pour le combat au contact. Et même alors, il ne s'est jamais suffi à lui-même, puisque pour combattre au contact, il a toujours fallu une grande *Agilité* pour toucher. Deux attributs à maxer au lieu d'un, et une prise de risque plus importante pour des dommages souvent insuffisants ont souvent fait du combat au corps à corps un second choix comparé au combat à distance. Exit donc la *Force*.

Concernant la *Constitution*, le constat semble similaire : trop peu de compétence liées, et celles-ci sont trop rares d'utilisation. Le grand avantage d'une valeur importante dans cet attribut a toujours évidemment été de bien encaisser les dommages. Cependant, pour chaque attaque ou presque, il y avait un jet spécifique d'encaissement. En simplifiant largement, on peut donc se dire que la 'moitié des jets de combat' était dédié à la seule *Consitution*. Donc, en se débarassant d'elle en tant qu'attribut, on peut potentiellement diviser le nombre de jets en combat par 2 !

À noter qu'avec la disparition de la *Force* et de la *Constitution*, on perd une bonne partie de la spécificité de 3 des 5 races de Shadowrun.
C'est à la fois un avantage (cela ouvre peut-être la voie à des races moins différentes mécaniquement et donc à une simplification de la création de personnage) et un inconvénient (comment permettre à nos amis orks, trolls et même nains de continuer à se différencier ?). Le problème est résolu par les changements apportés à la <<body,Constitution>>.

La séparation *Logique* - *Intuition* semblant artificielle, ces deux attributs (nés avec SR4) peuvent donc être à nouveau fusionnés dans l'ancien attribut <<intelligence,Intelligence>> (mort avec SR3).

La place de la *Volonté* semblait elle aussi discutable : outre sa niche des compétences de "survie en environnement non urbain", elle semblait n'être utilisé que pour la résistance au drain et aux effets des sorts. Un attribut pour et contre les magiciens, donc. Un genre de dépense que des personnages à priori peu intéressés par la magie était quand même obligés de payer sous peine de devenir des cibles faciles pour les menaces magiques.

Le *Charisme*, lui, intéresse tous les types de personnages, hormis les plus associaux : le relations avec les différents contacts et autres PNJs étant censé faire partie intégrante d'une run à part entière. Même les magiciens sont appelés à s'en servir pour l'invocation. Pourtant, la multiplicité des attributs et le coté prédominant du combat faisait que tout le monde était tenté, à *Shadowrun* comme dans de nombreux autres jeux de rôle, de laisser le *Charisme* au plus faible niveau.

*Volonté* et *Charisme* se voient donc fusionnés : après tout, un charisme au dessus de la moyenne traduit souvent une grande force de caractère, donc de grande volonté.
J'ai choisi d'appeler ce nouvel attribut <<charisma,Charisme>>, bien que *Volonté* aurait peut-être été moins connoté.
En effet, le 4 grandes qualités qui font une run réussie sont : capacité à s'infiltrer et à être discret, réagir plus vite que l'adversaire, se servir de l'information comme d'une arme, et avoir assez de bagout et de force de caractère pour contourner et exploiter le système. <<attribute_agility,Agilité>>, <<attribute_reaction,Réaction>>, <<attribute_intelligence,Intelligence,>>, <<attribute_charisma,Charisme>>.



==== Attributs spéciaux

Le nouveau fonctionnement des attriuts spéciaux est issu de plusieurs (vieux) constats :

* le câblé démarre avec un capital limité d'essence. Il n'a aucun moyen d'augmenter la limite de 6 points d'essence, alors que la puissance des magiciens et des adeptes est virtuellement infinie, grâce à l'initiation.
* le câblé est, d'une certaine manière, moins "fiable" que l'adepte. Il affole les détecteurs de cyberware. Si les malus sociaux du cyberware sont appliqués (et avec SR5, ce n'est plus une règle optionnelle), il lui devient très difficile de communiquer en face à face. Et, si les règles de dommage aux implants sont appliqués, son cyberware si coûteux devient encore plus ... coûteux.
* il y a un certain empiètement des adeptes sur les magiciens, et inversement, ce qui tend à rendre malaisé le fait de mixer les deux dans un même archétype. Les adeptes augmentent leur attribut de magie, acquérant ainsi des points de pouvoir avec lesquels ils achètent des pouvoirs d'adepte. Les adeptes mystiques rendent la situation encore plus alambiquée, répartissant les points de leur attribut de magie entre points de magie utilisés pour leurs pouvoirs de magicien et points magie convertis en points de pouvoirs que les adeptes "mystiques" utilisaient pour acheter leurs pouvoirs d'adepte "tout court", l'appelation d'adepte "physique" ayant pour ainsi dire disparu, et en plus on parle ici d'adeptes "mystiques", pas "physiques", vous me suivez ? Oui, je grossis le trait. Mais quand même : il doit y avoir moyen de faire plus simple.

Il semblait donc nécessaire de mettre tout ce petit monde (câblés, mages complets, adeptes et maintenant technomanciens) sur un meilleur pied d'égalité.
De leur permettre de briller dans leur domaine, sans que ce domaine n'empiète (trop) sur celui des autres, et sans non plus trop les cloisonner.

Donc là, chacun peut avoir 2 domaines différents, et même les mundane ont le leur, avec l'<<attribute_edge,Edge>>. Si un magicien veut se câbler ou devenir adepte mystique, il perd son <<attribute_edge,Edge>>.
Au mieux, il faudrait que les mundane non câblés aient deux attributs spéciaux vraiment utiles. Parce que là, ils ne tirent pas vraiment partie de leur <<attribute_essence,Essence>>.
Mais bon, "découper" les différentes possibilités de l'<<attribute_edge,Edge>> semble injuste car affaiblissant cet attribut, et je n'avais pas d'autre idée.
Si vous pensez à une solution, n'hésitez pas à m'en faire part !


===== Différents types de personnages

Pousser plus loin la séparation des attributs spéciaux que ne le faisaient SR4 et SR5, permet néanmoins de faire les mêmes profils qu'avant.
On peut cependant aussi créer plus facilement certains profils auparavant peu pratiques, voire impossibles à construire.

.Profils de personnages et attributs spéciaux
[width=60%,cols="4,6"]
|===
|Personnage de base | EDGE + ESSENCE
|Magicien           | EDGE + MAGIE
|Mage Burnout       | ESSENCE + MAGIE
|Adepte             | EDGE + ÉQUILIBRE
|Adepte mystique    | MAGIE + ÉQUILIBRE
|Technomancien      | RÉSONANCE + EDGE
|«Not Dodger»       | ESSENCE + RÉSONANCE
|«Not Jashugan»     | ESSENCE + ÉQUILIBRE
|Cyberzombie        | ESSENCE <<option_cybermancy,augmentée>>
|===

En théorie, les combinaisons MAGIE + RÉSONANCE et ÉQUILIBRE + RÉSONANCE semblent exclues du fluff de Shadowrun. À chaque MJ de trancher, s'il autorise l'une ou l'autre de ces combinaisons.
Si oui, il peut être intéressant de se poser les questions suivantes:

* Le technomancien peut-il percevoir les flux d'information depuis l'espace astral ?
* Le technomancien peut-il utiliser ses pouvoirs en perception / projection astrale ?
* Le technomancien peut-il user de perception astrale en RA ?

Dans tous les cas, on ne peut pas lancer de sorts ni invoquer d'esprits en étant connecté à la matrice, ni y bénéficier de pouvoirs d'adepte "physiques". Enfin, à vous de voir.

===== Équilibre de jeu

Maintenant qu'on a des attributs spéciaux différents, et qu'on peut en avoir deux en même temps, il a fallu s'assurer que chacun contribue réellement par rapport aux autres.

- L'<<attribute_edge,Edge>> permet de dépasser ponctuellement sa réserve de dés habituelle, de contourner les lois de l'univers (c'est à dire les règles de base) même après coup, ou encore de sauver la peau de son perso. Suivant le personnage, tout cela peut arriver en puisant dans sa nature, ses croyances, ou ses pouvoirs mystiques, en redlinant ses implants ou par pure et simple chance. Sans <<attribute_edge,Edge>>, tu es soumis au bon vouloir des dés.

- L'<<attribute_essence,Essence>> permet de se faire implanter du cyberware (ou du bioware, ou du geneware, etc). Certes, cela coûte en plus des nuyens, mais l'<<attribute_essence,Essence>> commence à 6, contrairement aux autres attributs. Ça économise 100 points de karma, rien que ça. Sans <<attribute_essence,Essence>>, pas de cyberware. Le personnage a un système sensible, son corps rejette systématiquement les implants bénéfiques, il meurt inexplicablement sur la table d'opération parce que son âme se fait la malle, et ainsi de suite. Pas d'exceptions.

- L'<<attribute_equilibrium,Équilibre>> permet d'obtenir généralement des effets similaires à ceux obtenus grâce au -ware. Il permet d'une certaine manière de payer ces bénéfices avec du karma plutôt qu'avec des nuyens. Il a cependant l'avantage d'être un peu plus discret : pour cette raison, et pour préserver l'équilibre de jeu, les effets des pouvoirs d'adeptes devraient être limité aux simples augmentations d'attributs, de réserve de dés, et à certaines niches (kinesics, armure mystique, ...), et ne pas reproduire les effets d'équipements implantés. La limite exacte entre ce que peuvent faire ou pas les pouvoirs d'adepte parait donc directement liée à la visibilité du -ware dans chaque campagne.

- La <<attribute_magic,Magie>> permet de lancer des sorts et d'invoquer des esprits. De manipuler à sa guise deux des trois mondes de Shadowrun. 'Nuff said.

- La <<attribute_resonance,Résonance>> permet de manipuler à sa guise le monde matriciel, de manière plus efficace qu'un decker. Par la compréhension des flux de communication et des réseaux, elle permet d'acquérir une perception plus fine du monde réel. Les technomanciens ne font pas que payer avec du karma ce que les deckers payent avec des nuyens : ils peuvent dépasser la limite dure du MPCP 6, ils ont accès aux formes complexes, et les sprites devraient pouvoir faire des choses hors de portée de simples agents.

À noter : un personnage possédant un attribut de <<attribute_magic,Magie>>, d'<<attribute_equilibrium,Équilibre>> ou de <<attribute_resonance,Résonance>> doit abandonner un de ses deux attributs spéciaux par défaut. S'il ne souhaite pas se câbler, il peut être tenté de conserver son <<attribute_edge,Edge>>, mécaniquement plus intéressant plus intéressant que son <<attribute_essence,Essence>>. En agissant ainsi, il conserve le style, la chance, ou quoi que soit qui lui fait bénéficier de ses effets. Mais il se sépare de la métahumanité, ce qui le rend plus étrange, compliquant ses interactions sociales, et il devient donc plus étrange, plus remarquable, plus visible -ce qui peut être un vrai handicap pour un runner.

Ceci étant dit, je suis quand même un peu inquiet que la <<attribute_resonance,Résonance>> reste en retrait par rapport aux autres et que la <<attribute_magic,Magie>> mange comme d'habitude sur la tête des autres de par sa nature généraliste. Il faudra aussi bien faire attention à la balance entre <<attribute_equilibrium,Équilibre>> et <<attribute_essence,Essence>>.

Mais allez, globalement, ça semble pas mal.

===== Pas de maximum

Quoi qu'il arrive, les attributs primaires ont un maximum non augmenté de 6, et un maximum augmenté de 9.
Les attributs spéciaux n'ont, eux, théoriquement pas de valeur maximum.
Cela parait dommageable pour l'inflation des réserves de dés, mais est à tempérer de la manière suivante :

* un attribut spécial ne peut pas profiter de l'augmentation. Donc, il faut payer avec son karma, coût qui est prohibitif.
* un attribut spécial est peu ou n'est plus du tout utilisé de façon directe dans les réserves de dés. Plus de magie qui fait tout même le café, et la résonance est affaiblie de la même manière pour la compilation de sprites. Maintenant, tu fais de la sorcellerie ou du hacking avec l'intelligence, et de l'invocation ou de la compilation avec le charisme. La magie et la résonance ne servent plus qu'à fixer l'effet et les limitations de ce que tu sais faire.

Donc, la seule manière de faire enfler les réserves de dés à l'infini reste les compétences.

===== Magiciens et cyberware

Avec ces nouvelles règles, un magicien qui se fait poser du -ware ne subit pas de perte de magie.
Par contre, il devra impérativement posséder l'attribut d'<<attribute_essence,Essence>>, puisqu'il est impossible de bénéficier d'augmentation technologiques sans cet attribut.
Étant donné qu'il a complètement abandonné tout possibilité de faire appel à l'<<attribute_edge,Edge>>, il a payé le prix de son chrome. Cela me semble équilibré.

Si le magicien décide de conserver son <<attribute_edge,Edge>>, il doit abandonner l'idée de se faire implanter un jour du -ware. On retrouve le magicien "traditionnel", qui ne possède aucune augmentation technologique.

Si le magicien décide  plutôt d'acquérir un attribut d'<<attribute_equilibrium,Équilibre>> en plus de son attribut de <<attribute_magic,Magie>>, il devient un adepte mystique, qui ne pourra jamais ni edger, ni se faire implanter.

Alors oui, cela signifie qu'un adepte mystique ne peut pas se faire câbler, ou qu'un sammie qui edge déjà ne pourra jamais en plus devenir technomancien ou magicien.
Personnellement, ça ne me gène pas (trop), car de tels personnages me semblent déjà avoir suffisamment de resources pour contribuer efficacement au cours d'une run.

Après, si vous avez une idée, toute suggestion est la bienvenue -du moment qu'il s'agit de renforcer le système au bénéfice de tous les types de persos, et pas d'une seule niche.
Mais là, j'ai le sentiment qu'autoriser plus de 2 attributs spéciaux, ou créer des exceptions me semble fragiliser le système de jeu pour l'unique bénéfice des Mary Sue ou des personnages à 1000 points de karma ...

===== Équilibrium

Sinon, au sujet du nommage de l'attribut <<attribute_equilibrium,Équilibre>>. Pour la petite histoire, nommer cet attribut "pouvoir" me semblait trop vague, donc j'ai repris et francisé le terme "equilibrium" issu de Shadowrun Returns [link] (commodément déjà utilisé par les adeptes pour leurs pouvoirs). En plus, ce terme me semble bien refléter l'équilibre/l'harmonie que doit maintenir tout adepte entre son comportement et sa nature profonde pour déployer ses pouvoirs. Mais bon, l'harmonie me faisait davantage penser à l'attribut spécial d'un barde de D&D catapulté dans le monde de Shadowrun.

D'ailleurs, j'ai l'impression que ce nouveau système d'attributs spéciaux est assez robuste pour permettre de créer de nouveaux attributs spéciaux. Je ne propose pas de règle optionnelle pour cela, car il s'agit plus d'un art pour équilibrer tout ça que d'un set de modificateurs à appliquer.
Mais, vous avez envie de jouer des psioniques, des negamages, des jedis ou même des bardes à Shadowrun ? Lancez-vous ! Mais essayez de garder ça équilibré avec le reste ...



==== Compétences

Ce que j'attends des compétences, c'est :

* que chaque compétence soit utile en jeu.
  Tout ce qui est peu utile ou est sympa niveau fluff passe en compétence de connaissance.
  Tout ce qui est inutile ou alourdit le système est purement et simplement supprimé.
* que deux compétences ne se "recouvrent" pas ; en d'autres termes qu'il ne faille pas monter
  2 compétences pour faire une seule chose :
** je tire avec mon pistolet automatique, j'utilise pistolets ou armes automatiques ?
** je me fais passer pour quelqu'un dans quel ordre j'utilise imposture et déguisement ?
   et j'ai qu'une des deux compétences, je fais comment ?
** mon expert en armes lourdes, saute dans la tourelle du véhicule du rigger et se met à tirer !
   en plus il est sympa, il y a installé mon arme de prédilection ... comment ? non, je n'ai pas
   la compétences armes de véhicule ... QUOI ? je dois défausser sur mon agilité ? mais j'ai
   7 en armes lourdes ! T_T
* qu'elles soient flexibles, qu'on puisse les utiliser dans plusieurs contextes, éventuellement
  en changeant l'attribut lié : tu as la compétence "tirer au pistolet" ? donc tu sais tirer avec
  tous les putains de pistolets et tu as aussi la compétence "connaissance des pistolets" au même indice.
  Par contre, c'est pas pour ça que tu sais réparer les pistolets.
* que résoudre les actions liées à une compétence soit _rapide_

Ce que j'attends d'un groupe de compétences, en plus de ce que j'attends des compétences individuelles,
c'est que les compétences qui le composent :

* couvrent des domaines voisins, pour que la réduction de karma qu'offrent les groupes se justifie
* que la notion de "casser" ou de "refusionner" un groupe n'existe plus: maintenant, un groupe a l'indice
  de la plus basse des compétences que le PJ possède. Lorsque le joueur monte une compétence d'un groupe,
  il le fait soit au coût normal (si c'est la première ou la seconde compétence du groupe en termes d'indice),
  soit il le fait à moitié prix (si c'est la troisième compétence du groupe en termes d'indice), soit il le fait
  gratuitement (si c'est la quatrième compétence du groupe en termes d'indice).

Au final, on obtient 15 groupes de compétences, pile autant qu'avant.

Toutes les compétences qui restent sont liées à un groupe de compétences, et elles semblent toutes utiles.
Certaines sont peut-être trop utiles (manipulation, discrétion) ... à voir.

===== Réorganisation en détails

Groupes conservés tels quels: CRACKING(PIRATAGE), ELECTRONICS(ÉLECTRONIQUE), TASKING(TECHNOMANCIE), SORCERY(SORCELLERIE), CONJURING(CONJURATION), ENCHANTING(ENCHANTEMENT).

Groupe modifié: INFLUENCE

* impersonation + disguise = impersonation (déguisement) - c'est le talent d'acteur qui prime ; si pas la bonne tenue et/ou pas le bon lieu -> malus
* con + negociation = con (manipulation) - on va pas créer une comp exprès pour négocier le salaire
* intimidation


Groupe modifié: FIREARMS(ARMES À FEU)

* pistols (pistolets)
* rifles (armes d'épaule)
* heavy weapons (armes lourdes)

Groupe modifié: CLOSE COMBAT(CORPS À CORPS)

* melee weapons (armes de mêlée)
* unarmed combat (combat à mains nues)
* dodge (esquive): utile dans ce groupe pour _atteindre_ le corps à corps


Groupe modifié: STEALTH(FURTIVITÉ)

* sneaking (discrétion): camouflage, discrétion, filature, escamotage
* perception (perception)
* lockpicking (serrurerie)

Groupe modifié: OUTDOORS(PLEIN AIR)

* gymnastics (athlétisme)
* lancer + arc (armes de jet)
* survival (survie)

Nouveau groupe: ASTRAL CRAFT(ASTRAL)

* arcana (arcanes): créer des trames de sort qui sont des entités astrales ... allez, ça va pas trop mal conceptuellement avec les deux autres
* assensing (perception astrale): trouver les indices dans le monde astral
* astral combat (combat astral): taper les indices dans le monde astral

Groupe modifié: PILOT(CONDUITE)

* pilot aircraft + pilot aerospace (pilotage aérien)
* pilot ground craft + pilot walkers (pilotage terrestre)
* pilot watercraft (pilotage nautique)

Groupe modifié: ENGINEERING(INGÉNIERIE)

* aeronautics + automotive + nautical mechanics = vehicle mechanic (mécanique de véhicules)
* gun mechanic (armurerie): construire/réparer les flingues
* industrial mechanic (mécanique industrielle): de facture industrielle, hors véhicule, flingue ou -ware
* artisan (artisanat): pour tout le reste, y compris le travail de faussaire (artistique ou papier)


Groupe modifié: BIOTECH

* medecine (médecine): premiers soins, administration de médicaments ...
* chirurgy (chirurgie): tout ce qui nécessite d'ouvrir, de découper ou de greffer
* cybertechnology + biotechnology (cybertech): construire/réparer ce qui est augmentation technologique


Compétences de connaissance:

* etiquette: devient plusieurs compétences de connaissance: etiquette:la rue, etiquette:corpos, etc
* animal handling, escape artist, diving, free fall, performance, tracking: toutes celles-là sont d'un usage trop rare/fluff
* demolitions: de peu d'usage (setup booby trap + gagner un peu de DV pour quelque chose qui en fait déjà tant que ça)
  --> les explosifs ça tue, avec ou sans la compétence
* instruction: une compétence de connaissance pour pouvoir faire un jet de teamwork et aider un copain à apprendre ...
  allez, ça passe! Baisser le prix à une compétence de connaissance peut servir à favoriser le travail d'équipe et à
  souder le groupe ... du point de vue d'un MJ, c'est un outil qui ne fait pas de mal, je pense.
* leadership: perso, ça me gêne quand les PJ ne sont pas tous sur un pied d'égalité.
  Donc je refuserais de laisser les PJs bénéficier du jet de leadership d'un autre PJ.
  Cette compétence est donc réservée aux cas d'usage:
** PNJ chef d'un groupe de PNJs ou d'un groupe de PJ (et dans ce cas,
   peu importe combien de karma a investi le PNJ pour faire évoluer sa compétence)
** PJ chef d'un groupe de PNJs: cas rare, à priori -hormis si le PNJ parvient à se faire passer pour le chef de la sécurité
   d'un site ou d'un officier de police ... auquel cas la compétence de leadership ne se suffit pas à elle-même, et c'est
   déguisement qui fait le gros du boulot.


Compétences supprimées:

* groupe ACTING: compétences déplacées dans INFLUENCE, ou supprimées ou passées en compétences de connaissance
* exotic melee weapon, exotic ranged weapon, exotic vehicle: pas mécontent de m'en être débarassées, de celles-là!
* gunnery: c'est pas parce que tu utilise une arme montée en anneau ou en tourelle qu'elle se manie différement.
  Et un interfacé doit avoir appris à manier l'arme montée sur le véhicule où il plonge pour l'utiliser correctement,
  de même qu'un sammie qui se fait greffer une arme dans son bras ...
  Si il y avait eu une compétence nécessaire pour utiliser une arme télécommandée, quelle que soit cette arme,
  je l'aurais conservée (en passant probablement pilot watercraft en compétence de connaissance), mais là ...
* navigation, running, swimming (atout: se noie jamais, handicap: coule comme une pierre, par défaut: à peu près)


=== Équipement

==== Grades

Les grades alpha et delta appliqués à davantage de technologies que le seul cyberware, ça le fait !

Les prix des grades avancés sont par contre aussi prohibitifs qu'en SR4 et précédents.
Cependant, je trouve que ça reflète bien le fossé béant qu'il y a entre la majorité et les nantis.
En effet, si on peut se procurer du matériel delta à seulement 2,5 fois le prix de base, qui va encore s'acheter du matériel standard ?
Et à quoi servent les grades alpha et beta ? Aurais-je du supprimer ces grades intermédiaires, et faire perdre des possibilités de personnalisation aux personnages ?
Peut être ...

Néanmoins, il faut bien le reconnaître : déployer des trésors de patience, accumuler des contacts et des informations, économiser des scénarios entiers et parfois risquer sa vie pour voir ses efforts se concrétiser en un équipement delta, potentiellement le seul de sa vie, représente un vrai achèvement.
Devoir attendre d'engranger assez de succès, à cause de ces satanées règles de disponibilité, seule barrière plus ou moins abstraite entre son personnage et son prochain équipement delta qu'il aurait pu se payer depuis déjà 5 scénarios au moins, et recommencer le processus à zéro pour l'équipement delta suivant, ça parait juste frustrant ... En SR5, où est le coté rare, quasiment inatteignable et presque légendaire de l'équipement delta ?

Et puis, ton équipement delta de l'époque techno-thriller, ça devient du alpha ou même du standard pendant la période cyberpunk, et il devient obsolète à l'ère post-cyberpunk.
Le SOTA d'hier est la risée de demain, la vie est une course perdue d'avance pour rester compétitif, il y aura toujours un plus gros poisson que toi, tout ça ... c'est du cyberpunk.

==== Signature

Le système pour savoir si un personnage arrive à transporter son arme dans un lieu donné ni vu ni connu était, selon moi, bancal.
Un bonus/malus à la réserve de dés qui dépend de chaque arme signifie qu'il faut faire un test pour chaque arme. C'est long à résoudre.
De plus, le concept de seuil, une des bases du système, ne sert à rien, puisqu'on est dans un cadre binaire : "mon arme est détectée ? oui/non".

Enfin, les armes, les véhicules et les personnages ont chacun un système spécifique pour savoir s'ils sont reconnus en tant que tel.
Ça complique les choses.

J'ai donc repris le concept de Signature, qui est suffisamment abstrait pour s'appliquer aux personnages et aux objets.
Cela simplifie la résolution : maintenant, le détecteur/garde fait son jet simple.
Ce jet est assorti de modificateurs positifs en fonction de son outillage ou de sa méthode (détecteur, fouille au corps, ...).
On applique aussi des modificateurs négatifs si le personnage a pris des mesures particulières (tout sous le black trenchcoat, armes démontées, ...).

Ensuite, on fait une seule fois le jet, au lieu d'une fois par arme.
Toutes les armes dont la signature est inférieure aux succès nets obtenus est détectée.
Les autres passent le contrôle.
La Signature d'une arme est donc le seuil nécessaire pour la détecter lors d'un contrôle.

J'espère pouvoir appliquer le même principe aux véhicules ainsi que pour reconnaître/filer/retrouver la trace d'un personnage.


==== Armes

Le système de règle ne présente plus que les différents types d'armes.
On perd en choix ce qu'on gagne en simplicité.
De toutes façons, le vaste choix apparent des tables d'origine aboutissait souvent à voir les mêmes (meilleures) armes apparaître sur les PJ.
À l'inverse, certaines armes n'étaient jamais choisies, car non optimales.

Un choix si vaste est difficile à appréhender pour certains joueurs (débutants ou peu intéressés par le matos).
Il ralentit la création de personnage et distrait les joueurs en cours de partie.

Donc : on choisit son type d'arme, on lui colle un nom pour le fluff, mais quel que soit le nom ce sont les mêmes caractéristiques.
Si tu veux altérer les propriétés de ton arme, tu peux toujours altérer son grade ou considérer certains accessoires ou types de munitions built-in pour un modèle donné.

==== Armures

Ouais, j'ai réduit leurs indices. Ils passent de 8-15 environ à 1-4.

D'abord, ça combat l'inflation des réserves de dés, donc le temps nécessaire à compter ses succès, donc ça accélère le jeu.

Ensuite, vu qu'il fallait résoudre chaque round de violence avec un seul jet opposé, je devais fusionner les tests d'esquive et d'encaissement en un seul.
Cependant, lancer la moitié ou davantage de la réserve dés de ce nouveau test de défense grâce à son armure aurait contrevenu à l'objectif de replacer les capacités d'un personnage au centre, plutôt que son équipement.

En plus, le test de défense est à la fois de l'esquive et de l'encaissement.
Or, on peut considérer qu'une grosse armure ralentit les mouvements : l'armure devient plus lourde, plus rigide ...
Donc, l'apport des dés d'armure à la réserve de défense n'est pas aussi grand qu'on peut le penser, puisqu'en gagnant en blindage, on perd en esquive.

Enfin, ça semble contribuer à valoriser les grades d'équipement: gagner deux dés sur sa veste blindée beta pour passer sa protection de 9 à 11 lors d'un seul des deux jets de "défense", c'est pas forcément terrible.
Gagner deux dés pour la passer de 2 à 4 dés et doubler son indice pour le _seul_ jet de défense, comparativement ça semble tout de suite avoir davantage d'impact et justifier les nuyens supplémentaires.

