[[chapter_gear]]
== Équipement

[[KEY]]
=== Karma équivalent nuyens (KE¥)

Une partie du système de règles est fondée sur le principe qu'un point de karma
possède une équivalence en termes de nuyens.
Cette équivalence est purement mécanique et une des garanties de l'équilibre du jeu.
Ce n'est pas vraiment un concept rôleplay.

Le cours actuel est : 1 point de karma vaut à 2500¥.

[[gear_grades]]
=== Grades d'équipement

Afin de répondre à tous les besoins (et à tous les segments de marché), de nombreux produits sont disponibles en plusieurs grades, reflétant leur qualité de production -et leur prix.
Les grades sont les suivants :

.Grades d'équipement
[width=50%, options="header", cols="2*,.>"]
|===
|Grade    |Disponibilité |Prix
|Standard |-             |×1
|Alpha    |+2            |×1.5
|Beta     |+4            |×3
|Delta    |+8            |×5
|Omega    |-4            |×0.5
|===

* Le grade *Standard* représente les produits de grande consommation, sans personnalisation. Tous les équipements présentés dans ce chapitre sont de grade Standard.
* Le grade *Omega* représente des produits d'occasion, usagés, endommagés, démodés, ou dont l'usage a été suplanté par une technologie plus récente. Dans la plupart des cas, et hormis son prix, il est en tout point inférieur au grade Standard.
* Les autres grades représentent divers raffinements et personnalisations du produit, toujours de qualité supérieure au grade Standard. Le grade *Delta* représente le SOTA, ce qui se fait de mieux, et qui profite des plus récentes avancées technologiques pour une époque donnée.

Un produit donné ne peut être que d'un seul grade, qui peut varier suivant l'époque.

Dans une époque techno-thriller, par exemple, il est en général encore impossible de se faire implanter du cyberware d'occasion, car cette technologie est encore trop neuve et trop peu fiable.
De même, l'avènement du cyberware est encore trop récent pour avoir été rafiné en produits de grade delta.
À l'inverse, au fur et à mesure des innovations et des changements de direction technologiques (en ce qui concerne les différentes infrastructures matricielles qui se sont succédées, par exemple),
les époques ultérieures ont rendu obsolètes plusieurs produits anciennement de grade Standard ou supérieur.
Ces produits sont passés au grade Omega, quand il n'ont pas été rendus purement et simplement inutilisables.



[[gear_weapons]]
=== Armes

==== Caractéristiques

===== Dégâts

Représente le nombre de dés supplémentaires à lancer lors d'un test d'attaque.

* Le caractère **+** devant signifie que la <<attribute_body,Constitution>> de l'utilisateur
  s'ajoute aux dégâts de l'arme.
* Le caractère **S** derrière signifie que l'arme occasionne des dégâts étourdissants.

===== Signature

La signature d'une arme représente son Seuil pour la détecter lors d'un contrôle.

[[gear_availability]]
===== Disponibilité

TODO


==== Armes de mêlée

[[gear_weapons_melee]]
.Armes de mêlée
[width="70%", options="header", cols="4,^1,^1,^1,>1"]
|===
|Arme                  |Dégâts|Signature|Disponibilité |Prix
|Bâton téléscopique    | +2S  | 2¹      |2             |   50¥
|Batte                 | +2   | 1       |-             |   10¥
|Couteau de combat     | +1   | 3       |-             |   25¥
|Électro-matraque      |  4S  | 1       |4R            |  750¥
|Épée                  | +2   | 1       |6R            |  500¥
|Fouet                 | +1   | 2¹      |2             |   50¥
|Fouet monofilament    |  3³  | 2¹      |12F           | 3000¥
|Gant énergétique²     |  4S  | 2       |6R            | 1000¥
|Hache de combat       | +4   | 0       |8R            | 1000¥
|Matraque              | +1S  | 3       |-             |   10¥
|Lames d'avant-bras²   | +2   | 2¹      |6R            |  150¥
|Tomahawk              | +2   | 2       |4             |   50¥
|===
¹ Lorsque cette arme est utilisée, sa Signature est diminuée de 2.

² S'utilise avec la compétence <<skill_unarmed,Combat à mains nues>>.

³ La cible ne bénéficie pas de son armure.



==== Armes à distance

[[gear_weapons_throwing]]
.Armes de jet
[options="header", cols="4,^1,^1,^3,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Signature|Disponibilité |Prix
|Couteau de lancer     | CC  | +1   |  TODO          | 3       | 4            |   25¥
|Grenade TODO          | CC  |TODO  |  TODO          | TODO    |TODO          | TODO¥
|Grenade TODO          | CC  |TODO  |  TODO          | TODO    |TODO          | TODO¥
|Grenade TODO          | CC  |TODO  |  TODO          | TODO    |TODO          | TODO¥
|Tomahawk              | CC  | +2   |  TODO          | 4       | 4            |   50¥
|===

[[gear_weapons_archery]]
.Armes de trait
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Signature|Disponibilité |Prix
|Arc                   | CC  |+4    |  5/50/150/300  |  1(f)   | 0       |2             |  300¥
|===

[[gear_weapons_pistols]]
.Armes de poing
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Signature|Disponibilité |Prix
|Arbalète de poing     |CC/TR|  2   |  5/10/15/20    |  3(f)   | 2       |4R            |  300¥
|Taser                 | CC  |  4S  |  5/10/15/20    |  4(m)   | 2       |-             |  200¥
|Pistolet petit calibre| CC  |  2   |  5/15/30/50    |  6(c)   | 4       |4R            |  150¥
|Pistolet léger        | SA  |  2   |  5/15/30/50    | 12(c)   | 3       |4R            |  250¥
|Pistolet automatique  | TR  |  2   |  5/15/30/50    | 35(c)   | 3       |8R            |  500¥
|Pistolet lourd        | SA  |  3   |  5/20/40/60    | 12(c)   | 2       |4R            |  500¥
|Pistolet mitrailleur  | TR  |  3   | 10/40/80/120   | 24(c)   | 1       |6R            |  750¥
|===

[[gear_weapons_rifles]]
.Armes d'épaule
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts|Portée          |Munitions|Signature|Disponibilité |Prix
|Arbalète lourde       | CC  |  4   | 10/40/80/120   |  1(f)   | 1       |4R            |  300¥
|Fusil à pompe         | SA  |  4   | 10/40/80/120   |  8(m)   | 1       |4R            | 1000¥
|Fusil d'assaut     |SA/TR/TA|  3   | 50/150/300/500 | 35(c)   | 1       |8F            | 2000¥
|Fusil de chasse       | CC  |  4   |100/250/500/800 |  8(m)   | 0       |4R            | 1000¥
|Fusil de sniper       | CC  |  5   |150/300/800/1500| 12(c)   | 0¹      |12F           |10000¥
|===

[[gear_weapons_heavy]]
.Armes lourdes
[options="header", cols="4,^1,^1,^3,^1,^1,^1,>1"]
|===
|Arme                  |Mode |Dégâts |Portée          |Munitions      |Signature|Disponibilité |Prix
|Mitrailleuse          | TA  |  6    | 80/250/800/1200|50(c) ou 100(b)|0/Oublie |12F           | 7500¥
|Canon d'assaut        | CC  |  8    |100/300/800/1500| 20(c)         |0/Oublie |20F           | 5000¥
|Lance-grenades        | CC  |Grenade|*50/100/150/500 |  8(m)         | 1       |10F           | 1500¥
|Lance-missiles        | CC  |Missile|*80/250/500/1500|  1(ml)        |0/Oublie |10F           | 1500¥
|===


==== Modification d'armes

[[gear_weapons_grades]]
.Armes: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Modifications
|Alpha    | 1
|Beta     | 2
|Delta    | 4
|Omega    | -¹
|===
¹ TODO Une arme de grade Omega s'enraye sur un glitch, et explose sur un critical glitch ?

TODO _faire les accessoires si ça vaut le coup ; sinon, intégrer les accessoires dans les grades d'armes_

TODO _le grade donne des améliorations: +dégâts, +portée, +munitions, signature(composition céramique, munitions caseless),_
_autre chargeur, changement du calibre, nouveau mode de tir, accessoire incorporé, et ainsi de suite_



[[gear_armor]]
=== Armures

L'indice d'une armure représente le nombre de dés supplémentaires à lancer lors du <<defense_test,test de défense>> du personnage qui la porte.

.Armures
[width=70%, options="header", cols="4,^2,>3,>3"]
|===
|Armure              |Indice |Disponibilité |Prix
|Vêtements normaux   |0      |-             |20¥-100000¥
|Vêtements renforcés |1      |2             |500¥
|Veste blindée       |2      |4             |1000¥
|Armure de sécurité  |4      |14R           |2000¥
|===

Altérer le grade d'une armure influe sur son indice de protection, comme l'indique la <<gear_armor_grades,table suivante>>.

[[gear_armor_grades]]
.Armures: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Indice
|Alpha    |+1
|Beta     |+2
|Delta    |+3
|Omega    |-1¹
|===
¹ L'indice ne peut pas passer en dessous de 0.
Des vêtements normaux de grade Omega sont très démodés ou portent clairement un ou plusieurs témoignages de leur porteur précédent, et peuvent infliger un modificateur négatif aux <<chapter_social,interactions sociales>> du personnage qui les porte.





[[gear_cyberware]]
=== Cyberware

L'Homme s'est toujours demandé comment surmonter ses limitations et améliorer le corps qui est le sien.
Le cyberware et ses descendants (bioware, geneware) Lui ont apporté une réponse.

Le cyberware permet à un personnage d'obtenir tous les bénéfices de l'<<chapter_augmentation,Augmentation>>.
Les augmentations issues du cyberware ont les limitations habituelles.

En termes de règles, on considère que chaque augmentation de caractéristique du personnage est due à un *implant*.
Chaque implant est une abstraction d'un ou plusieurs organes, membres artificiels ou équipements.
Lorsque cet implant est greffé sur le personnage (suite à une intervention médicale plus ou moins sûre),
celui-ci bénéficie du bonus d'augmentation désiré.

Il est nécessaire de prendre en compte les considérations suivantes :

* Le personnage doit posséder l'attribut <<attribute_essence,Essence>>.
  Le coût de toute augmentation obtenue par le cyberware est déduit de son <<attribute_essence,Essence>>.
* Le prix de base de tout item de cyberware est égal à son coût multiplié par 25 000¥.
* Un personnage peut payer plus ou moins que ce prix de base pour modifier le grade d'un item de cyberware.
  Cette modification du prix entraine une modification du coût de l'augmentation correspondante,
  comme l'indique la <<gear_cyberware_grades,table suivante>>.
  Le choix du grade d'un item de cyberware doit être fait avant son achat, car il influe sur le prix à payer
  ainsi que sur la disponibilité de l'objet.

[[gear_cyberware_grades]]
.Cyberware: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Essence
|Standard | ×1
|Alpha    | ×0.8
|Beta     | ×0.6
|Delta    | ×0.5
|Omega    | ×1.5
|===





[[gear_cyberdeck]]
=== Cyberdecks

L'indice d'un cyberdeck représente la puissance globale de ses composants et des programmes installés.
Le détail des spécifications techniques varie grandement, et l'indice lui même subit diverses appellations (par exemple, MPCP ou FADS) suivant l'époque.
Dans tous les cas, l'indice du cyberdeck utilisé par un personnage entre directement dans le calcul de la réserve de dés lors des <<chapter_matrix,actions matricielles>> qu'il entreprend.

.Cyberdecks
[width=25%, options="header", cols="^1,>2"]
|===
|Indice|Prix
|1     |  4000¥
|2     |  8000¥
|3     | 16000¥
|4     | 32000¥
|5     | 64000¥
|6     |128000¥
|===

Altérer le grade d'un cyberdeck influe sur l'initiative de son l'utilisateur, comme l'indique la <<gear_cyberdeck_grades,la table suivante>>.

[[gear_cyberdeck_grades]]
.Cyberdecks: grades
[width=25%, options="header", cols="2*"]
|===
|Grade    |Initiative
|Alpha    |+1D6
|Beta     |+2D6
|Delta    |+3D6
|Omega¹   |-
|===
¹ Un cyberdeck de grade Omega ne peut pas passer en VR.





[[gear_false_identity]]
=== Fausses identités

La Signature d'une fausse identité ou d'un faux permis correspond à son Indice.

L'Indice maximal d'une fausse identité ou d'un faux permis est de 6.

Un faux permis est forcément associé à une identité (réelle ou fausse).

Si une fausse identité est mise à jour, tous les faux permis associés le sont aussi.

.Fausses identités
[width=50%, options="header", cols="1,^1,>1"]
|===
|Type            |Disponibilité |Prix
|Fausse identité |(Indice × 3)F |Indice × 2500¥
|Faux permis     |(Indice × 3)F |Indice ×  200¥
|===



[[sensors]]
=== Senseurs

Chaque senseur est conçu pour détecter un chose précise. Les changements de pression,
la radioactivité, les ondes sonores, les perturbations électromagnétiques, les mouvements
en sont quelques exemples.

Lorsqu'un personnage utilise sa compétence de <<skill_perception,perception>> en utilisant un
senseur, celui-ci peut lui permettre d'obtenir des informations supplémentaires, en fonction
du type de senseur ainsi que du resultat de son test.

Un senseur a en général une portée de 10 mètres.
Une caméra, un microphone directionnel où un télémètre, peuvent évidemment avoir une portée plus longue.

Pour pouvoir enregistrer, un senseur doit être couplé à un stockage interne ou externe (25¥).

[[gear_sensor]]
.Senseurs
[width="40%", options="header", cols="4,>1"]
|===
|Senseur                |Prix
|Caméra                 | 50¥
|Compteur Geiger        | 50¥
|Détecteur de cyberware |300¥
|Détecteur de métaux    |150¥
|Détecteur de mouvement | 50¥
|Microphone             | 50¥
|Microphone laser       |200¥
|Radar                  |500¥
|Scanner radio          | 50¥
|Station météo          | 50¥
|Télémètre laser        |100¥
|===

Un senseur intelligent possède un indice pouvant aller de 1 à 12.
Cet indice constitue la réserve de dés du senseur pour ses jets de <<skill_perception,perception>>.
Un tel appareil est conçu pour fonctionner sans assistance, du moment qu'il est alimenté en énergie.
Pour être utile, un senseur automatisé doit évidemment être relié à quelque chose à qui
envoyer un signal lorsqu'il réagit à l'objet de sa détection.

Pour connaître le prix d'un senseur intelligent, il faut multiplier son prix de base par son indice.
Par exemple, un microphone laser à main coûte 200¥, tandis qu'un détecteur de mouvements
intelligent d'indice 6 coûte 300¥.

[[gear_automated_sensor]]
.Senseur intelligent
[width="50%", options="header", cols="3,>3"]
|===
|Senseur intelligent       |Prix
|Senseur intelligent (1-12)|(Indice × Prix de base)¥
|===

Les options suivantes peuvent être ajoutées à divers systèmes de vision (caméra, lentilles de contact, yeux cybernétiques, etc).

[[gear_vision]]
.Systèmes de vision
[width="40%", options="header", cols="4,>1"]
|===
|Type                   |Prix
|Anti-flash             | 50¥
|Afficheur rétinien     | 25¥
|Interface d'armes      |500¥
|Lumière faible         |100¥
|Thermographique        |100¥
|===

Les options suivantes peuvent être ajoutées à tout système audio.

[[gear_audio]]
.Systèmes audio
[width="40%", options="header", cols="4,>3"]
|===
|Type                   |Prix
|Amortisseur de sons    | 50¥
|Filtre sonore sélectif |Indice × 100¥
|Lecteur                | 25¥
|Ultrasons              |200¥
|===



=== Kits de compétence

*TODO*

=== Drogues

*TODO* _'Pas trop mon truc, mais bon ..._

