[[chapter_karma]]
=== Progression du personnage

[[karma_costs]]
.Progression du personnage
[width=70%, options="header", cols="2,>1"]
|===
|Progression                                |Coût en karma
|Améliorer un attribut de 1                 |Nouvel indice ×5
|Améliorer un groupe de compétences de 1    |Nouvel indice ×5
|Améliorer une compétence           de 1    |Nouvel indice ×2
|Améliorer une connaissance         de 1    |Nouvel indice
|<<chapter_special_grades,Initiation>>      |10 + (Nouveau grade ×3)
|Acquérir un nouvel avantage                |Valeur
|Surmonter un défaut¹                       |Valeur
|Nouveau sort                               | 5
|===
¹ Un défaut issu du métatype d'un personnage ne peut pas être surmonté.


[[chapter_special_grades]]
==== Initiation

Faire progresser un attribut spécial au delà de 6, bien que possible, représente pour un personnage
une étape importante dans la compréhension de lui-même et du monde qui l'entoure.
La nature de cette compréhension et le moyen pour y arriver varient suivant l'attribut spécial considéré,
et parfois le personnage lui-même : sa tradition, le moment de sa vie, et ainsi de suite.

Ce processus porte divers noms.
Par exemple, les magiciens et les adeptes nomment ce processus Initiation ; les technomanciens le nomment Submersion.
Dans un souci de simplification et que pour des raisons historiques, seul le terme *Initiation* sera utilisé ici,
quel que soit l'attribut spécial considéré.

Tous les processus d'initiation ont certains points communs :

* Chaque initiation est lié à un <<attribute_specials,attribut spécial>> donné.
* Le nombre de fois qu'un personnage s'est initié à un attribut spécial donné donne son *grade d'initié* dans cet attribut spécial.
* L'indice maximum d'un attribut spécial est de *6 + grade d'initié* du personnage dans l'attribut spécial concerné.
  Une fois initié, le personnage peut donc faire <<karma_costs,progresser>> cet attribut spécial plus loin.
* Atteindre un nouveau grade d'initié permet d'acquérir une *capacité* supplémentaire inédite.
  Cette capacité est souvent inaccessible aux pratiquants moins avancés que le personnage.
* En raison de l'investissement personnel important nécessaire pour atteindre une compréhension et une puissance supérieures,
  l'initiation coûte du karma. Il est possible d'accomplir une *épreuve* pour réduire ce coût en karma.
  Cependant, cette épreuve affaiblit bien souvent le personnage d'une manière ou d'une autre.

[[option_uninitiated]]
[NOTE.option,caption="Règle optionnelle"]
====
*Initiation facultative*

*Règle :*
Les attributs spéciaux n'ont plus de maximum.
Un personnage peut faire progresser la valeur de n'importe lequel de ses attributs spéciaux,
du moment qu'il possède le karma nécessaire.
Il n'a pas besoin de s'initier pour cela.

L'initiation reste cependant accessible, mais elle ne sert plus qu'à acquérir des capacités supplémentaires.

*Motivation :* Simplifier le jeu et permettre de pouvoir passer sous silence toute cette section.
Alternativement, le MJ peut même carrément limiter tous les attributs spéciaux à un indice maximum de 6 ...
====

*TODO* _Reprendre les règles de l'initiation et de la submersion, et peut-être créer des pouvoirs sympas pour l'Essence et les adeptes du -ware (redline ? capacité augmentée ? bonus aux effets ?), ainsi que pour l'Edge, pourquoi pas ..._

