
[[chapter_magic]]
== Magie

=== Actes magiques

Chaque test de compétence des groupes <<skill_group_sorcery,Sorcellerie>>, <<skill_group_conjuring,Conjuration>> et <<skill_group_enchanting,Enchantement>> est un acte magique.

Chaque acte magique est associé à une *Valeur de Drain (VD)*.
Ce Drain signifie à priori qu'immédiatement après chaque acte magique qu'il entreprend, un magicien <<apply_damage,souffrira du nombre de cases de dégâts>> correspondants.
Contrairement aux dommages habituels ne sont réduits ni par l'<<gear_armors,armure>>, ni par la <<attribute_body,Constitution>> du magicien.
Sauf mention contraire, les dégâts d'un Drain sont étourdissants.

Les actes magiques se résolvent soit par un <<simple_test,test simple>>, soit par un <<opposed_test,test opposé>>.
La procédure est cependant légèrement différente de d'habitude, en cela que le magicien peut ne pas utiliser tous ses *succès nets* pour améliorer sa marge de réussite.

Le magicien peut utiliser chacun des succès nets qu'il a obtenus lors de son test d'acte magique d'une des manières suivante :

* Réduire la VD de l'acte magique de 1.
  Les dommages dus au Drain peuvent être totalement annulés de cette manière.
* Réduire le temps nécessaire pour accomplir l'acte magique ...
** ... de 1 action si le temps se mesure en actions. +
   Le test ne peut pas prendre moins d'une action.
** ... de 1 minute si le temps se mesure en minutes. +
   Le test ne peut pas prendre moins d'une minute.
** ... de 1 heure si le temps se mesure en heures. +
   Le test ne peut pas prendre moins d'une heure.
* Améliorer sa marge de réussite.
  Cela modifie les effets comme décrit dans l'action magique en question.

==== Résistance à la magie

Une cible non consentante d'un acte magique effectue un test de [.formula]#<<attribute_charisma,Charisme>> + <<magic_defense,Défense magique>>#.
Chaque succès réduit la marge de réussite de l'acte magique la prenant pour cible de 1.
Ce test est automatique, et ne coûte aucune action à la cible.

Par défaut, on considère que toute cible est non consentante, y compris si elle est surprise ou inconsciente.

Les objets n'effectuent pas de test de résistance.
Le seuil de réussite pour les affecter dépend de leur complexité, comme indiqué dans la <<object_resistance,table ci-dessous>>.

.Résistance des objets
[[object_resistance]]
[options="header", cols="2,4e,^1"]
|===
|Type d'objet           |Exemples                                           |Seuil
|Naturel                |Arbre, sol, eau non-traitée                        |1
|Manufacturé, Low-tech  |Brique, cuir, meuble en bois                       |2
|Manufacturé, High-tech |Plastiques, équipement électronique                |3
|Hautement transformé   |Ordinateurs, drones, véhicules, produits chimiques |5+
|===



[[sorcery]]
=== Sorcellerie

==== Incantation

Le lancement d'un sort est un <<simple_test,test simple>> si la cible est consentante, et un <<opposed_test,test opposé>> si elle ne l'est pas.
Le magicien effectue un test [.formula]#Intelligence + <<skill_spellcasting,Incantation>>#.



[[magic_defense]]
==== Défense magique

Un magicien peut déployer une protection magique passive sur ses alliés.
Il dispose pour cela d'autant de dés de défense magique que son indice de compétence <<skill_counterspelling,Contresort>>.

Il peut étendre cette défense magique à un nombre maximum de personnages (lui y compris) égal à sa <<attribute_magic,Magie>>.
Chaque personnage peut bénéficier d'un nombre de dés de défense magique au maximum égal à la <<attribute_magic,Magie>> du magicien.

Il faut à un magicien une action complexe pour sélectionner les bénéficiaires de sa défense magique.
Une fois que c'est fait, cette protection dure jusqu'à ce que le magicien en change, qu'il tombe inconscient, ou qu'il subisse en une seule fois un nombre de cases de dégâts supérieur à son <<attribute_charisma,Charisme>>.

Toutefois, si un des personnages protégés quitte la ligne de vue du magicien, il n'est plus protégé.
Le magicien n'a pas besoin d'avoir constamment le personnage sous les yeux, mais il doit pouvoir le regarder s'il le faut.

La défense magique prodiguée par un magicien n'est efficace que contre les sorts.

Si un des personnages sous sa protection se fait attaquer par un sort, ce personnage peut bénéficier des dés de défense magique que le magicien lui a octroyés pour son test de résistance.
Ces dés supplémentaires ne sont disponibles que pour résister à ce sort en particulier.
Les dés de défense magique se reconstitue à chaque tour du magicien.

À noter que le <<adept_powers,pouvoir d'adepte>> *Défense magique* fonctionne contre tout acte magique, plusieurs fois par tour si nécessaire.
Cependant, seul l'adepte qui le possède en bénéficie.

Les défenses magiques issues de plusieurs sources sont cumulatives.



[[counterspelling]]
==== Dissipation

Un magicien qui dispose d'une action peut essayer de dissiper un sort actif ou en cours de lancement.
Il peut entreprendre cela que le sort le prenne pour cible ou non.
Il effectue un test d'[.formula]#<<attribute_intelligence,Intelligence>> + <<skill_counterspelling,Contresort>>#.
Chaque succès réduit la marge de réussite du sort.

Dissiper un sort est un acte magique dont la Valeur de Drain est égale à [.formula]#<DV du sort> /2#.

Un sort dissipé en cours de lancement ne dispense pas le magicien qui l'incante de son Drain.



[[ritual_sorcery]]
==== Sorcellerie rituelle

Le leader d'une équipe rituelle lance un sort <<spellcasting,de la manière habituelle>>.
Cela lui prend cependant toujours [.formula]#12 - <<attribute_magic,Magie>># heures.
Il peut néanmoins bénéficier des modificateurs de <<teamwork_test,travail en équipe>>.

Tous les membres de l'équipe rituelle (observateur inclus) souffrent des mêmes dommages dus au Drain.



[[spell_list]]
==== Grimoire

===== Sorts

*TODO*

===== Tours de magie

Un tour de magie permet de déclencher un effet magique mineur, bien inférieur aux possibilités habituelles d'un sort.
En termes de puissance, un tour de magie reproduit l'effet d'un élément d'équipement standard, sans personnalisation ni option, d'une valeur maximale de 500¥ environ.
Un tour de magie peut généralement être maintenu de la même manière qu'un sort normal.
Cependant, l'effet reproduit _ne peut entraîner aucun effet mécanique_ : un tour de magie ne peut occasionner aucun dommage direct, n'entraîner aucune modification d'indice, ne donner aucun modificateur, et ainsi de suite.

Voici quelques exemples de tours de magie usuels :

====== Combat
*Chasse Insectes :* Tue ou éloigne les petits insectes normaux dans une zone de 50cm autour du lanceur. +
*Court circuit :* Crée une légère impulsion magnétique. Insuffisante pour endommager un équipement électronique, elle peut cependant surprendre quelqu'un ou griller un tag RFID. +
*Flamme :* Une flamme équivalente à celle d'un briquet apparait dans la main du lanceur. +
*Lumière :* Le lanceur crée un globe de lumière éclairant autant qu'une lampe torche. +
*Mouillage / Séchage :* La cible est mouillée ou séchée ; le volume d'eau maximal affecté est celui contenu dans un seau. +

====== Détection
*Jumelles :* Le lanceur voit au loin comme s'il se servait de jumelles standard. +
*Éphéméride :* Le lanceur apprend l'heure et la température exactes. Il localise aussi la direction du Nord magnétique. +

====== Santé
*Coup de fouet :* Le lanceur est instantanément réveillé comme s'il avait avalé une tasse de café ou de boisson énergisante, mais n'en tire aucune plaisir particulier. +
*Nutrition :* Le lanceur est instantanément nourri comme s'il avait englouti une ration de voyage, mais n'en tire aucun plaisir particulier. +

====== Illusion
*Hologramme :* Le lanceur crée entre ses mains une réprésentation en volume de son choix. La représentation doit tenir dans un cube de 50cm de coté, et sa qualité est limitée par la compétence artistique du lanceur. +
*Ventriloquie :* Le lanceur produit un son ne dépassant pas les capacités d'un ventriloque. +

====== Manipulation
*Croissance :* Le lanceur fait pousser de manière accélérée une plante usuelle pour la région et d'une taille équivalente à celle d'une fleur ou d'un touffe d'herbe. +
*Doigts invisibles :* TODO +
*Maquillage :* La cible est maquillée ou démaquillée dans un style au choix du lanceur. +
*Mode :* La coupe des vêtements de la cible est altérée. La qualité de la coupe est limitée par la compétence du lanceur. Ce sort ne peut cibler les armures, ou donner aux vêtement l'apparence d'une armure. +



[[conjuring]]
=== Conjuration

Le drain des trois actions magiques de conjuration est étourdissant si la Puissance de l'esprit est inférieure ou égale à la magie du personnage, et physique si elle est strictement supérieure.

[[summoning]]
==== Invocation

[.opposition]
|===
|Personnage |Charisme + <<skill_invocation,Invocation>> |Gain de services
|Esprit     |Puissance                                  |Drain¹
|===

¹ Le Drain d'une invocation est égal au nombre de succès (_pas_ succès nets) obtenus par l'esprit à son test, avec un minimum de 1.

Invoquer un esprit prend *12 - <<attribute_magic,Magie>> de l'invocateur* actions complexes, avec un minimum de 1 action complexe.

*Effet :* Un succès net au test d'invocation permet d'obtenir un service de la part de l'esprit.

Un esprit invoqué doit rester dans un rayon de Puissance × 50 mètres de son lieu d'invocation.

Tous les services que doit un esprit invoqué expirent au lever ou au coucher de soleil, suivant ce qui arrive en premier.

[[banishing]]
==== Bannissement

[.opposition]
|===
|Personnage |Charisme + <<skill_invocation,Banissement>> |Réduction des services
|Esprit     |Puissance¹                                  |Drain
|===

¹ Un esprit lié ajoute la <<attribute_magic,Magie>> de son maître actuel à sa réserve de dés.

Tenter de bannir un esprit prend 1 action complexe.

Le Drain d'un banissement est égal au nombre de succès nets obtenus par l'esprit.

*Effet :*
Chaque succès net au test de banissement permet de réduire le nombre de services que doit l'esprit de 1.
Le service que l'esprit est actuellement en train d'exécuter est toujours annulé en dernier.
Si tous les services dus par l'esprit à son maître sont annulés de cette manière, l'esprit est banni.

Cependant, un esprit banni ne disparait qu'à la fin du tour suivant son banissement.
Il ne peut accomplir aucune action (hors action libre) durant ce laps de temps.
Un invocateur autre que son ancien maître peut cependant en profiter pour tenter de l'invoquer.
Le temps de l'invocation est dans ce cas réduit à une action complexe.

[[binding]]
==== Lien

[.opposition]
|===
|Personnage |Charisme + <<skill_binding,Lien>> |Gain de services permanents
|Esprit     |Puissance × 2                     |Drain¹
|===

¹ Le Drain d'une invocation est égal au nombre de succès (_pas_ succès nets) obtenus par l'esprit à son test, avec un minimum de 1.

Lier un esprit prend *12 - <<attribute_magic,Magie>> de l'invocateur + Puissance de l'esprit* heures, avec un minimum de 1 heure.

*Effet :* Un succès net au test de lien permet d'obtenir un service permanent de la part de l'esprit.

Un invocateur ne peut tenter de lier qu'un esprit qu'il a personnellement invoqué.

Toute tentative de lier un esprit provoque l'expiration de tous les services non permanents qu'il doit à son maître.

Un esprit lié ne disparait pas avec le lever ou le coucher du soleil.

Un esprit lié peut accomplir des services distants.



[[enchanting]]
=== Enchantement

*TODO*

[[traditions]]
=== Traditions

Traits pouvant être appliqués aux traditions.
Ces traits ne peuvent pas être appliqués à un personnage.

==== Esprit lié à son domaine (-) [tradition,invocation]

Un esprit invoqué ne peut se déplacer qu'au sein de son domaine.
Ce domaine s'étend au maximum à Puissance × 10 mètres de rayon de son lieu d'invocation.
Le domaine d'un esprit correspond à son type.

Un esprit lié à un maître n'est pas soumis à cette restriction.

==== Esprit lié à son invocateur (+) [tradition,invocation]

Un esprit invoqué n'est pas lié à son lieu d'invocation.
Il doit cependant rester aux alentours de son maître.
L'esprit ne peut s'éloigner de plus de Puissance × 10 mètres de celui qui l'a invoqué.

Un esprit lié à un magicien n'est pas soumis à cette restriction.

==== Invocation longue durée (+) [tradition,invocation]

Tous les services que doit un esprit invoqué expirent au lever ou au coucher de soleil, suivant ce qui arrive en dernier.

==== Offrandes (-) [tradition,invocation]

L'invocation d'un esprit nécessite des éléments difficilement trouvables en pratique.
Ces éléments ne sont pas forcément rares ou coûteux.
Cependant, l'invocateur doit réaliser ses invocations dans un lieu protégé et préparé à cette intention.

Par exemple, l'invocation d'un esprit particulier peut nécessiter un cercle d'invocation spécial, ou un élément matériel approprié à son type (un grand feu de cheminée, un bassin d'eau pure, les possessions d'un ancêtre, un cadavre frais, etc).
La qualité et/ou la quantité de l'offrande dépend en général de la puissance de l'esprit à invoquer.

