
[[chapter_magic]]
=== Magie

Chaque test de compétence des groupes Sorcellerie, Conjuration et Enchantement est une action magique.
Les actions magiques se résolvent soit par un test simple soit par un test opposé.
Le magicien peut utiliser chacun de ses succès nets obtenus lors d'un test d'action magique de la manière suivante :

* Réduire le temps nécessaire à accomplir l'action ...
** ... de 1 action si le temps se mesure en actions. Le test ne peut pas prendre moins d'une action.
** ... de 1 heure si le temps se mesure en heures. Le test ne peut pas prendre moins d'une heure.
* Réduire le Drain de 1. Les dommages dus au Drain peuvent être totalement annulés de cette manière.
* Améliorer les effets tel que décrit dans l'action magique en question.





==== Sorcellerie

===== Incantation

Le lancement d'un sort est un test simple si la cible est consentante, et un test opposé si elle ne l'est pas.

[.opposition]
|===
|Personnage |Intelligence + <<skill_spellcasting,Incantation>> |Effets du sort
|Cible      |Charisme + Défense Magique                        |-
|===

La *Défense Magique* de base d'un personnage est égale à :

* sa <<attribute_body,Constitution>> contre un sort physique
* la moitié de son <<attribute_intelligence,Intelligence>> contre un sort mental

Elle peut être augmentée de la manière suivante:
* en bénéficiant de la <<magic_defense,Défense magique>> d'un magicien
* par le <<pouvoir d'adepte,power_mystic_defense>> correspondant



===== Contresort

===== Défense magique

Un magicien peut déployer une protection magique passive sur ses alliés.
Il dispose pour cela d'autant de dés de défense magique que son indice de compétence <<skill_counterspelling,Contresort>>.

Il peut étendre cette défense à un nombre maximum de personnages (lui y compris) égal à sa <<attribute_magic,Magie>>.
Il faut à un magicien une action complexe pour sélectionner les bénéficiaires de sa défense magique.
Une fois que c'est fait, cette protection dure jusqu'à ce que le magicien en change ou qu'il tombe inconscient.

Toutefois, si un des personnages protégés quitte la ligne de vue du magicien, il n'est plus protégé.
Le magicien n'a pas besoin d'avoir constamment le personnage sous les yeux, mais il doit pouvoir le regarder s'il le faut.

La défense magique n'est efficace que contre les sorts.

Si un des personnages sous sa protection se fait attaquer par un sort, le magicien peut activer la Défense Magique de tous les bénéficiaires.
Le magicien doit prendre tout ou partie des dés de sa défense magique (avec un maximum égal à sa <<attribute_magic,Magie>>) pour augmenter d'autant la Défense Magique de tous ceux qu'il protège.
Cette augmentation ne s'applique que contre ce sort particulier.

La défense magique se reconstitue à chaque tour du magicien.

===== Dissipation

Un magicien peut aussi adopter une posture plus active en dissipant directement un sort actif ou en cours de lancement.

Si le sort est en cours de lancement, le magicien doit utiliser une action de réaction pour cela.

[.opposition]
|===
|Attaquant  |Intelligence + <<skill_spellcasting,Incantation>>     |Effets du sort
|Personnage |Intelligence + <<skill_counterspelling,Contresort>>   |-
|===

Contrer un sort en cours de lancement coûte une action de réaction.

Chaque succès réduit les succès du magicien attaquant.

Le personnage résiste ensuite au drain original du sort grâce à ces mêmes succès.

[.opposition]
|===
|Personnage |Intelligence + <<skill_counterspelling,Contresort>>   |Réduit les succès du sort
|Sort actif |<<attribute_magic,Magie>> du lanceur + Succès obtenus |-
|===

Dissiper un sort actif coûte une action complexe.

Chaque succès réduit les succès du sort.
Un sort réduit à 0 est complètement dissipé.

Le personnage résiste ensuite au drain original du sort grâce à ces mêmes succès.



===== Sorcellerie rituelle

*TODO* _Grosso modo pareil, à la sauce incantation. On pourrait aussi créer une technique métamagique pour supporter le départs/décès d'une partie de l'équipe rituelle?_





==== Conjuration

Le drain des trois actions magiques de conjuration est étourdissant si la Puissance de l'esprit est inférieure ou égale à la magie du personnage, et physique si elle est strictement supérieure.

===== Invocation

[.opposition]
|===
|Personnage |Charisme + <<skill_invocation,Invocation>> |Gain de services
|Esprit     |Puissance                                  |Drain¹
|===

¹ Le Drain d'une invocation est égal au nombre de succès (_pas_ succès nets) obtenus par l'esprit à son test, avec un minimum de 1.

Invoquer un esprit prend *12 - <<attribute_magic,Magie>> de l'invocateur* actions complexes, avec un minimum de 1 action complexe.

*Effet :* Un succès net au test d'invocation permet d'obtenir un service de la part de l'esprit.

Un esprit invoqué doit rester dans un rayon de Puissance × 50 mètres de son lieu d'invocation.

Tous les services que doit un esprit invoqué expirent au lever ou au coucher de soleil, suivant ce qui arrive en premier.

===== Bannissement

[.opposition]
|===
|Personnage |Charisme + <<skill_invocation,Banissement>> |Réduction des services
|Esprit     |Puissance¹                                  |Drain
|===

¹ Un esprit lié ajoute la <<attribute_magic,Magie>> de son maître actuel à sa réserve de dés.

Tenter de bannir un esprit prend 1 action complexe.

Le Drain d'un banissement est égal au nombre de succès nets obtenus par l'esprit.

*Effet :*
Chaque succès net au test de banissement permet de réduire le nombre de services que doit l'esprit de 1.
Le service que l'esprit est actuellement en train d'exécuter est toujours annulé en dernier.
Si tous les services dus par l'esprit à son maître sont annulés de cette manière, l'esprit est banni.

Cependant, un esprit banni ne disparait qu'à la fin du tour suivant son banissement.
Il ne peut accomplir aucune action (hors action libre) durant ce laps de temps.
Un invocateur autre que son ancien maître peut cependant en profiter pour tenter de l'invoquer.
Le temps de l'invocation est dans ce cas réduit à une action complexe.

===== Lien

[.opposition]
|===
|Personnage |Charisme + <<skill_binding,Lien>> |Gain de services permanents
|Esprit     |Puissance × 2                     |Drain¹
|===

¹ Le Drain d'une invocation est égal au nombre de succès (_pas_ succès nets) obtenus par l'esprit à son test, avec un minimum de 1.

Lier un esprit prend *12 - <<attribute_magic,Magie>> de l'invocateur + Puissance de l'esprit* heures, avec un minimum de 1 heure.

*Effet :* Un succès net au test de lien permet d'obtenir un service permanent de la part de l'esprit.

Un invocateur ne peut tenter de lier qu'un esprit qu'il a personnellement invoqué.

Toute tentative de lier un esprit provoque l'expiration de tous les services non permanents qu'il doit à son maître.

Un esprit lié ne disparait pas avec le lever ou le coucher du soleil.

Un esprit lié peut accomplir des services distants.



==== Enchantement

*TODO*

==== Traditions

Traits pouvant être appliqués aux traditions.
Ces traits ne peuvent pas être appliqués à un personnage.

===== Esprit lié à son domaine (-) [tradition,invocation]

Un esprit invoqué ne peut se déplacer qu'au sein de son domaine.
Ce domaine s'étend au maximum à Puissance × 10 mètres de rayon de son lieu d'invocation.
Le domaine d'un esprit correspond à son type.

Un esprit lié à un maître n'est pas soumis à cette restriction.

===== Esprit lié à son invocateur (+) [tradition,invocation]

Un esprit invoqué n'est pas lié à son lieu d'invocation.
Il doit cependant rester aux alentours de son maître.
L'esprit ne peut s'éloigner de plus de Puissance × 10 mètres de celui qui l'a invoqué.

Un esprit lié à un magicien n'est pas soumis à cette restriction.

===== Invocation longue durée (+) [tradition,invocation]

Tous les services que doit un esprit invoqué expirent au lever ou au coucher de soleil, suivant ce qui arrive en dernier.

===== Offrandes (-) [tradition,invocation]

L'invocation d'un esprit nécessite des éléments difficilement trouvables en pratique.
Ces éléments ne sont pas forcément rares ou coûteux.
Cependant, l'invocateur doit réaliser ses invocations dans un lieu protégé et préparé à cette intention.

Par exemple, l'invocation d'un esprit particulier peut nécessiter un cercle d'invocation spécial, ou un élément matériel approprié à son type (un grand feu de cheminée, un bassin d'eau pure, les possessions d'un ancêtre, un cadavre frais, etc).
La qualité et/ou la quantité de l'offrande dépend en général de la puissance de l'esprit à invoquer.

