
[[chapter_magic]]
== Magie

[[drain]]
=== Actions magiques et Drain

Chaque test de compétence des groupes <<skill_group_sorcery,Sorcellerie>>, <<skill_group_conjuring,Conjuration>> et <<skill_group_enchanting,Enchantement>> est une action magique.

Chaque action magique est associé à une *Valeur de Drain (VD)*.
Ce Drain signifie à priori qu'immédiatement après chaque action magique qu'il entreprend, un magicien <<apply_damage,souffrira du nombre de cases de dégâts>> correspondants.
Contrairement aux dommages habituels, ces dégâts ne sont réduits ni par l'<<gear_armors,armure>>, ni par la <<attribute_body,Constitution>> du magicien.
La magie est incapable de soigner les dégâts dus au Drain.

Sauf mention contraire, les dégâts d'un Drain sont étourdissants.

Les actions magiques se résolvent soit par un <<simple_test,test simple>>, soit par un <<opposed_test,test opposé>>.
La procédure est cependant légèrement différente de d'habitude, en cela que le magicien n'est pas obligé d'utiliser tous ses *succès nets* pour améliorer sa marge de réussite.

Le magicien peut utiliser chacun des succès nets qu'il a obtenus lors de son test d'action magique d'une des manières suivantes :

* Réduire la VD de l'action magique de 1.
  Les dommages dus au Drain peuvent être totalement annulés de cette manière.
* Réduire le temps nécessaire pour accomplir l'action magique ...
** ... de 1 action si le temps se mesure en actions. +
   Le test ne peut pas prendre moins d'une action.
** ... de 1 minute si le temps se mesure en minutes. +
   Le test ne peut pas prendre moins d'une minute.
** ... de 1 heure si le temps se mesure en heures. +
   Le test ne peut pas prendre moins d'une heure.
* Améliorer sa marge de réussite.
  Cela modifie les effets de l'action magique comme habituellement.

[[magic_resistance]]
==== Résistance à la magie

Toute cible non consentante d'une action magique effectue un test de [.formula]#<<attribute_charisma,Charisme>> + <<magic_defense,Défense magique>>#.
Chaque succès réduit la marge de réussite de l'action magique la prenant pour cible de 1.
Ce test est automatique, et ne coûte aucune action à la cible.

Par défaut, on considère que toute cible est non consentante, y compris si elle est surprise ou inconsciente.

Les objets n'effectuent pas de test de résistance.
Le seuil de réussite pour les affecter dépend de leur complexité, comme indiqué dans la <<object_resistance,table ci-dessous>>.

.Résistance des objets
[[object_resistance]]
[options="header", cols="2,4e,^1"]
|===
|Type d'objet           |Exemples                                           |Seuil
|Naturel                |Arbre, sol, eau non-traitée                        |1
|Manufacturé, Low-tech  |Brique, cuir, meuble en bois                       |2
|Manufacturé, High-tech |Plastiques, équipement électronique                |3
|Hautement transformé   |Ordinateurs, drones, véhicules, produits chimiques |4^+^
|===



[[sorcery]]
=== Sorcellerie

[[spellcasting]]
==== Incantation

Pour lancer un sort, un magicien effectue un test [.formula]#<<attribute_intelligence,Intelligence>> + <<skill_spellcasting,Incantation>>#.

[[overcasting]]
Avant d'effectuer ce test, il peut choisir d'obtenir un ou plusieurs succès supplémentaires.
Chaque succès supplémentaire obtenu de la sorte augmente la <<drain,VD>> du sort incanté de 2.
Le magicien peut obtenir un nombre maximal de succès supplémentaires égal à sa <<attribute_magic,Magie>>.


[[magic_defense]]
==== Défense magique

Un magicien peut déployer une protection magique passive sur ses alliés.
Il dispose pour cela d'autant de dés de défense magique que son indice de compétence <<skill_counterspelling,Contresort>>.

Il peut répartir ses dés de défense magique entre un nombre maximum de personnages (lui y compris) égal à sa <<attribute_magic,Magie>>.
Chaque personnage peut bénéficier d'un nombre de dés de défense magique au maximum égal à la <<attribute_magic,Magie>> du magicien : dans ce cas, cela signifie que le magicien affecte tous ses dés à la défense magique d'une seule personne.

Il faut à un magicien une action complexe pour sélectionner les bénéficiaires de sa défense magique.
Une fois que c'est fait, cette protection dure jusqu'à ce que le magicien en change, qu'il tombe inconscient, ou qu'il subisse en une seule fois un nombre de cases de dégâts supérieur à son <<attribute_charisma,Charisme>>.

Toutefois, si un des personnages protégés quitte la ligne de vue du magicien, il n'est plus protégé.
Le magicien n'a pas besoin d'avoir constamment le personnage sous les yeux, mais il doit pouvoir le regarder s'il le faut.

La défense magique prodiguée par un magicien n'est efficace que contre les sorts.

Si un des personnages sous sa protection se fait attaquer par un sort, ce personnage peut bénéficier des dés de défense magique que le magicien lui a octroyés pour son test de résistance.
Ces dés supplémentaires ne sont disponibles que pour résister à ce sort en particulier.
Les dés de défense magique se reconstitue à chaque tour du magicien.

À noter que le <<adept_powers,pouvoir d'adepte>> *Défense magique* fonctionne contre toute action magique, plusieurs fois par tour si nécessaire.
Cependant, seul l'adepte qui le possède en bénéficie.

Les défenses magiques issues de plusieurs sources sont cumulatives.



[[counterspelling]]
==== Dissipation

Un magicien qui dispose d'une action peut essayer de dissiper un sort actif ou en cours de lancement.
Il peut entreprendre cela que le sort le prenne pour cible ou non.
Il effectue un test d'[.formula]#<<attribute_intelligence,Intelligence>> + <<skill_counterspelling,Contresort>>#.
Chaque succès réduit la marge de réussite du sort.

Dissiper un sort est une action magique dont la <<drain,Valeur de Drain>> est égale à [.formula]#<DV du sort> /2#.

Un sort dissipé en cours de lancement ne dispense pas le magicien qui l'incante de son Drain.



[[ritual_sorcery]]
==== Sorcellerie rituelle

Le leader d'une équipe rituelle lance un sort <<spellcasting,de la manière habituelle>>.
Cela lui prend cependant toujours [.formula]#12 - <<attribute_magic,Magie>># heures.
Il peut néanmoins bénéficier des modificateurs de <<teamwork_test,travail en équipe>>.

Tous les membres de l'équipe rituelle doivent utiliser leur compétence <<skill_rituals,Sorcellerie rituelle>> en lieu et place de leur compétence <<skill_spellcasting,Incantation>>.

Tous les membres de l'équipe rituelle (observateur inclus) souffrent des mêmes dommages dus au Drain.



[[spells]]
==== Grimoire

Cette section décrit les sorts les plus communs.
Ils peuvent être appris tels quels par tout personnage disposant du trait <<quality_sorcerer,Sorcier>>.
Ils peuvent aussi servir de base pour la <<spell_design,création de nouveaux sorts>>.



[[spell_traits]]
===== Traits

*Actif / Passif :* ::
Un sort de détection _Actif_ peut être <<test_opposed,opposé>> par sa cible de la <<magic_resistance,manière habituelle>>. +
À l'opposé, un sort de détection _Passif_ est simplement « ON » tant que le magicien le maintient.
Celui-ci peut avoir à effectuer des <<infiltration,tests de perception>> pour remarquer quelque chose de particulier.
Dans ce cas, si le sens supplémentaire est exotique / mystique, il utilisera sa compétence d'<<skill_spellcasting,Incantation>> au lieu de celle de <<skill_perception,Perception>>.

*Direct / Indirect :* ::
Un sort de combat _Direct_ est résisté par sa cible de la <<magic_resistance,manière habituelle>>. +
À l'opposé, un sort de combat _Indirect_ se lance de manière similaire à un projectile physique.
Il fonctionne donc comme une <<combat_distance,attaque à distance>> qui peut être esquivée grâce à un jet de [.formula]#<<attribute_agility,Agilité>> + <<skill_dodge,Esquive>>#.

*Zone :* ::
Un sorts de zone touche un nombre de cibles proches les unes des autres égales à l'attribut de [.formula]#magie# du lanceur.
On peut aussi considérer qu'il a un rayon d'action égal à [.formula]#magie# mètres.



[[spell_list]]
===== Liste des sorts

.Modificateurs de Drain
[options="header", cols=".^2,.^1,.^5,.^1"]
|===
|Sort               |Traits                       |Effet                      |Drain

4+|*_Combat_*
h|Éclair mana       |Direct                       |Dégâts 2                   |1
h|Poigne électrique |Indirect,Toucher,Électricité |Dégâts 4                   |1
h|Jet d'acide       |Indirect,Acide               |Dégâts 4                   |2
h|Boule de feu      |Indirect,Zone,Feu            |Dégâts 4                   |4
h|Couche de glace   |Zone |[.formula]#<<attribute_reaction,Réaction>> (Succès)# sous peine de tomber à terre |2

4+|*_Détection_*
h|Analyse Technique       |Actif,Directionnel           |1 Succès: <<test_modifiers,bonus>> de +1 pour utiliser l'appareil |1
h|Analyser la Vérité      |Actif,Directionnel           |Seuil: [.formula]#Signature# du <<social,mensonge>>          |1
h|Clairaudience           |Passif,Zone                  |Capteur sensoriel (vue uniquement)                           |1
h|Clairvoyance            |Passif,Directionnel          |Capteur sensoriel (ouïe uniquement)                          |1
h|Détecter des Ennemis    |Actif,Étendue                |Seuil: [.formula]#<<signature,Signature>># de la créature ennemie à portée |3
h|Détecter un Individu    |Actif,Zone                   |Seuil: [.formula]#<<signature,Signature>># de la cible                     |1
h|Lien Mental             |Passif                       |Lien mental avec [.formula]#<<attribute_magic,Magie>># personnes maximum |1
h|Sonde Mentale           |Actif,Directionnel           |Sonder l'esprit d'une créature                           |3
h|Sens du Combat          |Passif                       |1 Succès: Modificateur de +1 à l'<<skill_dodge,Esquive>> |1

4+|*_Santé_*
h|Antidote                                 |- |1 Succès: +1 à la <<attribute_body,Constitution>> pour résister à une toxine ou maladie identifiée |[.formula]#<<toxins,Indice>> -2#
h|Diminuer l'<<attribute_agility,Agilité>> |- |1 Succès: Modificateur de -1 à l'attribut                                                          |3
h|Résistance à la douleur                  |- |1 Succès: <<wound_modifier,Malus de blessure>> réduit de 1                                         |[.formula]#<<wound_modifier,Malus de blessure>>#
h|Soins                                    |- |1 Succès: -1 <<apply_damage,case de dégâts>> physiques                                             |[.formula]#<<apply_damage,Dégâts>> -2#
h|Stabilisation                            |- |Stabilise un personnage mourant                                                                    |[.formula]#<<damage_overflow,Surplus de Dégâts>>#

4+|*_Illusion_*
h|Apparition        |Multisensoriel,Zone |Illusions réalistes au sein de la zone                       |3
h|Camouflage        |Multisensoriel |1 Succès: Modificateur de +1 à la <<skill_sneaking,Discrétion>>   |1
h|Chaos             |-              |1 Succès: Modificateur de -1 à tous les tests                     |2
h|Distraction       |Multisensoriel |1 Succès: Modificateur de -1 à la <<skill_perception,Perception>> |1
h|Invisibilité      |-              |1 Succès: +2 à la [.formula]#<<signature,Signature>># visuelle    |2
h|Masque            |Multisensoriel |Changement d'apparence                                            |2
h|Monde Chaotique   |Zone           |1 Succès: Modificateur de -1 à tous les tests                     |4

4+|*_Manipulation_*
h|Barrière Mana         |- |Barrière de [.formula]#<<attribute_magic,Magie>># mètres dont la <<barriers_structure,Structure>> est égal aux [.formula]#Succès ×2# +
                           Seules les créatures vivantes sont affectées |1
h|Barrière Physique     |- |Barrière dont la <<barriers_structure,Structure>> est égal aux [.formula]#Succès ×2# |3
h|Doigts Télékinésiques |- |1 Succès: 1 d'<<attribute_agilité,Agilité>> et de <<attribute_reaction,Réaction>> effective +
                           Modificateur de -2 pour agir via ces « mains invisibles »                                                          |1
h|Contrôle des Actions  |- |Contrôler la « marionnette » prend une action                                                                      |2
h|Contrôle des Émotions |- |1 Succès: Modificateur de -1 à tous les tests contraires à l'émotion                                               |1
h|Contrôle des Pensées  |- |Donner un ordre prend une action                                                                                   |4
h|Poltergeist           |Zone |1 Succès: Dans la zone, modificateur de -1 aux actions visuelles et attaque à distance DV 1.   |2
h|Lévitation            |- |Seuil: 1 par 200 kilos de la cible. Déplacement de [.formula]#<<attribute_magic,Magie>> × Succès# mètres par round |3
|===



[[magic_tricks]]
===== Tours de magie

Un tour de magie permet de déclencher un effet magique mineur, bien inférieur aux possibilités habituelles d'un <<spells,sort>>.
En termes de puissance, un tour de magie reproduit l'effet d'un seul élément d'équipement standard, peu complexe, sans personnalisation ni option, d'une valeur maximale de 500¥ environ.
En termes de jeu, l'effet reproduit _ne peut entraîner aucun effet mécanique_ : un tour de magie ne peut occasionner aucun dommage direct, n'entraîner aucun jet de dés, ne modifier aucun indice, ne donner aucun modificateur, et ainsi de suite.
Un tour de magie souffre évidemment aussi de toutes les autres limitations d'un sort.

Apprendre un tour de magie coûte <<karma_costs,1 point de karma>>, et prend six heures.

Lancer un tour de magie ne requiert aucun test, et n'entraîne aucun Drain.
Un tour de magie peut généralement être maintenu de la même manière qu'un sort normal.

Voici quelques exemples de tours de magie usuels :

====== Combat
*Chasse Insectes :* Éloigne les petits insectes normaux dans un rayon de 50cm autour du lanceur. +
*Court circuit :* Crée une légère impulsion magnétique. Insuffisante pour endommager un équipement électronique, elle peut cependant surprendre quelqu'un ou griller un tag RFID. +
*Flamme :* Une flamme équivalente à celle d'un briquet apparait dans la main du lanceur. +
*Lumière :* Le lanceur crée un globe de lumière éclairant autant qu'une lampe torche. +
*Mouillage / Séchage :* La cible est mouillée ou séchée ; le volume d'eau maximal affecté est celui contenu dans un seau. +

====== Détection
*Boussole :* Le lanceur localise la direction du Nord magnétique. +
*Jumelles :* Le lanceur voit au loin comme s'il se servait de jumelles standard. +
*Éphéméride :* Le lanceur apprend la date, l'heure et la température exactes. +

====== Santé
*Coup de fouet :* Le lanceur est instantanément réveillé comme s'il avait avalé une tasse de café ou de boisson énergisante, mais n'en tire aucune plaisir particulier. +
*Nutrition :* Le lanceur est instantanément nourri comme s'il avait englouti une ration de voyage, mais n'en tire aucun plaisir particulier. +

====== Illusion
*Hologramme :* Le lanceur crée entre ses mains une représentation en volume de son choix. La représentation doit tenir dans un cube de [.formula]#<<attribute_magic,Magie>> ×10# centimètres de coté, et sa qualité est limitée par la compétence artistique et, le cas échéant, la mémoire du lanceur. +
*Ventriloquie :* Le lanceur produit un son ne dépassant pas les capacités d'un ventriloque. +

====== Manipulation
*Croissance :* Le lanceur fait pousser de manière accélérée une plante usuelle pour la région et d'une taille équivalente à celle d'une fleur ou d'une touffe d'herbe. +
*Doigts invisibles :* Le lanceur manipule par télékinésie un objet non attaché ni tenu dont le poids n'excède pas [.formula]#<<attribute_magic,Magie>> ×100# grammes, à une distance maximale de [.formula]#<<attribute_magic,Magie>># mètres. +
*Maquillage :* La cible est maquillée ou démaquillée dans un style au choix du lanceur. +
*Mode :* La coupe des vêtements de la cible est altérée. La qualité de la coupe est limitée par la compétence du lanceur. Ce sort ne peut cibler les armures, ou donner aux vêtement l'apparence d'une armure. +



[[spell_design]]
===== Création de sorts

Tous les sorts ont une <<drain,Valeur de Drain>> (VD) de base de 2.
Modifiez cette VD en fonction des traits du sort.

.Modificateurs de Drain
[width=50%, options="header", cols="2*"]
|===
|Trait           |VD
2+|*_Portée_*
|Toucher         |-1
|Champ de vision |±0
|Zone            |+2
|Étendue         |+3
2+|*_Cible_*
|Limitée         |-1
2+|*_Dommages_*
|Directs         |-1
|Élémentaires    |+1
2+|*_Complexité_*
|Simple          |±0
|Moyenne         |+1
|Élevée          |\+2^+^
|===

Une formule de sort un prix égal à [.formula]#DV ×2500¥#.
Elle est créée par un test d'[.formula]#<<attribute_intelligence,Intelligence>> + <<skill_arcana,Arcanes>>#.
Voir la procédure de <<cr,construction/réparation>> pour davantage de détails.





[[conjuring]]
=== Conjuration

[[summoning]]
==== Invocation

Pour invoquer un esprit, un magicien choisit tout d'abord le type et la puissance de l'esprit qu'il souhaite invoquer.
Il effectue ensuite un <<opposed_test,test opposé>> de [.formula]#<<attribute_charisma,Charisme>> + <<skill_summoning,Invocation>># contre la [.formula]#Puissance# de l'esprit.
Chaque succès net force l'esprit à rendre un service au magicien.

Invoquer un esprit est une action magique dont la <<drain,Valeur de Drain>> est égale au nombre de succès (_pas_ au nombre de succès nets) obtenus par l'esprit lors du <<opposed_test,test opposé>>, avec un minimum de 1.
Ce Drain est étourdissant si la Puissance de l'esprit est inférieure ou égale à la <<attribute_magic,Magie>> du personnage, et physique si elle est strictement supérieure.

Invoquer un esprit prend [.formula]#12 -<<attribute_magic,Magie>># rounds, avec un minimum de 1 round.

Un esprit invoqué doit rester dans un rayon de [.formula]#Puissance ×50# mètres de son lieu d'invocation.

Tous les services que doit un esprit invoqué expirent au lever ou au coucher de soleil, suivant ce qui arrive en premier.
Un esprit invoqué disparait en même temps que les services qu'il doit expirent.

[[banishing]]
==== Bannissement

Pour bannir un esprit, le personnage doit le percevoir d'une manière ou d'une autre.
Il effectue ensuite un <<opposed_test,test opposé>> de [.formula]#<<attribute_charisma,Charisme>> + <<skill_banishing,Banissement>># contre la [.formula]#Puissance# de l'esprit.
Le personnage subit un modificateur négatif à son test égal à la <<attribute_magic,Magie>> du magicien qui a invoqué l'esprit qu'il tente de bannir.
Chaque succès net permet de réduire de 1 le nombre de services que l'esprit doit à son maître.
Le service que l'esprit est actuellement en train d'exécuter est toujours annulé en dernier, le cas échéant.
Si tous les services dus par l'espritsont annulés de cette manière, l'esprit est banni.

Bannir un esprit est une action magique dont la <<drain,Valeur de Drain>> est égale au nombre de succès (_pas_ au nombre de succès nets) obtenus par l'esprit lors du <<opposed_test,test opposé>>, avec un minimum de 1.
Ce Drain est étourdissant si la Puissance de l'esprit est inférieure ou égale à la <<attribute_magic,Magie>> du personnage, et physique si elle est strictement supérieure.

Tenter de bannir un esprit prend 1 round.

Cependant, un esprit banni ne disparait qu'à la fin du tour suivant son banissement.
Un invocateur autre que son ancien maître peut cependant en profiter pour tenter de l'invoquer.
Dans ce cas précis, étant donné que l'esprit est déjà présent, le temps nécessaire à l'invocation est réduit à un round.

[[binding]]
==== Lien

Pour lier un esprit, un magicien doit l'avoir préalablement personnellement <<summoning,invoqué>>, et l'esprit doit lui devoir encore au moins 1 service.
Le magicien effectue un <<opposed_test,test opposé>> de [.formula]#<<attribute_charisma,Charisme>> + <<skill_binding,Lien>># contre la [.formula]#Puissance ×2# de l'esprit.
Chaque succès net force l'esprit à rendre un service au magicien.

Lier un esprit est une action magique dont la <<drain,Valeur de Drain>> est égale au nombre de succès (_pas_ au nombre de succès nets) obtenus par l'esprit lors du <<opposed_test,test opposé>>, avec un minimum de 1.
Ce Drain est étourdissant si la Puissance de l'esprit est inférieure ou égale à la <<attribute_magic,Magie>> du personnage, et physique si elle est strictement supérieure.

Toute tentative de lier un esprit prend [.formula]#12 -<<attribute_magic,Magie>> +Puissance# heures, avec un minimum de 1 heure.
Cela provoque l'expiration de tous les services non permanents que cet esprit doit à son maître.

Lier un esprit avec succès coûte un nombre de <<karma_costs,points de karma>> égal à sa [.formula]#Puissance#.

Contrairement à ceux obtenus lors d'une <<summoning,invocation>>, les services obtenus lors d'un Lien n'ont pas de date limite d'utilisation.
Un esprit lié doit cependant pouvoir rendre chaque service dans un rayon de [.formula]#Puissance ×50# mètres du lieu où la demande de service a été exprimée.

Un esprit lié ne disparait pas avec le lever ou le coucher du soleil.

Un esprit lié peut accomplir des services distants.



[[enchanting]]
=== Enchantement

*TODO*

[[traditions]]
=== Traditions

Traits pouvant être appliqués aux traditions.
Ces traits ne peuvent pas être appliqués à un personnage.

[[tradition_quality_domain_spirits]]
==== Esprit lié à son domaine (-) [tradition,invocation]

Un esprit invoqué ne peut se déplacer qu'au sein de son domaine.
Ce domaine s'étend au maximum à [.formula]#Puissance ×10# mètres de rayon de son lieu d'invocation.
Le domaine d'un esprit correspond à son type.

Un esprit lié à un maître n'est pas soumis à cette restriction.

[[tradition_quality_summoner_spirits]]
==== Esprit lié à son invocateur (+) [tradition,invocation]

Un esprit invoqué n'est pas lié à son lieu d'invocation.
Il doit cependant rester aux alentours de son maître.
L'esprit ne peut s'éloigner de plus de [.formula]#Puissance ×10# mètres de celui qui l'a invoqué.

Un esprit lié à un magicien n'est pas soumis à cette restriction.

[[tradition_quality_long_summoning]]
==== Invocation longue durée (+) [tradition,invocation]

Tous les services que doit un esprit invoqué expirent au lever ou au coucher de soleil, suivant ce qui arrive en dernier.

[[tradition_quality_offering]]
==== Offrandes (-) [tradition,invocation]

L'invocation d'un esprit nécessite des éléments difficilement trouvables en pratique.
Ces éléments ne sont pas forcément rares ou coûteux.
Cependant, l'invocateur doit réaliser ses invocations dans un lieu protégé et préparé à cette intention.

Par exemple, l'invocation d'un esprit particulier peut nécessiter un cercle d'invocation spécial, ou un élément matériel approprié à son type (un grand feu de cheminée, un bassin d'eau pure, les possessions d'un ancêtre, un cadavre frais, etc).
La qualité et/ou la quantité de l'offrande dépend en général de la puissance de l'esprit à invoquer.

==== Exemples de traditions

*Chamanisme :* ::
Le chamanisme est une tradition magique basée sur l'intuition, sur l'expression artistique et sur l'aptitude à ressentir le naturel et la beauté des flux magiques.
Chaque chaman est guidé dans son chemin dans le monde magique par un esprit tutélaire qui est son mentor : le totem, esprit libre très puissant qui permet à ceux qui suivent ses préceptes d'accéder à une partie de son pouvoir.
Les chamans se livrant à un acte magique peuvent revêtir le masque chamanique, prenant ainsi temporairement certains traits distinctifs de leur totem. +
Ils peuvent invoquer les esprits de l'Eau, de la Terre, de l'Air et de l'Homme.

+
*Traits :* <<tradition_quality_domain_spirits,Esprit lié à son domaine>>, <<tradition_quality_long_summoning,Invocation longue durée>>.

*Hermétisme :* ::
L'hermétisme est une tradition magique dont les fondements datent de la Renaissance, voire de l'Antiquité grecque.
C'est le reflet de la société scientifique moderne.
Pour les mages hérmétiques, la magie repose sur des théorèmes et des algorithmes qui ne laissent aucune place au hasard.
Ainsi, un mage hermétique est en constant apprentissage, essayant de rationnaliser, de quantifier la magie pour l'asservir à son contrôle.
Le mage a besoin de formules et d'ouvrages de refférence issus de bibliothèques hermétiques pour apprendre ses sorts, invoquer ou enchanter. +
Ils peuvent invoquer les élémentaires de Feu, d'Air, d'Eau et de Terre.

+
*Traits :*
<<tradition_quality_summoner_spirits,Esprit lié à son invocateur>>, <<tradition_quality_offering,Offrandes>>.
