[[chapter_matrix]]
=== Matrice

==== Icônes

Un _device_ désigne n'importe quel appareil technologique remplissant une ou plusieurs fonctions.
Appareils ménagers, armes, caméras, serrures, et ainsi de suite, sont tous des devices.
Chaque device a un propriétaire.
Le propriétaire d'un device connecté à la Matrice peut le commander à distance, sans avoir à faire de test,
hormis si l'action elle-même requiert un test (comme tirer avec une arme par exemple).
Un hacker peut lui aussi tenter de prendre le contrôle d'un device, sous <<matrix_devices,certaines conditions>>.

Un cyberdeck ou un commlink constituent un type particulier de device.
En effet, ils sont directement liés à un utilisateur qui les utilise pour se connecter à la Matrice.
L'icône du commlink ou du deck fusionne alors avec la représentation maricielle de son utilisateur, appelée le _persona_.
L'icône persona se déplace dans la matrice au fur et à mesure des envies (et des compétences) de son utilisateur.
Cependant, quels que soient les lieux matriciels qu'il visite, un persona est toujours relié à l'endroit physique
d'où son utilisateur se connecte (voir la section <<icon_track,tracer une icône>>).

Tandis que les devices permettent d'accomplir des actions, les _fichiers_ renferment des informations.
Tout fichier existe forcément sur exactement un espace de stockage lié à un device.
Le propriétaire d'un fichier est toujours celui du device sur lequel le fichier existe.
Consultez la section <<matrix_files,fichiers>> pour savoir ce qu'il est possible de faire avec un fichier, et comment.

Bien que certains devices soient connectées de manières indépendante à la matrice (_standalone_), cela reste relativement rare.
La plupart du temps, les devices sont mis en _réseau_.
Dans ce cas, un de ces device devient le _serveur_ (il s'agit toujours d'un ordinateur: un commlink, un deck ou une machine plus puissante),
et les autres devices qui lui sont reliés deviennent ses _esclaves_.
Un réseau particulier ne peut avoir qu'un seul serveur en même temps. +
Il existe différents types d'infrastructures réseau :

* Un _PAN_ (Personal Area Network) assujettit un certain nombre de devices à un commlink ou à un cyberdeck particulier.
  Le cyberdeck ou le commlink fait office de serveur pour tous les autres devices du PAN, qui deviennent ses esclaves.
  Les devices esclaves appartiennent la plupart du temps au propriétaire du commlink ou du cyberdeck ;
  cependant, il peut aussi s'agir de devices appartenant à quelqu'un d'autre qui lui fait confiance. +
  Un cyberdeck ou un commlink peuvent avoir au même moment un nombre maximum d'esclaves égal à deux fois leur Indice.
* Un _WAN_ (Wide Area Network) assujettit un grand nombre de devices esclaves à un ordinateur maître qui sert de serveur.
  Il est différent d'un PAN en cela que, bien que le serveur ait toujours un propriétaire,
  ça n'est ni un commlink ni un cyberdeck : un WAN n'est donc pas lié à un persona.
  De plus, le serveur d'un WAN offrant une grande puissance de calcul,
  le nombre de devices qu'il peut accepter en tant qu'esclaves n'est pas limité.
  Enfin, le serveur d'un WAN donné peut lui même être assujetti à un serveur de plus haut niveau ;
  cela permet d'imbriquer des WANs en d'autre WANs plus vastes, afin de faciliter l'organisation des devices.
  Cela augmente aussi le niveau de sécurité : en effet, si un serveur de bas niveau tombe aux mains d'un hacker,
  seuls les devices dont ce serveur a la charge sont compromis, et pas les autres.
* Un _host_ est un WAN qui jouit d'une certaine isolation du reste de la Matrice.
  Un host peut aussi être protégé par des programmes de défense indépendant appelées _CI_.
  Consultez la section <<matrix_host,Hosts>> pour davantage de détails.

[[matrix_defense]]
==== Défense matricielle

Lorsqu'un hacker effectue une action illégale contre une autre icône, son test est opposé par la _Défense matricielle_ du défenseur.

* Un _persona_ utilise son [.test.opposed]#<<attribute_intelligence,Intelligence>> + <<device_rating,Indice>># de son cyberdeck ou de son commlink.
* Un _fichier_ utilise l'[.test.opposed]#<<device_rating,Indice>># du device sur lequel il est stocké.
* Un _device_ utilise soit son propre [.test.simple]#<<device_rating,Indice>># s'il est _standalone_,
  soit l'[.test.opposed]#<<device_rating,Indice>># de son serveur s'il fait partie d'un PAN ou d'un WAN, et que cet indice est supérieur.
  Le device ne peut toujours utiliser que son propre indice ou l'indice de son serveur direct ;
  si son serveur est lui-même l'esclave d'un autre serveur, le device ne peut bénéficier de la protection de cet autre serveur.
* Un _serveur_ utilise soit son propre [.test.opposed]#<<device_rating,Indice>>#,
  soit l'[.test.opposed]#<<device_rating,Indice>># de son serveur maître s'il fait partie d'un WAN de plus haut niveau.
* Un _host_ utilise son propre [.test.opposed]#<<device_rating,Indice>>#.
* Une _CI_ utilise son propre [.test.opposed]#<<device_rating,Indice>># (qui est égal à celui de son host).
* Une _databombe_ utilise son propre [.test.opposed]#<<device_rating,Indice>>#.

[[matrix_files]]
==== Fichiers

Le propriétaire d'un device peut créer, lire, modifier ou supprimer n'importe quel fichier sur ce device particulier.
Il peut aussi copier un de ses fichiers vers un autre device ; cet autre device doit lui appartenir.
Dans le cas contraire le propriétaire de cet autre device doit l'y autoriser.

Copier illégalement un fichier depuis ou vers son cyberdeck se résoud de la même manière que le supprimer.
Copier illégalement un fichier depuis son cyberdeck se résoud de la même manière que le créer.
Dans les deux cas, il s'agit d'une action d'<<matrix_edit_file,édition de fichier>>.

[[matrix_edit_file]]
===== Éditer un fichier

Éditer un fichier désigne le fait de le créer, le modifier ou le supprimer.

Le propriétaire d'un fichier peut l'éditer sans aucun test.

Si le personnage n'est pas le propriétaire du fichier à éditer, il s'agit d'une action illégale.
Le personnage effectue alors un test opposé d'[.test.opposed]#<<attribute_intelligence,Intelligence>> + <<skill_electronic_warfare,Guerre électronique>># contre la [.test.opposed]#<<matrix_defense,Défense>># du fichier#.
Chaque succès permet d'apporter une modification au fichier.

Il est impossible d'éditer un fichier <<file_encrypt,chiffré>> dont on ne possède pas la clé.
Au préalable, il est nécessaire de le <<file_decrypt,décrypter>>.

Éditer un fichier protégé par une <<databomb_disarm,databombe non désarmée>> déclenche celle-ci.

===== Chiffrement

[[file_encrypt]]
====== Chiffrer un fichier

Certains fichiers peuvent être protégés par un chiffrement.
Chiffrer un fichier nécessite un test d'[.test.simple]#<<attribute_intelligence,Intelligence>> + <<skill_computer,Analyse>>#.
Les succès nets deviennent la _Signature_ du chiffrement du fichier.

Chiffrer un fichier crée un autre fichier, appelé _clé_ de chiffrement.
Cette clé peut être un mot de passe, ou le fait d'exécuter une action matricielle précise.
Seul le propriétaire de la bonne clé peut déchiffrer le fichier concerné.

Un hacker qui ne possède pas la clé de chiffrement d'un fichier peut néanmoins tenter de <<file_decrypt,décrypter>> celui-ci.

[[file_decrypt]]
====== Décrypter un fichier

La plupart de fichiers de valeur sont chiffrées par leur propriétaire :
il est impossible d'y accéder sans connaître la clé qui servira à le déchiffrer.

Un personnage qui ne connaît pas la clé peut néanmoins tenter de briser la protection et décrypter l'information.
Décrypter un fichier nécessite un test d'[.test.simple]#<<attribute_intelligence,Intelligence>> + <<skill_computer,Analyse>># dont le seuil est égal à la Signature du chiffrement.

Il s'agit d'une action illégale.

===== Databombs

[[databomb_create]]
====== Créer une databombe

Certains fichiers peuvent être protégés par une databombe.
Une databombe est un type de fichier particulier, qui est toujours lié à un ou plusieurs autres fichiers.
Créer une databombe requiert un test simple d'[.test.simple]#<<attribute_intelligence,Intelligence>> + <<skill_software,Programmation>>#.
Les succès nets deviennent l'Indice de la databombe.
Le nombre maximum de fichiers auquel une databombe peut être liée est égal à son Indice.
La _Signature_ d'une databombe est égale à son Indice.

Lorsqu'elle est créée, une databombe est liée à certains paramètres :

* un mode de déclenchement : une databombe peut exploser après qu'un certain temps se soit écoulé,
  ou lorsqu'une ou plusieurs actions prédéterminées sont réalisées sur une ou plusieurs icônes particulières.
  L'icône visée est le plus souvent le fichier que protège la databombe, mais pas forcément.
* un type d'explosion : une databombe qui explose accomplit un nombre maximum d'actions prédéterminées.
  Outre détruire le ou les fichiers auquels elle est liée,
  une databombe peut accomplir n'importe quelle action que son créateur est capable d'accomplir,
  comme si celui-ci l'exécutait lui-même, qu'il soit actuellement connecté à la matrice ou non.
  Si une action particulière requiert un test, la databombe lance un nombre de dés égal à son Indice,
  ou au nombre de dés qu'utiliserait son créateur, si celui-ci est plus faible. +
  Le nombre maximum d'effets différents que peut avoir l'explosion d'une databombe est égal à son Indice.
* un mode de désactivation : une databombe peut être désactivée après qu'un certain temps se soit écoulé,
  ou lorsqu'une ou plusieurs actions prédéterminées sont réalisées sur une ou plusieurs icônes particulières.
  Une databombe peut évidemment n'avoir aucun mode de désactivation.

Rien n'interdit de lier une databombe à un fichier préalablement chiffré.

Si un hacker ne peut pas désactiver une databombe, il peut tenter de la <<databomb_disarm,désarmer>>.

[[databomb_disarm]]
====== Désarmer une databombe

Désamorçer une databombe requiert un test opposé d'[.test.opposed]#<<attribute_intelligence,Intelligence>> + <<skill_software,Programmation>># contre l'[.test.opposed]#<<matrix_defense,Indice>># de la databombe.
Un échec déclenche la databombe.

Il s'agit d'une action illégale.



[[matrix_perception]]
==== Percevoir la matrice

===== Voir une icône

N'importe qui peut percevoir une icône qui est connectée au même réseau.
La seule exception est si cette icône <<matrix_silent_mode,navigue incognito>>.

[[icon_track]]
===== Tracer une icone

Une fois que le personnage "voit" une icône, il peut tenter de remonter sa trace jusqu'au lieu physique auquel elle s'est connectée.
Il effectue pour cela un test d'[.test.simple]#<<attribute_intelligence,Intelligence>> + <<skill_computer,Analyse>>#,
avec un seuil égal au nombre de grilles supplémentaires successives auquel l'icône est connectée.

[[icon_snoop]]
===== Espionner une icône

Une fois que le personnage "voit" une icône, il peut tenter d'intercepter ses communications.
Il effectue pour cela un test d'<<attribute_intelligence,Intelligence>> + <<skill_electronic_warfare,Guerre électronique>>.
Une réussite signifie que le personnage peut consulter les communications de sa cible en temps réel.
Cela ne nécessite aucun test supplémentaire, tant qu'il garde la communication ouverte, ce qui lui impose un malus de -1 dé à toutes ses actions matricielles par fichier de communication gardé ouvert.

Alternativement, il peut choisir d'éditer cette communication.
Cela se résoud comme n'importe quelle <<matrix_edit_file,édition de fichier>>.

Il s'agit d'une action illégale.

[[matrix_silent_mode]]
===== Navigation incognito

Une icone peut décider d'entrer en mode incognito.
Elle devient ainsi moins détectable par les autres icones.

On effectue un test d'<<attribute_intelligence,Intelligence>> + <<skill_electronic_warfare,Guerre électronique>>. Le résultat devient la signature de l'icone.

Il s'agit d'une action illégale.

[[matrix_search]]
===== Rechercher une information

Chercher une information particulière sur la matrice se fait de la manière suivante :
. d'abord, le personnage choisit un réseau sur lequel il va effectuer sa recherche ;
. puis, il effectue un test étendu d'<<attribute_intelligence,Intelligence>> + <<skill_computer,Analyse>>, avec un seuil égal à la signature de l'information recherchée.

En cas de succès, le personnage trouve l'information recherchée.
Pour trouver l'information qu'il recherche, un personnage doit évidemment chercher au bon endroit.
Une recherche effectuée sur un réseau qui ne contient pas l'information n'a aucune chance d'aboutir !

La table suivante donne des exemples de signature suivant la nature de l'information recherchée.

[[signature_matrix_search]]
.Recherche matricielle
[width=40%, options="header", cols="1,^1"]
|===
|L'information est ...                          |Signature
|D'ordre général et publique                    | 1
|D'un intérêt limité ou indirectement accessible| 2
|Obscure ou ancienne                            | 6
|Activement dissimulée                          |10
|===

[[check_overwatch_score]]
===== Connaître son OS

Connaître la valeur de son score d'Overwatch se fait
par un test opposé si le personnage est connecté à un hôte,
et par un test simple sinon.

Un seul succès net permet de connaître son score actuel.

Cependant, l'action de se renseigner sur son score d'Overwatch
constitue en elle-même un acte illégal, et peut donc faire
augmenter ledit score encore plus haut, en particulier si le
personnage est actuellement dans un hôte !

[[matrix_take_control]]
===== Prendre le contrôle

TODO

* jump into rigged device
* control device
* spoof command
* refoot/format device

