[[chapter_principles]]
== Principes de jeu

[[simple_test]]
=== Test simple

. Le personnage lance une *réserve de dés* à 6 faces égale à [.formula]#<<<primary_attributes,attribut>>> + <<<chapter_skills,compétence>>>#.
  Chaque dé dont le score est de 5 ou 6 représente un *succès*.
. Pour déterminer si l'action est une réussite ou un échec, on compare les succès obtenus avec un *seuil de difficulté* fixé par le MJ et représentant la difficulté inhérente à la tâche entreprise.
  Par défaut, ce seuil de difficulté est égal à 1 et est sous-entendu.
  S'il est supérieur, le test est formulé comme ceci : [.formula]#<<<primary_attributes,attribut>>> + <<<chapter_skills,compétence>>> (<seuil de difficulté>)#.
. Pour estimer la qualité du résultat de l'action, on calcule les *succès nets* (aussi appelé *degré de réussite*) en faisant la différence entre le nombre de succès obtenus et le seuil.

[[thresholds]]
.Seuils de difficulté
[width=35%, options="header"]
|===
|Seuil |Difficulté

|1     |Facile
|2     |Moyenne
|3     |Complexe
|4^+^  |Difficile
|===

.Degrés de réussite
[width=35%, options="header"]
|===
|Succès nets |Réussite

|< 0   |Échec
|0     |Grossière
|1     |Normale
|2     |Bonne
|3^+^  |Excellente
|===

[[opposed_test]]
=== Test opposé

On procède comme à l'étape précédente : chaque opposant calcule et lance sa propre réserve de dés.
Celui qui obtient le plus de succès gagne la confrontation.

On retranche le nombre de succès du perdant au nombre de succès du gagnant pour calculer le nombre de *succès nets* de ce dernier.

[[extended_test]]
=== Test étendu

Certaines actions prennent beaucoup de temps.
Dans ce cas, un personnage effectue plusieurs jets d'[.formula]#<<<primary_attributes,attribut>>> + <<<chapter_skills,compétence>>> (<seuil>,<intervalle>)#.
Le personnage continue d'effectuer ses tests jusqu'à cumuler un nombre de succès nets supérieur au [.formula]#seuil# indiqué.
Effectuer chaque test prend une durée égale à l'[.formula]#intervalle# indiqué.

[[teamwork_test]]
=== Travail en équipe

Chaque personnage qui aide le personnage principal fournit à ce dernier un <<test_modifiers,modificateur>> cumulatif égal à son [.formula]#indice de compétence /2#.
Un personnage ne peut pas contribuer à un groupe d'une taille supérieure à son indice de compétence (lui-même inclus).

[[attribute_test]]
=== Test d'attribut

Il peut arriver qu'il n'y ait aucune <<chapter_skills,compétence>> qui reflète la nature de l'action entreprise.
L'action se résoud dans ce cas avec un test d'attribut.
La réserve de dés à utiliser est alors égale à la *somme de deux attributs*.
On lance [.formula]#<<<primary_attributes,attribut>>> + <<<primary_attributes,attribut>>># au lieu de [.formula]#<<<primary_attributes,attribut>>> + <<<chapter_skills,compétence>>>#.

[NOTE.example,caption="Exemple"]
====
Par exemple, un personnage peut tenter rédiger les paroles d'une nouvelle chanson ou les dialogues d'un nouveau film ([.formula]#<<attribute_intelligence,Intelligence>> + <<attribute_charisma,Charisme>>#), de jouer une partie de « tape-taupes » ([.formula]#<<attribute_agility,Agilité>> + <<attribute_reaction,Réaction>>#), ...
====

Il est possible d'utiliser *deux fois le même attribut*.
La réserve de dés sera à lancer est alors [.formula]#<<<primary_attributes,attribut>>> ×2#.
[NOTE.example,caption="Exemple"]
====
Par exemple, le personnage peut essayer de se rappeler un détail d'une situation qu'il a vécu (via un test de mémoire utilisant son [.formula]#<<attribute_intelligence,Intelligence>> ×2#), ou de rattraper un objet in extremis (en utilisant sa [.formula]#<<attribute_reaction,Réaction>> ×2#) ...
====

Le fait de résoudre une action grâce à un test d'attribut est destinée aux situations ponctuelles, où de peu d'importance pour le jeu.
Si ce cas de figure arrive régulièrement, il peut être justifié pour le MJ de <<create_new_skills,créer une nouvelle compétence active>>.


[[test_modifiers]]
=== Modificateurs

Chaque test peut se voir assorti de différents modificateurs reflétant les circonstances particulières dans lesquelles ce test se déroule (luminosité, distance, <<tools,outils>>, blessures, ...).
Quelle qu'en soit la source, un modificateur s'ajoute ou se retranche à la réserve de dés.
Si différents modificateurs s'appliquent à un test donné, il suffit d'en faire la somme avant de l'appliquer à la réserve de dés du personnage.
Cependant, la somme totale des modificateurs ne peut jamais dépasser ±0.
En d'autres termes, la taille de la réserve de dés à lancer après application des modificateurs ne peut jamais dépasser sa taille _avant_ application des modificateurs.

Ces modificateurs sont détaillés à travers les différents chapitres de ce livre.
Si une situation n'est pas couverte directement par une règle, ou que le MJ n'a pas envie de se compliquer la vie, il peut utiliser la table suivante, qui montre les modificateurs les plus courants.

.Modificateurs
[width=35%, options="header"]
|===
|Conditions             |Modificateur total

|Standards              | ±0
|Grandement facilitées  | +2
|Assez gênantes         |-1 à -3
|Franchement difficiles |-4 à -7
|Quasi-impossibles      |-8 à -10
|===

Si les modificateurs négatifs sont si importants qu'ils font passer la réserve de dés d'un personnage à 0 ou moins, la tâche entreprise semble impossible.
En conséquence, l'action échoue donc automatiquement.
Dans de telles circonstances, seul un personnage doté d'<<attribute_edge,Edge>> peut obtenir un dernier recours.


ifdef::with-designer-notes[]
displayer::design[label="Afficher"]
[.design]
****
Allez, ça vaut le coup de le répéter encore une fois :
[quote]
____
Cependant, la somme totale des modificateurs ne peut jamais dépasser ±0.
En d'autres termes, la taille de la réserve de dés à lancer après application des modificateurs ne peut jamais dépasser sa taille _avant_ application des modificateurs.
____
Ce passage est absolument fondamental à SR54.
À lui seul, il stoppe quasiment l'inflation des réserves de dés.
C'était un de mes <<objectives,objectifs>> primordiaux : c'est une chose de lancer plusieurs D6, ça fait partie du jeu.
Perdre cette base du système (genre lancer d'autres types de dés, passer à des jets de pourcentage, etc) aurait fait perdre, à mon sens, l'impression de jouer au même jeu.

Quand un runner est très très doué, il lance environ 12 ou 15 dés.
C'est déjà beaucoup (et, avec ces règles, ça représente déjà un certain investissement en karma).
Lancer 20 ou 30 dés pour la moindre action alors qu'on n'y est même pas spécialisé, c'est _trop_.
Les dés, ça coûte de l'argent.
Mais surtout, ça coûte le temps de réunir les dés, de compter qu'on en a le nombre exact, de les ramasser sous la table quand ils roulent partout, et de compter ses succès.
Plusieurs fois par passe d'initiative.
Tout ça ralentit l'action.
Or, accélerer l'action était un autre de mes <<objectives,objectifs>> prioritaires.
Permettons à l'action d'être aussi rapide, nerveuse et immersive qu'un monde cyberpunk est censé l'être.

Ensuite, je sais pas vous, mais je trouve ridicule qu'un perso avec 3 dans son attribut, et 1 dans sa compétence lance 15 dés, sous prétexte qu'il dispose d'un excellent matériel.
En gros, le syndrome du _script-kiddie_ dans le milieu de la Matrice.
Avec mes règles, un tel personnage lancera 4 dés, même avec le meilleur matos et dans les conditions les plus favorables du monde.
Les héros du jeu sont les runners, les PJs, _pas_ leur matos à whatmille nuyens.
Refaire des attributs et des compétences les stars du système était encore un de mes <<objectives,objectifs>>.

Enfin, un petit retour sur le modificateur de +2 pour « conditions grandement facilitées ».
Je l'ai mis par acquis de conscience, mais perso, dans ces conditions, je ne fais même pas lancer les dés : on n'a pas de temps à perdre avec des banalités !

****
endif::with-designer-notes[]


[[option_buy_successes]]
[NOTE.option,caption="Règle optionnelle"]
====
*Achat de succès*

*Règle :* Un personnage peut obtenir un succès automatique en ôtant 4 dés de sa réserve.
Sa réserve doit évidemment compter au moins 4 dés après application des modificateurs.
Il peut choisir de lancer ou pas les dés restants ; le nombre de succès obtenus en lançant ces dés restants s'ajoute à ses succès automatiques.

*Motivation :* Cette règle vise à accélérer le jeu, en réduisant le nombre de dés à lancer, et par la même le temps nécessaire pour rassembler les dés et comptabiliser les succès.
Elle offre aussi au MJ un moyen de soulager le nombre de choses qu'il a à faire durant une partie, en particulier au cours d'un combat.

Le MJ peut aussi décider de forcer les joueurs dont la réserve dépasse (par exemple) 12 dés à acheter des succès automatiques pour tous leurs dés excédentaires.
Cette règle a alors pour effet supplémentaire de rendre la puissance des personnages non exactement linéaire : au delà de 12 dés, un personnage n'a plus une moyenne d'un succès pour 3 dés lancés, mais d'un pour 4 ...
Elle peut donc être un moyen de limiter la puissance des personnages dotés de grosses réserves de dés.
====



[[option_limits]]
[NOTE.option,caption="Règle optionnelle"]
====
*Limites*

*Règle :* Le nombre de succès nets que peut obtenir un personnage sur un jet de dés est égal à l'indice de la compétence utilisée.
Ce nombre de succès nets maximal est appelé *Limite*.

Si le jet utilise deux attributs plutôt qu'un attribut et une compétence, la Limite est égale au plus faible des deux attributs.

*Motivation :* Cette règle vise à ... heu ... 
Faire comme SR5 ? Gâcher la joie d'un coup de chance sur un jet de dé ?
Avec la disparition des limites liées à l'équipement, elle permet peut-être de valoriser les compétences par rapport aux attributs.
À vous de voir.
====

