
[[chapter_qualities]]
=== Traits

Les traits sont un outil pour personnaliser un personnage, d'améliorer ses capacités ou de lui permettre d'en acquérir de nouvelles.

Sauf mention contraire, chaque trait ne peut être acquis qu'une seule fois par un même personnage.

Certains traits, appelés avantages, ont un impact positif sur le personnage.
Ils sont marqués d'un *(+)* dans leur description.
Ils coûtent un nombre de points de karma égal à leur valeur, indiquée entre parenthèses dans leur description.

D'autres traits, appelés défauts, ont un impact négatif sur le personnage.
Ils sont marqués d'un *(-)* dans leur description.
En compensation, les défauts rapportent en général un nombre de points de karma supplémentaires égal à leur valeur, indiquée entre parenthèses dans leur description.
Le MJ est cependant libre d'affecter un défaut à un personnage sans aucune compensation, pour refléter une complication particulière affectant le personnage en cours de partie.

Certains traits possèdent des prérequis qu'un personnage doit satisfaire avant de pouvoir les acquérir.
Satisfaire les prérequis d'un avantage ne dispense pas de payer le coût en points de karma associé à cet avantage.

Chaque trait acquis par un personnage devrait toujours l'être dans un contexte de jeu approprié et justifié par son background et/ou son développement de personnage.



[[quality_exceptional_attribute]]
==== Attribut exceptionnel (+)(20) ou Attribut affaibli (-)(20)

Lorsqu'un personnage achète ce trait, il doit le lier à un attribut primaire.
Il s'agit d'un avantage si l'attribut lié est exceptionnel, et d'un défaut s'il est affaibli.

* Un personnage ayant un attribut exceptionnel a une valeur supérieure de 1 par rapport au karma investi pour faire progresser cet attribut.
  Le maximum non augmenté d'un attribut primaire exceptionnel augmente de 1, jusqu'à un maximum de 6.
  Le maximum augmenté d'un attribut primaire exeptionnel augmente de 1, jusqu'à un maximum de 9.

* Un personnage ayant un attribut affaibli a une valeur inférieure à 1 par rapport au karma investi pour faire progresser cet attribut.
  Le minimum d'un attribut affaibli reste cependant de 1. À la création, un personnage devra donc au minimum payer un coût équivalent à une valeur de 2 pour un attribut standard, mais n'obtenant qu'une valeur de 1 pour son attribut affaibli.
  Le maximum non augmenté d'un attribut primaire affaibli est réduit de 1.
  Le maximum augmenté d'un attribut primaire affaibli est réduit de 1.

Ce trait peut être acquis plusieurs fois.
Il affecte cependant un attribut primaire différent à chaque fois.

[NOTE.example,caption="Exemple"]
====
* Elfie McElfson possède une agilité exceptionnelle.
  À la création de personnage, la joueuse d'Elfie dépense 25 points de karma pour faire progresser son agilité. Cela fait passer l'agilité d'Elfie à 4 au lieu de 3, car c'est son attribut exceptionnel.
* Beaucoup plus tard, la joueuse d'Elfie décide d'augmenter son agilité de 4 à 6.
  Cela lui coûte 45 points de karma (le coût pour faire progresser un attribut de 3 à 5) au lieu de 55 (le coût standard pour faire progresser un attribut de 4 à 6).
  Faire progresser son agilité à 6 lui aura coûté 70 points de karma au total au lieu de 100.
  Il ne lui est cependant plus possible de faire progresser son agilité au delà de 6.
====

[NOTE.example,caption="Exemple"]
====
* À sa création, la joueuse de Trolley McTrollson doit investir au minimum 2×10 points de karma pour obtenir son intelligence ainsi que son charisme à leur valeur minimum de 1.
  Par la suite, elle décide de faire progresser son intelligence à 3 et son charisme à 2, cela lui coûtera 50 points de karma de plus, pour un total de 70 points de karma (au lieu de 35 pour acheter ces valeurs dans deux attributs standard).
* Les maximums non augmentés de l'intelligence et du charisme de Trolley sont de 5 au lieu de 6.
  Les maximums augmentés de ces deux caractéristiques sont de 8.
====

[NOTE.option,caption="Règle optionnelle"]
====
Avec cet règle, un attribut exceptionnel ou affaibli n'intervient plus dans les règles de création ou de progression d'un personnage.
À la place, un attribut exceptionnel ou affaibli devient un modificateur appliqué à tout test où intervient cet attribut.

* Un attribut exceptionnel devient un modificateur de +1
* Un attribut affaibli devient un modificateur de -1

La règle de base complique quelque peu la création et la progression d'un personnage membre d'une race ayant un ou plusieurs attributs exceptionnels ou affaiblis, mais est transparente en cours de partie.
Cette règle optionnelle est plus simple à appréhender, mais il faut penser à appliquer le modificateur en cours de partie à _chaque_ test concerné, ce qui peut ralentir le jeu ...
====



[[quality_adept]]
==== Adepte (+)(10)
*Prérequis:* <<attribute_essence,Essence>>.

Le personnage est un adepte.
Ses <<chapter_augmentation,augmentations>> ne sont pas d'origine technologique, mais magique.
Sa nature différente offre au personnage les bénéfices suivants :
* Il peut s'augmenter gratuitement et sans délai, du moment qu'il lui reste suffisament d'<<attribute_essence,Essence>> disponible.
* Il peut bien sûr choisir de se procurer et de se faire greffer des <<gear_cyberware,implants>> de la manière habituelle,
  afin par exemple d'obtenir des capacités offertes uniquement par le cyberware,
  ou de bénéficier des <<gear_cyberware_grades,grades de cyberware>>.
* Il bénéficie de l'avantage <<quality_cyberware,'Ware discret>>, dans sa version à 20 points.
  Cependant, si le personnage possède des implants, ceux-ci ne sont pas couverts par le trait.
* Il a accès aux <<adept_powers,pouvoirs d'adeptes>>.



[[quality_special_attribute]]
==== Attribut spécial (+)(5)

Le personnage acquiert un nouvel <<special_attributes,attribut spécial>>.
Il ne doit pas déjà posséder l'attribut choisi.
Si votre personnage possède déjà deux attributs spéciaux, il doit en abandonner un.

Le nouvel attribut spécial a une valeur de base de 1.
Cette valeur peut <<chapter_karma,progresser>> par la suite grâce au karma.



[[quality_big_spender]]
==== Dépensier (-)(10)

Volontairement ou non, le personnage doit dépenser chaque mois bien davantage que la normale.
Les dépenses dues à son niveau de vie sont doublées.



[[quality_toughness]]
==== Dur-à-cuire (+)(20)

Le personnage est plus robuste et ignore les dommages plus facilement. Sa <<attribute_body,Constitution>> est augmentée de 1.



[[quality_enchanter]]
==== Enchanteur (+)(10)
*Prérequis:* <<attribute_magic,Magie>> 1.

Le personnage est capable d'user des compétences du groupe <<skill_group_enchanting,Enchantement>> :
<<skill_alchemy,Alchimie>>, <<skill_artificing,Artefacts>> et <<skill_disenchanting,Disjonction>>.
Cet avantage n'offre aucun rang dans aucune de ces compétences.
Celles-ci doivent être acquises et progresser normalement grâce au karma.



[[quality_pathogens_toxins_resistance]]
==== Immunorésistant (+)(5) ou Immunodéficient (-)(5)

La sensibilité du personnage aux toxines ou aux maladies est modifiée.
Immunorésistant est un avantage, Immunodéficient un défaut.

* Un personnage immunorésistant gagne un modificateur de +1 pour résister soit aux toxines, soit aux pathogènes.
* Un personnage immunodéficient souffre d'un modificateur de -1 pour résister soit aux toxines, soit aux pathogènes.

Ce trait peut être choisi plusieurs fois.
Le personnage doit préciser à chaque fois si le modificateur s'applique contre les toxines ou contre pathogènes.



[[quality_conjurer]]
==== Invocateur (+)(10)
*Prérequis:* <<attribute_magic,Magie>> 1.

Le personnage est capable d'user des compétences du groupe <<skill_group_conjuring,Conjuration>> :
<<skill_banishing,Bannissement>>, <<skill_summoning,Invocation>> et <<skill_binding,Lien>>.
Cet avantage n'offre aucun rang dans aucune de ces compétences.
Celles-ci doivent être acquises et progresser normalement grâce au karma.



[[quality_slow]]
==== Lent (-)(10)

Lorsqu'il se déplace à pied, le personnage est incapable de distancer ou de rattraper qui ou quoi que ce soit dont l'allure n'est pas ralentie ou qui n'a pas aussi ce défaut.



[[quality_astral_projection]]
==== Projection astrale (+)(10)
*Prérequis:* <<attribute_magic,Magie>> 1, <<quality_vision_astral,Vision astrale>>.

Le personnage est capable de se projeter sur le plan astral.



[[quality_sorcerer]]
==== Sorcier (+)(10)
*Prérequis:* <<attribute_magic,Magie>> 1.

Le personnage est capable d'user des compétences du groupe <<skill_group_sorcery,Sorcellerie>> :
<<skill_counterspelling,Contresort>>, <<skill_spellcasting,Incantation>> et <<skill_rituals,Sorcellerie rituelle>>.
Cet avantage n'offre aucun rang dans aucune de ces compétences.
Celles-ci doivent être acquises et progresser normalement grâce au karma.



[[quality_technomancer]]
==== Technomancien (+)(5)
*Prérequis:* <<attribute_resonance,Résonance>> 1.

Le personnage est capable d'user des compétences du groupe <<skill_group_tasking,Technomancie>> :
<<skill_compiling,Compilation>>, <<skill_decompiling,Décompilation>> et <<skill_registering,Enregistrement>>.
Cet avantage n'offre aucun rang dans aucune de ces compétences.
Celles-ci doivent être acquises et progresser normalement grâce au karma.



[[quality_vision_astral]]
==== Vision astrale (+)(5)
*Prérequis:* <<attribute_magic,Magie>> 1 _ou_ <<quality_adept,Adepte>>.

Le personnage est capable de percevoir le plan astral, et est capable d'user des compétences
<<skill_astral_combat,Combat astral>> et <<skill_assensing,Lecture d'aura>>.



[[quality_vision_low-light]]
==== Vision nocturne (+)(5)

Le personnage possède une vision nocturne naturelle, à l'instar des elfes ou des orks.



[[quality_vision_thermographic]]
==== Vision thermographique (+)(5)

Le personnage possède une vision thermographique naturelle, à l'instar des nains ou des trolls.



[[quality_cyberware]]
==== 'Ware discret (+)(10/15/20) ou 'Ware illégal (-) (10/15/20)
*Prérequis:* <<attribute_essence,Essence>>.

Lorsqu'un personnage ayant payé des augmentations avec son <<attribute_essence,Essence>> achète ce trait,
il doit choisir si ses augmentations passées (et futures) sont discrètes ou illégales.
Il s'agit d'un avantage si son 'ware est discret, et d'un défaut s'il est illégal.
Tous les bénéfices ou inconvénients apportés par ce trait sont cumulatifs.

* Si le personnage possède l'avantage, ses augmentations sont particulièrement difficiles à détecter.
Il s'agit d'organes bioware ou de traitement geneware, ou bien le personnage a été
greffé depuis si longtemps ou par un médecin si compétent que ses implants sont
devenus presque indifférenciables de ses organes naturels.

** Pour 10 points, leur signature augmente de 2 contre les détecteurs physiques.
** Pour 15 points, détecter ses augmentations nécessite un examen médical approfondi.
   Si le personnage est la cible d'une <<skill_assensing,lecture d'aura>>,
   la signature de ses augmentations augmente de 1.
** Pour 20 points, seule la magie permet de les détecter.
   Même alors, leur signature augmente encore de 1 contre les <<skill_assensing,lectures d'aura>>.

* Si le personnage possède le défaut, ses augmentations sont illégales.
Celui-ci risque de graves problèmes si il est découvert.

** Pour 10 points, ses implants sont suffisamment illégaux et/ou dangereux pour
   lui valoir automatiquement un séjour en prison s'ils viennent à être détectés.
** Pour 15 points, tous ses implants sont détectés automatiquement lors d'un contrôle.
** Pour 20 points, la dangerosité de ses implants est détectable à l'oeil nu.

Ce trait n'a aucune influence sur les implants particulièrement flagrants, tels que ceux d'un
personnage arborant un membre supplémentaire ou en train de faire feu avec une arme cyber-implantée.

