
[[chapter_skills]]
=== Compétences

* <<skill_group_influence,Influence>>
** <<skill_impersonation,Déguisement>>
** <<skill_con,Manipulation>>
** <<skill_intimidation,Intimidation>>

* <<skill_group_firearms,Armes à feu>>
** <<skill_pistols,Armes de poing>>
** <<skill_rifles,Armes d'épaule>>
** <<skill_heavy_weapons,Armes lourdes>>

* <<skill_group_close_combat,Corps à corps>>
** <<skill_melee_weapons,Armes de mêlée>>
** <<skill_unarmed,Combat à mains nues>>
** <<skill_dodge,Esquive>>

* <<skill_group_stealth,Furtivité>>
** <<skill_sneaking,Discrétion>>
** <<skill_perception,Perception>>
** <<skill_lockpicking,Effraction>>

* <<skill_group_outdoors,Plein air>>
** <<skill_gymnastics,Athlétisme>>
** <<skill_throwing weapons,Armes de jet>>
** <<skill_survival,Survie>>

* <<skill_group_astral_craft,Astral>>
** <<skill_arcana,Arcanes>>
** <<skill_assensing,Lecture d'aura>>
** <<skill_astral_combat,Combat astral>>

* <<skill_group_pilot,Conduite>>
** <<skill_pilot_aircraft,Pilotage aérien>>
** <<skill_pilot_groundcraft,Pilotage terrestre>>
** <<skill_pilot_watercraft,Pilotage nautique>>

* <<skill_group_engineering,Ingénierie>>
** <<skill_artisan,Artisanat>>
** <<skill_mechanic_gun,Armurerie>>
** <<skill_mechanic_vehicle,Mécanique de véhicules>>
** <<skill_mechanic_industrial,Mécanique industrielle>>

* <<skill_group_biotech,Biotech>>
** <<skill_medecine,Médecine>>
** <<skill_chirurgy,Chirurgie>>
** <<skill_cybertech,Cybertech>>

* <<skill_group_electronics,Électronique>>
** <<skill_computer,Informatique>>
** <<skill_hardware,Électronique>>
** <<skill_software,Logiciels>>

* <<skill_group_cracking,Piratage>>
** <<skill_cybercombat,Cybercombat>>
** <<skill_electronic warfare,Guerre électronique>>
** <<skill_hacking,Hacking>>

* <<skill_group_tasking,Technomancie>>
** <<skill_compiling,Compilation>>
** <<skill_decompiling,Décompilation>>
** <<skill_registering,Enregistrement>>

* <<skill_group_sorcery,Sorcellerie>>
** <<skill_counterspelling,Contresort>>
** <<skill_spellcasting,Incantation>>
** <<skill_rituals,Sorcellerie rituelle>>

* <<skill_group_conjuring,Conjuration>>
** <<skill_banishing,Banissement>>
** <<skill_summoning,Invocation>>
** <<skill_binding,Lien>>

* <<skill_group_enchanting,Enchantement>>
** <<skill_alchemy,Alchimie>>
** <<skill_artificing,Artefacts>>
** <<skill_disenchanting,Disjonction>>

==== Connaissances

Une compétence de connaissance existe pour représenter tout savoir (ou savoir faire) qui n'est pas déjà couvert par une compétence active.

Toutes les compétences de connaissance sont à priori basées sur l'<<attribute_intelligence,Intelligence>>.
Cependant, quand une connaissance particulière comporte une part de savoir faire, et qu'en cours de partie nait un enjeu suffisant pour justifier un test lié à cette connaissance, le MJ peut décider d'utiliser un autre attribut plus approprié.

[NOTE.example,caption="Exemple"]
====
Dans la cuisine de la suite royale du plus huppé des hôtels londoniens, Diesel se râcle la soupière pour trouver une idée de petit déjeuner capable d'impressionner à son réveil le lord qui se trouve dans la chambre voisine.
Diesel a déjà déployé de grands efforts pour plaire au plus proche cousin du Lord Protector, et il compte bien mettre à profit ses talents de cuisinier pour continuer à gagner des points.
Le lord incarne évidemment le summum du snobisme, et Diesel sait qu'une faute de goût lui rapporterait un nouvel aller simple pour les poubelles de l'hôtel à coups de bottes des gardes du corps en faction dans le couloir.

Diesel doit d'abord trouver une idée de recette.
Un succès à un jet d'<<attribute_intelligence,Intelligence>> + *Cuisine* lui rappelle qu'une manière particulière de cuisiner les œufs pochés issue du terroir anglais ferait honneur aux origines du lord.
Cependant, réussir ces œufs pochés requiert un vrai tour de main et, en ouvrant le frigo, il découvre avec stupeur qu'il n'y reste que deux véritables œufs.
En plus, il commence à entendre remuer dans la chambre. Magne-toi, Diesel !

Le MJ requiert un test d'<<attribute_agility,Agilité>> + *Cuisine* avec un seuil de 3 pour réaliser correctement la recette.
Diesel réussit miraculeusement !
Il dispose de son mieux le résultat sur un plateau et finit de composer un petit déjeuner coûtant plus cher que le salaire mensuel de dix employés du room service.
Emportant le tout dans la chambre, Diesel croise mentalement les doigts pour ne pas avoir ruiné ses efforts de la nuit ...
====

[NOTE.example,caption="Exemple"]
====
*TODO*: Équitation
====

===== Langages

Un langage s'acquiert et progresse comme une compétence de connaissance.
Il n'y a en pratique aucune différence entre un langage et une connaissance.
L'indice de compétence auquel un personnage possède un langage particulier reflète sa maîtrise de ce langage, comme indiqué dans la table ci-dessous.

.Langages
[width=40%, options="header", cols="^1,4"]
|===
|Indice   |Niveau
|1        |Moi-Tarzan-Toi-Jane¹
|2        |Enfant de 5 ans
|3        |Pratiquant régulier
|4        |Natif standard
|5        |Conférencier ou Rédacteur
|6+       |Étymologue du langage
|===
¹ Le MJ peut autoriser le joueur à connaître dix mots de vocabulaire en plus de son nom.



[NOTE.option,caption="Règle optionnelle"]
====
*Règle :* Les langages n'ont plus d'indice associé.
Un personnage est considéré soit savoir parler et comprendre suffisamment le langage, soit en être complètement ignorant.
Apprendre un nouveau langage coûte simplement 5 points de karma.

*Motivation :* Le fait d'affecter un indice de compétence à un langage semble offrir peu d'intérêt.
En cours de partie, la question se résume le plus souvent à : le personnage peut-il communiquer dans cette langue, oui ou non ?
Le reste n'est que du fluff ...
====

===== Nouvelles compétences actives

La liste de compétences actives telle que présentée dans ce livre semble suffisante pour couvrir telle quelle tous les besoins d'une partie standard.
Un personnage voulant maîtriser un domaine qui n'est pas couvert par une compétence active crée en général une compétence de connaissance appropriée.
Étant donné qu'une connaissance coûte moins cher à faire <<chapter_karma,progresser>> qu'une compétence active, cela évite de trop pénaliser la progression d'un joueur qui désire traduire sur sa fiche quelque chose d'intéressant mais qui, en cours de partie, a peu de chance d'avoir une réelle importance mécaniquement.

Cependant, certaines campagnes particulières sortent quelque peu de l'ordinaire.
Les personnages peuvent avoir à y faire régulièrement des choses inhabituelles et mal couvertes par le système de compétences actuelles.
Dans ce cas, le MJ peut décider de créer une nouvelle compétence active à partir de ce qui ne serait qu'une compétence de connaissance en temps normal.
Le MJ définit les règles et restriction de cette nouvelle compétence.
Le coût pour la faire <<chapter_karma,progresser>> est celui de toutes les compétences actives.
La création d'une nouvelle compétence active est justifié par le fait que, dans ce cadre de campagne, un personnage peut vouloir y investir davantage de karma pour en tirer un réel avantage mécanique.

[NOTE.example,caption="Exemple"]
====
Un MJ prépare un nouvelle campagne qu'il désire bientôt faire jouer à ses amis.
Cette campagne se passe dans les ombres de Las Vegas.
Les onzes personnages de ses amis évolueront au sein des plus grands casinos de la ville.
Ils participeront à diverses scénarios dont le dernier consistera en un braquage de grande envergure.

La majorité de l'action tournera autour des casinos et de ce qui s'y passe.
Le MJ décide que, dans ce cadre, créer une compétence active *Jeu* se justifie.
Il base cette compétence sur l'<<attribute_intelligence,Intelligence>>, même si certains tests pourront occasionellement se baser sur une autre caractéristique, comme l'<<attribute_agility,Agilité>>.
====
