
[[chapter_skills]]
=== Compétences

==== Groupes de compétences
[skillgroups]

* [[skill_group_influence]] Influence
** <<skill_impersonation,Imposture>>
** <<skill_intimidation,Intimidation>>
** <<skill_con,Manipulation>>

* [[skill_group_firearms]] Armes à feu
** <<skill_pistols,Armes de poing>>
** <<skill_rifles,Armes d'épaule>>
** <<skill_heavy_weapons,Armes lourdes>>

* [[skill_group_close_combat]] Corps à corps
** <<skill_melee_weapons,Armes de mêlée>>
** <<skill_unarmed,Combat à mains nues>>
** <<skill_dodge,Esquive>>

* [[skill_group_stealth]] Furtivité
** <<skill_sneaking,Discrétion>>
** <<skill_perception,Perception>>
** <<skill_lockpicking,Éffraction>>

* [[skill_group_outdoors]] Plein air
** <<skill_gymnastics,Athlétisme>>
** <<skill_throwing_weapons,Armes de jet>>
** <<skill_survival,Survie>>

* [[skill_group_pilot]] Pilotage
** <<skill_pilot_aircraft,Pilotage aérien>>
** <<skill_pilot_ground_craft,Pilotage terrestre>>
** <<skill_pilot_watercraft,Pilotage nautique>>

* [[skill_group_engineering]] Ingénierie
** <<skill_armorer,Armurerie>>
** <<skill_artisan,Artisanat>>
** <<skill_mechanic,Mécanique>>

* [[skill_group_medecine]] Médecine
** <<skill_biotech,Biotech>>
** <<skill_cybertech,Cybertech>>
** <<skill_first_aid,Premiers soins>>

* [[skill_group_cracking]] Informatique
** <<skill_computer,Analyse>>
** <<skill_cybercombat,Cybercombat>>
** <<skill_electronic_warfare,Guerre électronique>>
** <<skill_software,Programmation>>

* [[skill_group_tasking]] Technomancie
** <<skill_compiling,Compilation>>
** <<skill_decompiling,Décompilation>>
** <<skill_registering,Enregistrement>>

* [[skill_group_astral_craft]] Astral
** <<skill_arcana,Arcanes>>
** <<skill_assensing,Lecture d'aura>>
** <<skill_astral_combat,Combat astral>>

* [[skill_group_sorcery]] Sorcellerie
** <<skill_counterspelling,Contresort>>
** <<skill_spellcasting,Incantation>>
** <<skill_rituals,Sorcellerie rituelle>>

* [[skill_group_conjuring]] Conjuration
** <<skill_banishing,Banissement>>
** <<skill_summoning,Invocation>>
** <<skill_binding,Lien>>

* [[skill_group_enchanting]] Enchantement
** <<skill_alchemy,Alchimie>>
** <<skill_artificing,Artefacts>>
** <<skill_disenchanting,Disjonction>>



==== Compétences sociales


[[skill_impersonation]]
[role="skill description"]
===== Imposture

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_influence,Influence>>

====== Spécialisations
Aucune


[[skill_intimidation]]
[role="skill description"]
===== Intimidation

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_influence,Influence>>

====== Spécialisations
Aucune


[[skill_con]]
[role="skill description"]
===== Manipulation

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_influence,Influence>>

====== Spécialisations
Aucune



==== Compétences physiques


[[skill_gymnastics]]
[role="skill description"]
===== Athlétisme

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_outdoors,Plein air>>

====== Spécialisations
Aucune


[[skill_sneaking]]
[role="skill description"]
===== Discrétion

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_stealth,Furtivité>>

====== Spécialisations
Aucune


[[skill_perception]]
[role="skill description"]
===== Perception

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_stealth,Furtivité>>

====== Spécialisations
Aucune



==== Compétences de pilotage


[[skill_pilot_aircraft]]
[role="skill description"]
===== Pilotage aérien

Conduire, piloter ou opérer à distance tout type de véhicule volant.
Cela inclut les appareils à voilure fixe ou orientable, à rotors, à réacteurs, à pousée vectorielle, les ballons à air chaud, mais aussi les appareils non atmosphériques, tels que les vols semi-ballistiques, suborbitaux, les fusées, navettes ou autres engins opérant dans l'espace profond.

Réparer un véhicule aérien nécessite la compétence de <<skill_mechanic,Mécanique>>

====== Défausse
Non

====== Groupe
<<skill_group_pilot,Pilotage>>

====== Spécialisations
Aucune


[[skill_pilot_ground_craft]]
[role="skill description"]
===== Pilotage terrestre

Conduire, piloter ou opérer à distance tout type de véhicule terrestre.
Cela inclut les motos, voitures, camions et autres véhicules à roues, ainsi que les véhicules à chenilles et ceux à articulations mécanisées ou anthropomorphes, tels que les bipodes, les quadripodes ou les exosquelettes.

Réparer un véhicule terrestre nécessite la compétence de <<skill_mechanic,Mécanique>>

====== Défausse
Non

====== Groupe
<<skill_group_pilot,Pilotage>>

====== Spécialisations
Aucune


[[skill_pilot_watercraft]]
[role="skill description"]
===== Pilotage nautique

Conduire, piloter ou opérer à distance tout type de véhicule aquatique.
Cela inclut les bateaux et navires, à moteur ou à voile, les sous-marins, et ainsi de suite.

Concernant les véhicules amphibies tels que les aéroglisseurs, un personnage peut utiliser soit <<skill_pilot_ground_craft,Pilotage terrestre>>, soit <<skill_pilot_watercraft,Pilotage nautique>>, à la discrétion du MJ.

Réparer un véhicule aquatique nécessite la compétence de <<skill_mechanic,Mécanique>>

====== Défausse
Non

====== Groupe
<<skill_group_pilot,Pilotage>>

====== Spécialisations
Aucune



==== Compétences techniques


[[skill_armorer]]
[role="skill description"]
===== Armurerie
Construire, entretenir ou réparer tout type d'arme, allant du couteau au canon d'assaut en passant par l'arbalète.

====== Défausse
Non

====== Groupe
<<skill_group_engineering,Ingénierie>>

====== Specialisations
Aucune


[[skill_artisan]]
[role="skill description"]
===== Artisanat

Construire, entretenir ou réparer tout ce qui n'est pas couvert par les compétences <<skill_armorer,Armurerie>>, <<skill_mechanic,Mécanique>> ou <<skill_software,Programmation>>.
Cela inclut tout produit artisanal, fait à la main ou avec un minimum d'outils, ainsi que les bricolages temporaires non industriels.
Cette compétence est aussi utilisée pour les créations artistiques.

Distinguer si une tâche est couverte par la compétence <<skill_artisan,Artisanat>>, <<skill_mechanic,Mécanique>> ou <<skill_software,Programmation>> peut être difficile.
Le MJ utilisera son propre jugement et son bon sens, en s'aidant des indications suivantes :

* En général, si le matériau de base est naturel (bois, tissu, papier), on utilisera plutôt <<skill_artisan,Artisanat>>.
* Si la tâche est en rapport direct avec la Matrice ou le comportement d'une machine, que cela soit matériel (composants électroniques) ou logiciel (programmes), on utilisera <<skill_software,Programmation>>.
* Si la tâche utilise surtout des matériaux traités (alliages, plastiques, ...) et/ou nécessite davantage qu'une boîte à outils standard, on préfèrera <<skill_mechanic,Mécanique>>.

====== Défausse
Oui

====== Groupe
<<skill_group_engineering,Ingénierie>>

====== Specialisations
Aucune


[[skill_biotech]]
[role="skill description"]
===== Biotech

Cette compétence va au delà des tâches couvertes par <<skill_first_aid,Premiers soins>>.

Elle couvre divers types de chirurgie (tels que retirer une balle, soigner un organe),
ainsi que la transplantation ou l'entretien de membres ou d'organes naturels ou cultivés,
mais pas les implants cyber- ou bioware (qui nécessitent la compétence <<skill_cybertech,Cybertech>>).
Elle permet aussi de soigner des maladies rares ou orphelines, et couvre les applications
de la chimie appliquée aux métahumains (poisons, drogues ...).

L'usage de cette compétence nécessite en général une salle d'opération ou un laboratoire.

====== Défausse
Non

====== Groupe
<<skill_group_medecine,Médecine>>

====== Specialisations
Aucune


[[skill_cybertech]]
[role="skill description"]
===== Cybertech

Cette compétence permet de construire, entretenir ou réparer toutes les augmentations technologiques,
en particulier les implants et accessoires de cyberware, de bioware ou de geneware.

L'usage de cette compétence nécessite en général une salle d'opération ou un laboratoire.

====== Défausse
Non

====== Groupe
<<skill_group_medecine,Médecine>>

====== Specialisations
Aucune


[[skill_lockpicking]]
[role="skill description"]
===== Éffraction

Construire, entretenir, réparer ou désamorcer toute serrure ou mécanisme de restriction d'accès
(serrure, maglock, porte coupe-feu, ...), que celui-ci soit mécanique ou électronique.
Cette compétence est utilisée plus généralement pour s'introduire (éventuellement sans laisser de traces)
en un lieu quelconque, en surmontant les barrières ou obstacles physiques.
Un personnage peut aussi s'en servir pour ouvrir ou fermer un mécanisme (serrure, fenêtre, loquet, ...),
même s'il ne possède pas la clef correspondante ou est "du mauvais coté" de l'ouverture.

Cette compétence sert aussi à construire, entretenir, réparer, contourner,
désamorcer ou réenclencher la plupart des pièges et alarmes physiques.

Un personnage peut utiliser son niveau dans cette compétence à la place de son niveau de
<<skill_perception,Perception>> pour détecter un piège ou un mécanisme d'alarme dissimulé.

====== Défausse
Non

====== Groupe
<<skill_group_stealth,Furtivité>>

====== Spécialisations
Aucune



[[skill_mechanic]]
[role="skill description"]
===== Mécanique

Construire, entretenir ou réparer tout type d'objet de facture industrielle, mais qui n'est pas une arme.
Cela inclut entre autres: les véhicules, les drones, les armures, les machines industrielles.

====== Défausse
Non

====== Groupe
<<skill_group_engineering,Ingénierie>>

====== Specialisations
Aucune


[[skill_first_aid]]
[role="skill description"]
===== Premiers soins

Cette compétence sert à prodiguer les soins d'urgence, tels que ceux prodigués par les ambulanciers ou les pompiers.
On peut l'utiliser pour stabiliser une personne mourante, désinfecter et/ou bander une plaie, poser une attelle, et ainsi de suite.

Elle sert aussi à émettre les diagnostics les plus basiques d'un infirmier ou d'un généraliste,
comme encadrer le traitement les maladies usuelles ou préscrire et administrer les médicaments courants.

Tout ce qui dépasse ce cadre (et nécessite en général une salle d'opération ou un laboratoire) est couvert par la compétence <<skill_biotech,Biotech>>.

Cette compétence ne permet pas de réparer ou d'entretenir les implants technologiques (cela est couvert par la compétence <<skill_cybertech,Cybertech>>).

====== Défausse
Non

====== Groupe
<<skill_group_medecine,Médecine>>

====== Specialisations
Aucune


[[skill_survival]]
[role="skill description"]
===== Survival

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_outdoors,Plein air>>

====== Specialisations
Aucune



==== Compétences de combat

[[skill_throwing_weapons]]
[role="skill description"]
===== Armes de jet

Cette compétence permet d'utiliser efficacement avec toute arme de jet lors d'un combat à distance.
Les armes de cette catégorie mettent à profit la force de l'utilisateur pour tirer un projectile
soit de manière directe (grenade, couteau de lancer, ...) soit de manière indirecte (arc, propulseur).
Toutes les armes des tables <<gear_weapons_throwing,Armes de jet>> et <<gear_weapons_archery,Armes de trait>> utilisent cette compétence.

Cette compétence permet aussi à un personnage de lancer tout objet qu'il peut porter (pierre, tomate, arme de contact, métahumain ...).
Bien sûr, la portée et la précision du lancer diminuent suivant le poids et la forme de ce qui est lancé.

====== Défausse
Oui

====== Groupe
<<skill_group_outdoors,Plein air>>

====== Specialisations
Aucune

[[skill_melee_weapons]]
[role="skill description"]
===== Armes de mêlée

Cette compétence permet d'utiliser efficacement toute arme de mêlée lors d'un combat au corps à corps.
Sauf mention contraire, toutes les armes de la table des <<gear_weapons_melee,Armes de mêlée>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_close_combat,Corps à corps>>

====== Specialisations
Aucune

[[skill_rifles]]
[role="skill description"]
===== Armes d'épaule

Cette compétence permet de tirer efficacement avec toute arme à distance à canon long.
Les armes d'épaule sont à priori prévues pour être utilisée à deux mains.
Toutes les armes de la table des <<gear_weapons_rifles,Armes d'épaule>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_firearms,Armes à feu>>

====== Specialisations
Aucune

[[skill_pistols]]
[role="skill description"]
===== Armes de poing

Cette compétence permet de tirer efficacement avec toute arme à distance à canon court.
Les armes de poing sont à priori prévues pour être utilisée à une main.
Toutes les armes de la table des <<gear_weapons_pistols,Armes de poing>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_firearms,Armes à feu>>

====== Specialisations
Aucune

[[skill_heavy_weapons]]
[role="skill description"]
===== Armes lourdes

Cette compétence permet de tirer efficacement avec toute arme à distance de très gros calibre.
Les armes d'épaule sont à priori prévues pour être utilisée à deux mains, depuis un support et/ou une position fixe.
Toutes les armes de la table des <<gear_weapons_heavy,Armes lourdes>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_firearms,Armes à feu>>

====== Specialisations
Aucune


[[skill_unarmed]]
[role="skill description"]
===== Combat à mains nues

Cette compétence permet de combattre efficacement à mains nues lors d'un combat au corps à corps.
Elle permet aussi de manier des armes assimilées tels que les gants ou les poings américains.

====== Défausse
Oui

====== Groupe
<<skill_group_close_combat,Corps à corps>>

====== Specialisations
Aucune

[[skill_dodge]]
[role="skill description"]
===== Esquive

TODO

====== Défausse
Oui

====== Groupe
<<skill_group_close_combat,Corps à corps>>

====== Specialisations
Aucune



==== Compétences matricielles

[[skill_computer]]
[role="skill description"]
===== Analyse

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

[[skill_cybercombat]]
[role="skill description"]
===== Cybercombat

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

[[skill_electronic_warfare]]
[role="skill description"]
===== Guerre électronique

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

[[skill_software]]
[role="skill description"]
===== Programmation

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune



[[skill_compiling]]
[role="skill description"]
===== Compilation

TODO

====== Prérequis
<<quality_technomancer,Technomancien>>

====== Défausse
Non

====== Groupe
<<skill_group_tasking,Technomancie>>

====== Specialisations
Aucune

[[skill_decompiling]]
[role="skill description"]
===== Décompilation

TODO

====== Prérequis
<<quality_technomancer,Technomancien>>

====== Défausse
Non

====== Groupe
<<skill_group_tasking,Technomancie>>

====== Specialisations
Aucune

[[skill_registering]]
[role="skill description"]
===== Enregistrement

TODO

====== Prérequis
<<quality_technomancer,Technomancien>>

====== Défausse
Non

====== Groupe
<<skill_group_tasking,Technomancie>>

====== Specialisations
Aucune



==== Compétences magiques


[[skill_alchemy]]
[role="skill description"]
===== Alchimie

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_enchanting,Enchantement>>

====== Specialisations
Aucune


[[skill_artificing]]
[role="skill description"]
===== Artefacts

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_enchanting,Enchantement>>

====== Specialisations
Aucune

[[skill_arcana]]
[role="skill description"]
===== Arcanes

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_astral_craft,Astral>>

====== Specialisations
Aucune


[[skill_banishing]]
[role="skill description"]
===== Banissement

TODO

====== Prérequis
<<quality_conjurer,Invocateur>>

====== Défausse
Non

====== Groupe
<<skill_group_conjuring,Conjuration>>

====== Specialisations
Aucune


[[skill_astral_combat]]
[role="skill description"]
===== Combat astral

TODO

====== Prérequis
<<quality_vision_astral,Vision astrale>>

====== Défausse
Non

====== Groupe
<<skill_group_astral_craft,Astral>>

====== Specialisations
Aucune


[[skill_counterspelling]]
[role="skill description"]
===== Contresort

TODO

====== Prérequis
<<quality_sorcerer,Sorcier>>

====== Défausse
Non

====== Groupe
<<skill_group_sorcery,Sorcellerie>>

====== Specialisations
Aucune


[[skill_disenchanting]]
[role="skill description"]
===== Disjonction

TODO

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_enchanting,Enchantement>>

====== Specialisations
Aucune


[[skill_spellcasting]]
[role="skill description"]
===== Incantation

TODO

====== Prérequis
<<quality_sorcerer,Sorcier>>

====== Défausse
Non

====== Groupe
<<skill_group_sorcery,Sorcellerie>>

====== Specialisations
Aucune


[[skill_summoning]]
[role="skill description"]
===== Invocation

TODO

====== Prérequis
<<quality_conjurer,Invocateur>>

====== Défausse
Non

====== Groupe
<<skill_group_conjuring,Conjuration>>

====== Specialisations
Aucune


[[skill_assensing]]
[role="skill description"]
===== Lecture d'aura

TODO

====== Prérequis
<<quality_vision_astral,Vision astrale>>

====== Défausse
Non

====== Groupe
<<skill_group_astral_craft,Astral>>

====== Specialisations
Aucune


[[skill_binding]]
[role="skill description"]
===== Lien

TODO

====== Prérequis
<<quality_conjurer,Invocateur>>

====== Défausse
Non

====== Groupe
<<skill_group_conjuring,Conjuration>>

====== Specialisations
Aucune


[[skill_rituals]]
[role="skill description"]
===== Sorcellerie rituelle

TODO

====== Prérequis
<<quality_sorcerer,Sorcier>>

====== Défausse
Non

====== Groupe
<<skill_group_sorcery,Sorcellerie>>

====== Specialisations
Aucune





==== Connaissances

Une connaissance représente tout savoir ou savoir-faire qui n'est pas déjà couvert par une compétence.
Hormis un <<karma_costs,coût de progression réduit>>, rien ne distingue le fonctionnement d'une connaissance de celui d'une compétence.

Toutes les connaissances sont à priori basées sur l'<<attribute_intelligence,Intelligence>>.
Cependant, quand une connaissance particulière comporte une part de savoir-faire,
et qu'en cours de partie nait un enjeu suffisant pour justifier un test lié à cette connaissance,
le MJ peut décider d'utiliser un autre attribut plus approprié.

[NOTE.example,caption="Exemple"]
====
Dans la cuisine de la suite royale du plus huppé des hôtels londoniens, Diesel se râcle la soupière pour trouver une idée de petit déjeuner capable d'impressionner à son réveil le lord qui se trouve dans la chambre voisine.
Diesel a déjà déployé de grands efforts pour plaire au plus proche cousin du Lord Protector, et il compte bien mettre à profit ses talents de cuisinier pour continuer à gagner des points.
Le lord incarne évidemment le summum du snobisme, et Diesel sait qu'une faute de goût lui rapporterait un nouvel aller simple pour les poubelles de l'hôtel à coups de bottes des gardes du corps en faction dans le couloir.

Diesel doit d'abord trouver une idée de recette.
Un succès à un jet d'<<attribute_intelligence,Intelligence>> + *Cuisine* lui rappelle qu'une manière particulière de cuisiner les œufs pochés issue du terroir anglais ferait honneur aux origines du lord.
Cependant, réussir ces œufs pochés requiert un vrai tour de main et, en ouvrant le frigo, il découvre avec stupeur qu'il n'y reste que deux œufs véritables.
En plus, il commence à entendre remuer dans la chambre. Magne-toi, Diesel !

Le MJ requiert un test d'<<attribute_agility,Agilité>> + *Cuisine* avec un seuil de 3 pour réaliser correctement la recette.
Diesel réussit miraculeusement !
Il dispose de son mieux le résultat sur un plateau et finit de composer un petit déjeuner coûtant plus cher que le salaire mensuel de dix employés du room service.
Emportant le tout dans la chambre, Diesel croise mentalement les doigts pour ne pas avoir ruiné ses efforts de la nuit ...
====

[NOTE.example,caption="Exemple"]
====
*TODO*: Équitation
====



===== Langages

Un langage s'acquiert et progresse comme une connaissance.
Il n'y a en pratique aucune différence entre un langage et une connaissance.
L'indice auquel un personnage possède un langage donné reflète sa maîtrise de ce langage, comme indiqué dans la table ci-dessous.

.Langages
[width=40%, options="header", cols="^1,4"]
|===
|Indice   |Niveau
|1        |Moi-Tarzan-Toi-Jane¹
|2        |Enfant de 5 ans
|3        |Pratiquant régulier
|4        |Natif standard
|5        |Conférencier ou Rédacteur
|6+       |Étymologue du langage
|===
¹ Le MJ peut autoriser le joueur à ne connaître que dix mots de vocabulaire en plus de son nom.



[NOTE.option,caption="Règle optionnelle"]
====
*Hobbies*

*Règle :* Les connaissances n'ont plus d'indice associé.
Un personnage est considéré soit être suffisamment versé dans une connaissance pour détenir une information donnée,
soit être complètement ignorant du sujet.
Apprendre une nouvelle connaissance (ou un nouveau langage) coûte simplement 5 points de karma.

Si il est réellement nécessaire d'avoir le seuil de réussite d'un personnage dans un domaine qu'il connaît,
le MJ peut demander un test de l'attribut lié (donc <<attribute_intelligence,Intelligence>>, la plupart du temps).

*Motivation :* Le fait d'affecter un indice à une connaissance ou un langage semble offrir peu d'intérêt.
En cours de partie, la question se résume le plus souvent, de façon binaire, à :

* le personnage détient-il cette information, oui ou non ?
* le personnage peut-il communiquer dans cette langue, oui ou non ?

Le reste n'est que du fluff ...
====

===== Nouvelles compétences actives

La liste de compétences telle que présentée semble suffisante pour couvrir tous les besoins d'une partie standard.
Un personnage désirant maîtriser un domaine qui n'est pas couvert par une compétence crée en général une connaissance appropriée.
Étant donné qu'une connaissance coûte moins cher à faire <<chapter_karma,progresser>> qu'une compétence,
cela évite de trop pénaliser un joueur qui désire traduire sur sa fiche quelque chose d'intéressant pour lui
mais qui, en cours de partie, a peu de chance d'avoir une réelle importance mécaniquement.

Cependant, certaines campagnes sortent quelque peu de l'ordinaire.
Les personnages peuvent avoir à y faire régulièrement des choses inhabituelles
et à résoudre des situations mal couvertes par le système de compétences actuelles.
Dans ce cas, le MJ peut décider de promouvoir ce qui ne serait qu'une connaissance en temps normal en une nouvelle compétence.

Le MJ définit le champ d'application de cette nouvelle compétence ainsi que les règles particulières qui s'appliquent.
Le coût pour la faire <<chapter_karma,progresser>> est celui de toutes les compétences.

Il peut affecter cette nouvelle compétence à un groupe de compétences existant ou,
s'il crée plusieurs compétences différentes, celles-ci peuvent aussi être rassemblées dans un nouveau groupe.
Sinon, la nouvelle compétence peut rester orpheline, c'est à dire en dehors de tout groupe de compétence.

[NOTE.example,caption="Exemple"]
====
Un MJ prépare un nouvelle campagne qu'il désire bientôt faire jouer à ses amis.
Cette campagne se passe dans les ombres de Las Vegas.
Les onzes personnages de ses joueurs évolueront au sein des plus grands casinos de la ville.
Ils participeront à diverses scénarios dont le dernier consistera en un braquage de grande envergure.

La majorité de l'action tournera donc autour des casinos et de ce qui s'y passe.
Le MJ décide que, dans ce cadre, créer une compétence active *Jeu* se justifie.
Il base cette compétence sur l'<<attribute_intelligence,Intelligence>>,
même si certains tests pourront occasionellement se baser sur une autre caractéristique,
comme le <<attribute_charisma,Charisme>> (pour bluffer au cours d'une partie de cartes)
ou l'<<attribute_agility,Agilité>> (pour truquer une donne ou un tirage de dés).
====
