
[[chapter_skills]]
=== Compétences

ifdef::with-designer-notes[]
displayer::design[label="Afficher"]
[.design]
****
Ce que j'attends des compétences, c'est :

* Que chaque compétence soit utile en jeu.
  Tout ce qui est peu utile ou est sympa uniquement niveau fluff passe en compétence de connaissance.
  Tout ce qui est inutile ou alourdit le système pour rien est purement et simplement supprimé.
* Que deux compétences ne se « recouvrent » pas.
  En d'autres termes, qu'il ne faille pas monter 2 compétences pour faire une seule chose.
  Je ne veux pas non plus avoir à me poser la question de quelle compétence j'utilise dans une situation donnée :
** Je tire avec mon pistolet automatique ; j'utilise pistolets ou armes automatiques ?
** Je me fais passer pour quelqu'un ; dans quel ordre j'utilise imposture et déguisement ?
   Et si je n'ai qu'une des deux compétences, je fais comment ?
** Mon expert en armes lourdes saute dans la tourelle du véhicule du rigger et se met à tirer !
   En plus il est sympa le rigger, il vient d'y installer Pattie, ma mitrailleuse lourde préférée ...
   Comment ? Non, je n'ai pas la compétences Armes de véhicule ... QUOI ? Je dois défausser sur mon Agilité ?
   Mais le véhicule est à l'arrêt ! Et j'ai 7 en Armes lourdes ! Et j'ai dézingué toute une escouade avec Pattie la semaine dernière !! ... T_T
* Qu'elles soient flexibles, qu'on puisse les utiliser dans plusieurs contextes, éventuellement en changeant l'attribut lié.
  Tu as la compétence "tirer au pistolet" ?
  Donc tu sais tirer avec tous les putains de pistolets et tu as aussi la compétence de connaissance des pistolets au même indice.
  Par contre, c'est pas pour ça que tu sais _construire_ un pistolet.
* Que résoudre les actions liées à une compétence soit _rapide_, en un seul jet si possible.

Ce que j'attends d'un groupe de compétences, en plus de ce que j'attends des compétences individuelles, c'est que les compétences qui le composent :

* Couvrent des domaines voisins, pour que la réduction de karma qu'offre le groupe se justifie.
* Que la notion de "casser" ou de "refusionner" un groupe n'existe plus : maintenant, un groupe a l'indice de la plus basse des compétences que le PJ possède.
  Lorsque le joueur monte une compétence d'un groupe, il le fait soit au coût normal (si c'est la première ou la seconde compétence du groupe en termes d'indice), soit à moitié prix (si c'est la troisième compétence du groupe en termes d'indice), soit gratuitement (si c'est la quatrième compétence du groupe en termes d'indice).

Au final, on obtient 14 groupes de compétences ; un de moins qu'avant, mais je ne constate aucun manque au niveau de ce que peuvent faire les personnages.
Toutes les compétences qui ont survécu au grand ménage sont liées à un groupe de compétences (plus aucune n'est « orpheline »), et elles semblent toutes utiles.
Certaines sont peut-être _trop_ utiles (manipulation, discrétion) ... à voir.

****
endif::with-designer-notes[]





==== Groupes de compétences
[skillgroups]

* [[skill_group_influence]] Influence
** <<skill_impersonation,Imposture>>
** <<skill_intimidation,Intimidation>>
** <<skill_con,Manipulation>>

* [[skill_group_firearms]] Armes à feu
** <<skill_pistols,Armes de poing>>
** <<skill_rifles,Armes d'épaule>>
** <<skill_heavy_weapons,Armes lourdes>>

* [[skill_group_close_combat]] Corps à corps
** <<skill_melee_weapons,Armes de mêlée>>
** <<skill_unarmed,Combat à mains nues>>
** <<skill_dodge,Esquive>>

* [[skill_group_stealth]] Furtivité
** <<skill_sneaking,Discrétion>>
** <<skill_perception,Perception>>
** <<skill_lockpicking,Éffraction>>

* [[skill_group_outdoors]] Plein air
** <<skill_gymnastics,Athlétisme>>
** <<skill_throwing_weapons,Armes de jet>>
** <<skill_survival,Survie>>

* [[skill_group_pilot]] Pilotage
** <<skill_pilot_aircraft,Pilotage aérien>>
** <<skill_pilot_ground_craft,Pilotage terrestre>>
** <<skill_pilot_watercraft,Pilotage nautique>>

* [[skill_group_engineering]] Ingénierie
** <<skill_armorer,Armurerie>>
** <<skill_artisan,Artisanat>>
** <<skill_mechanic,Mécanique>>

* [[skill_group_medecine]] Médecine
** <<skill_biotech,Biotech>>
** <<skill_cybertech,Cybertech>>
** <<skill_first_aid,Premiers soins>>

* [[skill_group_cracking]] Informatique
** <<skill_computer,Analyse>>
** <<skill_cybercombat,Cybercombat>>
** <<skill_electronic_warfare,Guerre électronique>>
** <<skill_software,Programmation>>

* [[skill_group_tasking]] Technomancie
** <<skill_compiling,Compilation>>
** <<skill_decompiling,Décompilation>>
** <<skill_registering,Enregistrement>>

* [[skill_group_astral_craft]] Astral
** <<skill_arcana,Arcanes>>
** <<skill_assensing,Lecture d'aura>>
** <<skill_astral_combat,Combat astral>>

* [[skill_group_sorcery]] Sorcellerie
** <<skill_counterspelling,Contresort>>
** <<skill_spellcasting,Incantation>>
** <<skill_rituals,Sorcellerie rituelle>>

* [[skill_group_conjuring]] Conjuration
** <<skill_banishing,Banissement>>
** <<skill_summoning,Invocation>>
** <<skill_binding,Lien>>

* [[skill_group_enchanting]] Enchantement
** <<skill_alchemy,Alchimie>>
** <<skill_artificing,Artefacts>>
** <<skill_disenchanting,Disjonction>>



==== Compétences sociales


[[skill_impersonation]]
[role="skill description"]
===== Imposture

Cette compétence sert à prendre la place d'une personne, en imitant ses maniérismes et, le cas échéant, son apparence.
Tant que le personnage s'en tient à son rôle (et réussit son test d'imposture), son entourage se comporte avec lui
de la même manière qu'il se comporterait en présence de celui ou celle que le personnage incarne.

Il n'est pas indispensable que le personnage incarne une personne précise ;
il peut par exemple choisir d'incarner un agent de police ou un dirigeant corporatiste.
Cependant, certains cercles sociaux relativement fermés rendent difficile d'incarner un rôle donné
sans que son identité précise soit clairement vérifiable.
Outre des talents de comédien, cette compétence met le plus souvent en jeu une connaissance du milieu concerné
ainsi que de quoi confectionner un déguisement approprié.

Lorsqu'un personnage désire convaincre quelqu'un alors qu'il incarne quelqu'un d'autre, il peut être difficile de
distinguer si une tâche est couverte par la compétence <<skill_impersonation,Imposture>>, <<skill_intimidation,Intimidation>> ou <<skill_con,Manipulation>>.
Le MJ utilisera son propre jugement et son bon sens, en s'aidant des indications suivantes :

* Si le personnage donne des instructions courtes ou ponctuelles qui restent dans les prérogatives habituelles du rôle qu'il incarne,
  <<skill_impersonation,Imposture>> est suffisante.
* S'il s'adresse à des subordonnés du personnage qu'il incarne, le personnage peut utiliser l'<<skill_intimidation,Intimidation>>,
  mais seulement s'il a préalablement convaincu son interlocuteur qu'il était bien celui ou celle dont il a pris l'apparence grâce à un jet d'<<skill_impersonation,Imposture>> réussi.
* Le personnage peut aussi utiliser <<skill_con,Manipulation>> si la situation s'y prête mais, là encore,
  il doit préalablement convaincre son interlocuteur de son identité grâce à un jet d'<<skill_impersonation,Imposture>> réussi.
* Lorsque le personnage échoue à un jet d'<<skill_intimidation,Intimidation>> ou de <<skill_con,Manipulation>>
  et que sa marge d'échec est supérieure au nombre de succès qu'il a obtenu à son jet d'<<skill_impersonation,Imposture>>, sa couverture est éventée.

L'esprit de cette compétence est de prétendre à tous qu'on est quelqu'un d'autre, pas de se déguiser pour passer inaperçu (ce qui est du ressort de la compétence <<skill_sneaking,Discrétion>>).

====== Défausse
Oui

====== Groupe
<<skill_group_influence,Influence>>

====== Spécialisations
Aucune

====== Outils
* *Kit :* Ustensiles de coiffure, maquillages, masques, éléments de déguisement
* *Atelier :* Loge d'habillage et de maquillage
* *Usine :* Studio de cinéma


[[skill_intimidation]]
[role="skill description"]
===== Intimidation

Cette compétence sert à rapidement convaincre un personnage de faire (ou ne pas faire)
quelque chose de contraire à ses intentions, en utilisant l'autorité ou la peur.

Cette compétence sert aussi à donner un ordre, en montrant l'exemple ou en faisant preuve de son autorité envers un subordonné.

L'usage de cette compétence par un personnage est aussi rapide que le fait d'énoncer une ou deux phrases et,
si le test d'intimidation est réussi, son interlocuteur ne fait que bredouiller son accord ou le manifester silencieusement.

Un personnage ayant recours à l'intimidation physique bénéficie d'un modificateur égal à sa <<attribute_body,Constitution>>.

====== Défausse
Oui

====== Groupe
<<skill_group_influence,Influence>>

====== Spécialisations
Aucune

====== Outils
Non applicable


[[skill_con]]
[role="skill description"]
===== Manipulation

Cette compétence sert à convaincre autrui par la parole, que ce soit honnêtement, par la diplomatie ou la négociation,
ou de manière moins directe, par la séduction, le baratin, ou carrément le mensonge et l'escroquerie.

L'usage de cette compétence suppose un échange de point de vue entre les deux parties, ce qui prend en général au minimum quelques rounds.

====== Défausse
Oui

====== Groupe
<<skill_group_influence,Influence>>

====== Spécialisations
Aucune

====== Outils
Non applicable



==== Compétences physiques


[[skill_gymnastics]]
[role="skill description"]
===== Athlétisme

Cette compétence est utilisée pour escalader, courir, sauter, faire de la gymnastique, de la natation, s'évader de ses liens ...

Dans certaines situations faisant entrer en jeu l'endurance ou la résistance, le personnage bénéficie d'un modificateur égal à sa <<attribute_body,Constitution>>.

====== Défausse
Oui

====== Groupe
<<skill_group_outdoors,Plein air>>

====== Spécialisations
Aucune

====== Outils
* *Kit :* Équipement de plongée, matériel d'escalade, tenue appropriée au sport concerné
* *Atelier :* Piscine, mur d'escalade, salle de sport
* *Usine :* Stade


[[skill_sneaking]]
[role="skill description"]
===== Discrétion

Cette compétence sert ne pas se faire détecter, en marchant sans bruit, en se cachant derrière un obstacle ou dans la foule,
ou en bougeant de façon trop rapide ou imperceptible (en faisant les poches à quelqu'un, par exemple).

Elle peut aussi être utilisée au cours d'une filature, pour suivre discrètement quelqu'un sans se faire repérer.

Un personnage peut aussi utiliser cette compétence pour dissimuler un objet dans son environnement (par exemple en faisant passer sa voiture garée pour une carcasse déjà démantelée),
voire sur sa propre personne (par exemple pour qu'un contrôle de sécurité ne détecte pas son arme de poing).

Bien que l'usage de cette compétence puisse nécessiter de se déguiser
(changer de vêtements pendant une filature, se déguiser en clochard pour observer un bâtiment depuis la rue, ...),
le but premier de ces déguisement est toujours de passer inaperçu, et jamais d'être reconnu comme quelqu'un de digne d'intérêt.
Pour se déguiser en un individu particulier afin de bénéficier de son influence, se reporter à la compétence <<skill_impersonation,Imposture>>.

====== Défausse
Oui

====== Groupe
<<skill_group_stealth,Furtivité>>

====== Spécialisations
Aucune

====== Outils
Non applicable


[[skill_perception]]
[role="skill description"]
===== Perception

Cette compétence est utilisée pour remarquer quelque chose de particulier dans l'environnement d'un personnage.

Elle peut être utilisée de manière passive, pour représenter la vigilance habituelle d'un personnage,
ou de manière active, lorsque celui-ci fouille ou examine attentivement un pièce par exemple.

====== Défausse
Oui

====== Groupe
<<skill_group_stealth,Furtivité>>

====== Spécialisations
Aucune

====== Outils
* *Kit :* Micros, jumelles, senseurs
* *Atelier :* Loge d'espionnage
* *Usine :* Base radar, régiment de transmissions



==== Compétences de pilotage


[[skill_pilot_aircraft]]
[role="skill description"]
===== Pilotage aérien

Conduire, piloter ou opérer à distance tout type de véhicule volant.
Cela inclut les appareils à voilure fixe ou orientable, à rotors, à réacteurs, à pousée vectorielle, les ballons à air chaud, mais aussi les appareils non atmosphériques, tels que les vols semi-ballistiques, suborbitaux, les fusées, navettes ou autres engins opérant dans l'espace profond.

Réparer un véhicule aérien nécessite la compétence de <<skill_mechanic,Mécanique>>

====== Défausse
Non

====== Groupe
<<skill_group_pilot,Pilotage>>

====== Spécialisations
Aucune

====== Outils
Non applicable.
Chaque véhicule ou drone peut néanmoins apporter un bonus spécifique grâce à son <<gear_vehicle,grade>>.


[[skill_pilot_ground_craft]]
[role="skill description"]
===== Pilotage terrestre

Conduire, piloter ou opérer à distance tout type de véhicule terrestre.
Cela inclut les motos, voitures, camions et autres véhicules à roues, ainsi que les véhicules à chenilles et ceux à articulations mécanisées ou anthropomorphes, tels que les bipodes, les quadripodes ou les exosquelettes.

Réparer un véhicule terrestre nécessite la compétence de <<skill_mechanic,Mécanique>>

====== Défausse
Non

====== Groupe
<<skill_group_pilot,Pilotage>>

====== Spécialisations
Aucune

====== Outils
Non applicable.
Chaque véhicule ou drone peut néanmoins apporter un bonus spécifique grâce à son <<gear_vehicle,grade>>.


[[skill_pilot_watercraft]]
[role="skill description"]
===== Pilotage nautique

Conduire, piloter ou opérer à distance tout type de véhicule aquatique.
Cela inclut les bateaux et navires, à moteur ou à voile, les sous-marins, et ainsi de suite.

Concernant les véhicules amphibies tels que les aéroglisseurs, un personnage peut utiliser soit <<skill_pilot_ground_craft,Pilotage terrestre>>, soit <<skill_pilot_watercraft,Pilotage nautique>>, à la discrétion du MJ.

Réparer un véhicule aquatique nécessite la compétence de <<skill_mechanic,Mécanique>>

====== Défausse
Non

====== Groupe
<<skill_group_pilot,Pilotage>>

====== Spécialisations
Aucune

====== Outils
Non applicable.
Chaque véhicule ou drone peut néanmoins apporter un bonus spécifique grâce à son <<gear_vehicle,grade>>.



==== Compétences techniques


[[skill_armorer]]
[role="skill description"]
===== Armurerie
Construire, entretenir ou réparer tout type d'arme, allant du couteau au canon d'assaut en passant par l'arbalète.

Se reporter au chapitre <<chapter_crafting,Construction / Réparation>> pour davantage de détails.

====== Défausse
Non

====== Groupe
<<skill_group_engineering,Ingénierie>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Outils d'armurier
* *Atelier :* Armurerie
* *Usine :* Usine d'armement


[[skill_artisan]]
[role="skill description"]
===== Artisanat

Construire, entretenir ou réparer tout ce qui n'est pas couvert par les compétences <<skill_armorer,Armurerie>>, <<skill_mechanic,Mécanique>> ou <<skill_software,Programmation>>.
Cela inclut tout produit artisanal, fait à la main ou avec un minimum d'outils, ainsi que les bricolages temporaires non industriels.
Cette compétence est aussi utilisée pour les créations artistiques.

Se reporter au chapitre <<chapter_crafting,Construction / Réparation>> pour davantage de détails.

====== Défausse
Oui

====== Groupe
<<skill_group_engineering,Ingénierie>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Outils d'artisan
* *Atelier :* Boutique d'artisan
* *Usine :* Association d'artisans


[[skill_biotech]]
[role="skill description"]
===== Biotech

Cette compétence va au delà des tâches couvertes par <<skill_first_aid,Premiers soins>>.

Elle couvre divers types de chirurgie (tels que retirer une balle, soigner un organe, ...),
ainsi que la transplantation ou l'entretien de membres ou d'organes naturels ou cultivés,
mais pas les implants cyber- ou bioware (qui nécessitent la compétence <<skill_cybertech,Cybertech>>).
Elle permet aussi de soigner des maladies rares ou orphelines, et couvre les applications
de la chimie appliquée aux métahumains (poisons, drogues ...).

L'usage de cette compétence nécessite en général une salle d'opération ou un laboratoire.

====== Défausse
Non

====== Groupe
<<skill_group_medecine,Médecine>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Medkit
* *Atelier :* Clinique
* *Usine :* Hôpital


[[skill_cybertech]]
[role="skill description"]
===== Cybertech

Cette compétence permet de construire, greffer, entretenir ou réparer toutes les augmentations technologiques,
en particulier les implants et accessoires de cyberware, de bioware ou de geneware.

L'usage de cette compétence nécessite en général une salle d'opération ou un laboratoire.

La fabrication et la réparation de prothèses est converte dans le chapitre <<chapter_crafting,Construction / Réparation>>.

====== Défausse
Non

====== Groupe
<<skill_group_medecine,Médecine>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Outils de cybernétique
* *Atelier :* Cyber-clinique
* *Usine :* Laboratoire de cybernétique


[[skill_lockpicking]]
[role="skill description"]
===== Éffraction

Construire, entretenir, réparer ou désamorcer toute serrure ou mécanisme de restriction d'accès
(serrure, maglock, porte coupe-feu, ...), que celui-ci soit mécanique ou électronique.
Cette compétence est utilisée plus généralement pour s'introduire (éventuellement sans laisser de traces)
en un lieu quelconque, en surmontant les barrières ou obstacles physiques.
Un personnage peut aussi s'en servir pour ouvrir ou fermer un mécanisme (serrure, fenêtre, loquet, ...),
même s'il ne possède pas la clef correspondante ou est "du mauvais coté" de l'ouverture.

Cette compétence sert aussi à construire, entretenir, réparer, contourner,
désamorcer ou réenclencher la plupart des pièges et alarmes physiques.

Un personnage peut utiliser son niveau dans cette compétence à la place de son niveau de
<<skill_perception,Perception>> pour détecter un piège ou un mécanisme d'alarme dissimulé.

====== Défausse
Non

====== Groupe
<<skill_group_stealth,Furtivité>>

====== Spécialisations
Aucune

====== Outils
* *Kit :* Passes, outils de crochetage
* *Atelier :* Atelier de serrurier / d'électronique
* *Usine :* Usine spécialisée



[[skill_mechanic]]
[role="skill description"]
===== Mécanique

Construire, entretenir ou réparer tout type d'objet de facture industrielle, mais qui n'est pas une arme.
Cela inclut entre autres les véhicules, les drones, les armures et les machines industrielles.

Se reporter au chapitre <<chapter_crafting,Construction / Réparation>> pour davantage de détails.

====== Défausse
Non

====== Groupe
<<skill_group_engineering,Ingénierie>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Boîte à outils
* *Atelier :* Atelier de mécanique, garage
* *Usine :* Usine spécialisée


[[skill_first_aid]]
[role="skill description"]
===== Premiers soins

Cette compétence sert à prodiguer les soins d'urgence, tels que ceux prodigués par les ambulanciers ou les pompiers.
On peut l'utiliser pour stabiliser une personne mourante, désinfecter et/ou bander une plaie, poser une attelle, et ainsi de suite.

Elle sert aussi à émettre les diagnostics les plus basiques d'un infirmier ou d'un généraliste,
comme encadrer le traitement les maladies usuelles ou préscrire et administrer les médicaments courants.

Tout ce qui dépasse ce cadre (et nécessite en général une salle d'opération ou un laboratoire) est couvert par la compétence <<skill_biotech,Biotech>>.

Cette compétence ne permet pas non plus de s'occuper des implants technologiques, qui est couvert par la compétence <<skill_cybertech,Cybertech>>.

====== Défausse
Non

====== Groupe
<<skill_group_medecine,Médecine>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Boîte à outils
* *Atelier :* Clinique
* *Usine :* Hôpital


[[skill_survival]]
[role="skill description"]
===== Survie

Cette compétence sert à trouver de l'eau et de la nourriture en milieu sauvage (rural ou urbain), ainsi qu'à s'y orienter et à résister aux dangers habituels de ce milieu, en trouvant un abri par exemple.

Cette compétence permet aussi à retrouver des métahumains ou des métacréatures en analysant les diverses traces de leur passage.

====== Défausse
Oui

====== Groupe
<<skill_group_outdoors,Plein air>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Sac à dos de randonneur
* *Atelier :* Boutique de randonneur, cabane de robinson
* *Usine :* Non applicable



==== Compétences de combat

[[skill_throwing_weapons]]
[role="skill description"]
===== Armes de jet

Cette compétence permet de connaître et d'utiliser efficacement avec toute arme de jet lors d'un combat à distance.
Les armes de cette catégorie mettent à profit la force de l'utilisateur pour tirer un projectile
soit de manière directe (grenade, couteau de lancer, ...) soit de manière indirecte (arc, propulseur).
Toutes les armes des tables <<gear_weapons_throwing,Armes de jet>> et <<gear_weapons_archery,Armes de trait>> utilisent cette compétence.

Cette compétence permet aussi à un personnage de lancer tout objet qu'il peut porter (pierre, tomate, arme de contact, métahumain ...).
Bien sûr, la portée et la précision du lancer varient suivant le poids et la forme de ce qui est lancé.

====== Défausse
Oui

====== Groupe
<<skill_group_outdoors,Plein air>>

====== Specialisations
Aucune

====== Outils
Non applicable.
Chaque arme peut néanmoins apporter un modificateur spécifique grâce à son <<gear_weapons_grades,grade>>.

[[skill_melee_weapons]]
[role="skill description"]
===== Armes de mêlée

Cette compétence permet de connaître et d'utiliser efficacement toute arme de mêlée lors d'un combat au corps à corps.
Sauf mention contraire, toutes les armes de la table des <<gear_weapons_melee,Armes de mêlée>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_close_combat,Corps à corps>>

====== Specialisations
Aucune

====== Outils
Non applicable.
Chaque arme peut néanmoins apporter un modificateur spécifique grâce à son <<gear_weapons_grades,grade>>.

[[skill_rifles]]
[role="skill description"]
===== Armes d'épaule

Cette compétence permet de connaître et de tirer efficacement avec toute arme à distance à canon long.
Les armes d'épaule sont à priori prévues pour être utilisée à deux mains.
Toutes les armes de la table des <<gear_weapons_rifles,Armes d'épaule>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_firearms,Armes à feu>>

====== Specialisations
Aucune

====== Outils
Non applicable.
Chaque arme peut néanmoins apporter un modificateur spécifique grâce à son <<gear_weapons_grades,grade>>.

[[skill_pistols]]
[role="skill description"]
===== Armes de poing

Cette compétence permet de connaître et de tirer efficacement avec toute arme à distance à canon court.
Les armes de poing sont à priori prévues pour être utilisée à une main.
Toutes les armes de la table des <<gear_weapons_pistols,Armes de poing>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_firearms,Armes à feu>>

====== Specialisations
Aucune

====== Outils
Non applicable.
Chaque arme peut néanmoins apporter un modificateur spécifique grâce à son <<gear_weapons_grades,grade>>.

[[skill_heavy_weapons]]
[role="skill description"]
===== Armes lourdes

Cette compétence permet de connaître et de tirer efficacement avec toute arme à distance de très gros calibre.
Les armes d'épaule sont à priori prévues pour être utilisée à deux mains, depuis un support et/ou une position fixe.
Toutes les armes de la table des <<gear_weapons_heavy,Armes lourdes>> utilisent cette compétence.

====== Défausse
Oui

====== Groupe
<<skill_group_firearms,Armes à feu>>

====== Specialisations
Aucune

====== Outils
Non applicable.
Chaque arme peut néanmoins apporter un modificateur spécifique grâce à son <<gear_weapons_grades,grade>>.


[[skill_unarmed]]
[role="skill description"]
===== Combat à mains nues

Cette compétence permet de combattre efficacement à mains nues lors d'un combat au corps à corps.
Elle permet aussi de manier des armes assimilées tels que les gants ou les poings américains.

Un personnage qui possède cette compétence est versé dans plusieurs styles et techniques de combat non armé, qu'il peut reconnaître et comparer.

====== Défausse
Oui

====== Groupe
<<skill_group_close_combat,Corps à corps>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_dodge]]
[role="skill description"]
===== Esquive

Cette compétence sert à éviter les conséquences d'un danger physique menaçant le personnage, que celui-ci soit spécifiquement dirigé contre lui ou pas.

====== Défausse
Oui

====== Groupe
<<skill_group_close_combat,Corps à corps>>

====== Specialisations
Aucune

====== Outils
Non applicable.



==== Compétences matricielles

[[skill_computer]]
[role="skill description"]
===== Analyse

Cette compétence sert à détecter, reconnaître et rechercher des icônes et des informations sur la Matrice.

Se reporter à la section <<matrix_perception,Percevoir la Matrice>> du chapitre <<chapter_matrix,Matrice>> pour davantage de détails.

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_cybercombat]]
[role="skill description"]
===== Cybercombat

Cette compétence sert à combattre, à détruire ou à planter des icônes et des objets reliés à la Matrice.

Se reporter à la section <<combat,Planter la Matrice>> du chapitre <<chapter_matrix,Matrice>> pour davantage de détails.

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_electronic_warfare]]
[role="skill description"]
===== Guerre électronique

Cette compétence sert à perturber les communications et à prendre le contrôle d'icônes et d'objets reliés à la Matrice.

Se reporter à la section <<matrix_take_control,Prendre le contrôle>> du chapitre <<chapter_matrix,Matrice>> pour davantage de détails.

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_software]]
[role="skill description"]
===== Programmation

Cette compétence sert à créer et améliorer de équipements informatiques.
Elle couvre à la fois la partie hardware (les composants électronique) que la partie software (les programmes).

Cette compétence sert aussi à créer des <<matrix_databomb,Databombes>> matricielles.

Se reporter au chapitre <<chapter_crafting,Construction / Réparation>> pour davantage de détails.

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_cracking,Informatique>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Caisse à outils d'électronique
* *Atelier :* Atelier d'électronique
* *Usine :* Usine d'électronique



[[skill_compiling]]
[role="skill description"]
===== Compilation

Cette compétence sert à appeler un sprite.

Se reporter au chapitre <<chapter_matrix,Matrice>> pour davantage de détails.

====== Prérequis
<<quality_technomancer,Technomancien>>

====== Défausse
Non

====== Groupe
<<skill_group_tasking,Technomancie>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_decompiling]]
[role="skill description"]
===== Décompilation

Cette compétence sert à se débarrasser d'un sprite compilé.

Se reporter au chapitre <<chapter_matrix,Matrice>> pour davantage de détails.

====== Prérequis
<<quality_technomancer,Technomancien>>

====== Défausse
Non

====== Groupe
<<skill_group_tasking,Technomancie>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_registering]]
[role="skill description"]
===== Enregistrement

Cette compétence sert à renforcer un sprite compilé.

Se reporter au chapitre <<chapter_matrix,Matrice>> pour davantage de détails.

====== Prérequis
<<quality_technomancer,Technomancien>>

====== Défausse
Non

====== Groupe
<<skill_group_tasking,Technomancie>>

====== Specialisations
Aucune

====== Outils
Non applicable.



==== Compétences magiques


[[skill_alchemy]]
[role="skill description"]
===== Alchimie

Cette compétence sert à fabriquer un objet enchanté, comme une potion.
Elle permet aussi de créer une substance magique, par exemple de l'orichalque.

Se reporter au chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_enchanter,Enchanteur>>

====== Défausse
Non

====== Groupe
<<skill_group_enchanting,Enchantement>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_artificing]]
[role="skill description"]
===== Artefacts

Cette compétence sert à créer, réparer ou améliorer un focus.

Se reporter au chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_enchanter,Enchanteur>>

====== Défausse
Non

====== Groupe
<<skill_group_enchanting,Enchantement>>

====== Specialisations
Aucune

====== Outils
Non applicable.

[[skill_arcana]]
[role="skill description"]
===== Arcanes

Cette compétence sert à comprendre et à créer des formules magiques, par exemple des formules de sort ou d'esprit allié.

Se reporter au chapitre <<chapter_crafting,Construction / Réparation>>, ou au chapitre <<chapter_magic,Magie>>, pour davantage de détails.

====== Prérequis
Aucun

====== Défausse
Non

====== Groupe
<<skill_group_astral_craft,Astral>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Non applicable
* *Atelier :* Bibliothèque hermétique
* *Usine :* Non applicable


[[skill_banishing]]
[role="skill description"]
===== Banissement

Cette compétence sert à bannir un esprit invoqué par un autre magicien.

Se reporter à la section <<banishing,Banissement>> du chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_conjurer,Invocateur>>

====== Défausse
Non

====== Groupe
<<skill_group_conjuring,Conjuration>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_astral_combat]]
[role="skill description"]
===== Combat astral

Cette compétence sert à combattre dans l'espace astral.

Se reporter aux chapitre <<chapter_combat,Combat>> et <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_vision_astral,Vision astrale>>

====== Défausse
Non

====== Groupe
<<skill_group_astral_craft,Astral>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_counterspelling]]
[role="skill description"]
===== Contresort

Cette compétence sert à dissiper un sort, comme décrit dans la section <<counterspelling,Dissipation>>.
Elle permet aussi de se protéger soi-même ou autrui des sorts hostiles, comme décrit dans la section <<magic_defense,Défense magique>>.

====== Prérequis
<<quality_sorcerer,Sorcier>>

====== Défausse
Non

====== Groupe
<<skill_group_sorcery,Sorcellerie>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_disenchanting]]
[role="skill description"]
===== Disjonction

Cette compétence sert à dissiper des enchantements permanents.
En particulier, un personnage peut s'en servir pour dissiper la magie d'objets enchantés grâce aux compétences <<skill_alchemy,Alchimie>> ou <<skill_artificing,Artefacts>>.

Se reporter au chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_enchanter,Enchanteur>>

====== Défausse
Non

====== Groupe
<<skill_group_enchanting,Enchantement>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_spellcasting]]
[role="skill description"]
===== Incantation

Cette compétence sert à lancer un sort que le personnage connaît.

Se reporter aux sections <<sorcery,Sorcellerie>> et <<spell_list,Grimoire>> du chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_sorcerer,Sorcier>>

====== Défausse
Non

====== Groupe
<<skill_group_sorcery,Sorcellerie>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_summoning]]
[role="skill description"]
===== Invocation

Cette compétence sert à appeler un esprit afin que celui-ci serve temporairement le personnage.

Se reporter à la section <<conjuring,Conjuration>> du chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_conjurer,Invocateur>>

====== Défausse
Non

====== Groupe
<<skill_group_conjuring,Conjuration>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_assensing]]
[role="skill description"]
===== Lecture d'aura

Cette compétence sert à détecter et à analyser les auras astrales.

Lorsque le personnage analyse une aura, le nombre de succès nets détermine la précision des informations obtenues.

Sinon, cette compétence s'utilise comme celle de <<skill_perception,Perception>> dans le monde astral.

====== Prérequis
<<quality_vision_astral,Vision astrale>>

====== Défausse
Non

====== Groupe
<<skill_group_astral_craft,Astral>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_binding]]
[role="skill description"]
===== Lien

Cette compétence sert à étendre la durée durant laquelle un esprit doit servir le personnage.
L'esprit concerné doit préalabement avoir été invoqué par le personnage grâce à sa compétence d'<<skill_summoning,Invocation>>.

Se reporter à la section <<conjuring,Conjuration>> du chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_conjurer,Invocateur>>

====== Défausse
Non

====== Groupe
<<skill_group_conjuring,Conjuration>>

====== Specialisations
Aucune

====== Outils
Non applicable.


[[skill_rituals]]
[role="skill description"]
===== Sorcellerie rituelle

Cette compétence sert à lancer un sort au moyen d'un rituel.

Se reporter à la section <<ritual_sorcery,Sorcellerie Rituelle>> du chapitre <<chapter_magic,Magie>> pour davantage de détails.

====== Prérequis
<<quality_sorcerer,Sorcier>>

====== Défausse
Non

====== Groupe
<<skill_group_sorcery,Sorcellerie>>

====== Specialisations
Aucune

====== Outils
* *Kit :* Non applicable
* *Atelier :* Cercle hermétique, Loge chamanique
* *Usine :* Non applicable




[[knowledges]]
==== Connaissances

Une connaissance représente tout savoir ou savoir-faire qui n'est pas déjà couvert par une compétence.
Hormis un <<karma_costs,coût de progression réduit>>, rien ne distingue le fonctionnement d'une connaissance de celui d'une compétence.

Toutes les connaissances sont à priori basées sur l'<<attribute_intelligence,Intelligence>>.
Cependant, quand une connaissance particulière comporte une part de savoir-faire,
et qu'en cours de partie nait un enjeu suffisant pour justifier un test lié à cette connaissance,
le MJ peut décider d'utiliser un autre attribut plus approprié.

[NOTE.example,caption="Exemple"]
====
Dans la cuisine de la suite royale du plus huppé des hôtels londoniens, Diesel se râcle la soupière pour trouver une idée de petit déjeuner capable d'impressionner à son réveil le lord qui se trouve dans la chambre voisine.
Diesel a déjà déployé de grands efforts pour plaire au plus proche cousin du Lord Protector, et il compte bien mettre à profit ses talents de cuisinier pour continuer à gagner des points.
Le lord incarne évidemment le summum du snobisme, et Diesel sait qu'une faute de goût lui rapporterait un nouvel aller simple pour les poubelles de l'hôtel à coups de bottes des gardes du corps en faction dans le couloir.

Diesel doit d'abord trouver une idée de recette.
Un succès à un jet d'<<attribute_intelligence,Intelligence>> + *Cuisine* lui rappelle qu'une manière particulière de cuisiner les œufs pochés issue du terroir anglais ferait honneur aux origines du lord.
Cependant, réussir ces œufs pochés requiert un vrai tour de main et, en ouvrant le frigo, il découvre avec stupeur qu'il n'y reste que deux œufs véritables.
En plus, il commence à entendre remuer dans la chambre. Magne-toi, Diesel !

Le MJ requiert un test d'<<attribute_agility,Agilité>> + *Cuisine* avec un seuil de 3 pour réaliser correctement la recette.
Diesel réussit miraculeusement !
Il dispose de son mieux le résultat sur un plateau et finit de composer un petit déjeuner coûtant plus cher que le salaire mensuel de dix employés du room service.
Emportant le tout dans la chambre, Diesel croise mentalement les doigts pour ne pas avoir ruiné ses efforts de la nuit ...
====

[NOTE.example,caption="Exemple"]
====
*TODO*: Équitation
====



[[languages]]
===== Langages

Un langage s'acquiert et progresse comme une connaissance.
Il n'y a en pratique aucune différence entre un langage et une connaissance.
L'indice auquel un personnage possède un langage donné reflète sa maîtrise de ce langage, comme indiqué dans la table ci-dessous.

.Langages
[width=40%, options="header", cols="^1,4"]
|===
|Indice   |Niveau
|1        |Moi-Tarzan-Toi-Jane¹
|2        |Enfant de 5 ans
|3        |Pratiquant régulier
|4        |Natif standard
|5        |Conférencier ou Rédacteur
|6+       |Étymologue du langage
|===
¹ Le MJ peut autoriser le joueur à ne connaître que dix mots de vocabulaire en plus de son nom.



[NOTE.option,caption="Règle optionnelle"]
====
*Hobbies*

*Règle :* Les connaissances n'ont plus d'indice associé.
Un personnage est considéré soit être suffisamment versé dans une connaissance pour détenir une information donnée,
soit être complètement ignorant du sujet.
Apprendre une nouvelle connaissance (ou un nouveau langage) coûte simplement 5 points de karma.

Si il est réellement nécessaire d'avoir le seuil de réussite d'un personnage dans un domaine qu'il connaît,
le MJ peut demander un test de l'attribut lié (donc <<attribute_intelligence,Intelligence>>, la plupart du temps).

*Motivation :* Le fait d'affecter un indice à une connaissance ou un langage semble offrir peu d'intérêt.
En cours de partie, la question se résume le plus souvent, de façon binaire, à :

* le personnage détient-il cette information, oui ou non ?
* le personnage peut-il communiquer dans cette langue, oui ou non ?

Le reste n'est que du fluff ...
====



[[create_new_skills]]
===== Nouvelles compétences actives

La liste de compétences telle que présentée semble suffisante pour couvrir tous les besoins d'une partie standard.
Un personnage désirant maîtriser un domaine qui n'est pas couvert par une compétence crée en général une connaissance appropriée.
Étant donné qu'une connaissance coûte moins cher à faire <<chapter_karma,progresser>> qu'une compétence,
cela évite de trop pénaliser un joueur qui désire traduire sur sa fiche quelque chose d'intéressant pour lui
mais qui, en cours de partie, a peu de chance d'avoir une réelle importance mécaniquement.

Cependant, certaines campagnes sortent quelque peu de l'ordinaire.
Les personnages peuvent avoir à y faire régulièrement des choses inhabituelles
et à résoudre des situations mal couvertes par le système de compétences actuelles.
Dans ce cas, le MJ peut décider de promouvoir ce qui ne serait qu'une connaissance en temps normal en une nouvelle compétence.

Le MJ définit le champ d'application de cette nouvelle compétence ainsi que les règles particulières qui s'appliquent.
Le coût pour la faire <<chapter_karma,progresser>> est celui de toutes les compétences.

Il peut affecter cette nouvelle compétence à un groupe de compétences existant ou,
s'il crée plusieurs compétences différentes, celles-ci peuvent aussi être rassemblées dans un nouveau groupe.
Sinon, la nouvelle compétence peut rester orpheline, c'est à dire en dehors de tout groupe de compétence.

[NOTE.example,caption="Exemple"]
====
Un MJ prépare un nouvelle campagne qu'il désire bientôt faire jouer à ses amis.
Cette campagne se passe dans les ombres de Las Vegas.
Les onzes personnages de ses joueurs évolueront au sein des plus grands casinos de la ville.
Ils participeront à diverses scénarios dont le dernier consistera en un braquage de grande envergure.

La majorité de l'action tournera donc autour des casinos et de ce qui s'y passe.
Le MJ décide que, dans ce cadre, créer une compétence active *Jeu* se justifie.
Il base cette compétence sur l'<<attribute_intelligence,Intelligence>>,
même si certains tests pourront occasionellement se baser sur une autre caractéristique,
comme le <<attribute_charisma,Charisme>> (pour bluffer au cours d'une partie de cartes)
ou l'<<attribute_agility,Agilité>> (pour truquer une donne ou un tirage de dés).
====
